export const CHAT_COPY = {
  en: {
    selectChat: 'Select a chat to start messaging', privateBetween: 'Private one-to-one messaging stays between the two participants.', loadingMessages: 'Loading messages…', noMessages: 'No messages yet', firstMessage: "Send the first message when you're ready.", archiveChat: 'Archive chat', unableArchive: 'Unable to archive chat',
    addAttachment: 'Add attachment', photo: 'Photo', video: 'Video', document: 'Document', location: 'Location', typeMessage: 'Type a message', sendMessage: 'Send message', recordVoice: 'Record voice note', voiceNote: 'Voice note', cancelVoice: 'Cancel voice note', locationUnsupported: 'Location sharing is not supported by this browser', locationPermission: 'Location permission was not available', stagedMedia: 'Private text chat is active. Attachments and location sharing remain staged until their privacy backend is enabled.',
    sending: 'Sending', read: 'Read', delivered: 'Delivered', attachmentUnavailable: 'Attachment unavailable', refreshPrivateLink: 'Refresh the chat to request a new private link.', photoUnavailable: 'Photo unavailable', videoUnavailable: 'Video unavailable', voiceUnavailable: 'Voice note unavailable', documentUnavailable: 'Document unavailable', sharedPhoto: 'Shared photo', sharedLocation: 'Shared location', locationUnavailable: 'Location unavailable', documentLabel: 'Document', copied: 'Message copied', copyFailed: 'Unable to copy message', cancel: 'Cancel', save: 'Save', edited: 'edited', messageActions: 'Message actions', copy: 'Copy', edit: 'Edit', deleteMessage: 'Delete message', deleteConfirm: 'Delete this message from the conversation?',
    signInChat: 'Please sign in to use private chat.', unableOpen: 'Unable to open this chat', unableSend: 'Unable to send message', attachmentSent: 'Attachment sent', unableAttachment: 'Unable to send attachment', locationShared: 'Location shared', unableLocation: 'Unable to share location', messageUpdated: 'Message updated', unableEdit: 'Unable to edit message', messageDeleted: 'Message deleted', unableDelete: 'Unable to delete message', unableUpdateChat: 'Unable to update chat', pinned: 'Chat pinned', unpinned: 'Chat unpinned', muted: 'Chat muted', unmuted: 'Chat unmuted', archived: 'Chat archived',
  },
  es: {
    selectChat: 'Selecciona un chat para empezar', privateBetween: 'Los mensajes privados quedan entre las dos personas de la conversación.', loadingMessages: 'Cargando mensajes…', noMessages: 'Aún no hay mensajes', firstMessage: 'Envía el primer mensaje cuando quieras.', archiveChat: 'Archivar chat', unableArchive: 'No se pudo archivar el chat',
    addAttachment: 'Añadir archivo', photo: 'Foto', video: 'Video', document: 'Documento', location: 'Ubicación', typeMessage: 'Escribe un mensaje', sendMessage: 'Enviar mensaje', recordVoice: 'Grabar nota de voz', voiceNote: 'Nota de voz', cancelVoice: 'Cancelar nota de voz', locationUnsupported: 'Este navegador no permite compartir ubicación', locationPermission: 'No se pudo obtener permiso de ubicación', stagedMedia: 'El chat privado de texto está activo. Los archivos y la ubicación siguen en preparación hasta activar su sistema de privacidad.',
    sending: 'Enviando', read: 'Leído', delivered: 'Entregado', attachmentUnavailable: 'Archivo no disponible', refreshPrivateLink: 'Actualiza el chat para solicitar un nuevo enlace privado.', photoUnavailable: 'Foto no disponible', videoUnavailable: 'Video no disponible', voiceUnavailable: 'Nota de voz no disponible', documentUnavailable: 'Documento no disponible', sharedPhoto: 'Foto compartida', sharedLocation: 'Ubicación compartida', locationUnavailable: 'Ubicación no disponible', documentLabel: 'Documento', copied: 'Mensaje copiado', copyFailed: 'No se pudo copiar el mensaje', cancel: 'Cancelar', save: 'Guardar', edited: 'editado', messageActions: 'Acciones del mensaje', copy: 'Copiar', edit: 'Editar', deleteMessage: 'Eliminar mensaje', deleteConfirm: '¿Eliminar este mensaje de la conversación?',
    signInChat: 'Inicia sesión para usar el chat privado.', unableOpen: 'No se pudo abrir este chat', unableSend: 'No se pudo enviar el mensaje', attachmentSent: 'Archivo enviado', unableAttachment: 'No se pudo enviar el archivo', locationShared: 'Ubicación compartida', unableLocation: 'No se pudo compartir la ubicación', messageUpdated: 'Mensaje actualizado', unableEdit: 'No se pudo editar el mensaje', messageDeleted: 'Mensaje eliminado', unableDelete: 'No se pudo eliminar el mensaje', unableUpdateChat: 'No se pudo actualizar el chat', pinned: 'Chat fijado', unpinned: 'Chat desfijado', muted: 'Chat silenciado', unmuted: 'Sonido del chat activado', archived: 'Chat archivado',
  },
  fr: {
    selectChat: 'Sélectionnez une discussion pour commencer', privateBetween: 'La messagerie privée reste entre les deux participants.', loadingMessages: 'Chargement des messages…', noMessages: 'Aucun message pour le moment', firstMessage: 'Envoyez le premier message quand vous êtes prêt.', archiveChat: 'Archiver la discussion', unableArchive: 'Impossible d’archiver la discussion',
    addAttachment: 'Ajouter une pièce jointe', photo: 'Photo', video: 'Vidéo', document: 'Document', location: 'Localisation', typeMessage: 'Écrire un message', sendMessage: 'Envoyer le message', recordVoice: 'Enregistrer une note vocale', voiceNote: 'Note vocale', cancelVoice: 'Annuler la note vocale', locationUnsupported: 'Ce navigateur ne permet pas le partage de localisation', locationPermission: 'L’autorisation de localisation n’était pas disponible', stagedMedia: 'Le chat texte privé est actif. Les pièces jointes et la localisation restent en préparation jusqu’à l’activation de leur protection de confidentialité.',
    sending: 'Envoi', read: 'Lu', delivered: 'Livré', attachmentUnavailable: 'Pièce jointe indisponible', refreshPrivateLink: 'Actualisez la discussion pour demander un nouveau lien privé.', photoUnavailable: 'Photo indisponible', videoUnavailable: 'Vidéo indisponible', voiceUnavailable: 'Note vocale indisponible', documentUnavailable: 'Document indisponible', sharedPhoto: 'Photo partagée', sharedLocation: 'Localisation partagée', locationUnavailable: 'Localisation indisponible', documentLabel: 'Document', copied: 'Message copié', copyFailed: 'Impossible de copier le message', cancel: 'Annuler', save: 'Enregistrer', edited: 'modifié', messageActions: 'Actions du message', copy: 'Copier', edit: 'Modifier', deleteMessage: 'Supprimer le message', deleteConfirm: 'Supprimer ce message de la discussion ?',
    signInChat: 'Connectez-vous pour utiliser le chat privé.', unableOpen: 'Impossible d’ouvrir cette discussion', unableSend: 'Impossible d’envoyer le message', attachmentSent: 'Pièce jointe envoyée', unableAttachment: 'Impossible d’envoyer la pièce jointe', locationShared: 'Localisation partagée', unableLocation: 'Impossible de partager la localisation', messageUpdated: 'Message mis à jour', unableEdit: 'Impossible de modifier le message', messageDeleted: 'Message supprimé', unableDelete: 'Impossible de supprimer le message', unableUpdateChat: 'Impossible de mettre à jour la discussion', pinned: 'Discussion épinglée', unpinned: 'Discussion désépinglée', muted: 'Discussion en sourdine', unmuted: 'Son de la discussion réactivé', archived: 'Discussion archivée',
  },
  it: {
    selectChat: 'Seleziona una chat per iniziare', privateBetween: 'I messaggi privati restano tra i due partecipanti.', loadingMessages: 'Caricamento messaggi…', noMessages: 'Ancora nessun messaggio', firstMessage: 'Invia il primo messaggio quando vuoi.', archiveChat: 'Archivia chat', unableArchive: 'Impossibile archiviare la chat',
    addAttachment: 'Aggiungi allegato', photo: 'Foto', video: 'Video', document: 'Documento', location: 'Posizione', typeMessage: 'Scrivi un messaggio', sendMessage: 'Invia messaggio', recordVoice: 'Registra nota vocale', voiceNote: 'Nota vocale', cancelVoice: 'Annulla nota vocale', locationUnsupported: 'Questo browser non supporta la condivisione della posizione', locationPermission: 'Il permesso per la posizione non era disponibile', stagedMedia: 'La chat privata di testo è attiva. Allegati e posizione restano in preparazione finché non viene attivato il relativo sistema di privacy.',
    sending: 'Invio', read: 'Letto', delivered: 'Consegnato', attachmentUnavailable: 'Allegato non disponibile', refreshPrivateLink: 'Aggiorna la chat per richiedere un nuovo link privato.', photoUnavailable: 'Foto non disponibile', videoUnavailable: 'Video non disponibile', voiceUnavailable: 'Nota vocale non disponibile', documentUnavailable: 'Documento non disponibile', sharedPhoto: 'Foto condivisa', sharedLocation: 'Posizione condivisa', locationUnavailable: 'Posizione non disponibile', documentLabel: 'Documento', copied: 'Messaggio copiato', copyFailed: 'Impossibile copiare il messaggio', cancel: 'Annulla', save: 'Salva', edited: 'modificato', messageActions: 'Azioni messaggio', copy: 'Copia', edit: 'Modifica', deleteMessage: 'Elimina messaggio', deleteConfirm: 'Eliminare questo messaggio dalla conversazione?',
    signInChat: 'Accedi per usare la chat privata.', unableOpen: 'Impossibile aprire questa chat', unableSend: 'Impossibile inviare il messaggio', attachmentSent: 'Allegato inviato', unableAttachment: 'Impossibile inviare l’allegato', locationShared: 'Posizione condivisa', unableLocation: 'Impossibile condividere la posizione', messageUpdated: 'Messaggio aggiornato', unableEdit: 'Impossibile modificare il messaggio', messageDeleted: 'Messaggio eliminato', unableDelete: 'Impossibile eliminare il messaggio', unableUpdateChat: 'Impossibile aggiornare la chat', pinned: 'Chat fissata', unpinned: 'Chat non più fissata', muted: 'Chat silenziata', unmuted: 'Audio chat riattivato', archived: 'Chat archiviata',
  },
  de: {
    selectChat: 'Wähle einen Chat, um zu schreiben', privateBetween: 'Private Nachrichten bleiben zwischen den beiden Teilnehmern.', loadingMessages: 'Nachrichten werden geladen…', noMessages: 'Noch keine Nachrichten', firstMessage: 'Sende die erste Nachricht, wenn du bereit bist.', archiveChat: 'Chat archivieren', unableArchive: 'Chat konnte nicht archiviert werden',
    addAttachment: 'Anhang hinzufügen', photo: 'Foto', video: 'Video', document: 'Dokument', location: 'Standort', typeMessage: 'Nachricht schreiben', sendMessage: 'Nachricht senden', recordVoice: 'Sprachnachricht aufnehmen', voiceNote: 'Sprachnachricht', cancelVoice: 'Sprachnachricht abbrechen', locationUnsupported: 'Dieser Browser unterstützt das Teilen des Standorts nicht', locationPermission: 'Standortberechtigung war nicht verfügbar', stagedMedia: 'Privater Text-Chat ist aktiv. Anhänge und Standortfreigabe bleiben vorbereitet, bis ihr Datenschutz-Backend aktiviert ist.',
    sending: 'Wird gesendet', read: 'Gelesen', delivered: 'Zugestellt', attachmentUnavailable: 'Anhang nicht verfügbar', refreshPrivateLink: 'Aktualisiere den Chat, um einen neuen privaten Link anzufordern.', photoUnavailable: 'Foto nicht verfügbar', videoUnavailable: 'Video nicht verfügbar', voiceUnavailable: 'Sprachnachricht nicht verfügbar', documentUnavailable: 'Dokument nicht verfügbar', sharedPhoto: 'Geteiltes Foto', sharedLocation: 'Geteilter Standort', locationUnavailable: 'Standort nicht verfügbar', documentLabel: 'Dokument', copied: 'Nachricht kopiert', copyFailed: 'Nachricht konnte nicht kopiert werden', cancel: 'Abbrechen', save: 'Speichern', edited: 'bearbeitet', messageActions: 'Nachrichtenaktionen', copy: 'Kopieren', edit: 'Bearbeiten', deleteMessage: 'Nachricht löschen', deleteConfirm: 'Diese Nachricht aus dem Chat löschen?',
    signInChat: 'Melde dich an, um den privaten Chat zu nutzen.', unableOpen: 'Dieser Chat konnte nicht geöffnet werden', unableSend: 'Nachricht konnte nicht gesendet werden', attachmentSent: 'Anhang gesendet', unableAttachment: 'Anhang konnte nicht gesendet werden', locationShared: 'Standort geteilt', unableLocation: 'Standort konnte nicht geteilt werden', messageUpdated: 'Nachricht aktualisiert', unableEdit: 'Nachricht konnte nicht bearbeitet werden', messageDeleted: 'Nachricht gelöscht', unableDelete: 'Nachricht konnte nicht gelöscht werden', unableUpdateChat: 'Chat konnte nicht aktualisiert werden', pinned: 'Chat angeheftet', unpinned: 'Chat gelöst', muted: 'Chat stummgeschaltet', unmuted: 'Chat nicht mehr stumm', archived: 'Chat archiviert',
  },
};

export const getChatCopy = (language) => CHAT_COPY[language] || CHAT_COPY.en;
