export const LIKE_MINDED_DAILY_LIMITS = Object.freeze({ Premiere: null, Exclusive: null });
export const LIKE_MINDED_MAX_ROOM_QUESTIONS = 42;

export function depthKey(depth) {
  return depth === 'Easy' ? 'easy' : depth === 'Deep' ? 'deep' : 'real';
}

export function buildLikeMindedSlot(categories, startCategory, startDepth, setNo = 1, questionNo = 1) {
  const list = Array.isArray(categories) && categories.length ? categories : [];
  const depth = ['Easy','Real','Deep'].includes(startDepth) ? startDepth : 'Real';
  if (!list.length) return { category: startCategory, depth, variant: 0, questionId: '', absoluteIndex: 0 };
  const start = Math.max(0, list.indexOf(startCategory));
  const absolute = Math.max(0, (Number(setNo || 1) - 1) * 21 + (Number(questionNo || 1) - 1));
  const variant = Math.floor(absolute / list.length) % 3;
  const within = absolute % list.length;
  const category = list[(start + within + variant * 5) % list.length];
  return {
    category,
    depth,
    variant,
    questionId: category + ':' + depthKey(depth) + ':v' + (variant + 1),
    absoluteIndex: absolute,
  };
}

const TEXT = {
  en: {
    weekend:['Active and adventurous','Relaxed and cozy','Social and outgoing','A mix of all three'],
    importance:['Essential','Very important','Somewhat important','Not very important'],
    tradeoff:['Protect the relationship','Protect the long-term plan','Find a workable compromise','It depends on the situation'],
    timing:['Talk about it right away','Take a short pause first','Wait until both are ready','I need plenty of time'],
    disagreement:['Understand each other first','Solve the problem first','Keep the conversation respectful','It depends on the issue'],
    repair:['Listen again before responding','Explain it a different way','Pause and come back calmer','It depends on what happened'],
    similarity:['Very important to match','Helpful, but not required','Differences can work well','It depends on the subject'],
    involvement:['Very involved together','Some involvement with clear limits','Mostly independent as a couple','It depends on the situation'],
    structure:['I like a clear plan','I prefer flexibility','A balance of both','It depends on the day'],
    money:['Save and plan first','Enjoy life now','Balance saving and spending','It depends on the goal'],
    boundary:['Keep the boundary firm','Allow some flexibility','Decide case by case','Talk it through together'],
    future:['Plan well ahead','Adapt as life changes','Plan the big things only','Keep it mostly spontaneous'],
    fun:['Adventurous','Playful and silly','Relaxed and easy','A mix depending on the mood'],
    humor:['Joke about almost anything','Playful, but know the line','Keep serious topics serious','It depends on the moment'],
    activities:['Active and outdoors','Creative or hands-on','Relaxing together','A mix of different things'],
    travel:['Explore and adventure','Food, comfort and culture','Plan the details','Stay spontaneous'],
    entertainment:['Go out and be social','Movies, music or shows','Games and interactive fun','A mix of everything'],
    daily:['Structured routine','Flexible routine','Slow and easy pace','Fast and productive pace'],
    openness:['Very open','Open, but with care','Private about some things','It depends on the topic'],
    change:['Both should adapt','Meet somewhere in the middle','Respect the difference','It depends on how serious it is'],
    qualities:['Honesty and integrity','Kindness and empathy','Reliability and drive','Humor and warmth'],
    gatherings:['I love frequent gatherings','I enjoy them sometimes','Small doses work best','I prefer them rarely'],
    pace:['Fast and ambitious','Balanced and steady','Slow and relaxed','It changes with life'],
    windfall:['Save or invest it','Pay bills or debt','Enjoy it together','Split saving and fun'],
    income:['Contribute by percentage','Pool everything together','Split shared costs equally','Choose what feels fair together'],
    risk:['Yes, if we plan carefully','Maybe, with clear limits','Only with strong safeguards','No, the risk is too high'],
    alone:['A little every day','A few hours regularly','A full day sometimes','A lot of independence'],
    privacy:['No, private messages stay private','Only with clear permission','Only in a serious emergency','We should have open access'],
    futureGoal:['Build a home or family','Travel and experiences','Career and financial growth','Personal growth and freedom'],
    tripChoice:['City and culture','Nature and adventure','Beach and relaxation','Let the destination surprise me'],
    surpriseFail:['Laugh and adapt','Try to fix the plan','Pause and make a new plan','I would probably get frustrated'],
    spontaneity:['I could go tomorrow','I need a little preparation','I need a solid plan first','I rarely make sudden changes'],
    humorType:['Dry or witty','Silly and playful','Dark or edgy','Stories and observational humor'],
    hobbyTime:['Yes, regularly','Sometimes, when it feels natural','Only if both enjoy it','Separate hobbies are completely fine'],
    travelPriority:['Shared experiences','Comfort and relaxation','Food and culture','Keeping the trip low-stress'],
    effort:['Try them often','Try them sometimes','Support them without joining often','Keep entertainment mostly separate'],
    morning:['Up early and productive','Slow and peaceful','Flexible depending on the day','Definitely a night owl'],
    freeHour:['Rest and recharge','Spend it with someone I care about','Get something useful done','Do something spontaneous'],
    predictability:['Mostly predictability','Mostly surprise','A healthy balance of both','It depends on the season of life'],
    yesNo:['Yes, definitely','Probably, with work','Maybe, depending on the difference','Probably not'],
    familyDisapproval:['My relationship and my own judgment','Understanding my family’s concerns','Finding a middle ground','It depends on why they disapprove'],
    competingDreams:['Whose opportunity is most time-sensitive','Which benefits us both most','Take turns supporting each dream','Find a third option together'],
    relocation:['Yes, I could relocate','Maybe, for the right opportunity','Only temporarily or with conditions','No, staying near family matters too much'],
    qualityTime:['Yes, shared time matters more than shared taste','Usually, if we stay curious about each other','Maybe, but it takes intentional effort','Probably not for me'],
  },
  es: {
    weekend:['Activo y aventurero','Relajado y acogedor','Social y animado','Una mezcla de los tres'],
    importance:['Esencial','Muy importante','Algo importante','Poco importante'],
    tradeoff:['Proteger la relación','Proteger el plan a largo plazo','Buscar un compromiso viable','Depende de la situación'],
    timing:['Hablarlo de inmediato','Tomar una pausa corta primero','Esperar a que ambos estén listos','Necesito bastante tiempo'],
    disagreement:['Entenderse primero','Resolver el problema primero','Mantener el respeto','Depende del tema'],
    repair:['Escuchar de nuevo antes de responder','Explicarlo de otra manera','Pausar y volver más tranquilos','Depende de lo ocurrido'],
    similarity:['Muy importante coincidir','Ayuda, pero no es obligatorio','Las diferencias pueden funcionar','Depende del tema'],
    involvement:['Muy involucrados juntos','Algo de participación con límites claros','Mayormente independientes como pareja','Depende de la situación'],
    structure:['Me gusta un plan claro','Prefiero flexibilidad','Un equilibrio de ambos','Depende del día'],
    money:['Ahorrar y planificar primero','Disfrutar la vida ahora','Equilibrar ahorro y gasto','Depende de la meta'],
    boundary:['Mantener el límite firme','Permitir algo de flexibilidad','Decidir caso por caso','Hablarlo juntos'],
    future:['Planificar con mucha anticipación','Adaptarse a los cambios','Planificar solo lo importante','Mantenerlo bastante espontáneo'],
    fun:['Aventurero','Juguetón y divertido','Relajado y tranquilo','Una mezcla según el ánimo'],
    humor:['Bromear sobre casi todo','Ser juguetón, pero conocer el límite','Tomar en serio los temas serios','Depende del momento'],
    activities:['Activo y al aire libre','Creativo o manual','Relajarse juntos','Una mezcla de actividades'],
    travel:['Explorar y aventurarse','Comida, comodidad y cultura','Planificar los detalles','Ser espontáneo'],
    entertainment:['Salir y socializar','Películas, música o espectáculos','Juegos y diversión interactiva','Una mezcla de todo'],
    daily:['Rutina estructurada','Rutina flexible','Ritmo lento y tranquilo','Ritmo rápido y productivo'],
    openness:['Muy abierto','Abierto, pero con cuidado','Privado en algunas cosas','Depende del tema'],
    change:['Ambos deben adaptarse','Encontrarse a mitad de camino','Respetar la diferencia','Depende de qué tan serio sea'],
    qualities:['Honestidad e integridad','Amabilidad y empatía','Confiabilidad y ambición','Humor y calidez'],
    gatherings:['Me encantan las reuniones frecuentes','Las disfruto a veces','En pequeñas dosis','Prefiero que sean poco frecuentes'],
    pace:['Rápido y ambicioso','Equilibrado y estable','Lento y relajado','Cambia según la etapa de vida'],
    windfall:['Ahorrarlo o invertirlo','Pagar cuentas o deudas','Disfrutarlo juntos','Dividir entre ahorro y diversión'],
    income:['Aportar según el porcentaje de ingresos','Juntar todo el dinero','Dividir los gastos compartidos por igual','Elegir juntos lo que sea justo'],
    risk:['Sí, si planificamos bien','Tal vez, con límites claros','Solo con fuertes protecciones','No, el riesgo es demasiado alto'],
    alone:['Un poco cada día','Unas horas regularmente','Un día completo a veces','Mucha independencia'],
    privacy:['No, los mensajes privados siguen privados','Solo con permiso claro','Solo en una emergencia seria','Deberíamos tener acceso abierto'],
    futureGoal:['Construir hogar o familia','Viajes y experiencias','Crecimiento profesional y financiero','Crecimiento personal y libertad'],
    tripChoice:['Ciudad y cultura','Naturaleza y aventura','Playa y relajación','Que el destino me sorprenda'],
    surpriseFail:['Reírse y adaptarse','Intentar arreglar el plan','Pausar y hacer un plan nuevo','Probablemente me frustraría'],
    spontaneity:['Podría ir mañana','Necesito un poco de preparación','Necesito un plan sólido primero','Rara vez hago cambios repentinos'],
    humorType:['Seco o ingenioso','Tonto y juguetón','Oscuro o atrevido','Historias y humor de observación'],
    hobbyTime:['Sí, regularmente','A veces, cuando sea natural','Solo si ambos lo disfrutan','Los hobbies separados están bien'],
    travelPriority:['Experiencias compartidas','Comodidad y relajación','Comida y cultura','Mantener el viaje sin estrés'],
    effort:['Probarlos con frecuencia','Probarlos a veces','Apoyarlos sin participar mucho','Mantener el entretenimiento más separado'],
    morning:['Temprano y productivo','Lento y tranquilo','Flexible según el día','Definitivamente nocturno'],
    freeHour:['Descansar y recargar','Pasarla con alguien que quiero','Hacer algo útil','Hacer algo espontáneo'],
    predictability:['Más previsibilidad','Más sorpresa','Un equilibrio sano de ambas','Depende de la etapa de vida'],
    yesNo:['Sí, definitivamente','Probablemente, con trabajo','Tal vez, según la diferencia','Probablemente no'],
    familyDisapproval:['Mi relación y mi propio criterio','Entender las preocupaciones de mi familia','Buscar un punto medio','Depende de por qué desaprueban'],
    competingDreams:['La oportunidad más urgente','La que más beneficie a ambos','Turnarse para apoyar cada sueño','Encontrar juntos una tercera opción'],
    relocation:['Sí, podría mudarme','Tal vez, por la oportunidad correcta','Solo temporalmente o con condiciones','No, estar cerca de la familia importa demasiado'],
    qualityTime:['Sí, importa más el tiempo compartido que los mismos gustos','Normalmente, si seguimos interesados el uno en el otro','Tal vez, pero requiere intención','Probablemente no para mí'],
  },
  fr: {
    weekend:['Actif et aventureux','Détendu et confortable','Social et dynamique','Un mélange des trois'],
    importance:['Essentiel','Très important','Assez important','Peu important'],
    tradeoff:['Protéger la relation','Protéger le projet à long terme','Trouver un compromis viable','Cela dépend de la situation'],
    timing:['En parler tout de suite','Faire une courte pause','Attendre que les deux soient prêts','J’ai besoin de beaucoup de temps'],
    disagreement:['Se comprendre d’abord','Résoudre le problème d’abord','Rester respectueux','Cela dépend du sujet'],
    repair:['Écouter à nouveau avant de répondre','Expliquer autrement','Faire une pause et revenir plus calme','Cela dépend de ce qui s’est passé'],
    similarity:['Très important d’être alignés','Utile, mais pas obligatoire','Les différences peuvent fonctionner','Cela dépend du sujet'],
    involvement:['Très impliqués ensemble','Une certaine implication avec des limites claires','Plutôt indépendants comme couple','Cela dépend de la situation'],
    structure:['J’aime un plan clair','Je préfère la flexibilité','Un équilibre des deux','Cela dépend du jour'],
    money:['Épargner et planifier d’abord','Profiter de la vie maintenant','Équilibrer épargne et dépenses','Cela dépend de l’objectif'],
    boundary:['Garder la limite ferme','Permettre un peu de flexibilité','Décider au cas par cas','En parler ensemble'],
    future:['Planifier longtemps à l’avance','S’adapter aux changements','Planifier seulement les grandes choses','Rester plutôt spontané'],
    fun:['Aventureux','Joueur et drôle','Détendu et simple','Un mélange selon l’humeur'],
    humor:['Plaisanter sur presque tout','Être joueur tout en connaissant la limite','Garder les sujets sérieux sérieux','Cela dépend du moment'],
    activities:['Actif et en plein air','Créatif ou manuel','Se détendre ensemble','Un mélange d’activités'],
    travel:['Explorer et partir à l’aventure','Cuisine, confort et culture','Planifier les détails','Rester spontané'],
    entertainment:['Sortir et être sociable','Films, musique ou spectacles','Jeux et activités interactives','Un mélange de tout'],
    daily:['Routine structurée','Routine flexible','Rythme lent et tranquille','Rythme rapide et productif'],
    openness:['Très ouvert','Ouvert, mais avec prudence','Privé sur certaines choses','Cela dépend du sujet'],
    change:['Les deux devraient s’adapter','Se retrouver à mi-chemin','Respecter la différence','Cela dépend de son importance'],
    qualities:['Honnêteté et intégrité','Gentillesse et empathie','Fiabilité et ambition','Humour et chaleur'],
    gatherings:['J’adore les réunions fréquentes','Je les apprécie parfois','À petites doses','Je les préfère rares'],
    pace:['Rapide et ambitieux','Équilibré et stable','Lent et détendu','Cela change selon la période de vie'],
    windfall:['Épargner ou investir','Payer les factures ou dettes','En profiter ensemble','Partager entre épargne et plaisir'],
    income:['Contribuer selon le revenu','Tout mettre en commun','Partager les dépenses à parts égales','Choisir ensemble ce qui est juste'],
    risk:['Oui, avec une bonne préparation','Peut-être, avec des limites claires','Seulement avec de fortes protections','Non, le risque est trop élevé'],
    alone:['Un peu chaque jour','Quelques heures régulièrement','Une journée entière parfois','Beaucoup d’indépendance'],
    privacy:['Non, les messages privés restent privés','Seulement avec une permission claire','Seulement en cas d’urgence grave','Nous devrions avoir un accès ouvert'],
    futureGoal:['Construire un foyer ou une famille','Voyages et expériences','Évolution professionnelle et financière','Épanouissement personnel et liberté'],
    tripChoice:['Ville et culture','Nature et aventure','Plage et détente','Laisser la destination me surprendre'],
    surpriseFail:['Rire et s’adapter','Essayer de réparer le plan','Faire une pause et refaire un plan','Je serais probablement frustré'],
    spontaneity:['Je pourrais partir demain','J’ai besoin d’un peu de préparation','Il me faut d’abord un plan solide','Je fais rarement des changements soudains'],
    humorType:['Sec ou spirituel','Bête et joueur','Noir ou provocateur','Histoires et humour d’observation'],
    hobbyTime:['Oui, régulièrement','Parfois, quand cela vient naturellement','Seulement si les deux aiment','Des loisirs séparés conviennent très bien'],
    travelPriority:['Les expériences partagées','Le confort et la détente','La cuisine et la culture','Un voyage sans stress'],
    effort:['Les essayer souvent','Les essayer parfois','Les soutenir sans participer souvent','Garder des loisirs plutôt séparés'],
    morning:['Debout tôt et productif','Lent et paisible','Flexible selon le jour','Clairement nocturne'],
    freeHour:['Me reposer et recharger','La passer avec quelqu’un que j’aime','Faire quelque chose d’utile','Faire quelque chose de spontané'],
    predictability:['Surtout de la prévisibilité','Surtout de la surprise','Un bon équilibre des deux','Cela dépend de la période de vie'],
    yesNo:['Oui, certainement','Probablement, avec des efforts','Peut-être, selon la différence','Probablement pas'],
    familyDisapproval:['Ma relation et mon propre jugement','Comprendre les inquiétudes de ma famille','Trouver un terrain d’entente','Cela dépend de la raison du désaccord'],
    competingDreams:['L’opportunité la plus urgente','Celle qui profite le plus aux deux','Soutenir chaque rêve à tour de rôle','Trouver ensemble une troisième option'],
    relocation:['Oui, je pourrais déménager','Peut-être, pour la bonne opportunité','Seulement temporairement ou sous conditions','Non, rester près de la famille compte trop'],
    qualityTime:['Oui, le temps partagé compte plus que les mêmes goûts','Souvent, si nous restons curieux l’un de l’autre','Peut-être, mais cela demande un effort conscient','Probablement pas pour moi'],
  },
  it: {
    weekend:['Attivo e avventuroso','Rilassato e accogliente','Sociale e dinamico','Un mix di tutti e tre'],
    importance:['Essenziale','Molto importante','Abbastanza importante','Poco importante'],
    tradeoff:['Proteggere la relazione','Proteggere il piano a lungo termine','Trovare un compromesso pratico','Dipende dalla situazione'],
    timing:['Parlarne subito','Fare prima una breve pausa','Aspettare che entrambi siano pronti','Ho bisogno di molto tempo'],
    disagreement:['Capirsi prima','Risolvere prima il problema','Mantenere rispetto nella conversazione','Dipende dal problema'],
    repair:['Ascoltare di nuovo prima di rispondere','Spiegarlo in un altro modo','Fare una pausa e tornare più calmi','Dipende da cosa è successo'],
    similarity:['Molto importante essere allineati','Utile, ma non necessario','Le differenze possono funzionare','Dipende dall’argomento'],
    involvement:['Molto coinvolti insieme','Un po’ coinvolti con limiti chiari','Per lo più indipendenti come coppia','Dipende dalla situazione'],
    structure:['Mi piace un piano chiaro','Preferisco flessibilità','Un equilibrio tra i due','Dipende dalla giornata'],
    money:['Risparmiare e pianificare prima','Godersi la vita adesso','Bilanciare risparmio e spesa','Dipende dall’obiettivo'],
    boundary:['Mantenere il limite fermo','Consentire un po’ di flessibilità','Decidere caso per caso','Parlarne insieme'],
    future:['Pianificare con largo anticipo','Adattarsi mentre la vita cambia','Pianificare solo le cose importanti','Restare piuttosto spontanei'],
    fun:['Avventuroso','Giocoso e divertente','Rilassato e semplice','Un mix secondo l’umore'],
    humor:['Scherzare su quasi tutto','Essere giocosi ma conoscere il limite','Tenere seri gli argomenti seri','Dipende dal momento'],
    activities:['Attivo e all’aperto','Creativo o manuale','Rilassarsi insieme','Un mix di cose diverse'],
    travel:['Esplorare e avventurarsi','Cibo, comfort e cultura','Pianificare i dettagli','Restare spontanei'],
    entertainment:['Uscire e socializzare','Film, musica o spettacoli','Giochi e divertimento interattivo','Un mix di tutto'],
    daily:['Routine strutturata','Routine flessibile','Ritmo lento e tranquillo','Ritmo veloce e produttivo'],
    openness:['Molto aperto','Aperto, ma con attenzione','Privato su alcune cose','Dipende dall’argomento'],
    change:['Entrambi dovrebbero adattarsi','Incontrarsi a metà strada','Rispettare la differenza','Dipende da quanto è serio'],
    qualities:['Onestà e integrità','Gentilezza ed empatia','Affidabilità e ambizione','Umorismo e calore'],
    gatherings:['Amo gli incontri frequenti','Mi piacciono ogni tanto','Meglio a piccole dosi','Li preferisco rari'],
    pace:['Veloce e ambizioso','Equilibrato e stabile','Lento e rilassato','Cambia con la fase della vita'],
    windfall:['Risparmiare o investire','Pagare bollette o debiti','Goderselo insieme','Dividere tra risparmio e divertimento'],
    income:['Contribuire in proporzione al reddito','Mettere tutto in comune','Dividere equamente le spese comuni','Scegliere insieme ciò che è giusto'],
    risk:['Sì, con una buona pianificazione','Forse, con limiti chiari','Solo con forti tutele','No, il rischio è troppo alto'],
    alone:['Un po’ ogni giorno','Qualche ora regolarmente','Un giorno intero ogni tanto','Molta indipendenza'],
    privacy:['No, i messaggi privati restano privati','Solo con un permesso chiaro','Solo in una grave emergenza','Dovremmo avere accesso aperto'],
    futureGoal:['Costruire casa o famiglia','Viaggi ed esperienze','Crescita professionale e finanziaria','Crescita personale e libertà'],
    tripChoice:['Città e cultura','Natura e avventura','Spiaggia e relax','Lasciarmi sorprendere dalla destinazione'],
    surpriseFail:['Ridere e adattarsi','Provare a sistemare il piano','Fare una pausa e rifare il piano','Probabilmente mi frustrerei'],
    spontaneity:['Potrei partire domani','Mi serve un po’ di preparazione','Mi serve prima un piano solido','Faccio raramente cambi improvvisi'],
    humorType:['Secco o arguto','Sciocco e giocoso','Nero o provocatorio','Storie e umorismo di osservazione'],
    hobbyTime:['Sì, regolarmente','A volte, quando viene naturale','Solo se piace a entrambi','Gli hobby separati vanno benissimo'],
    travelPriority:['Esperienze condivise','Comfort e relax','Cibo e cultura','Un viaggio senza stress'],
    effort:['Provarli spesso','Provarli a volte','Sostenerli senza partecipare spesso','Tenere l’intrattenimento più separato'],
    morning:['Presto e produttivo','Lento e tranquillo','Flessibile secondo il giorno','Decisamente nottambulo'],
    freeHour:['Riposare e ricaricarmi','Passarla con qualcuno a cui tengo','Fare qualcosa di utile','Fare qualcosa di spontaneo'],
    predictability:['Più prevedibilità','Più sorpresa','Un equilibrio sano di entrambe','Dipende dalla fase della vita'],
    yesNo:['Sì, sicuramente','Probabilmente, con impegno','Forse, dipende dalla differenza','Probabilmente no'],
    familyDisapproval:['La mia relazione e il mio giudizio','Capire le preoccupazioni della famiglia','Trovare un punto d’incontro','Dipende dal motivo della disapprovazione'],
    competingDreams:['L’opportunità più urgente','Quella che giova di più a entrambi','Alternarsi nel sostenere ogni sogno','Trovare insieme una terza opzione'],
    relocation:['Sì, potrei trasferirmi','Forse, per l’opportunità giusta','Solo temporaneamente o con condizioni','No, stare vicino alla famiglia conta troppo'],
    qualityTime:['Sì, il tempo condiviso conta più degli stessi gusti','Di solito, se restiamo curiosi l’uno dell’altro','Forse, ma richiede impegno intenzionale','Probabilmente non per me'],
  },
  de: {
    weekend:['Aktiv und abenteuerlich','Entspannt und gemütlich','Gesellig und unternehmungslustig','Eine Mischung aus allem'],
    importance:['Unverzichtbar','Sehr wichtig','Etwas wichtig','Nicht besonders wichtig'],
    tradeoff:['Die Beziehung schützen','Den langfristigen Plan schützen','Einen tragfähigen Kompromiss finden','Es kommt auf die Situation an'],
    timing:['Sofort darüber sprechen','Erst kurz Pause machen','Warten, bis beide bereit sind','Ich brauche viel Zeit'],
    disagreement:['Erst einander verstehen','Erst das Problem lösen','Respektvoll bleiben','Es kommt auf das Thema an'],
    repair:['Noch einmal zuhören, bevor man antwortet','Es anders erklären','Pause machen und ruhiger zurückkommen','Es kommt darauf an, was passiert ist'],
    similarity:['Sehr wichtig, ähnlich zu sein','Hilfreich, aber nicht nötig','Unterschiede können gut funktionieren','Es kommt auf das Thema an'],
    involvement:['Sehr stark gemeinsam eingebunden','Etwas Beteiligung mit klaren Grenzen','Als Paar eher unabhängig','Es kommt auf die Situation an'],
    structure:['Ich mag einen klaren Plan','Ich bevorzuge Flexibilität','Eine Mischung aus beidem','Es kommt auf den Tag an'],
    money:['Zuerst sparen und planen','Das Leben jetzt genießen','Sparen und Ausgeben ausgleichen','Es kommt auf das Ziel an'],
    boundary:['Die Grenze klar halten','Etwas Flexibilität zulassen','Von Fall zu Fall entscheiden','Gemeinsam darüber sprechen'],
    future:['Weit im Voraus planen','Sich an Veränderungen anpassen','Nur die großen Dinge planen','Meist spontan bleiben'],
    fun:['Abenteuerlich','Verspielt und albern','Entspannt und unkompliziert','Je nach Stimmung eine Mischung'],
    humor:['Über fast alles scherzen','Verspielt sein, aber die Grenze kennen','Ernste Themen ernst lassen','Es kommt auf den Moment an'],
    activities:['Aktiv und draußen','Kreativ oder praktisch','Gemeinsam entspannen','Eine Mischung verschiedener Dinge'],
    travel:['Entdecken und Abenteuer erleben','Essen, Komfort und Kultur','Die Details planen','Spontan bleiben'],
    entertainment:['Ausgehen und gesellig sein','Filme, Musik oder Shows','Spiele und interaktive Aktivitäten','Eine Mischung aus allem'],
    daily:['Strukturierte Routine','Flexible Routine','Langsames und ruhiges Tempo','Schnelles und produktives Tempo'],
    openness:['Sehr offen','Offen, aber mit Bedacht','Bei manchen Dingen privat','Es kommt auf das Thema an'],
    change:['Beide sollten sich anpassen','Sich in der Mitte treffen','Den Unterschied respektieren','Es hängt davon ab, wie ernst es ist'],
    qualities:['Ehrlichkeit und Integrität','Freundlichkeit und Empathie','Zuverlässigkeit und Ehrgeiz','Humor und Wärme'],
    gatherings:['Ich liebe häufige Familientreffen','Manchmal genieße ich sie','Am besten in kleinen Dosen','Ich mag sie lieber selten'],
    pace:['Schnell und ehrgeizig','Ausgeglichen und stetig','Langsam und entspannt','Das ändert sich je nach Lebensphase'],
    windfall:['Sparen oder investieren','Rechnungen oder Schulden zahlen','Gemeinsam genießen','Zwischen Sparen und Spaß aufteilen'],
    income:['Nach Einkommen prozentual beitragen','Alles gemeinsam verwalten','Gemeinsame Kosten gleich teilen','Gemeinsam entscheiden, was fair ist'],
    risk:['Ja, wenn wir gut planen','Vielleicht, mit klaren Grenzen','Nur mit starken Absicherungen','Nein, das Risiko ist zu hoch'],
    alone:['Etwas jeden Tag','Regelmäßig ein paar Stunden','Manchmal einen ganzen Tag','Viel Unabhängigkeit'],
    privacy:['Nein, private Nachrichten bleiben privat','Nur mit klarer Erlaubnis','Nur in einem ernsten Notfall','Wir sollten offenen Zugang haben'],
    futureGoal:['Zuhause oder Familie aufbauen','Reisen und Erlebnisse','Berufliches und finanzielles Wachstum','Persönliche Entwicklung und Freiheit'],
    tripChoice:['Stadt und Kultur','Natur und Abenteuer','Strand und Entspannung','Mich vom Ziel überraschen lassen'],
    surpriseFail:['Lachen und anpassen','Versuchen, den Plan zu retten','Pause machen und neu planen','Ich wäre wahrscheinlich frustriert'],
    spontaneity:['Ich könnte morgen los','Ich brauche etwas Vorbereitung','Ich brauche zuerst einen soliden Plan','Ich ändere selten spontan alles'],
    humorType:['Trocken oder schlagfertig','Albern und verspielt','Dunkel oder gewagt','Geschichten und Beobachtungshumor'],
    hobbyTime:['Ja, regelmäßig','Manchmal, wenn es natürlich passt','Nur wenn beide es mögen','Getrennte Hobbys sind völlig in Ordnung'],
    travelPriority:['Gemeinsame Erlebnisse','Komfort und Entspannung','Essen und Kultur','Möglichst wenig Reisestress'],
    effort:['Oft ausprobieren','Manchmal ausprobieren','Unterstützen, ohne oft mitzumachen','Unterhaltung eher getrennt halten'],
    morning:['Früh auf und produktiv','Langsam und ruhig','Flexibel je nach Tag','Eindeutig eine Nachteule'],
    freeHour:['Ausruhen und auftanken','Mit einem geliebten Menschen verbringen','Etwas Nützliches erledigen','Etwas Spontanes tun'],
    predictability:['Meist Vorhersehbarkeit','Meist Überraschung','Eine gesunde Mischung aus beidem','Es kommt auf die Lebensphase an'],
    yesNo:['Ja, auf jeden Fall','Wahrscheinlich, mit Arbeit daran','Vielleicht, je nach Unterschied','Wahrscheinlich nicht'],
    familyDisapproval:['Meine Beziehung und mein eigenes Urteil','Die Sorgen meiner Familie verstehen','Einen Mittelweg finden','Es kommt auf den Grund der Ablehnung an'],
    competingDreams:['Die zeitkritischere Chance','Was uns beiden am meisten nützt','Abwechselnd jeden Traum unterstützen','Gemeinsam eine dritte Lösung finden'],
    relocation:['Ja, ich könnte umziehen','Vielleicht, für die richtige Chance','Nur vorübergehend oder unter Bedingungen','Nein, Familiennähe ist mir zu wichtig'],
    qualityTime:['Ja, gemeinsame Zeit zählt mehr als gleicher Geschmack','Meistens, wenn wir neugierig aufeinander bleiben','Vielleicht, aber es braucht bewusste Mühe','Wahrscheinlich nicht für mich'],
  },
};

const STYLE = {
  'Relationship Goals': {easy:'weekend',real:'importance',deep:'tradeoff'},
  Communication: {easy:'timing',real:'disagreement',deep:'repair'},
  Values: {easy:'qualities',real:'importance',deep:'yesNo'},
  Family: {easy:'gatherings',real:'involvement',deep:'familyDisapproval'},
  Lifestyle: {easy:'pace',real:'importance',deep:'yesNo'},
  'Money & Ambition': {easy:'windfall',real:'income',deep:'risk'},
  Boundaries: {easy:'alone',real:'privacy',deep:'boundary'},
  'Future Priorities': {easy:'futureGoal',real:'future',deep:'competingDreams'},
  'Fun Scenarios': {easy:'tripChoice',real:'surpriseFail',deep:'spontaneity'},
  Humor: {easy:'humorType',real:'importance',deep:'humor'},
  Activities: {easy:'activities',real:'hobbyTime',deep:'change'},
  'Food & Travel': {easy:'travel',real:'travelPriority',deep:'relocation'},
  Entertainment: {easy:'entertainment',real:'effort',deep:'qualityTime'},
  'Daily Preferences': {easy:'morning',real:'importance',deep:'change'},
  'Wild Card': {easy:'freeHour',real:'predictability',deep:'openness'},
}

export function getLikeMindedAnswerChoices(category, depth, language = 'en') {
  const lang = TEXT[language] ? language : 'en';
  const key = STYLE[category]?.[depthKey(depth)] || 'openness';
  return TEXT[lang][key] || TEXT.en[key] || TEXT.en.openness;
}

export function normalizeLikeMindedTier(value) {
  const raw = String(value || '').trim().toLowerCase();
  if (raw === 'exclusive' || raw === 'elite') return 'Exclusive';
  return 'Premiere';
}
