export const MEMBERSHIP_COPY = {
  en: {
    subscription: {
      back: 'Back', eyebrow: 'One2OneLove Membership', title: 'Start free. Go deeper when you are ready.', subtitle: 'Your free account keeps the Love Note and community experience open. One simple membership adds the reviewed premium relationship-growth tools.', alwaysFree: 'Always free', freeAccount: 'Free Account', createFree: 'Create Free Account', launchMembership: 'Launch membership', monthly: '/ month', firstMonths: 'for the first 6 months', thenPrice: 'Then $5.99 / month unless canceled. No separate free trial.',
      freeFeatures: ['365 Love Notes: browse, write, send, reveal, reply and save', 'Core Live Community rooms and participation', 'Love Language Quiz and Date Ideas', 'Member profile and privacy-limited member discovery', 'Accepted connections and private text Chat'],
      paidFeatures: ['AI Relationship Coach', 'AI Content Creator for romantic messages and ideas', 'Relationship Goals and progress tracking'],
      secureCheckout: 'Checkout is server-controlled. Your browser cannot choose a different price, Stripe Price ID, user account, or billing email.', rollout: 'The free-versus-membership boundary is approved. Checkout remains off only until the controlled backend and Stripe test sequence is complete.', checking: 'Checking membership…', active: 'Membership active', periodEnds: 'Current billing period ends', manage: 'Manage Billing', checkoutStaged: 'Checkout opens after controlled billing test', start: 'Start Membership', signIn: 'Sign In to Continue', checkoutUnavailable: 'Membership checkout is unavailable right now.', billingUnavailable: 'Billing management is unavailable right now.', development: 'Paid feature gating and live billing remain disabled in this development build until the controlled rollout prerequisites pass.'
    },
    payment: {
      checkingTitle: 'Checking your membership', checkingBody: "We are checking One2OneLove's server-side membership record. This page does not treat its URL as proof of payment.", activeEyebrow: 'One2OneLove Membership', activeTitle: 'Membership confirmed', activeBody: 'Your active membership status was confirmed from the server-side membership record.', introThrough: 'Intro pricing is scheduled through', processingTitle: 'Your checkout is still processing', processingBody: 'A checkout session marker was present, but we have not received a confirmed active membership state yet. Access will not be granted until the server-side record is active.', disabledTitle: 'Membership checkout is not active yet', disabledBody: 'Live billing is still disabled during the controlled relaunch build. No new paid membership is being claimed from this page.', unverifiedTitle: 'No verified checkout was found', unverifiedBody: 'This return URL did not include the expected checkout session marker, and no active membership was confirmed. Nothing has been marked paid from this page.', home: 'Back to One2OneLove', details: 'Membership Details'
    }
  },
  es: {
    subscription: {
      back: 'Volver', eyebrow: 'Membresía One2OneLove', title: 'Empieza gratis. Profundiza cuando estés listo.', subtitle: 'Tu cuenta gratis mantiene abiertos Love Notes y la comunidad. Una sola membresía añade las herramientas premium de crecimiento relacional ya revisadas.', alwaysFree: 'Siempre gratis', freeAccount: 'Cuenta Gratis', createFree: 'Crear Cuenta Gratis', launchMembership: 'Membresía de lanzamiento', monthly: '/ mes', firstMonths: 'durante los primeros 6 meses', thenPrice: 'Luego $5.99 / mes hasta que canceles. Sin prueba gratis adicional.',
      freeFeatures: ['365 Love Notes: explorar, escribir, enviar, revelar, responder y guardar', 'Salas principales de Live Community y participación', 'Quiz de Lenguajes del Amor e Ideas para Citas', 'Perfil y descubrimiento de miembros limitado por privacidad', 'Conexiones aceptadas y Chat privado de texto'],
      paidFeatures: ['Coach de Relaciones con IA', 'Creador de Contenido IA para mensajes e ideas románticas', 'Metas de Relación y seguimiento del progreso'],
      secureCheckout: 'El pago se crea en el servidor. El navegador no puede elegir otro precio, ID de Stripe, cuenta de usuario ni correo de facturación.', rollout: 'La separación entre cuenta gratis y membresía está aprobada. El pago sigue apagado solo hasta completar las pruebas controladas del backend y Stripe.', checking: 'Comprobando membresía…', active: 'Membresía activa', periodEnds: 'El período de facturación actual termina', manage: 'Administrar Facturación', checkoutStaged: 'El pago se abre después de la prueba controlada', start: 'Iniciar Membresía', signIn: 'Inicia Sesión para Continuar', checkoutUnavailable: 'El pago de membresía no está disponible ahora.', billingUnavailable: 'La administración de facturación no está disponible ahora.', development: 'Las funciones de pago y la facturación en vivo siguen desactivadas en esta versión hasta completar los requisitos del despliegue controlado.'
    },
    payment: {
      checkingTitle: 'Comprobando tu membresía', checkingBody: 'Estamos comprobando el registro de membresía del servidor de One2OneLove. Esta página no trata su URL como prueba de pago.', activeEyebrow: 'Membresía One2OneLove', activeTitle: 'Membresía confirmada', activeBody: 'Tu membresía activa fue confirmada desde el registro del servidor.', introThrough: 'El precio inicial está programado hasta', processingTitle: 'Tu pago todavía se está procesando', processingBody: 'Había un marcador de sesión de pago, pero aún no recibimos una membresía activa confirmada. El acceso no se concede hasta que el registro del servidor esté activo.', disabledTitle: 'El pago de membresía aún no está activo', disabledBody: 'La facturación en vivo sigue desactivada durante el relanzamiento controlado. Esta página no está declarando ninguna nueva membresía pagada.', unverifiedTitle: 'No se encontró un pago verificado', unverifiedBody: 'Esta URL no incluía el marcador esperado de Stripe y no se confirmó una membresía activa. Nada se ha marcado como pagado desde esta página.', home: 'Volver a One2OneLove', details: 'Detalles de Membresía'
    }
  },
  fr: {
    subscription: {
      back: 'Retour', eyebrow: 'Adhésion One2OneLove', title: 'Commencez gratuitement. Allez plus loin quand vous êtes prêt.', subtitle: 'Votre compte gratuit garde ouverts les Love Notes et la communauté. Une seule adhésion ajoute les outils premium de croissance relationnelle déjà examinés.', alwaysFree: 'Toujours gratuit', freeAccount: 'Compte Gratuit', createFree: 'Créer un Compte Gratuit', launchMembership: 'Adhésion de lancement', monthly: '/ mois', firstMonths: 'pendant les 6 premiers mois', thenPrice: 'Puis $5.99 / mois jusqu’à annulation. Aucun essai gratuit séparé.',
      freeFeatures: ['365 Love Notes : parcourir, écrire, envoyer, révéler, répondre et enregistrer', 'Salles principales de Live Community et participation', 'Quiz des Langages de l’Amour et Idées de Rendez-vous', 'Profil et découverte des membres limitée pour la confidentialité', 'Connexions acceptées et Chat texte privé'],
      paidFeatures: ['Coach Relationnel IA', 'Créateur de Contenu IA pour messages et idées romantiques', 'Objectifs de Relation et suivi des progrès'],
      secureCheckout: 'Le paiement est créé côté serveur. Le navigateur ne peut pas choisir un autre prix, identifiant Stripe, compte utilisateur ou e-mail de facturation.', rollout: 'La limite entre compte gratuit et adhésion est approuvée. Le paiement reste désactivé uniquement jusqu’à la fin des tests contrôlés du backend et de Stripe.', checking: 'Vérification de l’adhésion…', active: 'Adhésion active', periodEnds: 'La période de facturation actuelle se termine le', manage: 'Gérer la Facturation', checkoutStaged: 'Le paiement ouvrira après le test contrôlé', start: 'Démarrer l’Adhésion', signIn: 'Se Connecter pour Continuer', checkoutUnavailable: 'Le paiement de l’adhésion est indisponible pour le moment.', billingUnavailable: 'La gestion de la facturation est indisponible pour le moment.', development: 'Les fonctions payantes et la facturation en direct restent désactivées dans cette version jusqu’à la réussite des prérequis du déploiement contrôlé.'
    },
    payment: {
      checkingTitle: 'Vérification de votre adhésion', checkingBody: 'Nous vérifions le statut d’adhésion côté serveur de One2OneLove. Cette page ne considère pas son URL comme une preuve de paiement.', activeEyebrow: 'Adhésion One2OneLove', activeTitle: 'Adhésion confirmée', activeBody: 'Votre adhésion active a été confirmée à partir du registre côté serveur.', introThrough: 'Le tarif de lancement est prévu jusqu’au', processingTitle: 'Votre paiement est toujours en cours', processingBody: 'Un marqueur de session de paiement était présent, mais aucun statut actif confirmé n’a encore été reçu. L’accès n’est accordé qu’après confirmation côté serveur.', disabledTitle: 'Le paiement de l’adhésion n’est pas encore actif', disabledBody: 'La facturation en direct reste désactivée pendant la relance contrôlée. Cette page ne revendique aucune nouvelle adhésion payée.', unverifiedTitle: 'Aucun paiement vérifié trouvé', unverifiedBody: 'Cette URL ne contenait pas le marqueur Stripe attendu et aucune adhésion active n’a été confirmée. Rien n’a été marqué comme payé depuis cette page.', home: 'Retour à One2OneLove', details: 'Détails de l’Adhésion'
    }
  },
  it: {
    subscription: {
      back: 'Indietro', eyebrow: 'Abbonamento One2OneLove', title: 'Inizia gratis. Vai più in profondità quando sei pronto.', subtitle: 'L’account gratuito mantiene aperti Love Notes e community. Un unico abbonamento aggiunge gli strumenti premium di crescita relazionale già revisionati.', alwaysFree: 'Sempre gratis', freeAccount: 'Account Gratuito', createFree: 'Crea Account Gratuito', launchMembership: 'Abbonamento di lancio', monthly: '/ mese', firstMonths: 'per i primi 6 mesi', thenPrice: 'Poi $5.99 / mese fino alla cancellazione. Nessuna prova gratuita separata.',
      freeFeatures: ['365 Love Notes: sfoglia, scrivi, invia, rivela, rispondi e salva', 'Stanze principali della Live Community e partecipazione', 'Quiz dei Linguaggi dell’Amore e Idee per Appuntamenti', 'Profilo e scoperta membri limitata per la privacy', 'Connessioni accettate e Chat privata testuale'],
      paidFeatures: ['Coach Relazionale IA', 'Creatore di Contenuti IA per messaggi e idee romantiche', 'Obiettivi di Relazione e monitoraggio dei progressi'],
      secureCheckout: 'Il checkout è creato dal server. Il browser non può scegliere un prezzo diverso, ID Stripe, account utente o email di fatturazione.', rollout: 'Il confine tra account gratuito e abbonamento è approvato. Il checkout resta spento solo fino al completamento dei test controllati del backend e Stripe.', checking: 'Controllo abbonamento…', active: 'Abbonamento attivo', periodEnds: 'Il periodo di fatturazione attuale termina', manage: 'Gestisci Fatturazione', checkoutStaged: 'Il checkout apre dopo il test controllato', start: 'Avvia Abbonamento', signIn: 'Accedi per Continuare', checkoutUnavailable: 'Il checkout dell’abbonamento non è disponibile ora.', billingUnavailable: 'La gestione della fatturazione non è disponibile ora.', development: 'Le funzioni a pagamento e la fatturazione live restano disattivate in questa versione finché non superano i prerequisiti del rilascio controllato.'
    },
    payment: {
      checkingTitle: 'Controllo del tuo abbonamento', checkingBody: 'Stiamo controllando il registro server dell’abbonamento One2OneLove. Questa pagina non considera il proprio URL una prova di pagamento.', activeEyebrow: 'Abbonamento One2OneLove', activeTitle: 'Abbonamento confermato', activeBody: 'Il tuo abbonamento attivo è stato confermato dal registro server.', introThrough: 'Il prezzo introduttivo è programmato fino al', processingTitle: 'Il checkout è ancora in elaborazione', processingBody: 'Era presente un indicatore della sessione di checkout, ma non abbiamo ancora ricevuto uno stato attivo confermato. L’accesso non viene concesso finché il registro server non è attivo.', disabledTitle: 'Il checkout dell’abbonamento non è ancora attivo', disabledBody: 'La fatturazione live resta disattivata durante il rilancio controllato. Questa pagina non sta dichiarando alcun nuovo abbonamento pagato.', unverifiedTitle: 'Nessun checkout verificato trovato', unverifiedBody: 'Questo URL non conteneva l’indicatore Stripe previsto e non è stato confermato alcun abbonamento attivo. Nulla è stato segnato come pagato da questa pagina.', home: 'Torna a One2OneLove', details: 'Dettagli Abbonamento'
    }
  },
  de: {
    subscription: {
      back: 'Zurück', eyebrow: 'One2OneLove Mitgliedschaft', title: 'Kostenlos starten. Tiefer gehen, wenn du bereit bist.', subtitle: 'Dein kostenloses Konto hält Love Notes und Community offen. Eine einfache Mitgliedschaft ergänzt die bereits geprüften Premium-Werkzeuge für Beziehungswachstum.', alwaysFree: 'Immer kostenlos', freeAccount: 'Kostenloses Konto', createFree: 'Kostenloses Konto Erstellen', launchMembership: 'Relaunch-Mitgliedschaft', monthly: '/ Monat', firstMonths: 'für die ersten 6 Monate', thenPrice: 'Danach $5.99 / Monat bis zur Kündigung. Keine separate kostenlose Testphase.',
      freeFeatures: ['365 Love Notes: durchsuchen, schreiben, senden, enthüllen, antworten und speichern', 'Kernräume der Live Community und Teilnahme', 'Liebessprachen-Quiz und Date-Ideen', 'Profil und datenschutzbegrenzte Mitgliedersuche', 'Akzeptierte Verbindungen und privater Text-Chat'],
      paidFeatures: ['KI-Beziehungscoach', 'KI-Content-Ersteller für romantische Nachrichten und Ideen', 'Beziehungsziele und Fortschrittsverfolgung'],
      secureCheckout: 'Checkout wird serverseitig erstellt. Der Browser kann keinen anderen Preis, keine Stripe-Preis-ID, kein Benutzerkonto und keine Abrechnungs-E-Mail auswählen.', rollout: 'Die Grenze zwischen kostenlosem Konto und Mitgliedschaft ist genehmigt. Checkout bleibt nur bis zum Abschluss der kontrollierten Backend- und Stripe-Tests aus.', checking: 'Mitgliedschaft wird geprüft…', active: 'Mitgliedschaft aktiv', periodEnds: 'Der aktuelle Abrechnungszeitraum endet am', manage: 'Abrechnung Verwalten', checkoutStaged: 'Checkout öffnet nach dem kontrollierten Test', start: 'Mitgliedschaft Starten', signIn: 'Anmelden zum Fortfahren', checkoutUnavailable: 'Mitgliedschafts-Checkout ist derzeit nicht verfügbar.', billingUnavailable: 'Abrechnungsverwaltung ist derzeit nicht verfügbar.', development: 'Bezahlte Funktionen und Live-Abrechnung bleiben in dieser Version deaktiviert, bis die Voraussetzungen des kontrollierten Rollouts erfüllt sind.'
    },
    payment: {
      checkingTitle: 'Mitgliedschaft wird geprüft', checkingBody: 'Wir prüfen den serverseitigen One2OneLove-Mitgliedschaftsstatus. Diese Seite behandelt ihre URL nicht als Zahlungsnachweis.', activeEyebrow: 'One2OneLove Mitgliedschaft', activeTitle: 'Mitgliedschaft bestätigt', activeBody: 'Deine aktive Mitgliedschaft wurde anhand des serverseitigen Datensatzes bestätigt.', introThrough: 'Der Einführungspreis ist geplant bis', processingTitle: 'Dein Checkout wird noch verarbeitet', processingBody: 'Ein Checkout-Sitzungsmarker war vorhanden, aber wir haben noch keinen bestätigten aktiven Mitgliedschaftsstatus erhalten. Zugriff wird erst gewährt, wenn der serverseitige Datensatz aktiv ist.', disabledTitle: 'Mitgliedschafts-Checkout ist noch nicht aktiv', disabledBody: 'Live-Abrechnung bleibt während des kontrollierten Relaunchs deaktiviert. Diese Seite behauptet keine neue bezahlte Mitgliedschaft.', unverifiedTitle: 'Kein verifizierter Checkout gefunden', unverifiedBody: 'Diese Rückkehr-URL enthielt nicht den erwarteten Stripe-Marker und es wurde keine aktive Mitgliedschaft bestätigt. Von dieser Seite wurde nichts als bezahlt markiert.', home: 'Zurück zu One2OneLove', details: 'Mitgliedschaftsdetails'
    }
  }
};

export const getMembershipCopy = (language) => MEMBERSHIP_COPY[language] || MEMBERSHIP_COPY.en;
