-- ============================================================================
-- ONE2ONELOVE PLATFORM REVIEWS
-- Real member reviews only. Reviewer identity/location are sourced from profile.
-- Run this against the One2OneLove Supabase database before enabling submissions.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Reviews require City and Country to be part of the member profile.
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS country TEXT;

-- Preserve existing profile location data as the initial City value where needed.
UPDATE public.users
SET city = NULLIF(BTRIM(location), '')
WHERE NULLIF(BTRIM(COALESCE(city, '')), '') IS NULL
  AND NULLIF(BTRIM(COALESCE(location, '')), '') IS NOT NULL;

-- Launch signup already stores country in auth metadata. Backfill the profile column.
UPDATE public.users AS profile
SET country = NULLIF(BTRIM(auth_user.raw_user_meta_data ->> 'country'), '')
FROM auth.users AS auth_user
WHERE profile.id = auth_user.id
  AND NULLIF(BTRIM(COALESCE(profile.country, '')), '') IS NULL
  AND NULLIF(BTRIM(COALESCE(auth_user.raw_user_meta_data ->> 'country', '')), '') IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  reviewer_name TEXT NOT NULL,
  city TEXT NOT NULL,
  country TEXT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  review_text TEXT NOT NULL CHECK (char_length(BTRIM(review_text)) BETWEEN 10 AND 2000),
  is_published BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT reviews_one_per_user UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS reviews_published_created_idx
  ON public.reviews (is_published, created_at DESC);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Published reviews are publicly readable" ON public.reviews;
CREATE POLICY "Published reviews are publicly readable"
ON public.reviews
FOR SELECT
TO anon, authenticated
USING (is_published = TRUE);

-- Do not allow clients to provide reviewer names, cities, countries, or dates.
-- All inserts go through this authenticated function, which reads the member profile
-- and lets Postgres auto-populate created_at.
REVOKE INSERT, UPDATE, DELETE ON public.reviews FROM anon, authenticated;
GRANT SELECT ON public.reviews TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.submit_platform_review(
  p_rating INTEGER,
  p_review_text TEXT
)
RETURNS public.reviews
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_name TEXT;
  v_city TEXT;
  v_country TEXT;
  v_review public.reviews;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'AUTH_REQUIRED';
  END IF;

  IF p_rating IS NULL OR p_rating < 1 OR p_rating > 5 THEN
    RAISE EXCEPTION 'INVALID_RATING';
  END IF;

  IF p_review_text IS NULL OR char_length(BTRIM(p_review_text)) < 10 OR char_length(BTRIM(p_review_text)) > 2000 THEN
    RAISE EXCEPTION 'INVALID_REVIEW_LENGTH';
  END IF;

  SELECT
    NULLIF(BTRIM(name), ''),
    NULLIF(BTRIM(COALESCE(city, location)), ''),
    NULLIF(BTRIM(country), '')
  INTO v_name, v_city, v_country
  FROM public.users
  WHERE id = auth.uid();

  IF v_name IS NULL OR v_city IS NULL OR v_country IS NULL THEN
    RAISE EXCEPTION 'PROFILE_INCOMPLETE';
  END IF;

  INSERT INTO public.reviews (
    user_id,
    reviewer_name,
    city,
    country,
    rating,
    review_text
  )
  VALUES (
    auth.uid(),
    v_name,
    v_city,
    v_country,
    p_rating,
    BTRIM(p_review_text)
  )
  RETURNING * INTO v_review;

  RETURN v_review;
EXCEPTION
  WHEN unique_violation THEN
    RAISE EXCEPTION 'REVIEW_EXISTS';
END;
$$;

REVOKE ALL ON FUNCTION public.submit_platform_review(INTEGER, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.submit_platform_review(INTEGER, TEXT) TO authenticated;

-- ============================================================================
-- DONE
-- Reviewer name, city, and country are copied from the authenticated profile.
-- Review date/time is generated by the database through created_at DEFAULT NOW().
-- ============================================================================
