import React from 'react';
import { Heart, Radio, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { useLanguage } from '@/Layout';

const translations = {
  en: {
    title: 'About One2OneLove', subtitle: 'A relationship platform built to help people connect intentionally, communicate thoughtfully, and keep investing in the relationships that matter to them.', mission: 'Our purpose', missionCopy: 'One2OneLove brings practical relationship tools, couple activities, private shared spaces, educational support, community connection, and relationship-focused programming into one place.', approach: 'How O2OL is being built', privacy: 'Privacy first', privacyCopy: 'Personal relationship information is treated as private by default. Sharing is explicit where supported, and public discovery uses limited directory information rather than private account records.', real: 'Real before impressive', realCopy: 'O2OL does not need invented experts, testimonials, user counts, ratings, prizes, or features. If something is not active yet, the platform should say so clearly.', multilingual: 'Multilingual by design', multilingualCopy: 'The production experience supports English, Spanish, French, Italian, and German, and new user-facing work is expected to fit that same framework.', programming: 'Relationship programming', programmingCopy: 'The O2OL Global Relationship Room combines official O2OL programming, approved creators, replays, partner programming, and specials with scheduling and moderation controls.', hosts: 'O2OL & AMORA', hostsCopy: 'O2OL and AMORA are the platform’s relationship-programming hosts and guide users toward thoughtful reflection, connection, and practical tools.', explore: 'Explore Relationship Tools', room: 'Global Relationship Room', contact: 'Contact One2OneLove' },
  es: {
    title: 'Acerca de One2OneLove', subtitle: 'Una plataforma de relaciones creada para ayudar a las personas a conectar con intención, comunicarse con atención y seguir invirtiendo en las relaciones que importan.', mission: 'Nuestro propósito', missionCopy: 'One2OneLove reúne herramientas prácticas, actividades para parejas, espacios privados compartidos, apoyo educativo, conexión comunitaria y programación centrada en relaciones.', approach: 'Cómo se está construyendo O2OL', privacy: 'Privacidad primero', privacyCopy: 'La información personal de la relación se trata como privada por defecto. Compartir es explícito cuando se admite, y el descubrimiento público usa información limitada del directorio en lugar de registros privados de cuenta.', real: 'Real antes que impresionante', realCopy: 'O2OL no necesita expertos, testimonios, cifras de usuarios, calificaciones, premios o funciones inventadas. Si algo aún no está activo, la plataforma debe decirlo claramente.', multilingual: 'Multilingüe por diseño', multilingualCopy: 'La experiencia de producción admite inglés, español, francés, italiano y alemán, y todo nuevo contenido debe integrarse en ese mismo sistema.', programming: 'Programación de relaciones', programmingCopy: 'La Sala Global de Relaciones combina programación oficial de O2OL, creadores aprobados, repeticiones, programación de socios y especiales con controles de agenda y moderación.', hosts: 'O2OL y AMORA', hostsCopy: 'O2OL y AMORA son los anfitriones de programación de la plataforma y orientan a los usuarios hacia reflexión, conexión y herramientas prácticas.', explore: 'Explorar Herramientas', room: 'Sala Global de Relaciones', contact: 'Contactar a One2OneLove' },
  fr: {
    title: 'À propos de One2OneLove', subtitle: 'Une plateforme relationnelle conçue pour aider les personnes à se connecter avec intention, communiquer avec attention et continuer à investir dans les relations qui comptent.', mission: 'Notre objectif', missionCopy: 'One2OneLove rassemble des outils relationnels pratiques, des activités de couple, des espaces privés partagés, du soutien éducatif, des liens communautaires et une programmation centrée sur les relations.', approach: 'Comment O2OL est construit', privacy: 'La confidentialité d’abord', privacyCopy: 'Les informations relationnelles personnelles sont privées par défaut. Le partage est explicite lorsqu’il est pris en charge, et la découverte publique utilise des informations limitées du répertoire plutôt que les données privées du compte.', real: 'Le réel avant l’impressionnant', realCopy: 'O2OL n’a pas besoin d’experts, témoignages, nombres d’utilisateurs, notes, prix ou fonctions inventés. Si quelque chose n’est pas encore actif, la plateforme doit le dire clairement.', multilingual: 'Multilingue dès la conception', multilingualCopy: 'L’expérience de production prend en charge l’anglais, l’espagnol, le français, l’italien et l’allemand, et tout nouveau contenu doit rejoindre ce même système.', programming: 'Programmation relationnelle', programmingCopy: 'La Salle Mondiale des Relations réunit programmes officiels O2OL, créateurs approuvés, rediffusions, programmes partenaires et spéciaux avec des contrôles de planification et modération.', hosts: 'O2OL & AMORA', hostsCopy: 'O2OL et AMORA sont les animateurs de programmation de la plateforme et orientent les utilisateurs vers la réflexion, la connexion et des outils pratiques.', explore: 'Explorer les Outils', room: 'Salle Mondiale des Relations', contact: 'Contacter One2OneLove' },
  it: {
    title: 'Informazioni su One2OneLove', subtitle: 'Una piattaforma relazionale creata per aiutare le persone a connettersi intenzionalmente, comunicare con attenzione e continuare a investire nelle relazioni importanti.', mission: 'Il nostro scopo', missionCopy: 'One2OneLove riunisce strumenti pratici per le relazioni, attività di coppia, spazi privati condivisi, supporto educativo, connessione con la community e programmazione dedicata alle relazioni.', approach: 'Come viene costruito O2OL', privacy: 'Privacy prima di tutto', privacyCopy: 'Le informazioni personali sulla relazione sono private per impostazione predefinita. La condivisione è esplicita quando supportata e la scoperta pubblica usa informazioni limitate della directory, non i dati privati dell’account.', real: 'Reale prima che impressionante', realCopy: 'O2OL non ha bisogno di esperti, testimonianze, numeri di utenti, valutazioni, premi o funzioni inventate. Se qualcosa non è ancora attivo, la piattaforma deve dirlo chiaramente.', multilingual: 'Multilingue per design', multilingualCopy: 'L’esperienza di produzione supporta inglese, spagnolo, francese, italiano e tedesco e ogni nuovo contenuto deve inserirsi nello stesso sistema.', programming: 'Programmazione relazionale', programmingCopy: 'La Sala Globale delle Relazioni combina programmazione ufficiale O2OL, creator approvati, replay, programmi partner e speciali con controlli di pianificazione e moderazione.', hosts: 'O2OL & AMORA', hostsCopy: 'O2OL e AMORA sono i conduttori della programmazione della piattaforma e guidano gli utenti verso riflessione, connessione e strumenti pratici.', explore: 'Esplora gli Strumenti', room: 'Sala Globale delle Relazioni', contact: 'Contatta One2OneLove' },
  de: {
    title: 'Über One2OneLove', subtitle: 'Eine Beziehungsplattform, die Menschen dabei unterstützt, bewusst Verbindung aufzubauen, aufmerksam zu kommunizieren und weiter in wichtige Beziehungen zu investieren.', mission: 'Unser Zweck', missionCopy: 'One2OneLove vereint praktische Beziehungswerkzeuge, Paaraktivitäten, private gemeinsame Bereiche, pädagogische Unterstützung, Community-Verbindungen und beziehungsorientierte Programme.', approach: 'Wie O2OL gebaut wird', privacy: 'Datenschutz zuerst', privacyCopy: 'Persönliche Beziehungsinformationen sind standardmäßig privat. Teilen erfolgt ausdrücklich, wenn es unterstützt wird, und öffentliche Entdeckung verwendet begrenzte Verzeichnisinformationen statt privater Kontodaten.', real: 'Echt vor beeindruckend', realCopy: 'O2OL braucht keine erfundenen Experten, Testimonials, Nutzerzahlen, Bewertungen, Preise oder Funktionen. Wenn etwas noch nicht aktiv ist, soll die Plattform das klar sagen.', multilingual: 'Mehrsprachig von Anfang an', multilingualCopy: 'Die Produktion unterstützt Englisch, Spanisch, Französisch, Italienisch und Deutsch. Neue nutzerseitige Inhalte müssen in dasselbe System integriert werden.', programming: 'Beziehungsprogramme', programmingCopy: 'Der Globale Beziehungsraum verbindet offizielle O2OL-Programme, genehmigte Creator, Wiederholungen, Partnerprogramme und Specials mit Zeitplan- und Moderationskontrollen.', hosts: 'O2OL & AMORA', hostsCopy: 'O2OL und AMORA sind die Programm-Hosts der Plattform und führen Nutzer zu Reflexion, Verbindung und praktischen Werkzeugen.', explore: 'Beziehungswerkzeuge Entdecken', room: 'Globaler Beziehungsraum', contact: 'One2OneLove Kontaktieren' },
};

export default function AboutUs() {
  const { currentLanguage } = useLanguage();
  const t = translations[currentLanguage] || translations.en;
  const principles = [
    [ShieldCheck, t.privacy, t.privacyCopy],
    [Heart, t.real, t.realCopy],
    [Sparkles, t.multilingual, t.multilingualCopy],
  ];
  return (
    <main className="min-h-screen bg-gradient-to-br from-pink-50 via-white to-purple-50 px-4 py-12 md:py-20">
      <div className="mx-auto max-w-6xl">
        <header className="mx-auto max-w-4xl text-center"><Heart className="mx-auto h-14 w-14 fill-pink-100 text-pink-600" aria-hidden="true" /><h1 className="mt-5 text-4xl font-bold tracking-tight text-slate-900 md:text-5xl">{t.title}</h1><p className="mt-4 text-lg leading-7 text-slate-600">{t.subtitle}</p></header>

        <section className="mx-auto mt-10 max-w-4xl rounded-3xl border border-pink-100 bg-white p-6 shadow-sm md:p-8"><h2 className="text-2xl font-bold text-slate-900">{t.mission}</h2><p className="mt-3 leading-7 text-slate-600">{t.missionCopy}</p></section>

        <section className="mt-12" aria-labelledby="about-principles"><h2 id="about-principles" className="text-center text-2xl font-bold text-slate-900">{t.approach}</h2><div className="mt-6 grid gap-5 md:grid-cols-3">{principles.map(([Icon, title, copy]) => <Card key={title} className="border-slate-200"><CardContent className="p-6"><Icon className="h-7 w-7 text-purple-700" aria-hidden="true" /><h3 className="mt-4 text-lg font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></CardContent></Card>)}</div></section>

        <section className="mt-12 grid gap-5 md:grid-cols-2"><Card><CardContent className="p-6"><Radio className="h-7 w-7 text-fuchsia-700" aria-hidden="true" /><h2 className="mt-4 text-xl font-bold text-slate-900">{t.programming}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.programmingCopy}</p></CardContent></Card><Card><CardContent className="p-6"><Users className="h-7 w-7 text-blue-700" aria-hidden="true" /><h2 className="mt-4 text-xl font-bold text-slate-900">{t.hosts}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.hostsCopy}</p></CardContent></Card></section>

        <div className="mt-10 flex flex-col gap-3 sm:flex-row sm:justify-center"><Button asChild><Link to="/RelationshipLibrary">{t.explore}</Link></Button><Button asChild variant="outline"><Link to="/GlobalRelationshipRoom">{t.room}</Link></Button><Button asChild variant="outline"><Link to="/ContactUs">{t.contact}</Link></Button></div>
      </div>
    </main>
  );
}
