import React from "react";
import { BookOpen, Library, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useLanguage } from "@/Layout";

const translations = {
  en: { title: "Relationship Articles & Guides", subtitle: "One2OneLove is not launching with a fabricated expert article catalog or invented audience claims.", notice: "A real editorial library will be added after launch with accountable authorship, publication dates, review standards, and multilingual content. For launch, the Relationship Library organizes the real O2OL tools and programming already available.", library: "Open Relationship Library", show: "O2OL Show", room: "Global Relationship Room" },
  es: { title: "Artículos y Guías de Relaciones", subtitle: "One2OneLove no se lanza con un catálogo inventado de artículos de expertos ni afirmaciones falsas sobre la audiencia.", notice: "Después del lanzamiento se añadirá una biblioteca editorial real con autoría responsable, fechas de publicación, estándares de revisión y contenido multilingüe. En el lanzamiento, la Biblioteca de Relaciones organiza las herramientas y programación reales de O2OL ya disponibles.", library: "Abrir Biblioteca de Relaciones", show: "O2OL Show", room: "Sala Global de Relaciones" },
  fr: { title: "Articles et Guides Relationnels", subtitle: "One2OneLove ne se lance pas avec un catalogue d’articles d’experts inventé ni de fausses affirmations d’audience.", notice: "Une véritable bibliothèque éditoriale sera ajoutée après le lancement avec des auteurs identifiés, dates de publication, normes de révision et contenu multilingue. Au lancement, la Bibliothèque Relationnelle organise les vrais outils et programmes O2OL déjà disponibles.", library: "Ouvrir la Bibliothèque Relationnelle", show: "O2OL Show", room: "Salle Mondiale des Relations" },
  it: { title: "Articoli e Guide sulle Relazioni", subtitle: "One2OneLove non parte con un catalogo inventato di articoli di esperti o false affermazioni sul pubblico.", notice: "Dopo il lancio verrà aggiunta una vera biblioteca editoriale con autori responsabili, date di pubblicazione, standard di revisione e contenuti multilingue. Al lancio, la Biblioteca delle Relazioni organizza gli strumenti e la programmazione reali O2OL già disponibili.", library: "Apri Biblioteca delle Relazioni", show: "O2OL Show", room: "Sala Globale delle Relazioni" },
  de: { title: "Beziehungsartikel & Leitfäden", subtitle: "One2OneLove startet nicht mit einem erfundenen Experten-Artikelkatalog oder falschen Angaben zur Reichweite.", notice: "Nach dem Start wird eine echte redaktionelle Bibliothek mit nachvollziehbarer Autorenschaft, Veröffentlichungsdaten, Prüfstandards und mehrsprachigen Inhalten aufgebaut. Zum Start organisiert die Beziehungsbibliothek die bereits verfügbaren echten O2OL-Werkzeuge und Programme.", library: "Beziehungsbibliothek Öffnen", show: "O2OL Show", room: "Globaler Beziehungsraum" },
};

export default function ArticlesSupport() {
  const { currentLanguage } = useLanguage();
  const t = translations[currentLanguage] || translations.en;
  return <main className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-violet-50 px-4 py-12 md:py-20"><div className="mx-auto max-w-4xl text-center"><BookOpen className="mx-auto h-14 w-14 text-blue-700" aria-hidden="true"/><h1 className="mt-5 text-4xl font-bold text-slate-900 md:text-5xl">{t.title}</h1><p className="mt-4 text-lg text-slate-600">{t.subtitle}</p><Card className="mx-auto mt-8 max-w-3xl border-blue-100 text-left"><CardContent className="p-6 md:p-8"><div className="flex gap-3 rounded-2xl bg-blue-50 p-5 text-sm leading-6 text-blue-950"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0" aria-hidden="true"/><p>{t.notice}</p></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><Button asChild><Link to="/RelationshipLibrary"><Library className="mr-2 h-4 w-4" aria-hidden="true"/>{t.library}</Link></Button><Button asChild variant="outline"><Link to="/O2OLShow">{t.show}</Link></Button><Button asChild variant="outline"><Link to="/GlobalRelationshipRoom">{t.room}</Link></Button></div></CardContent></Card></div></main>;
}
