import React from "react";
import { BookOpen, Heart, HelpCircle, MessageCircle, Radio, ShieldCheck, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useLanguage } from "@/Layout";

const translations = {
  en: {
    title: "Help Center", subtitle: "Quick guidance for the One2OneLove launch experience.", account: "Account & Profile", accountCopy: "Create an account, sign in, recover your password, and maintain your own profile information.", couple: "Couple Tools", coupleCopy: "Use Love Notes, Shared Journals, Memory Lane, goals, milestones, anniversary tools, calendar, check-ins, rituals, and date activities.", community: "Community & Chat", communityCopy: "Find members through the privacy-safe directory, send a buddy request, and use private chat after the connection is accepted. Community stories are reviewed before publication.", room: "Global Relationship Room", roomCopy: "View live and upcoming programming. Approved creators can use Creator Access to manage scheduling under current Room rules.", ai: "AI features", aiCopy: "The AI Relationship Coach and AI Content Creator are previews at launch. They do not collect relationship details or provide live AI generation yet.", paid: "Paid membership", paidCopy: "Paid membership checkout is not active at launch. No paid tier or charge should be inferred from older test links.", professional: "Professional support", professionalCopy: "O2OL does not operate a verified therapist directory or professional booking service at launch. Relationship Support is educational and not therapy or crisis care.", privacy: "Privacy & sharing", privacyCopy: "Private relationship data stays account-scoped by default. Partner sharing is explicit where supported, and community discovery excludes account email and billing information.", needHelp: "Still need help?", contact: "Contact One2OneLove", library: "Relationship Library" },
  es: {
    title: "Centro de Ayuda", subtitle: "Guía rápida para la experiencia de lanzamiento de One2OneLove.", account: "Cuenta y Perfil", accountCopy: "Crea una cuenta, inicia sesión, recupera tu contraseña y administra la información de tu propio perfil.", couple: "Herramientas de Pareja", coupleCopy: "Usa Notas de Amor, Diarios Compartidos, Camino de Recuerdos, metas, hitos, aniversario, calendario, revisiones semanales, rituales y actividades para citas.", community: "Comunidad y Chat", communityCopy: "Encuentra miembros mediante el directorio seguro, envía una solicitud y usa el chat privado después de aceptar la conexión. Las historias se revisan antes de publicarse.", room: "Sala Global de Relaciones", roomCopy: "Consulta programación en vivo y próxima. Los creadores aprobados pueden usar Acceso de Creadores para gestionar horarios según las reglas actuales.", ai: "Funciones de IA", aiCopy: "El Coach de Relaciones con IA y el Creador de Contenido con IA son vistas previas en el lanzamiento. No recopilan detalles de la relación ni generan contenido con IA todavía.", paid: "Membresía de pago", paidCopy: "El checkout de membresía de pago no está activo en el lanzamiento. Ningún plan de pago o cargo debe inferirse de enlaces de prueba antiguos.", professional: "Apoyo profesional", professionalCopy: "O2OL no opera un directorio verificado de terapeutas ni un servicio de reservas profesionales en el lanzamiento. El Apoyo para Relaciones es educativo y no es terapia ni atención de crisis.", privacy: "Privacidad y uso compartido", privacyCopy: "Los datos privados de la relación permanecen limitados a la cuenta por defecto. Compartir con la pareja es explícito cuando se admite y el descubrimiento comunitario excluye correo y facturación.", needHelp: "¿Aún necesitas ayuda?", contact: "Contactar a One2OneLove", library: "Biblioteca de Relaciones" },
  fr: {
    title: "Centre d’Aide", subtitle: "Guide rapide de l’expérience de lancement One2OneLove.", account: "Compte et Profil", accountCopy: "Créez un compte, connectez-vous, récupérez votre mot de passe et gérez les informations de votre propre profil.", couple: "Outils de Couple", coupleCopy: "Utilisez Notes d’Amour, Journaux Partagés, Souvenirs, objectifs, jalons, anniversaire, calendrier, bilans, rituels et activités de rendez-vous.", community: "Communauté et Chat", communityCopy: "Trouvez des membres via l’annuaire sécurisé, envoyez une demande et utilisez le chat privé après acceptation. Les histoires sont examinées avant publication.", room: "Salle Mondiale des Relations", roomCopy: "Consultez les programmes en direct et à venir. Les créateurs approuvés peuvent gérer leurs horaires via l’Accès Créateur selon les règles actuelles.", ai: "Fonctions IA", aiCopy: "Le Coach Relationnel IA et le Créateur de Contenu IA sont des aperçus au lancement. Ils ne collectent pas de détails relationnels et ne génèrent pas encore de contenu IA en direct.", paid: "Abonnement payant", paidCopy: "Le paiement des abonnements n’est pas actif au lancement. Aucun tarif ou débit ne doit être déduit d’anciens liens de test.", professional: "Soutien professionnel", professionalCopy: "O2OL n’exploite pas d’annuaire vérifié de thérapeutes ni de service de réservation professionnelle au lancement. Le soutien relationnel est éducatif et ne constitue ni thérapie ni aide de crise.", privacy: "Confidentialité et partage", privacyCopy: "Les données relationnelles privées restent limitées au compte par défaut. Le partage partenaire est explicite lorsqu’il existe et la découverte communautaire exclut e-mail et facturation.", needHelp: "Encore besoin d’aide ?", contact: "Contacter One2OneLove", library: "Bibliothèque Relationnelle" },
  it: {
    title: "Centro Assistenza", subtitle: "Guida rapida all’esperienza di lancio One2OneLove.", account: "Account e Profilo", accountCopy: "Crea un account, accedi, recupera la password e gestisci le informazioni del tuo profilo.", couple: "Strumenti di Coppia", coupleCopy: "Usa Note d’Amore, Diari Condivisi, Ricordi, obiettivi, traguardi, anniversario, calendario, check-in, rituali e attività per appuntamenti.", community: "Comunità e Chat", communityCopy: "Trova membri tramite la directory sicura, invia una richiesta e usa la chat privata dopo l’accettazione. Le storie vengono revisionate prima della pubblicazione.", room: "Sala Globale delle Relazioni", roomCopy: "Consulta programmazione live e prossima. I creator approvati possono gestire gli orari tramite Accesso Creator secondo le regole attuali.", ai: "Funzioni IA", aiCopy: "Il Coach Relazionale IA e il Creatore di Contenuti IA sono anteprime al lancio. Non raccolgono dettagli della relazione e non effettuano ancora generazione IA live.", paid: "Abbonamento a pagamento", paidCopy: "Il checkout degli abbonamenti a pagamento non è attivo al lancio. Nessun piano o addebito deve essere dedotto da vecchi link di test.", professional: "Supporto professionale", professionalCopy: "O2OL non gestisce un elenco verificato di terapeuti né un servizio di prenotazione professionale al lancio. Il supporto relazionale è educativo e non è terapia o assistenza di crisi.", privacy: "Privacy e condivisione", privacyCopy: "I dati privati della relazione restano limitati all’account per impostazione predefinita. La condivisione con il partner è esplicita dove supportata e la scoperta community esclude email e fatturazione.", needHelp: "Serve ancora aiuto?", contact: "Contatta One2OneLove", library: "Biblioteca delle Relazioni" },
  de: {
    title: "Hilfezentrum", subtitle: "Kurze Hilfe zur One2OneLove-Starterfahrung.", account: "Konto & Profil", accountCopy: "Erstelle ein Konto, melde dich an, stelle dein Passwort wieder her und verwalte deine eigenen Profilinformationen.", couple: "Paar-Werkzeuge", coupleCopy: "Nutze Liebesbotschaften, Gemeinsame Journale, Erinnerungen, Ziele, Meilensteine, Jahrestag, Kalender, Check-ins, Rituale und Date-Aktivitäten.", community: "Community & Chat", communityCopy: "Finde Mitglieder über das datenschutzsichere Verzeichnis, sende eine Anfrage und nutze privaten Chat nach Annahme der Verbindung. Community-Geschichten werden vor Veröffentlichung geprüft.", room: "Globaler Beziehungsraum", roomCopy: "Sieh Live- und kommende Programme. Genehmigte Creator können ihre Zeitplanung über Creator-Zugang nach den aktuellen Regeln verwalten.", ai: "KI-Funktionen", aiCopy: "KI-Beziehungscoach und KI-Content-Creator sind zum Start Vorschauen. Sie sammeln keine Beziehungsdetails und bieten noch keine Live-KI-Generierung.", paid: "Bezahlte Mitgliedschaft", paidCopy: "Der Checkout für bezahlte Mitgliedschaften ist zum Start nicht aktiv. Aus alten Testlinks darf kein Tarif oder eine Belastung abgeleitet werden.", professional: "Professionelle Unterstützung", professionalCopy: "O2OL betreibt zum Start kein verifiziertes Therapeutenverzeichnis und keinen professionellen Buchungsdienst. Beziehungsunterstützung ist pädagogisch und keine Therapie oder Krisenversorgung.", privacy: "Datenschutz & Teilen", privacyCopy: "Private Beziehungsdaten bleiben standardmäßig kontogebunden. Partnerfreigabe ist ausdrücklich, wo sie unterstützt wird, und Community-Suche schließt Konto-E-Mail und Abrechnungsdaten aus.", needHelp: "Noch Hilfe nötig?", contact: "One2OneLove Kontaktieren", library: "Beziehungsbibliothek" },
};

export default function HelpCenter() {
  const { currentLanguage } = useLanguage();
  const t = translations[currentLanguage] || translations.en;
  const sections = [
    [Heart, t.account, t.accountCopy],
    [Users, t.couple, t.coupleCopy],
    [MessageCircle, t.community, t.communityCopy],
    [Radio, t.room, t.roomCopy],
    [BookOpen, t.ai, t.aiCopy],
    [ShieldCheck, t.paid, t.paidCopy],
    [HelpCircle, t.professional, t.professionalCopy],
    [ShieldCheck, t.privacy, t.privacyCopy],
  ];

  return (
    <main className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 px-4 py-12 md:py-20">
      <div className="mx-auto max-w-6xl">
        <header className="mx-auto max-w-3xl text-center"><HelpCircle className="mx-auto h-14 w-14 text-blue-700" aria-hidden="true" /><h1 className="mt-4 text-4xl font-bold text-slate-900 md:text-5xl">{t.title}</h1><p className="mt-3 text-lg text-slate-600">{t.subtitle}</p></header>
        <section className="mt-10 grid gap-5 md:grid-cols-2" aria-label={t.title}>{sections.map(([Icon, title, copy]) => <Card key={title} className="border-slate-200"><CardContent className="p-6"><Icon className="h-6 w-6 text-blue-700" aria-hidden="true" /><h2 className="mt-3 text-lg font-bold text-slate-900">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></CardContent></Card>)}</section>
        <div className="mt-10 rounded-3xl bg-gradient-to-r from-blue-600 to-purple-600 p-8 text-center text-white"><h2 className="text-2xl font-bold">{t.needHelp}</h2><div className="mt-5 flex flex-col gap-3 sm:flex-row sm:justify-center"><Button asChild variant="secondary"><Link to="/ContactUs">{t.contact}</Link></Button><Button asChild variant="outline" className="border-white bg-transparent text-white hover:bg-white/10"><Link to="/RelationshipLibrary">{t.library}</Link></Button></div></div>
      </div>
    </main>
  );
}
