import React from "react";
import { Radio, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useLanguage } from "@/Layout";

const translations = {
  en: { title: "Creators & Relationship Voices", subtitle: "One2OneLove does not publish an unverified influencer or expert directory with invented follower counts, credentials, or endorsements.", notice: "Creator discovery will grow from real approved Global Relationship Room programming. Brand and expert directories will only appear when identities, disclosures, and participation standards can be verified.", creator: "Global Room Creator Access", room: "Explore Global Relationship Room", library: "Relationship Library" },
  es: { title: "Creadores y Voces de Relaciones", subtitle: "One2OneLove no publica un directorio no verificado de influencers o expertos con seguidores, credenciales o recomendaciones inventadas.", notice: "El descubrimiento de creadores crecerá a partir de programación real y aprobada de la Sala Global de Relaciones. Los directorios de marcas o expertos solo aparecerán cuando puedan verificarse identidades, divulgaciones y estándares de participación.", creator: "Acceso de Creadores de la Sala Global", room: "Explorar la Sala Global", library: "Biblioteca de Relaciones" },
  fr: { title: "Créateurs et Voix Relationnelles", subtitle: "One2OneLove ne publie pas d’annuaire non vérifié d’influenceurs ou d’experts avec abonnés, qualifications ou recommandations inventés.", notice: "La découverte de créateurs se développera à partir de programmes réels et approuvés de la Salle Mondiale des Relations. Les annuaires de marques ou d’experts n’apparaîtront que lorsque les identités, divulgations et normes de participation pourront être vérifiées.", creator: "Accès Créateur de la Salle Mondiale", room: "Explorer la Salle Mondiale", library: "Bibliothèque Relationnelle" },
  it: { title: "Creator e Voci sulle Relazioni", subtitle: "One2OneLove non pubblica un elenco non verificato di influencer o esperti con follower, credenziali o approvazioni inventate.", notice: "La scoperta dei creator crescerà a partire da programmazione reale e approvata della Sala Globale delle Relazioni. Elenchi di brand o esperti appariranno solo quando identità, disclosure e standard di partecipazione saranno verificabili.", creator: "Accesso Creator Sala Globale", room: "Esplora la Sala Globale", library: "Biblioteca delle Relazioni" },
  de: { title: "Creator & Beziehungsstimmen", subtitle: "One2OneLove veröffentlicht kein unverifiziertes Influencer- oder Expertenverzeichnis mit erfundenen Followerzahlen, Qualifikationen oder Empfehlungen.", notice: "Creator-Entdeckung wird aus realen, genehmigten Programmen des Globalen Beziehungsraums wachsen. Marken- oder Expertenverzeichnisse erscheinen erst, wenn Identitäten, Offenlegungen und Teilnahmebedingungen überprüfbar sind.", creator: "Creator-Zugang Globaler Beziehungsraum", room: "Globalen Beziehungsraum Entdecken", library: "Beziehungsbibliothek" },
};

export default function InfluencersSupport() {
  const { currentLanguage } = useLanguage();
  const t = translations[currentLanguage] || translations.en;
  return <main className="min-h-screen bg-gradient-to-br from-purple-50 via-white to-pink-50 px-4 py-12 md:py-20"><div className="mx-auto max-w-4xl text-center"><Radio className="mx-auto h-14 w-14 text-purple-700" aria-hidden="true"/><h1 className="mt-5 text-4xl font-bold text-slate-900 md:text-5xl">{t.title}</h1><p className="mx-auto mt-4 max-w-3xl text-lg leading-7 text-slate-600">{t.subtitle}</p><Card className="mx-auto mt-8 max-w-3xl border-purple-100 text-left"><CardContent className="p-6 md:p-8"><div className="flex gap-3 rounded-2xl bg-purple-50 p-5 text-sm leading-6 text-purple-950"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0" aria-hidden="true"/><p>{t.notice}</p></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><Button asChild><Link to="/RoomCreatorAccess"><Sparkles className="mr-2 h-4 w-4" aria-hidden="true"/>{t.creator}</Link></Button><Button asChild variant="outline"><Link to="/GlobalRelationshipRoom">{t.room}</Link></Button><Button asChild variant="outline"><Link to="/RelationshipLibrary">{t.library}</Link></Button></div></CardContent></Card></div></main>;
}
