import React from "react";
import { ShieldCheck, Target, Trophy } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useLanguage } from "@/Layout";

const translations = {
  en: { title: "Relationship Progress — Post Launch", subtitle: "One2OneLove will not rank couples against fabricated people or imply that one relationship is better than another.", notice: "The previous leaderboard concept has been retired for launch. If an opt-in progress or community recognition feature returns later, it will use real consented data and focus on healthy participation rather than relationship competition.", goals: "Relationship Goals", challenges: "Couples Challenges", dashboard: "Couples Dashboard" },
  es: { title: "Progreso de la Relación — Después del Lanzamiento", subtitle: "One2OneLove no clasificará parejas contra personas inventadas ni sugerirá que una relación es mejor que otra.", notice: "El concepto anterior de clasificación se ha retirado para el lanzamiento. Si vuelve más adelante una función opcional de progreso o reconocimiento comunitario, usará datos reales con consentimiento y se centrará en la participación saludable, no en competir relaciones.", goals: "Metas de Relación", challenges: "Desafíos para Parejas", dashboard: "Panel de Pareja" },
  fr: { title: "Progression Relationnelle — Après le Lancement", subtitle: "One2OneLove ne classera pas les couples face à des personnes inventées et ne laissera pas entendre qu’une relation est meilleure qu’une autre.", notice: "L’ancien concept de classement est retiré pour le lancement. Si une fonction optionnelle de progression ou de reconnaissance communautaire revient plus tard, elle utilisera des données réelles avec consentement et valorisera une participation saine plutôt que la compétition entre relations.", goals: "Objectifs de Relation", challenges: "Défis de Couple", dashboard: "Tableau de Bord du Couple" },
  it: { title: "Progresso di Coppia — Dopo il Lancio", subtitle: "One2OneLove non classificherà le coppie contro persone inventate né suggerirà che una relazione sia migliore di un’altra.", notice: "Il vecchio concetto di classifica è stato ritirato per il lancio. Se in futuro tornerà una funzione opzionale di progresso o riconoscimento della community, userà dati reali e consensuali e premierà la partecipazione sana, non la competizione tra relazioni.", goals: "Obiettivi di Relazione", challenges: "Sfide di Coppia", dashboard: "Dashboard di Coppia" },
  de: { title: "Beziehungsfortschritt — Nach dem Start", subtitle: "One2OneLove wird Paare nicht gegen erfundene Personen ranken oder suggerieren, eine Beziehung sei besser als eine andere.", notice: "Das frühere Bestenlisten-Konzept ist für den Start eingestellt. Falls später eine optionale Fortschritts- oder Community-Anerkennung zurückkehrt, nutzt sie echte, eingewilligte Daten und fördert gesunde Teilnahme statt Beziehungswettbewerb.", goals: "Beziehungsziele", challenges: "Paar-Challenges", dashboard: "Paar-Dashboard" },
};

export default function Leaderboard() {
  const { currentLanguage } = useLanguage();
  const t = translations[currentLanguage] || translations.en;
  return <main className="min-h-screen bg-gradient-to-br from-yellow-50 via-white to-purple-50 px-4 py-12 md:py-20"><div className="mx-auto max-w-4xl text-center"><Trophy className="mx-auto h-14 w-14 text-amber-600" aria-hidden="true"/><h1 className="mt-5 text-4xl font-bold text-slate-900 md:text-5xl">{t.title}</h1><p className="mt-4 text-lg text-slate-600">{t.subtitle}</p><Card className="mx-auto mt-8 max-w-3xl text-left"><CardContent className="p-6 md:p-8"><div className="flex gap-3 rounded-2xl bg-amber-50 p-5 text-sm leading-6 text-amber-950"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0" aria-hidden="true"/><p>{t.notice}</p></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><Button asChild><Link to="/RelationshipGoals"><Target className="mr-2 h-4 w-4" aria-hidden="true"/>{t.goals}</Link></Button><Button asChild variant="outline"><Link to="/CouplesChallenges">{t.challenges}</Link></Button><Button asChild variant="outline"><Link to="/CouplesDashboard">{t.dashboard}</Link></Button></div></CardContent></Card></div></main>;
}
