import React from "react";
import { Heart, Rainbow, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useLanguage } from "@/Layout";

const translations = {
  en: { title: "LGBTQ+ Relationship Support", subtitle: "A dedicated verified LGBTQ+ resource hub is planned for post launch.", notice: "We removed the legacy page’s unverified therapist referrals, hard-coded crisis contacts, and legal-rights guidance. A future LGBTQ+ hub will use current, reviewed resources and clear source attribution before presenting location-sensitive legal, professional, or crisis information.", inclusive: "One2OneLove’s launch relationship tools are designed for couples of different identities and relationship backgrounds. You can use the same communication, connection, reflection, and support tools available across the platform.", support: "Relationship Support", library: "Relationship Library", communication: "Communication Practice" },
  es: { title: "Apoyo para Relaciones LGBTQ+", subtitle: "Un centro dedicado y verificado de recursos LGBTQ+ está previsto para después del lanzamiento.", notice: "Eliminamos las referencias no verificadas a terapeutas, contactos de crisis codificados y orientación sobre derechos legales de la página anterior. Un futuro centro LGBTQ+ usará recursos actuales, revisados y con atribución clara antes de presentar información legal, profesional o de crisis que dependa de la ubicación.", inclusive: "Las herramientas de relaciones de One2OneLove en el lanzamiento están diseñadas para parejas con distintas identidades y contextos. Puedes usar las mismas herramientas de comunicación, conexión, reflexión y apoyo disponibles en toda la plataforma.", support: "Apoyo para Relaciones", library: "Biblioteca de Relaciones", communication: "Práctica de Comunicación" },
  fr: { title: "Soutien aux Relations LGBTQ+", subtitle: "Un espace dédié de ressources LGBTQ+ vérifiées est prévu après le lancement.", notice: "Nous avons retiré de l’ancienne page les références non vérifiées à des thérapeutes, les contacts de crise codés en dur et les conseils juridiques. Un futur espace LGBTQ+ utilisera des ressources actuelles, révisées et clairement sourcées avant de présenter des informations juridiques, professionnelles ou de crise dépendant du lieu.", inclusive: "Les outils relationnels One2OneLove au lancement sont conçus pour des couples d’identités et de parcours variés. Vous pouvez utiliser les mêmes outils de communication, connexion, réflexion et soutien disponibles sur toute la plateforme.", support: "Soutien Relationnel", library: "Bibliothèque Relationnelle", communication: "Pratique de Communication" },
  it: { title: "Supporto per Relazioni LGBTQ+", subtitle: "Un hub dedicato di risorse LGBTQ+ verificate è previsto dopo il lancio.", notice: "Abbiamo rimosso dalla vecchia pagina referral non verificati a terapeuti, contatti di crisi inseriti direttamente e indicazioni sui diritti legali. Un futuro hub LGBTQ+ userà risorse aggiornate, revisionate e chiaramente attribuite prima di presentare informazioni legali, professionali o di crisi dipendenti dalla località.", inclusive: "Gli strumenti relazionali One2OneLove al lancio sono pensati per coppie con identità e percorsi diversi. Puoi usare gli stessi strumenti di comunicazione, connessione, riflessione e supporto disponibili in tutta la piattaforma.", support: "Supporto Relazionale", library: "Biblioteca delle Relazioni", communication: "Pratica di Comunicazione" },
  de: { title: "LGBTQ+ Beziehungsunterstützung", subtitle: "Ein eigener, verifizierter LGBTQ+ Ressourcenbereich ist für die Zeit nach dem Start geplant.", notice: "Wir haben unverifizierte Therapeutenverweise, fest eingetragene Krisenkontakte und Rechtsinformationen von der alten Seite entfernt. Ein zukünftiger LGBTQ+ Bereich wird aktuelle, geprüfte und klar zugeordnete Quellen verwenden, bevor standortabhängige rechtliche, professionelle oder Kriseninformationen angezeigt werden.", inclusive: "Die Beziehungswerkzeuge von One2OneLove zum Start sind für Paare mit unterschiedlichen Identitäten und Hintergründen gedacht. Ihr könnt dieselben Kommunikations-, Verbindungs-, Reflexions- und Unterstützungswerkzeuge der gesamten Plattform nutzen.", support: "Beziehungsunterstützung", library: "Beziehungsbibliothek", communication: "Kommunikationsübung" },
};

export default function LGBTQSupport() {
  const { currentLanguage } = useLanguage();
  const t = translations[currentLanguage] || translations.en;
  return <main className="min-h-screen bg-gradient-to-br from-pink-50 via-white to-indigo-50 px-4 py-12 md:py-20"><div className="mx-auto max-w-4xl text-center"><Rainbow className="mx-auto h-14 w-14 text-pink-600" aria-hidden="true"/><h1 className="mt-5 text-4xl font-bold text-slate-900 md:text-5xl">{t.title}</h1><p className="mt-4 text-lg text-slate-600">{t.subtitle}</p><Card className="mx-auto mt-8 max-w-3xl text-left"><CardContent className="p-6 md:p-8"><div className="flex gap-3 rounded-2xl bg-pink-50 p-5 text-sm leading-6 text-pink-950"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0" aria-hidden="true"/><p>{t.notice}</p></div><div className="mt-6 flex gap-3 rounded-2xl border border-slate-200 p-5"><Heart className="mt-0.5 h-5 w-5 shrink-0 text-pink-600" aria-hidden="true"/><p className="text-sm leading-6 text-slate-700">{t.inclusive}</p></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><Button asChild><Link to="/CoupleSupport">{t.support}</Link></Button><Button asChild variant="outline"><Link to="/RelationshipLibrary">{t.library}</Link></Button><Button asChild variant="outline"><Link to="/CommunicationPractice">{t.communication}</Link></Button></div></CardContent></Card></div></main>;
}
