import { useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { BrainCircuit, Coins, Loader2, MessageCircle, PlayCircle, Plus, RotateCcw, Send, ShieldCheck, Sparkles, Trash2 } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { useLanguage } from './Layout';
import { createBiancaConversation, deleteBiancaConversation, generateBiancaReport, getBiancaProfile, listBiancaConversations, listBiancaMessages, resetBiancaPersonalization, sendBiancaMessage } from '@/lib/aiService';
import { getTokenWallet, isTokensRequiredError, tokenRequiredDetails } from '@/lib/tokenService';

const COPY={
 en:{eyebrow:'Casual talk with Bianca',title:'Talk to Bianca like a real conversation.',intro:'Ask a relationship question, talk through something on your mind, or just chat. Bianca can laugh with you, apologize when appropriate, empathize, and learn the words and phrases you naturally use.',accuracy:'The more frequently you talk with Bianca, the more context she has. That can improve the accuracy and personalization of your Personality & Relationship Pattern Reports.',newChat:'New conversation',placeholder:'Talk to Bianca…',send:'Send',signIn:'Sign in to talk with Bianca',create:'Create One2OneLove account',cardRequired:'Bianca is available to every verified O2OL member. Sending a message uses Credit.',cardAction:'Add Credit To Access',studio:'See Bianca in Conversation',studioSub:'Watch O2OL Studio — Season 1, Episode 1',empty:'Start a casual conversation with Bianca.',context:'Report context depth',report:'Generate updated report',reportReady:'Your updated private report has been created.',privacy:'Private self-reflection only. Bianca is not therapy, diagnosis, or emergency support.',preview:'The live Bianca API is staged for Prelaunch but this visual preview currently blocks API writes.', deleteChat:'Delete conversation', resetLearning:'Reset learned phrases', resetDone:'Bianca’s learned phrases were reset. Your conversations and reports were kept.', confirmDelete:'Delete this conversation?'},
 es:{eyebrow:'Charla casual con Bianca',title:'Habla con Bianca como en una conversación real.',intro:'Haz una pregunta de relación, habla de algo que tengas en mente o simplemente conversa. Bianca puede reír contigo, disculparse cuando corresponde, mostrar empatía y aprender las palabras y frases que usas naturalmente.',accuracy:'Cuanto más frecuentemente hables con Bianca, más contexto tendrá. Eso puede mejorar la precisión y personalización de tus Informes de Patrones de Personalidad y Relaciones.',newChat:'Nueva conversación',placeholder:'Habla con Bianca…',send:'Enviar',signIn:'Inicia sesión para hablar con Bianca',create:'Crear cuenta One2OneLove',cardRequired:'Bianca está disponible para todos los miembros verificados de O2OL. Enviar un mensaje usa Crédito.',cardAction:'Agregar Crédito para Acceder',studio:'Ver a Bianca en Conversación',studioSub:'Mira O2OL Studio — Temporada 1, Episodio 1',empty:'Comienza una conversación casual con Bianca.',context:'Profundidad de contexto del informe',report:'Generar informe actualizado',reportReady:'Tu informe privado actualizado ha sido creado.',privacy:'Solo para autorreflexión privada. Bianca no es terapia, diagnóstico ni apoyo de emergencia.',preview:'La API en vivo de Bianca está preparada para Prelaunch, pero esta vista visual actualmente bloquea escrituras de API.', deleteChat:'Eliminar conversación', resetLearning:'Restablecer frases aprendidas', resetDone:'Se restablecieron las frases aprendidas de Bianca. Tus conversaciones e informes se conservaron.', confirmDelete:'¿Eliminar esta conversación?'},
 fr:{eyebrow:'Discussion décontractée avec Bianca',title:'Parlez à Bianca comme dans une vraie conversation.',intro:'Posez une question relationnelle, parlez de ce qui vous préoccupe ou discutez simplement. Bianca peut rire avec vous, s’excuser lorsque c’est approprié, faire preuve d’empathie et apprendre les mots et expressions que vous utilisez naturellement.',accuracy:'Plus vous parlez régulièrement avec Bianca, plus elle dispose de contexte. Cela peut améliorer la précision et la personnalisation de vos Rapports sur les Schémas de Personnalité et de Relation.',newChat:'Nouvelle conversation',placeholder:'Parlez à Bianca…',send:'Envoyer',signIn:'Connectez-vous pour parler à Bianca',create:'Créer un compte One2OneLove',cardRequired:'Bianca est disponible pour chaque membre O2OL vérifié. Envoyer un message utilise du Crédit.',cardAction:'Ajouter du Crédit pour Accéder',studio:'Voir Bianca en Conversation',studioSub:'Regardez O2OL Studio — Saison 1, Épisode 1',empty:'Commencez une discussion décontractée avec Bianca.',context:'Profondeur du contexte du rapport',report:'Générer un rapport actualisé',reportReady:'Votre rapport privé actualisé a été créé.',privacy:'Pour l’autoréflexion privée uniquement. Bianca n’est ni une thérapie, ni un diagnostic, ni un service d’urgence.',preview:'L’API Bianca est prête pour Prelaunch, mais cet aperçu visuel bloque actuellement les écritures API.', deleteChat:'Supprimer la conversation', resetLearning:'Réinitialiser les phrases apprises', resetDone:'Les phrases apprises de Bianca ont été réinitialisées. Vos conversations et rapports ont été conservés.', confirmDelete:'Supprimer cette conversation ?'},
 it:{eyebrow:'Conversazione informale con Bianca',title:'Parla con Bianca come in una vera conversazione.',intro:'Fai una domanda sulla relazione, parla di qualcosa che hai in mente o semplicemente chiacchiera. Bianca può ridere con te, scusarsi quando è opportuno, mostrare empatia e imparare le parole e frasi che usi naturalmente.',accuracy:'Più frequentemente parli con Bianca, più contesto avrà. Questo può migliorare l’accuratezza e la personalizzazione dei tuoi Rapporti sui Pattern di Personalità e Relazione.',newChat:'Nuova conversazione',placeholder:'Parla con Bianca…',send:'Invia',signIn:'Accedi per parlare con Bianca',create:'Crea account One2OneLove',cardRequired:'Bianca è disponibile per ogni membro O2OL verificato. Inviare un messaggio usa Credito.',cardAction:'Aggiungi Credito per Accedere',studio:'Guarda Bianca in Conversazione',studioSub:'Guarda O2OL Studio — Stagione 1, Episodio 1',empty:'Inizia una conversazione informale con Bianca.',context:'Profondità del contesto del rapporto',report:'Genera rapporto aggiornato',reportReady:'Il tuo rapporto privato aggiornato è stato creato.',privacy:'Solo per autoriflessione privata. Bianca non è terapia, diagnosi o supporto di emergenza.',preview:'L’API live di Bianca è pronta per Prelaunch, ma questa anteprima visiva al momento blocca le scritture API.', deleteChat:'Elimina conversazione', resetLearning:'Reimposta frasi apprese', resetDone:'Le frasi apprese da Bianca sono state reimpostate. Le tue conversazioni e i tuoi rapporti sono stati conservati.', confirmDelete:'Eliminare questa conversazione?'},
 de:{eyebrow:'Lockeres Gespräch mit Bianca',title:'Sprechen Sie mit Bianca wie in einem echten Gespräch.',intro:'Stellen Sie eine Beziehungsfrage, sprechen Sie über etwas, das Sie beschäftigt, oder plaudern Sie einfach. Bianca kann mit Ihnen lachen, sich angemessen entschuldigen, empathisch reagieren und Wörter und Formulierungen lernen, die Sie natürlich verwenden.',accuracy:'Je häufiger Sie mit Bianca sprechen, desto mehr Kontext hat sie. Das kann die Genauigkeit und Personalisierung Ihrer Berichte zu Persönlichkeits- und Beziehungsmustern verbessern.',newChat:'Neues Gespräch',placeholder:'Mit Bianca sprechen…',send:'Senden',signIn:'Anmelden, um mit Bianca zu sprechen',create:'One2OneLove-Konto erstellen',cardRequired:'Bianca ist für jedes verifizierte O2OL-Mitglied verfügbar. Das Senden einer Nachricht verwendet Credit.',cardAction:'Credit Hinzufügen für Zugriff',studio:'Bianca im Gespräch Sehen',studioSub:'O2OL Studio ansehen — Staffel 1, Folge 1',empty:'Beginnen Sie ein lockeres Gespräch mit Bianca.',context:'Kontexttiefe des Berichts',report:'Aktualisierten Bericht erstellen',reportReady:'Ihr aktualisierter privater Bericht wurde erstellt.',privacy:'Nur zur privaten Selbstreflexion. Bianca ist keine Therapie, Diagnose oder Notfallhilfe.',preview:'Die Bianca-Live-API ist für Prelaunch vorbereitet, aber diese visuelle Vorschau blockiert derzeit API-Schreibvorgänge.', deleteChat:'Gespräch löschen', resetLearning:'Gelernte Formulierungen zurücksetzen', resetDone:'Biancas gelernte Formulierungen wurden zurückgesetzt. Ihre Gespräche und Berichte wurden beibehalten.', confirmDelete:'Dieses Gespräch löschen?'}
};
const money=(cents)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(cents||0)/100);

export default function MyMatchIQBianca(){
 const {currentLanguage}=useLanguage(); const {isAuthenticated}=useAuth(); const t=COPY[currentLanguage]||COPY.en;
 const [walletBalance,setWalletBalance]=useState(0); const [tokenPrompt,setTokenPrompt]=useState(null);
 const [conversations,setConversations]=useState([]); const [activeId,setActiveId]=useState(null); const [messages,setMessages]=useState([]); const [profile,setProfile]=useState(null); const [draft,setDraft]=useState(''); const [responseLength,setResponseLength]=useState('short'); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [reportMessage,setReportMessage]=useState(''); const bottomRef=useRef(null);
 const active=useMemo(()=>conversations.find(c=>c.id===activeId)||null,[conversations,activeId]);
 const refreshWallet=async()=>{ try{const wallet=await getTokenWallet();setWalletBalance(Number(wallet?.wallet?.balance||0));return wallet;}catch(_){return null;} };
 const premiumError=(e,fallback)=>{
   if(isTokensRequiredError(e)){const info=tokenRequiredDetails(e);setTokenPrompt(info);setError(`${t.cardAction} — ${money(info.required)} Credit required. Current balance: ${money(info.balance)}.`);}
   else{setTokenPrompt(null);setError(e?.message||fallback||t.preview);}
 };
 useEffect(()=>{
  if(!isAuthenticated){setWalletBalance(0);setTokenPrompt(null);return;}
  let cancelled=false;
  (async()=>{ try{
    const [list,p,wallet]=await Promise.all([listBiancaConversations(),getBiancaProfile(),getTokenWallet()]);
    if(cancelled)return;
    setConversations(list);setProfile(p);setWalletBalance(Number(wallet?.wallet?.balance||0));if(list[0])setActiveId(v=>v||list[0].id);
  }catch(e){if(!cancelled)setError(e?.message||t.preview);} })();
  return()=>{cancelled=true};
 },[isAuthenticated,currentLanguage]);
 useEffect(()=>{ if(!activeId||!isAuthenticated)return; listBiancaMessages(activeId).then(setMessages).catch(e=>setError(e?.message||t.preview)); },[activeId,isAuthenticated]);
 useEffect(()=>bottomRef.current?.scrollIntoView({behavior:'smooth'}),[messages]);
 async function newChat(){ setLoading(true); setError('');setTokenPrompt(null); try{ const conv=await createBiancaConversation(); setConversations(v=>[conv,...v]); setActiveId(conv.id); setMessages([]); setProfile(await getBiancaProfile()); }catch(e){setError(e?.message||t.preview);}finally{setLoading(false);} }
 async function send(){ const text=draft.trim(); if(!text||loading)return; setLoading(true); setDraft(''); setError('');setTokenPrompt(null); try{ let id=activeId; if(!id){const conv=await createBiancaConversation(); setConversations(v=>[conv,...v]); id=conv.id; setActiveId(id);} const result=await sendBiancaMessage(id,text,currentLanguage,responseLength); setMessages(v=>[...v,result.userMessage,result.message]); if(result.profile)setProfile(result.profile); if(result?.tokens?.balance!=null)setWalletBalance(Number(result.tokens.balance)); else await refreshWallet(); }catch(e){setDraft(text);premiumError(e,t.preview);}finally{setLoading(false);} }
 async function report(){ setLoading(true); setReportMessage(''); setError('');setTokenPrompt(null); try{ await generateBiancaReport(currentLanguage); setReportMessage(t.reportReady);await refreshWallet(); }catch(e){premiumError(e,t.preview);}finally{setLoading(false);} }
 async function removeChat(id){ if(!id||!window.confirm(t.confirmDelete))return; setLoading(true); setError(''); try{ await deleteBiancaConversation(id); const next=conversations.filter(conv=>conv.id!==id); setConversations(next); setMessages([]); setActiveId(next[0]?.id||null); setProfile(await getBiancaProfile()); }catch(e){setError(e?.message||t.preview);}finally{setLoading(false);} }
 async function resetLearning(){ setLoading(true); setError(''); try{ setProfile(await resetBiancaPersonalization()); setReportMessage(t.resetDone); }catch(e){setError(e?.message||t.preview);}finally{setLoading(false);} }
 if(!isAuthenticated)return <main className="min-h-screen bg-[#070312] px-4 py-12 text-white"><section className="mx-auto max-w-3xl rounded-[2rem] border border-fuchsia-200/25 bg-white/[0.06] p-8 text-center"><img src="/assets/bianca-mymatchiq-portrait-v2.webp" alt="Bianca" className="mx-auto w-48 rounded-3xl"/><h1 className="mt-6 text-4xl font-black">{t.title}</h1><p className="mt-4 text-white/75">{t.intro}</p><div className="mx-auto mt-6 max-w-xl rounded-2xl border border-fuchsia-200/20 bg-fuchsia-950/25 p-4 text-sm leading-6 text-fuchsia-50"><Coins className="mx-auto mb-2 h-5 w-5"/>{t.cardRequired}</div><div className="mt-7 flex flex-wrap justify-center gap-3"><Link to="/SignIn?source=mymatchiq-bianca&redirect=/MyMatchIQ/Bianca" className="rounded-full border border-white/30 bg-white/10 px-6 py-3 font-black">{t.signIn}</Link><Link to="/SignUp?source=mymatchiq-bianca&feature=bianca&return=/MyMatchIQ/Bianca" className="inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-6 py-3 font-black">{t.create}</Link><Link to="/O2OLStudio?from=bianca" className="inline-flex items-center gap-3 rounded-2xl border border-cyan-200/30 bg-white/10 px-5 py-3 text-left font-black text-white hover:bg-white/15"><PlayCircle className="h-5 w-5 shrink-0 text-cyan-200"/><span><span className="block">{t.studio}</span><span className="block text-[0.68rem] font-semibold text-cyan-100/80">{t.studioSub}</span></span></Link></div></section></main>;
 return <main className="min-h-screen bg-[#070312] px-3 py-5 text-white sm:px-6 sm:py-8" style={{backgroundImage:'radial-gradient(circle at 12% 0%, #5b126f 0%, transparent 30%), radial-gradient(circle at 88% 12%, #162e78 0%, transparent 28%)'}}>
  <section className="mx-auto max-w-7xl">
   <div className="grid gap-5 lg:grid-cols-[300px_1fr]">
    <aside className="rounded-[1.75rem] border border-fuchsia-200/25 bg-black/35 p-5 shadow-xl backdrop-blur">
     <img src="/assets/bianca-mymatchiq-portrait-v2.webp" alt="Bianca" className="mx-auto w-44 rounded-3xl border border-white/15"/>
     <p className="mt-5 text-xs font-black uppercase tracking-[0.2em] text-fuchsia-200">{t.eyebrow}</p><h1 className="mt-2 text-2xl font-black">{t.title}</h1><p className="mt-3 text-sm leading-6 text-white/75">{t.intro}</p>
     <div className="mt-5 rounded-2xl border border-cyan-200/25 bg-cyan-950/30 p-4 text-sm leading-6 text-cyan-50"><Sparkles className="mb-2 h-5 w-5"/>{t.accuracy}<Link to="/O2OLStudio?from=bianca-live" className="mt-4 flex items-center gap-3 rounded-xl border border-cyan-200/20 bg-white/10 px-4 py-3 text-white hover:bg-white/15"><PlayCircle className="h-5 w-5 shrink-0 text-cyan-200"/><span><span className="block font-black">{t.studio}</span><span className="block text-[0.68rem] font-semibold text-cyan-100/80">{t.studioSub}</span></span></Link></div>
     <div className="mt-4 rounded-2xl border border-white/15 bg-white/[0.05] p-4"><div className="flex items-center justify-between text-sm font-bold"><span>{t.context}</span><span>{profile?.context_depth_score||10}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-fuchsia-500 to-cyan-400" style={{width:`${profile?.context_depth_score||10}%`}}/></div></div><Link to="/Credit?return=/MyMatchIQ/Bianca" className="mt-3 flex items-center justify-between rounded-2xl border border-amber-200/25 bg-amber-300/10 p-4 text-amber-50"><span className="inline-flex items-center gap-2 font-black"><Coins className="h-5 w-5"/>Credit</span><span className="text-xl font-black">{money(walletBalance)}</span></Link>
     <button onClick={newChat} disabled={loading} className="mt-4 flex w-full items-center justify-center gap-2 rounded-full border border-white/25 bg-white/10 px-4 py-3 text-sm font-black hover:bg-white/15"><Plus className="h-4 w-4"/>{t.newChat}</button>
     <button onClick={report} disabled={loading} className="mt-3 flex w-full items-center justify-center gap-2 rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-4 py-3 text-sm font-black"><BrainCircuit className="h-4 w-4"/>{t.report}</button>
     <button onClick={resetLearning} disabled={loading} className="mt-3 flex w-full items-center justify-center gap-2 rounded-full border border-white/20 bg-white/[0.06] px-4 py-3 text-sm font-black text-white/80 hover:bg-white/10"><RotateCcw className="h-4 w-4"/>{t.resetLearning}</button>
     <div className="mt-5 space-y-2">{conversations.slice(0,8).map(c=><div key={c.id} className={`flex items-center gap-2 rounded-xl pr-2 ${activeId===c.id?'bg-fuchsia-500/25':'bg-white/[0.05] hover:bg-white/10'}`}><button onClick={()=>setActiveId(c.id)} className={`min-w-0 flex-1 px-3 py-2 text-left text-sm ${activeId===c.id?'text-white':'text-white/70'}`}><span className="block truncate font-bold">{c.title}</span><span className="block truncate text-xs opacity-70">{c.last_message||''}</span></button><button type="button" onClick={()=>removeChat(c.id)} aria-label={t.deleteChat} className="rounded-lg p-2 text-white/45 hover:bg-white/10 hover:text-white"><Trash2 className="h-4 w-4"/></button></div>)}</div>
    </aside>
    <section className="flex min-h-[72vh] flex-col overflow-hidden rounded-[1.75rem] border border-white/15 bg-black/35 shadow-2xl backdrop-blur">
     <div className="border-b border-white/10 px-5 py-4"><div className="flex items-center gap-3"><MessageCircle className="h-6 w-6 text-fuchsia-200"/><div><h2 className="font-black">{active?.title||t.eyebrow}</h2><p className="text-xs text-white/55">{t.privacy}</p></div></div></div>
     <div className="flex-1 space-y-4 overflow-y-auto p-5">{!messages.length&&<div className="mx-auto mt-20 max-w-md text-center text-white/55"><MessageCircle className="mx-auto h-10 w-10 text-fuchsia-300"/><p className="mt-3">{t.empty}</p></div>}{messages.map(m=><div key={m.id||m.created_at} className={`flex ${m.is_user||m.role==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[82%] whitespace-pre-wrap rounded-2xl px-4 py-3 text-sm leading-6 ${m.is_user||m.role==='user'?'bg-fuchsia-600 text-white':'border border-cyan-200/20 bg-cyan-950/35 text-cyan-50'}`}>{m.text||m.content}</div></div>)}<div ref={bottomRef}/></div>
     {(error||reportMessage)&&<div className={`mx-5 mb-3 rounded-xl border p-3 text-sm ${error?'border-amber-200/25 bg-amber-950/25 text-amber-50':'border-emerald-200/25 bg-emerald-950/25 text-emerald-50'}`}>{error||reportMessage}{tokenPrompt&&<Link to="/Credit?return=/MyMatchIQ/Bianca" className="ml-3 inline-flex items-center gap-1 rounded-lg bg-amber-300 px-3 py-1.5 font-black text-amber-950"><Coins className="h-4 w-4"/>{t.cardAction}</Link>}</div>}
     <div className="border-t border-white/10 p-4">
      <div className="mb-3 flex flex-wrap gap-2" aria-label="Choose Bianca response length">
       {[['short','Short','50–100 words','$0.10'],['medium','Medium','150–250 words','$0.15'],['long','Long','300–400 words','$0.20']].map(([value,label,words,price])=><button key={value} type="button" onClick={()=>setResponseLength(value)} className={`rounded-xl border px-3 py-2 text-left text-xs font-black ${responseLength===value?'border-fuchsia-300 bg-fuchsia-500/25 text-white':'border-white/15 bg-white/5 text-white/65 hover:bg-white/10'}`}><span className="block">{label} · {price}</span><span className="block font-semibold opacity-70">{words}</span></button>)}
      </div>
      <div className="flex items-end gap-3"><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}}} rows={2} placeholder={t.placeholder} className="min-h-[54px] flex-1 resize-none rounded-2xl border border-white/15 bg-slate-950/80 px-4 py-3 text-white outline-none focus:border-fuchsia-300"/><button onClick={send} disabled={loading||!draft.trim()} aria-label={t.send} className="flex h-[54px] w-[54px] items-center justify-center rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 disabled:opacity-40">{loading?<Loader2 className="h-5 w-5 animate-spin"/>:<Send className="h-5 w-5"/>}</button></div>
      <div className="mt-3 flex items-start gap-2 text-xs leading-5 text-white/45"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0"/><span>{t.privacy}<span className="ml-2 font-black text-fuchsia-200">{responseLength==='short'?'Short · 50–100 words · $0.10':responseLength==='medium'?'Medium · 150–250 words · $0.15':'Long · 300–400 words · $0.20'}</span></span></div>
     </div>
    </section>
   </div>
  </section>
 </main>;
}
