import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Check, HeartHandshake, LockKeyhole, RefreshCw, Sparkles, WalletCards } from 'lucide-react';
import { useLanguage } from './Layout';

const COPY = {
  en:{ eyebrow:'MyMatchIQ wallet', title:'Use credits only when something meaningful begins.', body:'MyMatchIQ is free to join. Credits unlock private insight and intentional two-person experiences without forcing a monthly subscription.', balance:'Your credit balance', balanceValue:'0 credits', balanceNote:'Create and verify an account to use and track credits.', personalTitle:'Private insight', personalBody:'Use an Insight Credit for a full Compatibility Passport or a deeper Personality & Relationship Pattern Report.', playTitle:'Mutual Let’s Play', playBody:'Each person uses one $1.99 Play Credit only after both accept the invitation. Nothing is consumed while an invitation is waiting.', controlTitle:'You stay in control', controlBody:'Your credit wallet is separate from membership. Auto Replenish is always optional and can be turned off anytime.', choiceTitle:'Credit choices', one:'Single Play Credit', bundle:'Six-credit bundle', reserve:'Twelve-credit bundle', onePrice:'US$1.99', bundlePrice:'US$9.99', reservePrice:'US$19.99', oneNote:'One person, one intentional Play session.', bundleNote:'Six credits for private insights or Play sessions.', reserveNote:'Twelve credits for members who want a ready credit balance.', autoTitle:'Auto Replenish', autoBody:'Choose the credit package and the minimum balance that should trigger a refill.', enable:'Enable Auto Replenish', refillAmount:'Refill amount', minimumBalance:'Refill when balance reaches', minimumZero:'0 credits', minimumOne:'1 credit', minimumTwo:'2 credits', autoPreview:'Prelaunch preview: Auto Replenish is off and cannot charge your account. Before launch it will require a verified payment method and your explicit confirmation.', noCharge:'Prelaunch pricing preview — checkout is not active and no payment can be collected here.', assessment:'Start Bianca’s assessment', member:'Create a free MyMatchIQ account', included:['Transparent credit balance','No automatic per-feature charge','Clear consent before Mutual Play'] },
  es:{ eyebrow:'Billetera MyMatchIQ', title:'Usa créditos solo cuando comienza algo significativo.', body:'Unirse a MyMatchIQ es gratis. Los créditos desbloquean información privada y experiencias intencionales para dos personas sin forzar una suscripción mensual.', balance:'Tu saldo de créditos', balanceValue:'0 créditos', balanceNote:'Crea y verifica una cuenta para usar y seguir créditos.', personalTitle:'Información privada', personalBody:'Usa un Crédito de Insight para un Pasaporte de Compatibilidad completo o un Informe más profundo de Patrones de Personalidad y Relaciones.', playTitle:'Let’s Play mutuo', playBody:'Cada persona usa un Crédito Play de US$1.99 solo después de que ambas aceptan la invitación. No se consume nada mientras la invitación espera.', controlTitle:'Tú mantienes el control', controlBody:'Tu billetera de créditos es independiente de la membresía. La Recarga Automática siempre es opcional y se puede desactivar en cualquier momento.', choiceTitle:'Opciones de créditos', one:'Crédito Play individual', bundle:'Paquete de seis créditos', reserve:'Paquete de doce créditos', onePrice:'US$1.99', bundlePrice:'US$9.99', reservePrice:'US$19.99', oneNote:'Una persona, una sesión Play intencional.', bundleNote:'Seis créditos para información privada o sesiones Play.', reserveNote:'Doce créditos para miembros que quieren un saldo listo.', autoTitle:'Recarga Automática', autoBody:'Elige el paquete de créditos y el saldo mínimo que debe activar una recarga.', enable:'Activar Recarga Automática', refillAmount:'Monto de recarga', minimumBalance:'Recargar cuando el saldo llegue a', minimumZero:'0 créditos', minimumOne:'1 crédito', minimumTwo:'2 créditos', autoPreview:'Vista previa Prelaunch: la Recarga Automática está desactivada y no puede cobrar tu cuenta. Antes del lanzamiento requerirá un método de pago verificado y tu confirmación explícita.', noCharge:'Vista previa de precios Prelaunch: checkout no está activo y aquí no se puede cobrar ningún pago.', assessment:'Comenzar la evaluación de Bianca', member:'Crear una cuenta MyMatchIQ gratuita', included:['Saldo de créditos transparente','Sin cargo automático por función','Consentimiento claro antes de un Play mutuo'] },
  fr:{ eyebrow:'Portefeuille MyMatchIQ', title:'Utilisez des crédits uniquement lorsqu’une expérience significative commence.', body:'MyMatchIQ est gratuit à rejoindre. Les crédits débloquent des perspectives privées et des expériences intentionnelles à deux sans imposer un abonnement mensuel.', balance:'Votre solde de crédits', balanceValue:'0 crédit', balanceNote:'Créez et vérifiez un compte pour utiliser et suivre vos crédits.', personalTitle:'Perspective privée', personalBody:'Utilisez un Crédit Insight pour un Passeport de Compatibilité complet ou un Rapport approfondi sur les Schémas de Personnalité et de Relation.', playTitle:'Let’s Play mutuel', playBody:'Chaque personne utilise un Crédit Play de 1,99 $ US uniquement après que les deux ont accepté l’invitation. Rien n’est consommé tant que l’invitation est en attente.', controlTitle:'Vous gardez le contrôle', controlBody:'Votre portefeuille de crédits est distinct de votre abonnement. La Recharge automatique reste facultative et peut être désactivée à tout moment.', choiceTitle:'Choix de crédits', one:'Crédit Play unique', bundle:'Lot de six crédits', reserve:'Lot de douze crédits', onePrice:'1,99 $ US', bundlePrice:'9,99 $ US', reservePrice:'19,99 $ US', oneNote:'Une personne, une session Play intentionnelle.', bundleNote:'Six crédits pour des perspectives privées ou des sessions Play.', reserveNote:'Douze crédits pour les membres qui souhaitent un solde prêt.', autoTitle:'Recharge automatique', autoBody:'Choisissez le forfait de crédits et le solde minimum qui doit déclencher une recharge.', enable:'Activer la recharge automatique', refillAmount:'Montant de la recharge', minimumBalance:'Recharger lorsque le solde atteint', minimumZero:'0 crédit', minimumOne:'1 crédit', minimumTwo:'2 crédits', autoPreview:'Aperçu Prelaunch : la Recharge automatique est désactivée et ne peut pas débiter votre compte. Avant le lancement, elle exigera un moyen de paiement vérifié et votre confirmation explicite.', noCharge:'Aperçu tarifaire Prelaunch : le paiement n’est pas actif et aucun paiement ne peut être collecté ici.', assessment:'Commencer l’évaluation de Bianca', member:'Créer un compte MyMatchIQ gratuit', included:['Solde de crédits transparent','Pas de frais automatiques par fonctionnalité','Consentement clair avant un Play mutuel'] },
  it:{ eyebrow:'Portafoglio MyMatchIQ', title:'Usa i crediti solo quando inizia qualcosa di significativo.', body:'Iscriversi a MyMatchIQ è gratuito. I crediti sbloccano insight privati ed esperienze intenzionali per due persone senza imporre un abbonamento mensile.', balance:'Il tuo saldo crediti', balanceValue:'0 crediti', balanceNote:'Crea e verifica un account per usare e monitorare i crediti.', personalTitle:'Insight privato', personalBody:'Usa un Credito Insight per un Passaporto di Compatibilità completo o un Rapporto più approfondito sui Pattern di Personalità e Relazione.', playTitle:'Let’s Play reciproco', playBody:'Ogni persona usa un Credito Play da US$1,99 solo dopo che entrambi accettano l’invito. Non viene consumato nulla mentre un invito è in attesa.', controlTitle:'Hai tu il controllo', controlBody:'Il tuo portafoglio crediti è separato dall’abbonamento. La Ricarica Automatica è sempre opzionale e può essere disattivata in qualsiasi momento.', choiceTitle:'Scelte di credito', one:'Credito Play singolo', bundle:'Pacchetto da sei crediti', reserve:'Pacchetto da dodici crediti', onePrice:'US$1,99', bundlePrice:'US$9,99', reservePrice:'US$19,99', oneNote:'Una persona, una sessione Play intenzionale.', bundleNote:'Sei crediti per insight privati o sessioni Play.', reserveNote:'Dodici crediti per membri che vogliono un saldo disponibile.', autoTitle:'Ricarica Automatica', autoBody:'Scegli il pacchetto di crediti e il saldo minimo che deve attivare una ricarica.', enable:'Attiva Ricarica Automatica', refillAmount:'Importo della ricarica', minimumBalance:'Ricarica quando il saldo raggiunge', minimumZero:'0 crediti', minimumOne:'1 credito', minimumTwo:'2 crediti', autoPreview:'Anteprima Prelaunch: la Ricarica Automatica è disattivata e non può addebitare il tuo account. Prima del lancio richiederà un metodo di pagamento verificato e la tua conferma esplicita.', noCharge:'Anteprima prezzi Prelaunch: checkout non è attivo e qui non può essere riscosso alcun pagamento.', assessment:'Inizia la valutazione di Bianca', member:'Crea un account MyMatchIQ gratuito', included:['Saldo crediti trasparente','Nessun addebito automatico per funzione','Consenso chiaro prima di un Play reciproco'] },
  de:{ eyebrow:'MyMatchIQ-Wallet', title:'Verwenden Sie Credits nur, wenn etwas Sinnvolles beginnt.', body:'Der Beitritt zu MyMatchIQ ist kostenlos. Credits schalten private Erkenntnisse und bewusste Erlebnisse für zwei Personen frei, ohne ein Monatsabonnement zu erzwingen.', balance:'Ihr Credit-Guthaben', balanceValue:'0 Credits', balanceNote:'Erstellen und verifizieren Sie ein Konto, um Credits zu nutzen und nachzuverfolgen.', personalTitle:'Private Erkenntnisse', personalBody:'Nutzen Sie einen Insight-Credit für einen vollständigen Kompatibilitäts-Pass oder einen tieferen Bericht zu Persönlichkeits- und Beziehungsmustern.', playTitle:'Gegenseitiges Let’s Play', playBody:'Jede Person verwendet einen Play-Credit für 1,99 US$ erst, nachdem beide die Einladung akzeptiert haben. Solange eine Einladung wartet, wird nichts verbraucht.', controlTitle:'Sie behalten die Kontrolle', controlBody:'Ihr Credit-Wallet ist von der Mitgliedschaft getrennt. Automatisches Auffüllen ist immer optional und kann jederzeit ausgeschaltet werden.', choiceTitle:'Credit-Optionen', one:'Einzelner Play-Credit', bundle:'Sechs-Credit-Paket', reserve:'Zwölf-Credit-Paket', onePrice:'1,99 US$', bundlePrice:'9,99 US$', reservePrice:'19,99 US$', oneNote:'Eine Person, eine bewusste Play-Sitzung.', bundleNote:'Sechs Credits für private Erkenntnisse oder Play-Sitzungen.', reserveNote:'Zwölf Credits für Mitglieder, die ein verfügbares Guthaben wünschen.', autoTitle:'Automatisch auffüllen', autoBody:'Wählen Sie das Credit-Paket und den Mindeststand, der eine Auffüllung auslöst.', enable:'Automatisches Auffüllen aktivieren', refillAmount:'Auffüllbetrag', minimumBalance:'Auffüllen, wenn das Guthaben erreicht', minimumZero:'0 Credits', minimumOne:'1 Credit', minimumTwo:'2 Credits', autoPreview:'Prelaunch-Vorschau: Automatisches Auffüllen ist ausgeschaltet und kann Ihr Konto nicht belasten. Vor dem Launch sind eine verifizierte Zahlungsmethode und Ihre ausdrückliche Bestätigung erforderlich.', noCharge:'Prelaunch-Preisvorschau: Checkout ist nicht aktiv und hier kann keine Zahlung erhoben werden.', assessment:'Biancas Assessment starten', member:'Kostenloses MyMatchIQ-Konto erstellen', included:['Transparentes Credit-Guthaben','Keine automatische Gebühr pro Funktion','Klare Einwilligung vor gegenseitigem Play'] },
};

export default function MyMatchIQCredits() {
  const { currentLanguage } = useLanguage();
  const t = COPY[currentLanguage] || COPY.en;
  const [autoReplenish, setAutoReplenish] = useState(false);
  const [refillAmount, setRefillAmount] = useState('9.99');
  const [minimumBalance, setMinimumBalance] = useState('1');
  const choices = [[t.one,t.onePrice,t.oneNote,'border-fuchsia-300/40'],[t.bundle,t.bundlePrice,t.bundleNote,'border-cyan-300/40'],[t.reserve,t.reservePrice,t.reserveNote,'border-amber-300/40']];
  const refillOptions = [{ value:'1.99', label:t.onePrice }, { value:'9.99', label:t.bundlePrice }, { value:'19.99', label:t.reservePrice }];
  const thresholdOptions = [{ value:'0', label:t.minimumZero }, { value:'1', label:t.minimumOne }, { value:'2', label:t.minimumTwo }];

  return <main className="min-h-screen bg-[#070312] px-4 py-10 text-white sm:px-6" style={{ backgroundImage:'radial-gradient(circle at 12% 0%, #5b126f 0%, transparent 30%), radial-gradient(circle at 90% 24%, #162e78 0%, transparent 32%)' }}>
    <section className="mx-auto max-w-6xl">
      <p className="text-center text-xs font-black uppercase tracking-[0.22em] text-fuchsia-200">{t.eyebrow}</p><h1 className="mx-auto mt-4 max-w-4xl text-center text-4xl font-black sm:text-5xl">{t.title}</h1><p className="mx-auto mt-4 max-w-3xl text-center text-lg leading-8 text-white/80">{t.body}</p>
      <section className="mx-auto mt-8 max-w-3xl rounded-3xl border border-fuchsia-200/30 bg-black/35 p-6 text-center shadow-xl backdrop-blur"><WalletCards className="mx-auto h-9 w-9 text-fuchsia-200" /><p className="mt-3 text-sm font-bold text-fuchsia-100">{t.balance}</p><h2 className="mt-1 text-3xl font-black">{t.balanceValue}</h2><p className="mt-2 text-sm text-white/70">{t.balanceNote}</p></section>
      <section className="mt-7 grid gap-5 md:grid-cols-3">{[[Sparkles,t.personalTitle,t.personalBody],[HeartHandshake,t.playTitle,t.playBody],[LockKeyhole,t.controlTitle,t.controlBody]].map(([Icon,title,body])=><article key={title} className="rounded-3xl border border-white/15 bg-white/[0.06] p-6 shadow-xl backdrop-blur"><Icon className="h-9 w-9 text-cyan-200" /><h2 className="mt-4 text-xl font-black">{title}</h2><p className="mt-3 text-sm leading-6 text-white/75">{body}</p></article>)}</section>
      <h2 className="mt-12 text-center text-2xl font-black">{t.choiceTitle}</h2><section className="mt-5 grid gap-5 md:grid-cols-3">{choices.map(([title,price,note,border])=><article key={title} className={`rounded-3xl border ${border} bg-black/35 p-6 text-center shadow-xl`}><h3 className="text-xl font-black">{title}</h3><p className="mt-4 text-3xl font-black text-fuchsia-100">{price}</p><p className="mt-4 text-sm leading-6 text-white/75">{note}</p></article>)}</section>
      <section className="mx-auto mt-8 max-w-4xl rounded-3xl border border-cyan-200/35 bg-cyan-950/20 p-6 shadow-xl backdrop-blur"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><div className="flex items-center gap-3"><RefreshCw className="h-7 w-7 text-cyan-200"/><h2 className="text-2xl font-black">{t.autoTitle}</h2></div><p className="mt-3 max-w-2xl text-sm leading-6 text-cyan-50/85">{t.autoBody}</p></div><button type="button" aria-pressed={autoReplenish} onClick={()=>setAutoReplenish(value=>!value)} className={`inline-flex min-w-[148px] items-center justify-center rounded-full border px-4 py-3 text-sm font-black transition ${autoReplenish?'border-fuchsia-200 bg-fuchsia-500 text-white':'border-cyan-100/40 bg-white/10 text-cyan-50 hover:bg-white/20'}`}>{autoReplenish?'✓ ':''}{t.enable}</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-black text-cyan-50"><span className="mb-2 block">{t.refillAmount}</span><select value={refillAmount} onChange={event=>setRefillAmount(event.target.value)} className="w-full rounded-xl border border-cyan-100/30 bg-slate-950 px-4 py-3 font-semibold text-white">{refillOptions.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label className="text-sm font-black text-cyan-50"><span className="mb-2 block">{t.minimumBalance}</span><select value={minimumBalance} onChange={event=>setMinimumBalance(event.target.value)} className="w-full rounded-xl border border-cyan-100/30 bg-slate-950 px-4 py-3 font-semibold text-white">{thresholdOptions.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label></div><p className="mt-5 rounded-2xl border border-amber-200/25 bg-amber-950/25 p-4 text-sm leading-6 text-amber-50">{t.autoPreview}</p></section>
      <div className="mt-7 rounded-2xl border border-amber-200/25 bg-amber-950/25 p-4 text-center text-sm leading-6 text-amber-50">{t.noCharge}</div><ul className="mx-auto mt-7 max-w-2xl space-y-3 text-sm text-white/80">{t.included.map(item=><li key={item} className="flex items-center gap-3"><Check className="h-5 w-5 shrink-0 text-cyan-200" />{item}</li>)}</ul><div className="mt-8 flex flex-wrap justify-center gap-3"><Link to="/MyMatchIQ/Assessment" className="rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-5 py-3 text-sm font-black shadow-lg">{t.assessment}</Link><Link to="/MyMatchIQ/SignUp" className="rounded-full border border-white/30 bg-white/10 px-5 py-3 text-sm font-black transition hover:bg-white/20">{t.member}</Link></div>
    </section>
  </main>;
}
