import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Ban, Flag, HeartHandshake, Loader2, ShieldCheck, UserRoundCheck, UsersRound } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { useLanguage } from './Layout';
import { blockMyMatchIQMember, discoverMyMatchIQMembers, getMyMatchIQMemberProfile, listMyMatchIQInvitations, reportMyMatchIQMember, respondMyMatchIQInvitation, sendMyMatchIQInvitation, updateMyMatchIQMemberProfile } from '@/lib/aiService';

const COPY={
 en:{eyebrow:'MyMatchIQ intentional-member space',title:'Meet Intentional Members',body:'A consent-first space for people who want to learn compatibility before deciding where a connection could go.',signIn:'Sign in to One2OneLove',profile:'Your discovery profile',display:'Display name',bio:'Short bio',intent:'Relationship intention',discoverable:'Allow my profile to appear in discovery',invites:'Allow invitations',save:'Save profile',discover:'Discover members',empty:'No opted-in members are available right now.',invite:'Send Let’s Play invitation',incoming:'Invitations',accept:'Accept',decline:'Decline',cancel:'Cancel',block:'Block',report:'Report',reportDone:'Report submitted for review.',safety:'No open public chat. No unsolicited direct messages. Discovery and invitations require explicit opt-in, and either person can block or report at any time.',saved:'Profile saved.',sent:'Invitation sent.',error:'This feature is not available in the current visual preview.'},
 es:{eyebrow:'Espacio de miembros intencionales MyMatchIQ',title:'Conoce Miembros Intencionales',body:'Un espacio basado en consentimiento para quienes desean explorar compatibilidad antes de decidir hacia dónde puede ir una conexión.',signIn:'Iniciar sesión en One2OneLove',profile:'Tu perfil de descubrimiento',display:'Nombre visible',bio:'Biografía breve',intent:'Intención de relación',discoverable:'Permitir que mi perfil aparezca',invites:'Permitir invitaciones',save:'Guardar perfil',discover:'Descubrir miembros',empty:'No hay miembros disponibles ahora.',invite:'Enviar invitación Let’s Play',incoming:'Invitaciones',accept:'Aceptar',decline:'Rechazar',cancel:'Cancelar',block:'Bloquear',report:'Reportar',reportDone:'Reporte enviado para revisión.',safety:'Sin chat público abierto ni mensajes directos no solicitados. El descubrimiento y las invitaciones requieren consentimiento explícito.',saved:'Perfil guardado.',sent:'Invitación enviada.',error:'Esta función no está disponible en la vista previa actual.'},
 fr:{eyebrow:'Espace membres intentionnels MyMatchIQ',title:'Rencontrer des Membres Intentionnels',body:'Un espace fondé sur le consentement pour explorer la compatibilité avant de décider de la suite.',signIn:'Se connecter à One2OneLove',profile:'Votre profil de découverte',display:'Nom affiché',bio:'Courte bio',intent:'Intention relationnelle',discoverable:'Autoriser mon profil dans la découverte',invites:'Autoriser les invitations',save:'Enregistrer le profil',discover:'Découvrir des membres',empty:'Aucun membre inscrit n’est disponible pour le moment.',invite:'Envoyer une invitation Let’s Play',incoming:'Invitations',accept:'Accepter',decline:'Refuser',cancel:'Annuler',block:'Bloquer',report:'Signaler',reportDone:'Signalement envoyé pour examen.',safety:'Pas de chat public ouvert ni de messages directs non sollicités. Découverte et invitations exigent un consentement explicite.',saved:'Profil enregistré.',sent:'Invitation envoyée.',error:'Cette fonctionnalité n’est pas disponible dans l’aperçu actuel.'},
 it:{eyebrow:'Spazio membri intenzionali MyMatchIQ',title:'Incontra Membri Intenzionali',body:'Uno spazio basato sul consenso per esplorare la compatibilità prima di decidere come proseguire.',signIn:'Accedi a One2OneLove',profile:'Il tuo profilo di scoperta',display:'Nome visualizzato',bio:'Breve bio',intent:'Intenzione relazionale',discoverable:'Consenti al mio profilo di apparire',invites:'Consenti inviti',save:'Salva profilo',discover:'Scopri membri',empty:'Nessun membro disponibile al momento.',invite:'Invia invito Let’s Play',incoming:'Inviti',accept:'Accetta',decline:'Rifiuta',cancel:'Annulla',block:'Blocca',report:'Segnala',reportDone:'Segnalazione inviata per revisione.',safety:'Nessuna chat pubblica aperta o messaggi diretti non richiesti. Scoperta e inviti richiedono consenso esplicito.',saved:'Profilo salvato.',sent:'Invito inviato.',error:'Questa funzione non è disponibile nell’anteprima corrente.'},
 de:{eyebrow:'MyMatchIQ-Bereich für absichtsvolle Mitglieder',title:'Absichtsvolle Mitglieder Treffen',body:'Ein zustimmungsbasierter Bereich, um Kompatibilität zu erkunden, bevor über weitere Schritte entschieden wird.',signIn:'Bei One2OneLove anmelden',profile:'Ihr Entdeckungsprofil',display:'Anzeigename',bio:'Kurze Bio',intent:'Beziehungsabsicht',discoverable:'Mein Profil in der Entdeckung anzeigen',invites:'Einladungen erlauben',save:'Profil speichern',discover:'Mitglieder entdecken',empty:'Derzeit sind keine freigegebenen Mitglieder verfügbar.',invite:'Let’s-Play-Einladung senden',incoming:'Einladungen',accept:'Annehmen',decline:'Ablehnen',cancel:'Abbrechen',block:'Blockieren',report:'Melden',reportDone:'Meldung wurde zur Prüfung eingereicht.',safety:'Kein offener öffentlicher Chat und keine unerwünschten Direktnachrichten. Entdeckung und Einladungen erfordern ausdrückliche Zustimmung.',saved:'Profil gespeichert.',sent:'Einladung gesendet.',error:'Diese Funktion ist in der aktuellen Vorschau nicht verfügbar.'}
};

export default function MyMatchIQMeet(){
 const {currentLanguage}=useLanguage();const {isAuthenticated,user}=useAuth();const t=COPY[currentLanguage]||COPY.en;
 const [profile,setProfile]=useState(null);const [members,setMembers]=useState([]);const [invitations,setInvitations]=useState([]);const [loading,setLoading]=useState(isAuthenticated);const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');const [error,setError]=useState('');
 const [form,setForm]=useState({displayName:'',bio:'',relationshipIntent:'',discoverable:false,allowInvitations:false,showProfilePhoto:true,interests:[]});

 async function refresh(){if(!isAuthenticated)return;setLoading(true);setError('');try{const [p,m,i]=await Promise.all([getMyMatchIQMemberProfile(),discoverMyMatchIQMembers(),listMyMatchIQInvitations()]);setProfile(p);setForm({displayName:p?.display_name||'',bio:p?.bio||'',relationshipIntent:p?.relationship_intent||'',discoverable:Boolean(p?.discoverable),allowInvitations:Boolean(p?.allow_invitations),showProfilePhoto:p?.show_profile_photo!==false,interests:Array.isArray(p?.interests)?p.interests:[]});setMembers(m);setInvitations(i);}catch(e){setError(e?.message||t.error);}finally{setLoading(false);}}
 useEffect(()=>{refresh();},[isAuthenticated]);

 async function save(){setBusy('save');setError('');setNotice('');try{const p=await updateMyMatchIQMemberProfile(form);setProfile(p);setNotice(t.saved);await refresh();}catch(e){setError(e?.message||t.error);}finally{setBusy('');}}
 async function invite(member){setBusy(member.user_id);setError('');setNotice('');try{await sendMyMatchIQInvitation({toUserId:member.user_id,invitationType:'like_minded'});setNotice(t.sent);setInvitations(await listMyMatchIQInvitations());}catch(e){setError(e?.message||t.error);}finally{setBusy('');}}
 async function respond(id,status){setBusy(id);setError('');try{await respondMyMatchIQInvitation(id,status);setInvitations(await listMyMatchIQInvitations());}catch(e){setError(e?.message||t.error);}finally{setBusy('');}}
 async function block(member){setBusy('block'+member.user_id);try{await blockMyMatchIQMember(member.user_id);setMembers(v=>v.filter(x=>x.user_id!==member.user_id));setInvitations(await listMyMatchIQInvitations());}catch(e){setError(e?.message||t.error);}finally{setBusy('');}}
 async function report(member){const details=window.prompt(t.report)||'';if(details===null)return;setBusy('report'+member.user_id);try{await reportMyMatchIQMember({reportedUserId:member.user_id,category:'other',details});setNotice(t.reportDone);}catch(e){setError(e?.message||t.error);}finally{setBusy('');}}

 if(!isAuthenticated)return <main className="min-h-screen bg-[#070312] px-4 py-12 text-white"><section className="mx-auto max-w-3xl rounded-[2rem] border border-fuchsia-200/25 bg-white/[0.06] p-8 text-center"><UsersRound className="mx-auto h-12 w-12 text-fuchsia-200"/><h1 className="mt-5 text-4xl font-black">{t.title}</h1><p className="mt-4 text-white/75">{t.body}</p><Link to="/SignIn?source=mymatchiq-meet&redirect=%2FMyMatchIQ%2FMeet" className="mt-7 inline-flex rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-6 py-3 font-black">{t.signIn}</Link></section></main>;

 return <main className="min-h-screen bg-[#070312] px-4 py-10 text-white sm:px-6" style={{backgroundImage:'radial-gradient(circle at 18% 0%, #5b126f 0%, transparent 32%), radial-gradient(circle at 82% 12%, #162e78 0%, transparent 30%)'}}>
  <section className="mx-auto max-w-7xl">
   <p className="text-center text-xs font-black uppercase tracking-[0.22em] text-fuchsia-200">{t.eyebrow}</p><h1 className="mx-auto mt-4 max-w-4xl text-center text-4xl font-black sm:text-5xl">{t.title}</h1><p className="mx-auto mt-4 max-w-3xl text-center text-lg leading-8 text-white/80">{t.body}</p>
   <div className="mx-auto mt-7 flex max-w-4xl items-start gap-3 rounded-2xl border border-cyan-200/25 bg-cyan-950/30 p-4 text-sm leading-6 text-cyan-50"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0"/>{t.safety}</div>
   {loading&&<div className="mt-10 flex justify-center"><Loader2 className="h-8 w-8 animate-spin text-fuchsia-200"/></div>}
   {!loading&&<div className="mt-9 grid gap-6 lg:grid-cols-[0.85fr_1.15fr]">
    <section className="rounded-[1.75rem] border border-fuchsia-200/25 bg-black/35 p-6 shadow-xl"><div className="flex items-center gap-3"><UserRoundCheck className="h-8 w-8 text-fuchsia-200"/><h2 className="text-2xl font-black">{t.profile}</h2></div>
     <div className="mt-5 space-y-4"><label className="block text-sm font-bold">{t.display}<input value={form.displayName} onChange={e=>setForm(v=>({...v,displayName:e.target.value}))} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-950 px-4 py-3 text-white"/></label><label className="block text-sm font-bold">{t.bio}<textarea value={form.bio} onChange={e=>setForm(v=>({...v,bio:e.target.value}))} rows={4} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-950 px-4 py-3 text-white"/></label><label className="block text-sm font-bold">{t.intent}<input value={form.relationshipIntent} onChange={e=>setForm(v=>({...v,relationshipIntent:e.target.value}))} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-950 px-4 py-3 text-white"/></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={form.discoverable} onChange={e=>setForm(v=>({...v,discoverable:e.target.checked}))}/>{t.discoverable}</label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={form.allowInvitations} onChange={e=>setForm(v=>({...v,allowInvitations:e.target.checked}))}/>{t.invites}</label><button onClick={save} disabled={Boolean(busy)} className="w-full rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-5 py-3 font-black">{busy==='save'?<Loader2 className="mx-auto h-4 w-4 animate-spin"/>:t.save}</button></div>
    </section>
    <section className="rounded-[1.75rem] border border-cyan-200/25 bg-black/35 p-6 shadow-xl"><div className="flex items-center gap-3"><UsersRound className="h-8 w-8 text-cyan-200"/><h2 className="text-2xl font-black">{t.discover}</h2></div>
     <div className="mt-5 space-y-4">{members.length?members.map(member=><article key={member.user_id} className="rounded-2xl border border-white/10 bg-white/[0.05] p-5"><h3 className="text-xl font-black">{member.display_name}</h3><p className="mt-2 text-sm leading-6 text-white/70">{member.bio}</p>{member.relationship_intent&&<p className="mt-2 text-xs font-bold text-cyan-200">{member.relationship_intent}</p>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>invite(member)} disabled={Boolean(busy)} className="inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-4 py-2 text-sm font-black"><HeartHandshake className="h-4 w-4"/>{busy===member.user_id?<Loader2 className="h-4 w-4 animate-spin"/>:t.invite}</button><button onClick={()=>block(member)} className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/[0.06] px-4 py-2 text-sm"><Ban className="h-4 w-4"/>{t.block}</button><button onClick={()=>report(member)} className="inline-flex items-center gap-2 rounded-full border border-amber-200/20 bg-amber-950/20 px-4 py-2 text-sm text-amber-100"><Flag className="h-4 w-4"/>{t.report}</button></div></article>):<p className="text-white/50">{t.empty}</p>}</div>
    </section>
   </div>}
   {!loading&&<section className="mx-auto mt-7 max-w-5xl rounded-[1.75rem] border border-white/15 bg-white/[0.04] p-6"><h2 className="text-xl font-black">{t.incoming}</h2><div className="mt-4 space-y-3">{invitations.map(inv=><div key={inv.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm"><div><p className="font-bold">{inv.from_user_id===user?.id?`${inv.to_name||'Member'}`:`${inv.from_name||'Member'}`}</p><p className="text-white/45 capitalize">{String(inv.status||'').replaceAll('_',' ')}</p></div>{inv.status==='pending'&&<div className="flex gap-2">{inv.to_user_id===user?.id?<><button onClick={()=>respond(inv.id,'accepted')} className="rounded-full bg-cyan-600 px-4 py-2 font-black">{t.accept}</button><button onClick={()=>respond(inv.id,'declined')} className="rounded-full border border-white/20 px-4 py-2">{t.decline}</button></>:<button onClick={()=>respond(inv.id,'cancelled')} className="rounded-full border border-white/20 px-4 py-2">{t.cancel}</button>}</div>}</div>)}</div></section>}
   {(notice||error)&&<div className={`mx-auto mt-6 max-w-4xl rounded-2xl border p-4 text-sm ${error?'border-amber-200/25 bg-amber-950/25 text-amber-50':'border-cyan-200/25 bg-cyan-950/25 text-cyan-50'}`}>{error||notice}</div>}
  </section>
 </main>;
}
