import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, ArrowRight, BrainCircuit, CheckCircle2, Loader2, MessageCircle, ShieldCheck, Sparkles } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { useLanguage } from './Layout';
import { completePassport, createPassport, getAssessmentQuestions, getPassport, getPassportAnswers, savePassportAnswer } from '@/lib/mymatchiqService';
import { generateBiancaReport } from '@/lib/aiService';

const COPY={
 en:{eyebrow:'Bianca’s guided Compatibility Passport',title:'Personality & Relationship Pattern Assessment',intro:'Your Compatibility Passport is organized into 15 relationship dimensions with 15 questions in each dimension. Your progress saves as you go, so you can stop and return without starting over.',accuracy:'The more frequently you talk with Bianca, the more context she has. That can improve the accuracy and personalization of your Personality & Relationship Pattern Reports.',casual:'Casual talk with Bianca',start:'Start my Compatibility Passport',resume:'Resume my Compatibility Passport',progress:'Question {current} of {total}',dimension:'Dimension {current} of {total}',previous:'Previous',saving:'Saving…',complete:'Complete my Passport',done:'Compatibility Passport complete',doneBody:'Your answers are saved. Bianca can now combine this assessment with your conversations for a deeper private report.',report:'Generate my Bianca report',reportDone:'Your updated private report has been generated.',signIn:'Sign in to begin',create:'Create MyMatchIQ account',privacy:'Private self-reflection only. This is not therapy, diagnosis, or a guarantee of compatibility.',preview:'The live assessment API is staged for Prelaunch but this visual preview currently blocks API writes.'},
 es:{eyebrow:'Pasaporte de Compatibilidad guiado por Bianca',title:'Evaluación de Patrones de Personalidad y Relaciones',intro:'Tu Pasaporte de Compatibilidad está organizado en 15 dimensiones de relación con 15 preguntas en cada dimensión. Tu progreso se guarda mientras avanzas.',accuracy:'Cuanto más frecuentemente hables con Bianca, más contexto tendrá. Eso puede mejorar la precisión y personalización de tus Informes de Patrones de Personalidad y Relaciones.',casual:'Charla casual con Bianca',start:'Comenzar mi Pasaporte de Compatibilidad',resume:'Continuar mi Pasaporte de Compatibilidad',progress:'Pregunta {current} de {total}',dimension:'Dimensión {current} de {total}',previous:'Anterior',saving:'Guardando…',complete:'Completar mi Pasaporte',done:'Pasaporte de Compatibilidad completado',doneBody:'Tus respuestas están guardadas. Bianca ahora puede combinar esta evaluación con tus conversaciones para un informe privado más profundo.',report:'Generar mi informe de Bianca',reportDone:'Tu informe privado actualizado ha sido generado.',signIn:'Inicia sesión para comenzar',create:'Crear cuenta MyMatchIQ',privacy:'Solo para autorreflexión privada. Esto no es terapia, diagnóstico ni garantía de compatibilidad.',preview:'La API de evaluación está preparada para Prelaunch, pero esta vista visual actualmente bloquea escrituras API.'},
 fr:{eyebrow:'Passeport de Compatibilité guidé par Bianca',title:'Évaluation des Schémas de Personnalité et de Relation',intro:'Votre Passeport de Compatibilité est organisé en 15 dimensions relationnelles comportant chacune 15 questions. Votre progression est enregistrée au fur et à mesure.',accuracy:'Plus vous parlez régulièrement avec Bianca, plus elle dispose de contexte. Cela peut améliorer la précision et la personnalisation de vos rapports.',casual:'Discussion décontractée avec Bianca',start:'Commencer mon Passeport de Compatibilité',resume:'Reprendre mon Passeport de Compatibilité',progress:'Question {current} sur {total}',dimension:'Dimension {current} sur {total}',previous:'Précédent',saving:'Enregistrement…',complete:'Terminer mon Passeport',done:'Passeport de Compatibilité terminé',doneBody:'Vos réponses sont enregistrées. Bianca peut maintenant combiner cette évaluation avec vos conversations pour un rapport privé plus approfondi.',report:'Générer mon rapport Bianca',reportDone:'Votre rapport privé actualisé a été généré.',signIn:'Connectez-vous pour commencer',create:'Créer un compte MyMatchIQ',privacy:'Pour l’autoréflexion privée uniquement. Ceci n’est ni une thérapie, ni un diagnostic, ni une garantie de compatibilité.',preview:'L’API d’évaluation est prête pour Prelaunch, mais cet aperçu visuel bloque actuellement les écritures API.'},
 it:{eyebrow:'Passaporto di Compatibilità guidato da Bianca',title:'Valutazione dei Pattern di Personalità e Relazione',intro:'Il tuo Passaporto di Compatibilità è organizzato in 15 dimensioni relazionali con 15 domande per ciascuna. I progressi vengono salvati mentre procedi.',accuracy:'Più frequentemente parli con Bianca, più contesto avrà. Questo può migliorare l’accuratezza e la personalizzazione dei tuoi rapporti.',casual:'Conversazione informale con Bianca',start:'Inizia il mio Passaporto di Compatibilità',resume:'Riprendi il mio Passaporto di Compatibilità',progress:'Domanda {current} di {total}',dimension:'Dimensione {current} di {total}',previous:'Precedente',saving:'Salvataggio…',complete:'Completa il mio Passaporto',done:'Passaporto di Compatibilità completato',doneBody:'Le tue risposte sono salvate. Bianca può ora combinare questa valutazione con le tue conversazioni per un rapporto privato più approfondito.',report:'Genera il mio rapporto Bianca',reportDone:'Il tuo rapporto privato aggiornato è stato generato.',signIn:'Accedi per iniziare',create:'Crea account MyMatchIQ',privacy:'Solo per autoriflessione privata. Non è terapia, diagnosi o garanzia di compatibilità.',preview:'L’API di valutazione è pronta per Prelaunch, ma questa anteprima visiva attualmente blocca le scritture API.'},
 de:{eyebrow:'Von Bianca geführter Kompatibilitäts-Pass',title:'Assessment zu Persönlichkeits- und Beziehungsmustern',intro:'Ihr Kompatibilitäts-Pass ist in 15 Beziehungsdimensionen mit jeweils 15 Fragen gegliedert. Ihr Fortschritt wird laufend gespeichert.',accuracy:'Je häufiger Sie mit Bianca sprechen, desto mehr Kontext hat sie. Das kann die Genauigkeit und Personalisierung Ihrer Berichte verbessern.',casual:'Lockeres Gespräch mit Bianca',start:'Meinen Kompatibilitäts-Pass starten',resume:'Meinen Kompatibilitäts-Pass fortsetzen',progress:'Frage {current} von {total}',dimension:'Dimension {current} von {total}',previous:'Zurück',saving:'Speichern…',complete:'Meinen Pass abschließen',done:'Kompatibilitäts-Pass abgeschlossen',doneBody:'Ihre Antworten sind gespeichert. Bianca kann dieses Assessment nun mit Ihren Gesprächen zu einem tieferen privaten Bericht verbinden.',report:'Meinen Bianca-Bericht erstellen',reportDone:'Ihr aktualisierter privater Bericht wurde erstellt.',signIn:'Zum Start anmelden',create:'MyMatchIQ-Konto erstellen',privacy:'Nur zur privaten Selbstreflexion. Dies ist keine Therapie, Diagnose oder Garantie für Kompatibilität.',preview:'Die Assessment-API ist für Prelaunch vorbereitet, aber diese visuelle Vorschau blockiert derzeit API-Schreibvorgänge.'}
};
const DIMENSIONS={
 en:{values_priorities:'Values & Priorities',communication:'Communication',conflict:'Conflict & Repair',emotional_needs:'Emotional Needs',expectations:'Expectations',commitment:'Commitment',lifestyle:'Lifestyle',finances:'Finances',intimacy:'Intimacy & Consent',family:'Family',boundaries:'Boundaries',stress:'Stress & Coping',time:'Time & Availability',life_planning:'Life Planning',safety_red_flags:'Safety & Red Flags'},
 es:{values_priorities:'Valores y Prioridades',communication:'Comunicación',conflict:'Conflicto y Reparación',emotional_needs:'Necesidades Emocionales',expectations:'Expectativas',commitment:'Compromiso',lifestyle:'Estilo de Vida',finances:'Finanzas',intimacy:'Intimidad y Consentimiento',family:'Familia',boundaries:'Límites',stress:'Estrés y Afrontamiento',time:'Tiempo y Disponibilidad',life_planning:'Planificación de Vida',safety_red_flags:'Seguridad y Señales de Alerta'},
 fr:{values_priorities:'Valeurs et Priorités',communication:'Communication',conflict:'Conflit et Réparation',emotional_needs:'Besoins Émotionnels',expectations:'Attentes',commitment:'Engagement',lifestyle:'Mode de Vie',finances:'Finances',intimacy:'Intimité et Consentement',family:'Famille',boundaries:'Limites',stress:'Stress et Adaptation',time:'Temps et Disponibilité',life_planning:'Planification de Vie',safety_red_flags:'Sécurité et Signaux d’Alerte'},
 it:{values_priorities:'Valori e Priorità',communication:'Comunicazione',conflict:'Conflitto e Riparazione',emotional_needs:'Bisogni Emotivi',expectations:'Aspettative',commitment:'Impegno',lifestyle:'Stile di Vita',finances:'Finanze',intimacy:'Intimità e Consenso',family:'Famiglia',boundaries:'Confini',stress:'Stress e Adattamento',time:'Tempo e Disponibilità',life_planning:'Pianificazione della Vita',safety_red_flags:'Sicurezza e Segnali d’Allarme'},
 de:{values_priorities:'Werte und Prioritäten',communication:'Kommunikation',conflict:'Konflikt und Wiedergutmachung',emotional_needs:'Emotionale Bedürfnisse',expectations:'Erwartungen',commitment:'Verbindlichkeit',lifestyle:'Lebensstil',finances:'Finanzen',intimacy:'Intimität und Einvernehmen',family:'Familie',boundaries:'Grenzen',stress:'Stress und Bewältigung',time:'Zeit und Verfügbarkeit',life_planning:'Lebensplanung',safety_red_flags:'Sicherheit und Warnsignale'}
};

export default function MyMatchIQAssessment(){
 const {currentLanguage}=useLanguage();const {isAuthenticated}=useAuth();const t=COPY[currentLanguage]||COPY.en;const labels=DIMENSIONS[currentLanguage]||DIMENSIONS.en;
 const [questions,setQuestions]=useState([]);const [passport,setPassport]=useState(null);const [answerMap,setAnswerMap]=useState({});const [index,setIndex]=useState(0);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [completed,setCompleted]=useState(null);const [reportDone,setReportDone]=useState(false);
 const answeredCount=Object.keys(answerMap).length;const q=questions[index];const total=questions.length;const dimensionKeys=useMemo(()=>[...new Set(questions.map(x=>x.dimension_key))],[questions]);const dimensionIndex=q?Math.max(0,dimensionKeys.indexOf(q.dimension_key)):0;
 useEffect(()=>{if(!isAuthenticated)return;(async()=>{try{const [qs,p]=await Promise.all([getAssessmentQuestions(currentLanguage),getPassport()]);setQuestions(qs);setPassport(p);if(p){const a=await getPassportAnswers(p.id);const map=Object.fromEntries(a.map(x=>[x.question_id,x.value]));setAnswerMap(map);const first=qs.findIndex(x=>!map[x.id]);setIndex(first>=0?first:Math.max(0,qs.length-1));if(p.status==='complete')setCompleted({passport:p});}}catch(e){setError(e?.message||t.preview);}})();},[isAuthenticated,currentLanguage]);
 async function begin(){setLoading(true);setError('');try{const p=passport||await createPassport(currentLanguage);setPassport(p);if(passport){const a=await getPassportAnswers(passport.id);const map=Object.fromEntries(a.map(x=>[x.question_id,x.value]));setAnswerMap(map);const first=questions.findIndex(x=>!map[x.id]);setIndex(first>=0?first:0);}}catch(e){setError(e?.message||t.preview);}finally{setLoading(false);}}
 async function choose(value){if(!passport||!q||loading)return;setLoading(true);setError('');try{await savePassportAnswer(passport.id,q.id,value);const next={...answerMap,[q.id]:value};setAnswerMap(next);if(index<total-1)setIndex(index+1);}catch(e){setError(e?.message||t.preview);}finally{setLoading(false);}}
 async function finish(){if(!passport||loading)return;setLoading(true);setError('');try{const result=await completePassport(passport.id);setCompleted(result);try{await generateBiancaReport(currentLanguage);setReportDone(true);}catch{} }catch(e){setError(e?.message||t.preview);}finally{setLoading(false);}}
 async function makeReport(){setLoading(true);setError('');try{await generateBiancaReport(currentLanguage);setReportDone(true);}catch(e){setError(e?.message||t.preview);}finally{setLoading(false);}}
 if(!isAuthenticated)return <main className="min-h-screen bg-[#070312] px-4 py-12 text-white"><section className="mx-auto max-w-3xl rounded-[2rem] border border-fuchsia-200/25 bg-white/[0.06] p-8 text-center"><img src="/assets/bianca-mymatchiq-portrait-v2.webp" alt="Bianca" className="mx-auto w-48 rounded-3xl"/><h1 className="mt-6 text-4xl font-black">{t.title}</h1><p className="mt-4 text-white/75">{t.intro}</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link to="/MyMatchIQ/SignIn" className="rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-6 py-3 font-black">{t.signIn}</Link><Link to="/MyMatchIQ/SignUp" className="rounded-full border border-white/30 bg-white/10 px-6 py-3 font-black">{t.create}</Link></div></section></main>;
 if(completed)return <main className="min-h-screen bg-[#070312] px-4 py-12 text-white"><section className="mx-auto max-w-5xl rounded-[2rem] border border-fuchsia-200/25 bg-black/35 p-8 shadow-2xl"><CheckCircle2 className="h-14 w-14 text-emerald-300"/><h1 className="mt-4 text-4xl font-black">{t.done}</h1><p className="mt-3 max-w-3xl text-white/75">{t.doneBody}</p>{completed.dimensionScores&&<div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(completed.dimensionScores).map(([key,val])=><div key={key} className="rounded-2xl border border-white/10 bg-white/[0.05] p-4"><div className="flex justify-between gap-3 text-sm font-bold"><span>{labels[key]||key}</span><span>{Math.round(val.score)}%</span></div><div className="mt-2 h-2 rounded-full bg-white/10"><div className="h-2 rounded-full bg-gradient-to-r from-fuchsia-500 to-cyan-400" style={{width:`${Math.round(val.score)}%`}}/></div></div>)}</div>}<div className="mt-8 flex flex-wrap gap-3"><button onClick={makeReport} disabled={loading} className="inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-5 py-3 font-black"><BrainCircuit className="h-4 w-4"/>{t.report}</button><Link to="/MyMatchIQ/Bianca" className="inline-flex items-center gap-2 rounded-full border border-white/25 bg-white/10 px-5 py-3 font-black"><MessageCircle className="h-4 w-4"/>{t.casual}</Link></div>{reportDone&&<p className="mt-4 text-sm font-bold text-emerald-200">{t.reportDone}</p>}</section></main>;
 return <main className="min-h-screen bg-[#070312] px-3 py-6 text-white sm:px-6" style={{backgroundImage:'radial-gradient(circle at 14% 0%, #5b126f 0%, transparent 30%), radial-gradient(circle at 86% 16%, #162e78 0%, transparent 28%)'}}><section className="mx-auto max-w-5xl">
  <div className="overflow-hidden rounded-[2rem] border border-fuchsia-200/25 bg-black/35 shadow-2xl backdrop-blur">
   <div className="grid items-end gap-4 border-b border-white/10 bg-gradient-to-r from-fuchsia-950/70 to-indigo-950/70 px-6 pt-8 sm:grid-cols-[1fr_210px] sm:px-10"><div className="pb-8"><p className="text-xs font-black uppercase tracking-[0.22em] text-fuchsia-200">{t.eyebrow}</p><h1 className="mt-3 text-3xl font-black leading-tight sm:text-5xl">{t.title}</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-white/70 sm:text-base">{t.intro}</p></div><img src="/assets/bianca-mymatchiq-portrait-v2.webp" alt="Bianca" className="mx-auto w-[168px] rounded-t-[1.25rem] border-x border-t border-white/20 object-contain object-bottom sm:w-[190px]"/></div>
   <div className="border-b border-white/10 bg-cyan-950/20 px-6 py-5 sm:px-10"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-2xl text-sm leading-6 text-cyan-50/85"><Sparkles className="mr-2 inline h-4 w-4 text-fuchsia-200"/>{t.accuracy}</p><Link to="/MyMatchIQ/Bianca" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-full bg-gradient-to-r from-fuchsia-500 via-pink-500 to-violet-600 px-5 py-3 text-sm font-black"><MessageCircle className="h-4 w-4"/>{t.casual}</Link></div></div>
   {!passport?<div className="p-8 text-center sm:p-12"><ShieldCheck className="mx-auto h-10 w-10 text-cyan-200"/><p className="mx-auto mt-4 max-w-2xl text-sm leading-6 text-white/65">{t.privacy}</p><button onClick={begin} disabled={loading||!questions.length} className="mt-7 inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-6 py-3 font-black">{loading?<Loader2 className="h-5 w-5 animate-spin"/>:<BrainCircuit className="h-5 w-5"/>}{t.start}</button></div>:q?<div className="p-6 sm:p-10">
    <div className="flex flex-wrap items-center justify-between gap-3 text-sm font-bold text-fuchsia-100"><span>{t.dimension.replace('{current}',String(dimensionIndex+1)).replace('{total}',String(dimensionKeys.length))}: {labels[q.dimension_key]||q.dimension_key}</span><span>{t.progress.replace('{current}',String(index+1)).replace('{total}',String(total))}</span></div>
    <div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-fuchsia-500 to-cyan-400 transition-all" style={{width:`${total?((index+1)/total)*100:0}%`}}/></div>
    <h2 className="mt-8 text-2xl font-black leading-snug sm:text-3xl">{q.prompt}</h2>
    <div className="mt-7 grid gap-3">{(q.options||[]).map(opt=><button key={opt.value} disabled={loading} onClick={()=>choose(Number(opt.value))} className={`flex items-center justify-between rounded-2xl border px-5 py-4 text-left font-semibold transition ${answerMap[q.id]===Number(opt.value)?'border-fuchsia-200 bg-fuchsia-500/25':'border-white/20 bg-white/[0.05] hover:border-fuchsia-200 hover:bg-fuchsia-500/10'}`}><span>{opt.label}</span>{answerMap[q.id]===Number(opt.value)&&<CheckCircle2 className="h-5 w-5 text-fuchsia-200"/>}</button>)}</div>
    <div className="mt-8 flex flex-wrap items-center justify-between gap-3"><button onClick={()=>setIndex(v=>Math.max(0,v-1))} disabled={index===0||loading} className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-5 py-3 text-sm font-black disabled:opacity-30"><ArrowLeft className="h-4 w-4"/>{t.previous}</button><span className="text-sm text-white/55">{answeredCount}/{total}</span>{index===total-1&&answeredCount===total?<button onClick={finish} disabled={loading} className="inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-emerald-500 to-cyan-500 px-6 py-3 text-sm font-black">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<CheckCircle2 className="h-4 w-4"/>}{t.complete}</button>:<button onClick={()=>setIndex(v=>Math.min(total-1,v+1))} disabled={index>=total-1||loading} className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-5 py-3 text-sm font-black disabled:opacity-30"><ArrowRight className="h-4 w-4"/></button>}</div>
   </div>:<div className="p-10 text-center text-white/60"><Loader2 className="mx-auto h-7 w-7 animate-spin"/></div>}
   {error&&<div className="mx-6 mb-6 rounded-xl border border-amber-200/25 bg-amber-950/25 p-4 text-sm text-amber-50 sm:mx-10">{error}</div>}
  </div>
 </section></main>;
}
