import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { BrainCircuit, ClipboardCheck, Loader2, MessageCircle, ShieldCheck } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { useLanguage } from './Layout';
import { claimMyMatchIQLegacyMigration, getMyMatchIQLatestAssessmentSession, getMyMatchIQLegacyMigrationStatus, listBiancaReports } from '@/lib/aiService';
import { MMIQ_DIMENSIONS } from '@/lib/mymatchiqAssessment';

const COPY={
 en:{eyebrow:'Compatibility Passport',title:'Your private MyMatchIQ record',body:'Your Compatibility Passport brings together your latest structured assessment and Bianca-generated Personality & Relationship Pattern Reports.',assessment:'Latest assessment',reports:'Saved Bianca reports',emptyAssessment:'No saved assessment yet.',emptyReports:'No saved Bianca report yet.',start:'Take the assessment',talk:'Talk with Bianca',status:'Status',questions:'Questions answered',latest:'Latest report',evidence:'Evidence points',context:'Context depth',privacy:'Private to your account. These records are for self-reflection and are not a diagnosis or guarantee of compatibility.',signIn:'Sign in to view your Compatibility Passport', legacyTitle:'Legacy MyMatchIQ record found', legacyBody:'We found a MyMatchIQ record that matches your verified email. Claiming it preserves the legacy record under this verified One2OneLove identity without copying a password.', legacyClaim:'Claim my MyMatchIQ record', legacyClaimed:'Legacy MyMatchIQ record linked successfully.'},
 es:{eyebrow:'Pasaporte de Compatibilidad',title:'Tu registro privado de MyMatchIQ',body:'Tu Pasaporte de Compatibilidad reúne tu evaluación estructurada más reciente y los Informes de Patrones de Personalidad y Relaciones creados por Bianca.',assessment:'Evaluación más reciente',reports:'Informes guardados de Bianca',emptyAssessment:'Aún no hay una evaluación guardada.',emptyReports:'Aún no hay un informe guardado de Bianca.',start:'Realizar la evaluación',talk:'Hablar con Bianca',status:'Estado',questions:'Preguntas respondidas',latest:'Informe más reciente',evidence:'Puntos de evidencia',context:'Profundidad de contexto',privacy:'Privado para tu cuenta. Estos registros son para autorreflexión y no constituyen un diagnóstico ni garantía de compatibilidad.',signIn:'Inicia sesión para ver tu Pasaporte de Compatibilidad', legacyTitle:'Registro anterior de MyMatchIQ encontrado', legacyBody:'Encontramos un registro MyMatchIQ que coincide con tu correo verificado. Al reclamarlo se conserva bajo esta identidad verificada de One2OneLove sin copiar contraseñas.', legacyClaim:'Reclamar mi registro MyMatchIQ', legacyClaimed:'Registro MyMatchIQ anterior vinculado correctamente.'},
 fr:{eyebrow:'Passeport de Compatibilité',title:'Votre dossier privé MyMatchIQ',body:'Votre Passeport de Compatibilité réunit votre dernière évaluation structurée et les rapports créés par Bianca.',assessment:'Dernière évaluation',reports:'Rapports Bianca enregistrés',emptyAssessment:'Aucune évaluation enregistrée pour le moment.',emptyReports:'Aucun rapport Bianca enregistré pour le moment.',start:'Faire l’évaluation',talk:'Parler avec Bianca',status:'Statut',questions:'Questions répondues',latest:'Dernier rapport',evidence:'Éléments de preuve',context:'Profondeur du contexte',privacy:'Privé pour votre compte. Ces informations servent à l’autoréflexion et ne constituent ni un diagnostic ni une garantie de compatibilité.',signIn:'Connectez-vous pour voir votre Passeport de Compatibilité', legacyTitle:'Ancien dossier MyMatchIQ trouvé', legacyBody:'Un dossier MyMatchIQ correspond à votre e-mail vérifié. Le réclamer le rattache à cette identité One2OneLove vérifiée sans copier de mot de passe.', legacyClaim:'Réclamer mon dossier MyMatchIQ', legacyClaimed:'Ancien dossier MyMatchIQ lié avec succès.'},
 it:{eyebrow:'Passaporto di Compatibilità',title:'Il tuo registro privato MyMatchIQ',body:'Il tuo Passaporto di Compatibilità riunisce l’ultima valutazione strutturata e i rapporti creati da Bianca.',assessment:'Valutazione più recente',reports:'Rapporti Bianca salvati',emptyAssessment:'Nessuna valutazione salvata.',emptyReports:'Nessun rapporto Bianca salvato.',start:'Fai la valutazione',talk:'Parla con Bianca',status:'Stato',questions:'Domande risposte',latest:'Rapporto più recente',evidence:'Elementi di evidenza',context:'Profondità del contesto',privacy:'Privato per il tuo account. Questi dati sono per autoriflessione e non costituiscono diagnosi né garanzia di compatibilità.',signIn:'Accedi per vedere il tuo Passaporto di Compatibilità', legacyTitle:'Record MyMatchIQ precedente trovato', legacyBody:'Abbiamo trovato un record MyMatchIQ che corrisponde alla tua e-mail verificata. Il recupero lo collega a questa identità One2OneLove senza copiare password.', legacyClaim:'Recupera il mio record MyMatchIQ', legacyClaimed:'Record MyMatchIQ precedente collegato correttamente.'},
 de:{eyebrow:'Kompatibilitäts-Pass',title:'Ihr privater MyMatchIQ-Datensatz',body:'Ihr Kompatibilitäts-Pass vereint Ihr aktuelles strukturiertes Assessment und die von Bianca erstellten Berichte.',assessment:'Aktuelles Assessment',reports:'Gespeicherte Bianca-Berichte',emptyAssessment:'Noch kein Assessment gespeichert.',emptyReports:'Noch kein Bianca-Bericht gespeichert.',start:'Assessment starten',talk:'Mit Bianca sprechen',status:'Status',questions:'Beantwortete Fragen',latest:'Aktueller Bericht',evidence:'Evidenzpunkte',context:'Kontexttiefe',privacy:'Privat für Ihr Konto. Diese Daten dienen der Selbstreflexion und sind keine Diagnose oder Kompatibilitätsgarantie.',signIn:'Anmelden, um den Kompatibilitäts-Pass zu sehen', legacyTitle:'Früherer MyMatchIQ-Datensatz gefunden', legacyBody:'Wir haben einen MyMatchIQ-Datensatz zu Ihrer verifizierten E-Mail gefunden. Beim Übernehmen wird er dieser verifizierten One2OneLove-Identität zugeordnet, ohne ein Passwort zu kopieren.', legacyClaim:'Meinen MyMatchIQ-Datensatz übernehmen', legacyClaimed:'Früherer MyMatchIQ-Datensatz erfolgreich verknüpft.'}
};

export default function MyMatchIQPassport(){
 const {currentLanguage}=useLanguage();
 const {isAuthenticated}=useAuth();
 const t=COPY[currentLanguage]||COPY.en;
 const [assessment,setAssessment]=useState(null);
 const [reports,setReports]=useState([]);
 const [legacy,setLegacy]=useState(null);
 const [claiming,setClaiming]=useState(false);
 const [loading,setLoading]=useState(isAuthenticated);
 const [error,setError]=useState('');
 const labels=useMemo(()=>Object.fromEntries(MMIQ_DIMENSIONS.map(d=>[d.id,d.label[currentLanguage]||d.label.en])),[currentLanguage]);

 useEffect(()=>{ if(!isAuthenticated)return; let cancelled=false; setLoading(true); Promise.all([getMyMatchIQLatestAssessmentSession(),listBiancaReports(),getMyMatchIQLegacyMigrationStatus()]).then(([a,r,m])=>{if(cancelled)return;setAssessment(a);setReports(r||[]);setLegacy(m);}).catch(e=>{if(!cancelled)setError(e?.message||'Unable to load passport.');}).finally(()=>{if(!cancelled)setLoading(false);}); return()=>{cancelled=true}; },[isAuthenticated]);

 async function claimLegacy(){setClaiming(true);setError('');try{const result=await claimMyMatchIQLegacyMigration();setLegacy(v=>({...v,status:'claimed',...result}));setError('');setAssessment(await getMyMatchIQLatestAssessmentSession());}catch(e){setError(e?.message||'Unable to claim legacy record.');}finally{setClaiming(false);}}

 if(!isAuthenticated)return <main className="min-h-screen bg-[#070312] px-4 py-12 text-white"><section className="mx-auto max-w-3xl rounded-[2rem] border border-fuchsia-200/25 bg-white/[0.06] p-8 text-center"><ClipboardCheck className="mx-auto h-12 w-12 text-fuchsia-200"/><h1 className="mt-5 text-4xl font-black">{t.title}</h1><p className="mt-4 text-white/75">{t.body}</p><Link to="/SignIn?source=mymatchiq-passport&redirect=%2FMyMatchIQ%2FPassport" className="mt-7 inline-flex rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-6 py-3 font-black">{t.signIn}</Link></section></main>;

 return <main className="min-h-screen bg-[#070312] px-4 py-10 text-white sm:px-6" style={{backgroundImage:'radial-gradient(circle at 16% 0%, #5b126f 0%, transparent 32%), radial-gradient(circle at 86% 20%, #162e78 0%, transparent 32%)'}}>
  <section className="mx-auto max-w-6xl">
   <p className="text-center text-xs font-black uppercase tracking-[0.22em] text-fuchsia-200">{t.eyebrow}</p><h1 className="mx-auto mt-4 max-w-4xl text-center text-4xl font-black sm:text-5xl">{t.title}</h1><p className="mx-auto mt-4 max-w-3xl text-center text-lg leading-8 text-white/80">{t.body}</p>
   {loading&&<div className="mt-10 flex justify-center"><Loader2 className="h-8 w-8 animate-spin text-fuchsia-200"/></div>}
   {legacy?.eligible&&legacy.status==='pending'&&<section className="mx-auto mt-7 max-w-4xl rounded-2xl border border-fuchsia-200/30 bg-fuchsia-950/25 p-5 text-white"><h2 className="font-black text-fuchsia-100">{t.legacyTitle}</h2><p className="mt-2 text-sm leading-6 text-white/75">{t.legacyBody}</p><button type="button" onClick={claimLegacy} disabled={claiming} className="mt-4 rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-5 py-3 text-sm font-black disabled:opacity-50">{claiming?<Loader2 className="h-4 w-4 animate-spin"/>:t.legacyClaim}</button></section>}
   {legacy?.eligible&&legacy.status==='claimed'&&<div className="mx-auto mt-7 max-w-4xl rounded-2xl border border-cyan-200/25 bg-cyan-950/25 p-4 text-sm text-cyan-50">{t.legacyClaimed}</div>}
   {error&&<div className="mx-auto mt-7 max-w-3xl rounded-2xl border border-amber-200/25 bg-amber-950/25 p-4 text-amber-50">{error}</div>}
   {!loading&&<div className="mt-9 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]">
    <section className="rounded-[1.75rem] border border-fuchsia-200/25 bg-black/35 p-6 shadow-xl backdrop-blur"><div className="flex items-center gap-3"><ClipboardCheck className="h-8 w-8 text-fuchsia-200"/><h2 className="text-2xl font-black">{t.assessment}</h2></div>
     {!assessment?<div className="mt-6"><p className="text-white/65">{t.emptyAssessment}</p><Link to="/MyMatchIQ/Assessment" className="mt-5 inline-flex rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-5 py-3 text-sm font-black">{t.start}</Link></div>:<div className="mt-6 space-y-4"><div className="grid grid-cols-2 gap-3 text-sm"><div className="rounded-2xl bg-white/[0.06] p-4"><p className="text-white/50">{t.status}</p><p className="mt-1 font-black capitalize">{assessment.status}</p></div><div className="rounded-2xl bg-white/[0.06] p-4"><p className="text-white/50">{t.questions}</p><p className="mt-1 text-2xl font-black">{assessment.question_count||0}</p></div></div><div className="grid gap-3 sm:grid-cols-2">{Object.entries(assessment.dimension_scores||{}).map(([key,value])=><div key={key} className="rounded-xl border border-white/10 bg-white/[0.04] p-3"><div className="flex items-center justify-between gap-3 text-sm"><span className="font-bold">{labels[key]||key}</span><span>{value}/100</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-fuchsia-500 to-cyan-400" style={{width:`${value}%`}}/></div></div>)}</div><Link to="/MyMatchIQ/Assessment" className="inline-flex rounded-full border border-white/25 bg-white/10 px-5 py-3 text-sm font-black">{t.start}</Link></div>}
    </section>
    <section className="rounded-[1.75rem] border border-cyan-200/25 bg-black/35 p-6 shadow-xl backdrop-blur"><div className="flex items-center gap-3"><BrainCircuit className="h-8 w-8 text-cyan-200"/><h2 className="text-2xl font-black">{t.reports}</h2></div>
     {!reports.length?<div className="mt-6"><p className="text-white/65">{t.emptyReports}</p><Link to="/MyMatchIQ/Bianca" className="mt-5 inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-5 py-3 text-sm font-black"><MessageCircle className="h-4 w-4"/>{t.talk}</Link></div>:<div className="mt-6 space-y-4">{reports.map((report,index)=><article key={report.id} className="rounded-2xl border border-white/10 bg-white/[0.05] p-5"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-black text-cyan-100">{index===0?t.latest:new Date(report.created_at).toLocaleDateString()}</p><div className="flex gap-3 text-xs text-white/50"><span>{t.evidence}: {report.evidence_count}</span><span>{t.context}: {report.context_depth_score}%</span></div></div><p className="mt-3 leading-7 text-white/80">{report.summary}</p>{Array.isArray(report.strengths)&&report.strengths.length>0&&<ul className="mt-4 space-y-2 text-sm text-white/70">{report.strengths.slice(0,3).map(item=><li key={item}>• {item}</li>)}</ul>}</article>)}</div>}
    </section>
   </div>}
   <div className="mx-auto mt-7 flex max-w-4xl items-start gap-3 rounded-2xl border border-white/15 bg-white/[0.04] p-4 text-sm leading-6 text-white/65"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-cyan-200"/>{t.privacy}</div>
  </section>
 </main>;
}
