import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Check, HeartHandshake, Loader2, LockKeyhole, RefreshCw, Sparkles, WalletCards } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { useLanguage } from './Layout';
import { createMyMatchIQCreditCheckout, createMyMatchIQSetupIntent, getMyMatchIQCreditWallet, updateMyMatchIQAutoReplenish } from '@/lib/aiService';

const COPY={
 en:{eyebrow:'MyMatchIQ wallet',title:'Use credits only when something meaningful begins.',body:'MyMatchIQ is free to join. Credits unlock private insight and intentional two-person experiences without forcing a monthly subscription.',balance:'Your credit balance',balanceNote:'Your wallet updates only after a verified paid transaction.',personalTitle:'Private insight',personalBody:'Use an Insight Credit for a full Compatibility Passport or a deeper Personality & Relationship Pattern Report.',playTitle:'Mutual Let’s Play',playBody:'Each person uses one $1.99 Play Credit only after both accept the invitation. Nothing is consumed while an invitation is waiting.',controlTitle:'You stay in control',controlBody:'Your credit wallet is separate from membership. Auto Replenish is optional and can be turned off anytime.',choiceTitle:'Credit choices',one:'Single Play Credit',bundle:'Six-credit bundle',reserve:'Twelve-credit bundle',onePrice:'US$1.99',bundlePrice:'US$9.99',reservePrice:'US$19.99',oneNote:'One credit.',bundleNote:'Six credits.',reserveNote:'Twelve credits.',buy:'Buy credits',autoTitle:'Auto Replenish',autoBody:'Choose the credit package and the minimum balance that should trigger a refill.',enable:'Enable Auto Replenish',disable:'Disable Auto Replenish',refillAmount:'Refill amount',minimumBalance:'Refill when balance reaches',paymentNeeded:'A verified payment method is required before Auto Replenish can be enabled.', addPayment:'Add payment method',prelaunch:'Prelaunch is fail-closed: no charge occurs unless Stripe Prelaunch checkout is configured and you complete checkout.',assessment:'Start Bianca’s assessment',member:'Create a free MyMatchIQ account',signIn:'Sign in to use your wallet',loading:'Loading wallet…',transactions:'Recent wallet activity',none:'No credit transactions yet.',error:'Wallet service is not available in this preview.',included:['Transparent credit balance','No automatic per-feature charge','Clear consent before Mutual Play']},
 es:{eyebrow:'Billetera MyMatchIQ',title:'Usa créditos solo cuando comienza algo significativo.',body:'Unirse a MyMatchIQ es gratis. Los créditos desbloquean información privada y experiencias intencionales sin forzar una suscripción mensual.',balance:'Tu saldo de créditos',balanceNote:'Tu billetera se actualiza solo después de una transacción pagada verificada.',personalTitle:'Información privada',personalBody:'Usa un Crédito de Insight para un Pasaporte de Compatibilidad completo o un informe más profundo.',playTitle:'Let’s Play mutuo',playBody:'Cada persona usa un Crédito Play de US$1.99 solo después de que ambas aceptan.',controlTitle:'Tú mantienes el control',controlBody:'Tu billetera es independiente de la membresía. La recarga automática es opcional.',choiceTitle:'Opciones de créditos',one:'Crédito Play individual',bundle:'Paquete de seis créditos',reserve:'Paquete de doce créditos',onePrice:'US$1.99',bundlePrice:'US$9.99',reservePrice:'US$19.99',oneNote:'Un crédito.',bundleNote:'Seis créditos.',reserveNote:'Doce créditos.',buy:'Comprar créditos',autoTitle:'Recarga Automática',autoBody:'Elige el paquete y el saldo mínimo que debe activar una recarga.',enable:'Activar Recarga Automática',disable:'Desactivar Recarga Automática',refillAmount:'Monto de recarga',minimumBalance:'Recargar cuando el saldo llegue a',paymentNeeded:'Se requiere un método de pago verificado antes de activar la Recarga Automática.', addPayment:'Agregar método de pago',prelaunch:'Prelaunch se mantiene cerrado por seguridad: no se realiza ningún cobro a menos que Stripe Prelaunch esté configurado y completes el checkout.',assessment:'Comenzar la evaluación de Bianca',member:'Crear una cuenta MyMatchIQ gratuita',signIn:'Inicia sesión para usar tu billetera',loading:'Cargando billetera…',transactions:'Actividad reciente',none:'Aún no hay transacciones.',error:'El servicio de billetera no está disponible en esta vista previa.',included:['Saldo transparente','Sin cargo automático por función','Consentimiento claro antes de un Play mutuo']},
 fr:{eyebrow:'Portefeuille MyMatchIQ',title:'Utilisez des crédits uniquement lorsqu’une expérience significative commence.',body:'MyMatchIQ est gratuit à rejoindre. Les crédits débloquent des perspectives privées sans imposer un abonnement mensuel.',balance:'Votre solde de crédits',balanceNote:'Votre portefeuille est mis à jour uniquement après une transaction payée vérifiée.',personalTitle:'Perspective privée',personalBody:'Utilisez un Crédit Insight pour un Passeport de Compatibilité complet ou un rapport plus approfondi.',playTitle:'Let’s Play mutuel',playBody:'Chaque personne utilise un crédit de 1,99 $ US seulement après acceptation mutuelle.',controlTitle:'Vous gardez le contrôle',controlBody:'Votre portefeuille est distinct de l’abonnement. La recharge automatique est facultative.',choiceTitle:'Choix de crédits',one:'Crédit Play unique',bundle:'Lot de six crédits',reserve:'Lot de douze crédits',onePrice:'1,99 $ US',bundlePrice:'9,99 $ US',reservePrice:'19,99 $ US',oneNote:'Un crédit.',bundleNote:'Six crédits.',reserveNote:'Douze crédits.',buy:'Acheter des crédits',autoTitle:'Recharge automatique',autoBody:'Choisissez le forfait et le solde minimum qui doit déclencher une recharge.',enable:'Activer la recharge automatique',disable:'Désactiver la recharge automatique',refillAmount:'Montant de la recharge',minimumBalance:'Recharger lorsque le solde atteint',paymentNeeded:'Un moyen de paiement vérifié est requis avant d’activer la recharge automatique.', addPayment:'Ajouter un moyen de paiement',prelaunch:'Prelaunch reste fermé par sécurité : aucun débit n’a lieu sans Stripe Prelaunch configuré et un paiement finalisé.',assessment:'Commencer l’évaluation de Bianca',member:'Créer un compte MyMatchIQ gratuit',signIn:'Connectez-vous pour utiliser votre portefeuille',loading:'Chargement du portefeuille…',transactions:'Activité récente',none:'Aucune transaction pour le moment.',error:'Le service de portefeuille n’est pas disponible dans cet aperçu.',included:['Solde transparent','Pas de frais automatiques par fonctionnalité','Consentement clair avant un Play mutuel']},
 it:{eyebrow:'Portafoglio MyMatchIQ',title:'Usa i crediti solo quando inizia qualcosa di significativo.',body:'Iscriversi a MyMatchIQ è gratuito. I crediti sbloccano insight privati senza imporre un abbonamento mensile.',balance:'Il tuo saldo crediti',balanceNote:'Il portafoglio si aggiorna solo dopo una transazione pagata verificata.',personalTitle:'Insight privato',personalBody:'Usa un Credito Insight per un Passaporto di Compatibilità completo o un rapporto più approfondito.',playTitle:'Let’s Play reciproco',playBody:'Ogni persona usa un credito da US$1,99 solo dopo l’accettazione reciproca.',controlTitle:'Hai tu il controllo',controlBody:'Il portafoglio è separato dall’abbonamento. La ricarica automatica è facoltativa.',choiceTitle:'Scelte di credito',one:'Credito Play singolo',bundle:'Pacchetto da sei crediti',reserve:'Pacchetto da dodici crediti',onePrice:'US$1,99',bundlePrice:'US$9,99',reservePrice:'US$19,99',oneNote:'Un credito.',bundleNote:'Sei crediti.',reserveNote:'Dodici crediti.',buy:'Acquista crediti',autoTitle:'Ricarica Automatica',autoBody:'Scegli il pacchetto e il saldo minimo che deve attivare una ricarica.',enable:'Attiva Ricarica Automatica',disable:'Disattiva Ricarica Automatica',refillAmount:'Importo della ricarica',minimumBalance:'Ricarica quando il saldo raggiunge',paymentNeeded:'È necessario un metodo di pagamento verificato prima di attivare la ricarica automatica.', addPayment:'Aggiungi metodo di pagamento',prelaunch:'Prelaunch è fail-closed: nessun addebito avviene senza Stripe Prelaunch configurato e checkout completato.',assessment:'Inizia la valutazione di Bianca',member:'Crea account MyMatchIQ gratuito',signIn:'Accedi per usare il portafoglio',loading:'Caricamento portafoglio…',transactions:'Attività recente',none:'Nessuna transazione.',error:'Il servizio portafoglio non è disponibile in questa anteprima.',included:['Saldo trasparente','Nessun addebito automatico per funzione','Consenso chiaro prima di un Play reciproco']},
 de:{eyebrow:'MyMatchIQ-Wallet',title:'Verwenden Sie Credits nur, wenn etwas Sinnvolles beginnt.',body:'Der Beitritt zu MyMatchIQ ist kostenlos. Credits schalten private Erkenntnisse frei, ohne ein Monatsabonnement zu erzwingen.',balance:'Ihr Credit-Guthaben',balanceNote:'Ihr Wallet wird nur nach einer verifizierten bezahlten Transaktion aktualisiert.',personalTitle:'Private Erkenntnisse',personalBody:'Nutzen Sie einen Insight-Credit für einen vollständigen Kompatibilitäts-Pass oder einen tieferen Bericht.',playTitle:'Gegenseitiges Let’s Play',playBody:'Jede Person nutzt einen Credit für 1,99 US$ erst nach gegenseitiger Annahme.',controlTitle:'Sie behalten die Kontrolle',controlBody:'Ihr Wallet ist von der Mitgliedschaft getrennt. Automatisches Auffüllen ist optional.',choiceTitle:'Credit-Optionen',one:'Einzelner Play-Credit',bundle:'Sechs-Credit-Paket',reserve:'Zwölf-Credit-Paket',onePrice:'1,99 US$',bundlePrice:'9,99 US$',reservePrice:'19,99 US$',oneNote:'Ein Credit.',bundleNote:'Sechs Credits.',reserveNote:'Zwölf Credits.',buy:'Credits kaufen',autoTitle:'Automatisch auffüllen',autoBody:'Wählen Sie Paket und Mindeststand für die Auffüllung.',enable:'Automatisches Auffüllen aktivieren',disable:'Automatisches Auffüllen deaktivieren',refillAmount:'Auffüllbetrag',minimumBalance:'Auffüllen bei Guthaben',paymentNeeded:'Vor Aktivierung ist eine verifizierte Zahlungsmethode erforderlich.', addPayment:'Zahlungsmethode hinzufügen',prelaunch:'Prelaunch bleibt fail-closed: Ohne konfigurierte Stripe-Prelaunch-Zahlung und abgeschlossenen Checkout erfolgt keine Belastung.',assessment:'Biancas Assessment starten',member:'Kostenloses MyMatchIQ-Konto erstellen',signIn:'Anmelden, um das Wallet zu nutzen',loading:'Wallet wird geladen…',transactions:'Letzte Wallet-Aktivität',none:'Noch keine Transaktionen.',error:'Der Wallet-Dienst ist in dieser Vorschau nicht verfügbar.',included:['Transparentes Guthaben','Keine automatische Funktionsgebühr','Klare Einwilligung vor gegenseitigem Play']}
};

const PACKAGE_ROWS=[['single','one','onePrice','oneNote','border-fuchsia-300/40'],['six','bundle','bundlePrice','bundleNote','border-cyan-300/40'],['twelve','reserve','reservePrice','reserveNote','border-amber-300/40']];

export default function MyMatchIQCredits(){
 const {currentLanguage}=useLanguage();const {isAuthenticated}=useAuth();const t=COPY[currentLanguage]||COPY.en;
 const [state,setState]=useState(null);const [loading,setLoading]=useState(isAuthenticated);const [error,setError]=useState('');const [busy,setBusy]=useState('');
 const [packageCode,setPackageCode]=useState('six');const [triggerBalance,setTriggerBalance]=useState('1');

 useEffect(()=>{if(!isAuthenticated)return;let cancelled=false;setLoading(true);getMyMatchIQCreditWallet().then(data=>{if(cancelled)return;setState(data);setPackageCode(data?.settings?.package_code||'six');setTriggerBalance(String(data?.settings?.trigger_balance??1));}).catch(e=>{if(!cancelled)setError(e?.message||t.error);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true};},[isAuthenticated]);

 const balance=state?.wallet?.balance??0;
 const autoEnabled=Boolean(state?.settings?.enabled);
 const hasPayment=Boolean(state?.settings?.payment_method_reference);
 const transactionRows=useMemo(()=>state?.transactions||[],[state]);

 async function buy(code){setBusy(code);setError('');try{const result=await createMyMatchIQCreditCheckout(code);if(result?.checkout?.url)window.location.assign(result.checkout.url);else throw new Error(t.error);}catch(e){setError(e?.message||t.error);}finally{setBusy('');}}
 async function saveAuto(enabled){setBusy('auto');setError('');try{const settings=await updateMyMatchIQAutoReplenish({enabled,packageCode,triggerBalance:Number(triggerBalance)});setState(v=>({...v,settings}));}catch(e){setError(e?.message||t.paymentNeeded);}finally{setBusy('');}}
 async function addPaymentMethod(){setBusy('payment');setError('');try{const result=await createMyMatchIQSetupIntent();if(result?.setupIntent?.url)window.location.assign(result.setupIntent.url);else throw new Error(t.error);}catch(e){setError(e?.message||t.error);}finally{setBusy('');}}

 return <main className="min-h-screen bg-[#070312] px-4 py-10 text-white sm:px-6" style={{backgroundImage:'radial-gradient(circle at 12% 0%, #5b126f 0%, transparent 30%), radial-gradient(circle at 90% 24%, #162e78 0%, transparent 32%)'}}>
  <section className="mx-auto max-w-6xl">
   <p className="text-center text-xs font-black uppercase tracking-[0.22em] text-fuchsia-200">{t.eyebrow}</p><h1 className="mx-auto mt-4 max-w-4xl text-center text-4xl font-black sm:text-5xl">{t.title}</h1><p className="mx-auto mt-4 max-w-3xl text-center text-lg leading-8 text-white/80">{t.body}</p>
   <section className="mx-auto mt-8 max-w-3xl rounded-3xl border border-fuchsia-200/30 bg-black/35 p-6 text-center shadow-xl backdrop-blur"><WalletCards className="mx-auto h-9 w-9 text-fuchsia-200"/><p className="mt-3 text-sm font-bold text-fuchsia-100">{t.balance}</p><h2 className="mt-1 text-4xl font-black">{loading?<Loader2 className="mx-auto h-8 w-8 animate-spin"/>:`${balance} credits`}</h2><p className="mt-2 text-sm text-white/70">{isAuthenticated?t.balanceNote:t.signIn}</p></section>
   <section className="mt-7 grid gap-5 md:grid-cols-3">{[[Sparkles,t.personalTitle,t.personalBody],[HeartHandshake,t.playTitle,t.playBody],[LockKeyhole,t.controlTitle,t.controlBody]].map(([Icon,title,body])=><article key={title} className="rounded-3xl border border-white/15 bg-white/[0.06] p-6 shadow-xl backdrop-blur"><Icon className="h-9 w-9 text-cyan-200"/><h2 className="mt-4 text-xl font-black">{title}</h2><p className="mt-3 text-sm leading-6 text-white/75">{body}</p></article>)}</section>

   <h2 className="mt-12 text-center text-2xl font-black">{t.choiceTitle}</h2><section className="mt-5 grid gap-5 md:grid-cols-3">{PACKAGE_ROWS.map(([code,titleKey,priceKey,noteKey,border])=><article key={code} className={`rounded-3xl border ${border} bg-black/35 p-6 text-center shadow-xl`}><h3 className="text-xl font-black">{t[titleKey]}</h3><p className="mt-4 text-3xl font-black text-fuchsia-100">{t[priceKey]}</p><p className="mt-4 text-sm leading-6 text-white/75">{t[noteKey]}</p>{isAuthenticated?<button type="button" disabled={Boolean(busy)} onClick={()=>buy(code)} className="mt-6 inline-flex min-w-[150px] items-center justify-center rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-5 py-3 text-sm font-black disabled:opacity-40">{busy===code?<Loader2 className="h-4 w-4 animate-spin"/>:t.buy}</button>:<Link to="/MyMatchIQ/SignIn" className="mt-6 inline-flex rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-5 py-3 text-sm font-black">{t.signIn}</Link>}</article>)}</section>

   <section className="mx-auto mt-8 max-w-4xl rounded-3xl border border-cyan-200/35 bg-cyan-950/20 p-6 shadow-xl backdrop-blur"><div className="flex items-center gap-3"><RefreshCw className="h-7 w-7 text-cyan-200"/><div><h2 className="text-2xl font-black">{t.autoTitle}</h2><p className="mt-2 text-sm leading-6 text-cyan-50/85">{t.autoBody}</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-black"><span className="mb-2 block">{t.refillAmount}</span><select value={packageCode} onChange={e=>setPackageCode(e.target.value)} className="w-full rounded-xl border border-cyan-100/30 bg-slate-950 px-4 py-3 text-white"><option value="single">{t.onePrice}</option><option value="six">{t.bundlePrice}</option><option value="twelve">{t.reservePrice}</option></select></label><label className="text-sm font-black"><span className="mb-2 block">{t.minimumBalance}</span><select value={triggerBalance} onChange={e=>setTriggerBalance(e.target.value)} className="w-full rounded-xl border border-cyan-100/30 bg-slate-950 px-4 py-3 text-white">{[0,1,2,3,4,5].map(v=><option key={v} value={v}>{v} credits</option>)}</select></label></div><div className="mt-5 flex flex-wrap items-center gap-3">{isAuthenticated&&!hasPayment&&<button type="button" disabled={Boolean(busy)} onClick={addPaymentMethod} className="rounded-full bg-gradient-to-r from-cyan-500 to-blue-600 px-5 py-3 text-sm font-black disabled:opacity-40">{busy==='payment'?<Loader2 className="h-4 w-4 animate-spin"/>:t.addPayment}</button>}{isAuthenticated&&<button type="button" disabled={Boolean(busy)||(!hasPayment&&!autoEnabled)} onClick={()=>saveAuto(!autoEnabled)} className="rounded-full border border-cyan-100/35 bg-white/10 px-5 py-3 text-sm font-black disabled:opacity-40">{busy==='auto'?<Loader2 className="h-4 w-4 animate-spin"/>:(autoEnabled?t.disable:t.enable)}</button>}<p className="text-sm text-cyan-50/70">{!hasPayment?t.paymentNeeded:''}</p></div></section>

   {error&&<div className="mx-auto mt-6 max-w-4xl rounded-2xl border border-amber-200/25 bg-amber-950/25 p-4 text-sm text-amber-50">{error}</div>}
   <div className="mx-auto mt-6 max-w-4xl rounded-2xl border border-amber-200/25 bg-amber-950/25 p-4 text-center text-sm leading-6 text-amber-50">{t.prelaunch}</div>
   {isAuthenticated&&<section className="mx-auto mt-7 max-w-4xl rounded-3xl border border-white/15 bg-white/[0.04] p-6"><h2 className="font-black">{t.transactions}</h2><div className="mt-4 space-y-2">{transactionRows.length?transactionRows.map(row=><div key={row.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm"><span className="capitalize">{String(row.transaction_type||'').replaceAll('_',' ')}</span><span className={Number(row.wallet_delta)>=0?'text-cyan-200':'text-amber-200'}>{Number(row.wallet_delta)>=0?'+':''}{row.wallet_delta} credits</span><span className="text-white/45">{new Date(row.created_at).toLocaleDateString()}</span></div>):<p className="text-sm text-white/50">{t.none}</p>}</div></section>}
   <ul className="mx-auto mt-7 max-w-2xl space-y-3 text-sm text-white/80">{t.included.map(item=><li key={item} className="flex items-center gap-3"><Check className="h-5 w-5 shrink-0 text-cyan-200"/>{item}</li>)}</ul>
   <div className="mt-8 flex flex-wrap justify-center gap-3"><Link to="/MyMatchIQ/Assessment" className="rounded-full bg-gradient-to-r from-fuchsia-500 to-violet-600 px-5 py-3 text-sm font-black">{t.assessment}</Link>{!isAuthenticated&&<Link to="/MyMatchIQ/SignUp" className="rounded-full border border-white/30 bg-white/10 px-5 py-3 text-sm font-black">{t.member}</Link>}</div>
  </section>
 </main>;
}
