import React from 'react';
import { CreditCard, ShieldAlert } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { useLanguage } from '@/Layout';

const translations = {
  en: { title: 'Membership Checkout Is Not Active', subtitle: 'This page does not confirm that a payment was completed.', notice: 'One2OneLove paid membership checkout is not open for launch. If you reached this page from an old or test payment link, do not treat it as a receipt or subscription confirmation. If you believe you were charged, contact One2OneLove support so the transaction can be reviewed.', contact: 'Contact Support', membership: 'Membership Status', home: 'Back Home' },
  es: { title: 'El Pago de Membresía No Está Activo', subtitle: 'Esta página no confirma que se haya completado un pago.', notice: 'El checkout de membresía de pago de One2OneLove no está abierto para el lanzamiento. Si llegaste aquí desde un enlace antiguo o de prueba, no lo consideres un recibo ni confirmación de suscripción. Si crees que se realizó un cargo, contacta al soporte de One2OneLove para revisar la transacción.', contact: 'Contactar Soporte', membership: 'Estado de Membresía', home: 'Volver al Inicio' },
  fr: { title: 'Le Paiement d’Abonnement N’Est Pas Actif', subtitle: 'Cette page ne confirme pas qu’un paiement a été effectué.', notice: 'Le paiement des abonnements One2OneLove n’est pas ouvert au lancement. Si vous avez atteint cette page depuis un ancien lien ou un lien de test, ne la considérez pas comme un reçu ou une confirmation d’abonnement. Si vous pensez avoir été débité, contactez le support One2OneLove pour faire vérifier la transaction.', contact: 'Contacter le Support', membership: 'État de l’Abonnement', home: 'Retour à l’Accueil' },
  it: { title: 'Il Checkout Abbonamenti Non È Attivo', subtitle: 'Questa pagina non conferma che un pagamento sia stato completato.', notice: 'Il checkout degli abbonamenti One2OneLove non è aperto al lancio. Se sei arrivato qui da un vecchio link o da un link di test, non considerarlo una ricevuta o conferma di abbonamento. Se ritieni di aver ricevuto un addebito, contatta il supporto One2OneLove per verificare la transazione.', contact: 'Contatta Supporto', membership: 'Stato Abbonamento', home: 'Torna alla Home' },
  de: { title: 'Mitgliedschafts-Checkout Ist Nicht Aktiv', subtitle: 'Diese Seite bestätigt keinen abgeschlossenen Zahlungsvorgang.', notice: 'Der Checkout für bezahlte One2OneLove-Mitgliedschaften ist zum Start nicht geöffnet. Wenn du diese Seite über einen alten oder Test-Zahlungslink erreicht hast, gilt sie nicht als Beleg oder Abonnementbestätigung. Falls du glaubst, dass eine Belastung erfolgt ist, kontaktiere den One2OneLove-Support zur Prüfung.', contact: 'Support Kontaktieren', membership: 'Mitgliedschaftsstatus', home: 'Zurück zur Startseite' },
};

export default function PaymentSuccess() {
  const { currentLanguage } = useLanguage();
  const t = translations[currentLanguage] || translations.en;
  return <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-blue-50 px-4 py-12 md:py-20"><div className="mx-auto max-w-4xl text-center"><CreditCard className="mx-auto h-14 w-14 text-slate-700" aria-hidden="true"/><h1 className="mt-5 text-4xl font-bold text-slate-900 md:text-5xl">{t.title}</h1><p className="mt-4 text-lg text-slate-600">{t.subtitle}</p><Card className="mx-auto mt-8 max-w-3xl text-left"><CardContent className="p-6 md:p-8"><div className="flex gap-3 rounded-2xl bg-amber-50 p-5 text-sm leading-6 text-amber-950"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0" aria-hidden="true"/><p>{t.notice}</p></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><Button asChild><Link to="/ContactUs">{t.contact}</Link></Button><Button asChild variant="outline"><Link to="/Subscription">{t.membership}</Link></Button><Button asChild variant="ghost"><Link to="/">{t.home}</Link></Button></div></CardContent></Card></div></main>;
}
