import React from "react";
import { Crown, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useLanguage } from "@/Layout";

const translations = {
  en: { title: "Premium Membership — Post Launch", subtitle: "One2OneLove is not using points, levels, or pretend unlocks to sell premium features at launch.", notice: "Paid membership will be introduced only after the free launch experience is stable and premium benefits can be described truthfully. Future plans may include expanded creator experiences, advanced guided tools, early access, and additional personalization—but no feature will be advertised as active before it is real.", launch: "Explore Launch Features", room: "Global Relationship Room", library: "Relationship Library" },
  es: { title: "Membresía Premium — Después del Lanzamiento", subtitle: "One2OneLove no usa puntos, niveles ni desbloqueos ficticios para vender funciones premium en el lanzamiento.", notice: "La membresía de pago se introducirá solo cuando la experiencia gratuita de lanzamiento sea estable y los beneficios premium puedan describirse con veracidad. Los planes futuros podrán incluir experiencias ampliadas para creadores, herramientas guiadas avanzadas, acceso anticipado y más personalización, pero ninguna función se anunciará como activa antes de ser real.", launch: "Explorar Funciones de Lanzamiento", room: "Sala Global de Relaciones", library: "Biblioteca de Relaciones" },
  fr: { title: "Abonnement Premium — Après le Lancement", subtitle: "One2OneLove n’utilise pas de points, niveaux ou faux déblocages pour vendre des fonctions premium au lancement.", notice: "L’abonnement payant sera introduit uniquement lorsque l’expérience gratuite de lancement sera stable et que les avantages premium pourront être décrits honnêtement. Les futurs forfaits pourront inclure davantage d’expériences créateurs, des outils guidés avancés, un accès anticipé et plus de personnalisation, mais aucune fonction ne sera annoncée comme active avant de l’être réellement.", launch: "Découvrir les Fonctions de Lancement", room: "Salle Mondiale des Relations", library: "Bibliothèque Relationnelle" },
  it: { title: "Abbonamento Premium — Dopo il Lancio", subtitle: "One2OneLove non usa punti, livelli o sblocchi fittizi per vendere funzioni premium al lancio.", notice: "L’abbonamento a pagamento sarà introdotto solo quando l’esperienza gratuita di lancio sarà stabile e i vantaggi premium potranno essere descritti in modo veritiero. I piani futuri potranno includere esperienze creator ampliate, strumenti guidati avanzati, accesso anticipato e più personalizzazione, ma nessuna funzione sarà pubblicizzata come attiva prima di esserlo realmente.", launch: "Esplora Funzioni di Lancio", room: "Sala Globale delle Relazioni", library: "Biblioteca delle Relazioni" },
  de: { title: "Premium-Mitgliedschaft — Nach dem Start", subtitle: "One2OneLove verwendet zum Start keine Punkte, Levels oder erfundenen Freischaltungen, um Premium-Funktionen zu verkaufen.", notice: "Bezahlte Mitgliedschaften werden erst eingeführt, wenn die kostenlose Starterfahrung stabil ist und Premium-Vorteile wahrheitsgemäß beschrieben werden können. Zukünftige Tarife können erweiterte Creator-Erlebnisse, fortgeschrittene geführte Werkzeuge, frühen Zugang und zusätzliche Personalisierung umfassen, aber keine Funktion wird als aktiv beworben, bevor sie tatsächlich verfügbar ist.", launch: "Startfunktionen Entdecken", room: "Globaler Beziehungsraum", library: "Beziehungsbibliothek" },
};

export default function PremiumFeatures() {
  const { currentLanguage } = useLanguage();
  const t = translations[currentLanguage] || translations.en;
  return <main className="min-h-screen bg-gradient-to-br from-amber-50 via-white to-fuchsia-50 px-4 py-12 md:py-20"><div className="mx-auto max-w-4xl text-center"><Crown className="mx-auto h-14 w-14 text-amber-600" aria-hidden="true"/><h1 className="mt-5 text-4xl font-bold text-slate-900 md:text-5xl">{t.title}</h1><p className="mt-4 text-lg text-slate-600">{t.subtitle}</p><Card className="mx-auto mt-8 max-w-3xl text-left"><CardContent className="p-6 md:p-8"><div className="flex gap-3 rounded-2xl bg-amber-50 p-5 text-sm leading-6 text-amber-950"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0" aria-hidden="true"/><p>{t.notice}</p></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><Button asChild><Link to="/CoupleActivities"><Sparkles className="mr-2 h-4 w-4" aria-hidden="true"/>{t.launch}</Link></Button><Button asChild variant="outline"><Link to="/GlobalRelationshipRoom">{t.room}</Link></Button><Button asChild variant="outline"><Link to="/RelationshipLibrary">{t.library}</Link></Button></div></CardContent></Card></div></main>;
}
