import React from "react";
import { useLanguage } from "@/Layout";
import { Card, CardContent } from "@/components/ui/card";
import { Shield, ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { motion } from "framer-motion";

const translations = {
  en: {
    title: "Privacy Policy",
    subtitle: "How One2OneLove collects, uses, shares, protects, and manages personal information",
    back: "Back",
    lastUpdated: "Last Updated: September 12, 2026",
    translationNotice: "If a translated version differs from the English version, the English version controls to the extent permitted by applicable law.",
    sections: [
      { title: "1. Scope of This Privacy Policy", content: "This Privacy Policy applies to One2OneLove websites, applications, account services, relationship tools, community and chat features, AI-assisted features, quizzes, Love Notes, date ideas, milestones, memories, support resources, professional or therapist-related directories, subscriptions, and other services that link to this Policy. By using One2OneLove, you acknowledge the practices described here. This Policy does not apply to third-party websites or services that maintain their own privacy policies." },
      { title: "2. Information You Provide to Us", content: "We may collect information you provide directly, including name, email address, password or authentication data, profile details, language preference, relationship status or relationship-related information, interests, goals, milestones, quiz responses, Love Notes, memories, photos, messages, community posts, reviews, suggestions, support requests, survey responses, and any other information you choose to submit. If you register as or interact with a professional, therapist, coach, contributor, or similar provider, we may also collect professional profile, credential, practice, contact, availability, or verification information." },
      { title: "3. Relationship, Personal, and Potentially Sensitive Information", content: "Some One2OneLove features are designed for personal relationship reflection and may involve information that users consider private or sensitive, including relationship concerns, sexual orientation, gender identity, faith, family circumstances, emotional experiences, or other personal context. You decide what to provide. Please avoid submitting information that is unnecessary for the feature you are using. We use this information only for the purposes described in this Policy and subject to applicable law." },
      { title: "4. Community, Chat, Messages, and User-Generated Content", content: "Information you choose to post in community areas, reviews, comments, public profiles, or other shared spaces may be visible to other users according to the settings and design of the feature. Direct messages and chat content are intended for the participants in the conversation, but may be processed or reviewed when necessary to operate the service, investigate abuse, enforce rules, comply with law, or protect users. Do not post or send information you do not have the right to share." },
      { title: "5. AI-Assisted Features", content: "When you use AI-assisted features, we may process the prompts, questions, relationship context, text, selections, or other information you submit in order to generate a response. AI inputs and outputs may be processed by service providers that support the AI feature. Do not provide highly sensitive information unless it is necessary and you are comfortable with it being processed for that purpose. AI outputs can be inaccurate and should not be treated as medical, mental-health, legal, financial, emergency, or other professional advice." },
      { title: "6. Information Collected Automatically", content: "When you use One2OneLove, we may automatically collect device and technical information such as IP address, browser type, operating system, device identifiers, language, approximate location derived from network information, referring pages, pages viewed, clicks, feature usage, dates and times, error logs, crash information, and security events. We may use cookies, local storage, pixels, SDKs, and similar technologies to maintain sessions, remember preferences, protect accounts, measure performance, and understand how the service is used." },
      { title: "7. Location, Maps, Directions, and Date Ideas", content: "Some date-idea, map, location, or directions features may request or use location information. Precise device location should only be accessed when you choose to provide permission through your device or browser. Location and directions may also be provided or processed by third-party mapping or location services. We do not guarantee the accuracy, availability, safety, hours, pricing, or suitability of any suggested location or route." },
      { title: "8. Payments, Subscriptions, and Transaction Information", content: "If One2OneLove offers paid subscriptions, purchases, trials, or other transactions, payment information may be collected and processed by third-party payment processors. We generally do not need to store full payment-card numbers. We may receive transaction details such as payment status, subscription level, billing date, amount, currency, limited payment method information, and identifiers needed to manage purchases, refunds, disputes, taxes, fraud prevention, or customer support." },
      { title: "9. How We Use Information", content: "We may use information to create and manage accounts; provide requested features; personalize language, content, and recommendations; generate AI-assisted responses; deliver Love Notes or invitations; support community and messaging functions; save memories, milestones, goals, and preferences; provide customer support; process transactions; prevent fraud and abuse; maintain security; troubleshoot errors; analyze product performance; improve and develop features; send service, security, transactional, and permitted promotional communications; comply with legal obligations; and protect the rights and safety of One2OneLove, users, and others." },
      { title: "10. When We Share or Disclose Information", content: "We may disclose information to vendors and service providers that help operate hosting, databases, authentication, email, messaging, customer support, analytics, security, AI, mapping, storage, payments, and other platform functions. We may also disclose information when you direct us to do so, when a feature is designed to share it with another user, to comply with lawful requests or legal process, to investigate fraud or abuse, to protect rights or safety, or as part of a merger, financing, acquisition, reorganization, bankruptcy, sale of assets, or similar business transaction. We do not sell personal information for monetary consideration. If future practices are considered a sale or sharing under applicable privacy law, we will provide legally required notices and choices." },
      { title: "11. Third-Party Professionals, Resources, and External Services", content: "One2OneLove may display or link to therapists, counselors, coaches, professionals, businesses, articles, videos, maps, payment providers, social networks, or other third-party resources. If you choose to contact, visit, or transact with a third party, that party may collect information under its own terms and privacy policy. One2OneLove is not responsible for a third party's independent privacy practices. A listing or link does not by itself mean One2OneLove endorses, verifies, or guarantees that provider unless expressly stated." },
      { title: "12. Cookies and Similar Technologies", content: "Cookies and similar technologies may be used for essential account and security functions, preference storage, session management, performance, analytics, and feature operation. You can often control cookies through browser settings, but blocking essential storage may prevent parts of One2OneLove from working correctly. Where consent is legally required for non-essential technologies, we will seek it as required." },
      { title: "13. Data Retention and Deletion", content: "We retain personal information for as long as reasonably necessary for the purpose for which it was collected, to provide the service, maintain legitimate business records, resolve disputes, enforce agreements, protect against abuse, and comply with legal, tax, accounting, security, and regulatory obligations. Retention periods vary by data type and context. Deletion from active systems may not immediately remove information from backups, logs, fraud-prevention records, or records we must retain by law. We may retain de-identified or aggregated information that no longer reasonably identifies you." },
      { title: "14. Data Security", content: "We use reasonable administrative, technical, and organizational safeguards designed to protect personal information against unauthorized access, loss, misuse, alteration, and disclosure. No internet service, database, transmission, or storage system can be guaranteed to be completely secure. You are responsible for using a strong, unique password, protecting account credentials, securing your devices, and notifying us promptly if you suspect unauthorized account access." },
      { title: "15. Your Choices and Privacy Rights", content: "Depending on your location and applicable law, you may have rights to request access to personal information, correction, deletion, portability, restriction, objection, withdrawal of consent, or information about certain disclosures. You may also have the right to appeal a privacy-request decision. Some rights are subject to verification, exceptions, retention requirements, or limitations. You can update certain information through available account controls and may submit other requests through the contact information below." },
      { title: "16. U.S. State Privacy Rights and Preference Signals", content: "Residents of certain U.S. states may have additional rights regarding access, deletion, correction, portability, sensitive data, targeted advertising, sale or sharing, and profiling. Where legally required and technically applicable, we will honor recognized browser-based opt-out preference signals such as Global Privacy Control. Because privacy laws vary and change, the rights available to you depend on your jurisdiction and our applicable processing activities." },
      { title: "17. International Users and Cross-Border Processing", content: "One2OneLove may use service providers or infrastructure located in countries other than the country where you live. As a result, information may be transferred to or processed in jurisdictions with different data-protection laws. Where required, we use legally recognized safeguards for international transfers and apply the protections required by applicable law." },
      { title: "18. Children and Younger Users", content: "One2OneLove is not intended for children under 13, and we do not knowingly collect personal information from children under 13. Users who are not yet the age of majority where they live should use the service only where permitted by law and with a parent or guardian's involvement when required. Certain features may be restricted to adults. If you believe a child has provided personal information in violation of this section, contact us so we can review and take appropriate action." },
      { title: "19. Legal Requirements, Safety, and Abuse Prevention", content: "We may preserve, use, or disclose information when we reasonably believe it is necessary to comply with law, court orders, lawful government requests, legal process, or regulatory obligations; enforce our terms and policies; investigate suspected fraud, exploitation, harassment, threats, or misuse; respond to emergencies involving danger of death or serious physical harm; or protect the rights, property, and safety of users, One2OneLove, or others, subject to applicable law." },
      { title: "20. Changes to This Privacy Policy and Contact", content: "We may update this Privacy Policy as One2OneLove evolves, laws change, or our data practices change. The updated date will be shown on this page, and we may provide additional notice when required. Questions, privacy requests, or legal inquiries may be directed to legal@one2onelove.com. General product support may be directed to support@one2onelove.com." }
    ]
  },
  es: {
    title: "Política de Privacidad", subtitle: "Cómo One2OneLove recopila, usa, comparte, protege y administra la información personal", back: "Volver", lastUpdated: "Última Actualización: 12 de Septiembre de 2026", translationNotice: "Si una versión traducida difiere de la versión en inglés, la versión en inglés prevalece en la medida permitida por la ley aplicable.",
    sections: [
      { title: "1. Alcance de Esta Política", content: "Esta Política se aplica a los sitios, aplicaciones, cuentas, herramientas de relación, comunidad y chat, funciones asistidas por IA, cuestionarios, Notas de Amor, ideas para citas, hitos, recuerdos, recursos de apoyo, directorios profesionales o de terapeutas, suscripciones y demás servicios de One2OneLove que enlacen esta Política. No se aplica a servicios externos que mantengan sus propias políticas." },
      { title: "2. Información que Nos Proporcionas", content: "Podemos recopilar nombre, correo, datos de autenticación, perfil, idioma, estado o contexto de relación, intereses, metas, hitos, respuestas a cuestionarios, Notas de Amor, recuerdos, fotos, mensajes, publicaciones, reseñas, sugerencias, solicitudes de soporte y otra información que decidas enviar. Si participas como profesional, terapeuta, coach o proveedor similar, también podemos recopilar datos profesionales, credenciales, práctica, contacto, disponibilidad o verificación." },
      { title: "3. Información Personal o Potencialmente Sensible", content: "Algunas funciones pueden incluir información privada o sensible, como preocupaciones de relación, orientación sexual, identidad de género, fe, circunstancias familiares o experiencias emocionales. Tú decides qué proporcionar. Evita enviar información innecesaria para la función que utilizas." },
      { title: "4. Comunidad, Chat y Contenido del Usuario", content: "La información que publiques en espacios comunitarios, reseñas, comentarios, perfiles públicos u otras áreas compartidas puede ser visible para otros usuarios. Los mensajes directos están destinados a sus participantes, pero pueden procesarse o revisarse cuando sea necesario para operar el servicio, investigar abuso, hacer cumplir reglas, cumplir la ley o proteger a usuarios." },
      { title: "5. Funciones Asistidas por IA", content: "Cuando utilizas funciones de IA, podemos procesar prompts, preguntas, contexto, texto, selecciones u otra información para generar una respuesta. Proveedores que apoyan la función de IA también pueden procesar entradas y salidas. No incluyas información altamente sensible salvo que sea necesaria y estés cómodo con ese procesamiento. La IA puede equivocarse y no debe tratarse como asesoramiento médico, de salud mental, legal, financiero o de emergencia." },
      { title: "6. Información Recopilada Automáticamente", content: "Podemos recopilar dirección IP, navegador, sistema operativo, identificadores de dispositivo, idioma, ubicación aproximada derivada de la red, páginas de referencia, vistas, clics, uso de funciones, fechas, errores y eventos de seguridad. Podemos utilizar cookies, almacenamiento local, píxeles, SDK y tecnologías similares para sesiones, preferencias, seguridad, rendimiento y análisis." },
      { title: "7. Ubicación, Mapas, Direcciones e Ideas para Citas", content: "Algunas funciones pueden solicitar o usar ubicación. La ubicación precisa del dispositivo solo debe accederse cuando tú otorgas permiso. Servicios externos de mapas o ubicación también pueden procesar información. No garantizamos exactitud, disponibilidad, seguridad, horarios, precios ni idoneidad de lugares o rutas sugeridas." },
      { title: "8. Pagos, Suscripciones y Transacciones", content: "Cuando existan servicios de pago, la información de pago puede ser recopilada y procesada por procesadores externos. Normalmente no necesitamos almacenar números completos de tarjeta. Podemos recibir estado de pago, nivel de suscripción, fecha, importe, moneda, información limitada del método de pago e identificadores necesarios para gestionar compras, reembolsos, disputas, impuestos, fraude o soporte." },
      { title: "9. Cómo Usamos la Información", content: "Podemos usar información para crear y gestionar cuentas; prestar funciones; personalizar idioma, contenido y recomendaciones; generar respuestas de IA; entregar Notas de Amor o invitaciones; operar comunidad y mensajería; guardar recuerdos, hitos, metas y preferencias; brindar soporte; procesar transacciones; prevenir fraude y abuso; mantener seguridad; solucionar errores; analizar rendimiento; mejorar productos; enviar comunicaciones permitidas; cumplir obligaciones legales; y proteger derechos y seguridad." },
      { title: "10. Cuándo Compartimos Información", content: "Podemos divulgar información a proveedores que apoyan alojamiento, bases de datos, autenticación, correo, mensajería, soporte, análisis, seguridad, IA, mapas, almacenamiento, pagos y otras funciones. También podemos compartir cuando lo ordenas, cuando una función está diseñada para compartir con otro usuario, por solicitudes legales, seguridad, fraude o una transacción empresarial. No vendemos información personal por dinero. Si una práctica futura se considera venta o intercambio bajo una ley aplicable, ofreceremos los avisos y opciones requeridos." },
      { title: "11. Profesionales y Servicios Externos", content: "One2OneLove puede mostrar o enlazar terapeutas, consejeros, coaches, negocios, artículos, videos, mapas, pagos, redes sociales u otros recursos externos. Si interactúas con un tercero, ese tercero puede recopilar información bajo sus propias reglas. One2OneLove no es responsable de sus prácticas independientes. Un enlace o listado no implica por sí solo respaldo, verificación o garantía." },
      { title: "12. Cookies y Tecnologías Similares", content: "Podemos usar cookies y tecnologías similares para seguridad, sesión, preferencias, rendimiento, análisis y operación. Puedes controlarlas desde tu navegador, pero bloquear almacenamiento esencial puede impedir que partes de One2OneLove funcionen. Cuando la ley exija consentimiento para tecnologías no esenciales, lo solicitaremos según corresponda." },
      { title: "13. Retención y Eliminación", content: "Conservamos información durante el tiempo razonablemente necesario para prestar el servicio, mantener registros legítimos, resolver disputas, aplicar acuerdos, prevenir abuso y cumplir obligaciones legales, fiscales, contables, de seguridad o regulatorias. La eliminación de sistemas activos puede no borrar inmediatamente copias de seguridad, logs o registros que debamos conservar. Podemos mantener datos desidentificados o agregados." },
      { title: "14. Seguridad de Datos", content: "Utilizamos medidas administrativas, técnicas y organizativas razonables diseñadas para proteger la información. Ningún sistema puede garantizar seguridad absoluta. Tú eres responsable de usar una contraseña fuerte y única, proteger tus credenciales y dispositivos y avisarnos si sospechas acceso no autorizado." },
      { title: "15. Tus Opciones y Derechos", content: "Según tu ubicación, puedes tener derechos de acceso, corrección, eliminación, portabilidad, restricción, oposición, retiro de consentimiento o información sobre divulgaciones. Algunos lugares también permiten apelar decisiones. Estos derechos pueden estar sujetos a verificación, excepciones y requisitos de retención. Puedes usar controles de cuenta disponibles o contactar con nosotros para otras solicitudes." },
      { title: "16. Derechos Estatales de EE. UU. y Señales de Preferencia", content: "Algunos estados de EE. UU. ofrecen derechos adicionales sobre acceso, eliminación, corrección, portabilidad, datos sensibles, publicidad dirigida, venta o intercambio y ciertos perfiles. Cuando sea legalmente requerido y técnicamente aplicable, respetaremos señales reconocidas como Global Privacy Control. Los derechos disponibles dependen de tu jurisdicción y del tratamiento que realicemos." },
      { title: "17. Usuarios Internacionales", content: "Podemos usar proveedores o infraestructura en países distintos al tuyo. Por ello, los datos pueden transferirse o procesarse en jurisdicciones con leyes diferentes. Cuando sea obligatorio, utilizamos salvaguardas reconocidas legalmente para transferencias internacionales." },
      { title: "18. Niños y Usuarios Jóvenes", content: "One2OneLove no está dirigido a menores de 13 años y no recopilamos conscientemente información personal de menores de 13. Quienes no tengan la mayoría de edad deben usar el servicio solo cuando la ley lo permita y con participación de padre, madre o tutor cuando sea requerida. Algunas funciones pueden limitarse a adultos." },
      { title: "19. Requisitos Legales, Seguridad y Prevención de Abuso", content: "Podemos conservar, usar o divulgar información cuando razonablemente sea necesario para cumplir leyes o procesos legales; hacer cumplir términos y políticas; investigar fraude, explotación, acoso, amenazas o uso indebido; responder a emergencias con riesgo de muerte o daño grave; o proteger derechos, propiedad y seguridad, sujeto a la ley aplicable." },
      { title: "20. Cambios y Contacto", content: "Podemos actualizar esta Política cuando cambien One2OneLove, la ley o nuestras prácticas. Mostraremos la fecha actualizada y daremos avisos adicionales cuando sean exigidos. Para privacidad o asuntos legales: legal@one2onelove.com. Para soporte general: support@one2onelove.com." }
    ]
  },
  fr: {
    title: "Politique de Confidentialité", subtitle: "Comment One2OneLove collecte, utilise, partage, protège et gère les données personnelles", back: "Retour", lastUpdated: "Dernière Mise à Jour : 12 Septembre 2026", translationNotice: "Si une traduction diffère de la version anglaise, la version anglaise prévaut dans la mesure permise par le droit applicable.",
    sections: [
      { title: "1. Champ d'Application", content: "Cette Politique s'applique aux sites, applications, comptes, outils relationnels, fonctions communautaires et de chat, fonctions assistées par IA, quiz, Love Notes, idées de rendez-vous, étapes, souvenirs, ressources de soutien, annuaires professionnels ou de thérapeutes, abonnements et autres services One2OneLove qui renvoient à cette Politique. Elle ne couvre pas les services tiers ayant leurs propres politiques." },
      { title: "2. Informations que Vous Nous Fournissez", content: "Nous pouvons recueillir nom, e-mail, données d'authentification, profil, langue, situation ou contexte relationnel, intérêts, objectifs, étapes, réponses aux quiz, Love Notes, souvenirs, photos, messages, publications, avis, suggestions, demandes d'assistance et toute autre information volontaire. Pour les professionnels, thérapeutes, coachs ou prestataires, nous pouvons aussi recueillir profil professionnel, qualifications, coordonnées, disponibilité ou éléments de vérification." },
      { title: "3. Informations Personnelles ou Potentiellement Sensibles", content: "Certaines fonctions peuvent contenir des informations privées ou sensibles : difficultés relationnelles, orientation sexuelle, identité de genre, religion, situation familiale ou expériences émotionnelles. Vous choisissez ce que vous fournissez. Évitez de transmettre des informations inutiles à la fonction utilisée." },
      { title: "4. Communauté, Chat et Contenu Utilisateur", content: "Les informations publiées dans les espaces communautaires, avis, commentaires, profils publics ou autres zones partagées peuvent être visibles par d'autres utilisateurs. Les messages directs sont destinés aux participants, mais peuvent être traités ou examinés pour exploiter le service, enquêter sur un abus, appliquer les règles, respecter la loi ou protéger les utilisateurs." },
      { title: "5. Fonctions Assistées par IA", content: "Lorsque vous utilisez l'IA, nous pouvons traiter vos questions, contexte, texte, choix ou autres informations pour produire une réponse. Des prestataires soutenant la fonction peuvent aussi traiter les entrées et sorties. N'envoyez pas d'informations très sensibles sauf nécessité et accord de votre part. L'IA peut se tromper et ne remplace pas un avis médical, psychologique, juridique, financier ou d'urgence." },
      { title: "6. Informations Collectées Automatiquement", content: "Nous pouvons recueillir adresse IP, navigateur, système d'exploitation, identifiants d'appareil, langue, localisation approximative issue du réseau, pages référentes, pages consultées, clics, utilisation des fonctions, dates, erreurs et événements de sécurité. Cookies, stockage local, pixels, SDK et technologies similaires peuvent servir aux sessions, préférences, sécurité, performance et analyses." },
      { title: "7. Localisation, Cartes, Itinéraires et Idées de Rendez-vous", content: "Certaines fonctions peuvent demander ou utiliser une localisation. La localisation précise de l'appareil ne doit être utilisée que lorsque vous donnez votre autorisation. Des services tiers de cartographie ou localisation peuvent aussi traiter des données. Nous ne garantissons pas l'exactitude, la disponibilité, la sécurité, les horaires, les prix ou l'adéquation d'un lieu ou itinéraire." },
      { title: "8. Paiements, Abonnements et Transactions", content: "Lorsque des services payants sont proposés, les données de paiement peuvent être traitées par des prestataires de paiement. Nous n'avons généralement pas besoin de conserver les numéros complets de carte. Nous pouvons recevoir statut du paiement, formule, date, montant, devise, informations limitées sur le moyen de paiement et identifiants nécessaires à la gestion des achats, remboursements, litiges, taxes, fraude et assistance." },
      { title: "9. Utilisation des Informations", content: "Nous pouvons utiliser les informations pour créer et gérer des comptes, fournir les fonctions, personnaliser langue, contenu et recommandations, générer des réponses IA, livrer des Love Notes ou invitations, exploiter communauté et messagerie, enregistrer souvenirs, étapes, objectifs et préférences, assurer l'assistance, traiter les transactions, prévenir fraude et abus, maintenir la sécurité, corriger les erreurs, analyser les performances, améliorer le produit, envoyer les communications autorisées et respecter nos obligations légales." },
      { title: "10. Partage et Divulgation", content: "Nous pouvons divulguer des informations à des prestataires soutenant hébergement, bases de données, authentification, e-mail, messagerie, assistance, analyse, sécurité, IA, cartes, stockage, paiements et autres fonctions. Nous pouvons aussi divulguer selon vos instructions, par conception d'une fonction, pour répondre à une demande légale, protéger la sécurité, lutter contre la fraude ou dans le cadre d'une opération commerciale. Nous ne vendons pas les données personnelles contre paiement. Si une pratique future est juridiquement considérée comme vente ou partage, nous fournirons les avis et choix requis." },
      { title: "11. Professionnels et Services Tiers", content: "One2OneLove peut afficher ou lier des thérapeutes, conseillers, coachs, entreprises, articles, vidéos, cartes, paiements, réseaux sociaux ou autres ressources tierces. Ces tiers peuvent collecter des données selon leurs propres règles. One2OneLove n'est pas responsable de leurs pratiques indépendantes. Un lien ou une fiche ne constitue pas automatiquement une approbation, vérification ou garantie." },
      { title: "12. Cookies et Technologies Similaires", content: "Nous pouvons utiliser cookies et technologies similaires pour sécurité, session, préférences, performance, analyses et fonctionnement. Les réglages du navigateur permettent souvent de les contrôler, mais bloquer un stockage essentiel peut empêcher certaines fonctions. Lorsque la loi exige un consentement pour des technologies non essentielles, nous le demanderons." },
      { title: "13. Conservation et Suppression", content: "Nous conservons les données aussi longtemps que raisonnablement nécessaire pour fournir le service, tenir des registres légitimes, résoudre des litiges, appliquer nos accords, prévenir les abus et respecter les obligations légales, fiscales, comptables, de sécurité ou réglementaires. La suppression des systèmes actifs n'efface pas toujours immédiatement sauvegardes, journaux ou dossiers devant être conservés. Les données agrégées ou désidentifiées peuvent être conservées." },
      { title: "14. Sécurité des Données", content: "Nous utilisons des mesures administratives, techniques et organisationnelles raisonnables pour protéger les données. Aucun système ne peut garantir une sécurité absolue. Vous devez utiliser un mot de passe fort et unique, protéger vos identifiants et appareils et nous signaler tout accès suspect." },
      { title: "15. Vos Choix et Vos Droits", content: "Selon votre lieu de résidence, vous pouvez avoir des droits d'accès, rectification, suppression, portabilité, limitation, opposition, retrait du consentement ou information sur certaines divulgations. Un droit de recours peut également exister. Ces droits peuvent être soumis à vérification, exceptions et obligations de conservation. Utilisez les contrôles du compte ou contactez-nous pour d'autres demandes." },
      { title: "16. Droits des États Américains et Signaux de Préférence", content: "Certains États américains accordent des droits supplémentaires sur l'accès, la suppression, la correction, la portabilité, les données sensibles, la publicité ciblée, la vente ou le partage et certains profils. Lorsque la loi l'exige et que cela est techniquement applicable, nous respectons des signaux reconnus tels que Global Privacy Control. Les droits varient selon la juridiction et nos traitements." },
      { title: "17. Utilisateurs Internationaux", content: "Nous pouvons utiliser des prestataires ou infrastructures situés dans d'autres pays. Les données peuvent donc être transférées vers des juridictions dont les lois diffèrent. Lorsque nécessaire, nous utilisons des garanties juridiques reconnues pour les transferts internationaux." },
      { title: "18. Enfants et Jeunes Utilisateurs", content: "One2OneLove ne s'adresse pas aux enfants de moins de 13 ans et ne collecte pas sciemment leurs données. Les personnes n'ayant pas l'âge de la majorité doivent utiliser le service uniquement lorsque la loi le permet et avec l'implication d'un parent ou tuteur lorsque nécessaire. Certaines fonctions peuvent être réservées aux adultes." },
      { title: "19. Obligations Légales, Sécurité et Prévention des Abus", content: "Nous pouvons conserver, utiliser ou divulguer des informations lorsqu'il est raisonnablement nécessaire de respecter la loi ou une procédure légale, appliquer nos règles, enquêter sur fraude, exploitation, harcèlement, menaces ou abus, répondre à une urgence impliquant un risque grave ou protéger les droits, biens et sécurité, sous réserve du droit applicable." },
      { title: "20. Modifications et Contact", content: "Nous pouvons mettre à jour cette Politique lorsque One2OneLove, la loi ou nos pratiques évoluent. La date sera mise à jour et des avis supplémentaires seront fournis si nécessaire. Confidentialité ou juridique : legal@one2onelove.com. Assistance générale : support@one2onelove.com." }
    ]
  },
  it: {
    title: "Informativa sulla Privacy", subtitle: "Come One2OneLove raccoglie, usa, condivide, protegge e gestisce i dati personali", back: "Indietro", lastUpdated: "Ultimo Aggiornamento: 12 Settembre 2026", translationNotice: "Se una traduzione differisce dalla versione inglese, la versione inglese prevale nella misura consentita dalla legge applicabile.",
    sections: [
      { title: "1. Ambito dell'Informativa", content: "Questa Informativa si applica a siti, applicazioni, account, strumenti relazionali, community e chat, funzioni assistite dall'AI, quiz, Love Notes, idee per appuntamenti, traguardi, ricordi, risorse di supporto, directory professionali o di terapeuti, abbonamenti e altri servizi One2OneLove che rimandano a questa Informativa. Non copre servizi terzi con proprie informative." },
      { title: "2. Informazioni Fornite dall'Utente", content: "Possiamo raccogliere nome, email, dati di autenticazione, profilo, lingua, stato o contesto relazionale, interessi, obiettivi, traguardi, risposte ai quiz, Love Notes, ricordi, foto, messaggi, post, recensioni, suggerimenti, richieste di supporto e altre informazioni che scegli di inviare. Per professionisti, terapeuti, coach o fornitori simili possiamo raccogliere anche profilo professionale, credenziali, pratica, contatti, disponibilità o dati di verifica." },
      { title: "3. Informazioni Personali o Potenzialmente Sensibili", content: "Alcune funzioni possono includere informazioni private o sensibili, come problemi di relazione, orientamento sessuale, identità di genere, fede, situazione familiare o esperienze emotive. Sei tu a decidere cosa fornire. Evita informazioni non necessarie alla funzione utilizzata." },
      { title: "4. Community, Chat e Contenuti degli Utenti", content: "Le informazioni pubblicate in community, recensioni, commenti, profili pubblici o altre aree condivise possono essere visibili ad altri utenti. I messaggi diretti sono destinati ai partecipanti, ma possono essere trattati o esaminati quando necessario per gestire il servizio, indagare abusi, applicare regole, rispettare la legge o proteggere gli utenti." },
      { title: "5. Funzioni Assistite dall'AI", content: "Quando usi funzioni AI, possiamo trattare prompt, domande, contesto, testo, selezioni o altre informazioni per generare una risposta. Anche fornitori che supportano l'AI possono trattare input e output. Non inviare dati altamente sensibili salvo necessità e consenso. L'AI può sbagliare e non sostituisce consulenza medica, psicologica, legale, finanziaria o di emergenza." },
      { title: "6. Informazioni Raccolte Automaticamente", content: "Possiamo raccogliere indirizzo IP, browser, sistema operativo, identificatori del dispositivo, lingua, posizione approssimativa derivata dalla rete, pagine di provenienza, visualizzazioni, clic, uso delle funzioni, date, errori ed eventi di sicurezza. Cookie, memoria locale, pixel, SDK e tecnologie simili possono essere usati per sessioni, preferenze, sicurezza, prestazioni e analisi." },
      { title: "7. Posizione, Mappe, Indicazioni e Idee per Appuntamenti", content: "Alcune funzioni possono richiedere o usare la posizione. La posizione precisa del dispositivo dovrebbe essere usata solo quando concedi il permesso. Servizi terzi di mappe o localizzazione possono trattare dati. Non garantiamo accuratezza, disponibilità, sicurezza, orari, prezzi o idoneità di luoghi o percorsi suggeriti." },
      { title: "8. Pagamenti, Abbonamenti e Transazioni", content: "Quando sono disponibili servizi a pagamento, i dati di pagamento possono essere trattati da processori terzi. In genere non dobbiamo conservare numeri completi di carta. Possiamo ricevere stato del pagamento, livello di abbonamento, data, importo, valuta, dati limitati del metodo di pagamento e identificatori necessari per acquisti, rimborsi, contestazioni, imposte, frodi o supporto." },
      { title: "9. Come Usiamo le Informazioni", content: "Possiamo usare i dati per creare e gestire account, fornire funzioni, personalizzare lingua, contenuti e raccomandazioni, generare risposte AI, consegnare Love Notes o inviti, gestire community e messaggi, salvare ricordi, traguardi, obiettivi e preferenze, fornire supporto, gestire transazioni, prevenire frodi e abusi, mantenere sicurezza, risolvere errori, analizzare prestazioni, migliorare il prodotto, inviare comunicazioni consentite e rispettare obblighi legali." },
      { title: "10. Condivisione e Divulgazione", content: "Possiamo condividere dati con fornitori che supportano hosting, database, autenticazione, email, messaggistica, supporto, analisi, sicurezza, AI, mappe, archiviazione, pagamenti e altre funzioni. Possiamo condividere anche su tua richiesta, per il funzionamento di una funzione, per richieste legali, sicurezza, frodi o operazioni aziendali. Non vendiamo dati personali in cambio di denaro. Se una pratica futura sarà considerata vendita o condivisione ai sensi della legge, forniremo gli avvisi e le opzioni richiesti." },
      { title: "11. Professionisti e Servizi Terzi", content: "One2OneLove può mostrare o collegare terapeuti, counselor, coach, attività, articoli, video, mappe, pagamenti, social network o altre risorse terze. Se interagisci con un terzo, questo può raccogliere dati secondo le proprie regole. One2OneLove non è responsabile delle pratiche indipendenti di terzi. Un link o elenco non implica automaticamente approvazione, verifica o garanzia." },
      { title: "12. Cookie e Tecnologie Simili", content: "Possiamo usare cookie e tecnologie simili per sicurezza, sessioni, preferenze, prestazioni, analisi e funzionamento. Puoi controllarli nel browser, ma bloccare l'archiviazione essenziale può impedire il funzionamento di alcune parti del servizio. Quando la legge richiede consenso per tecnologie non essenziali, lo richiederemo." },
      { title: "13. Conservazione e Cancellazione", content: "Conserviamo i dati per il tempo ragionevolmente necessario a fornire il servizio, mantenere registri legittimi, risolvere controversie, applicare accordi, prevenire abusi e rispettare obblighi legali, fiscali, contabili, di sicurezza o regolatori. La cancellazione dai sistemi attivi può non eliminare subito backup, log o registri da conservare. Possiamo conservare dati aggregati o de-identificati." },
      { title: "14. Sicurezza dei Dati", content: "Usiamo misure amministrative, tecniche e organizzative ragionevoli per proteggere le informazioni. Nessun sistema può garantire sicurezza assoluta. Devi usare una password forte e unica, proteggere credenziali e dispositivi e informarci in caso di accesso sospetto." },
      { title: "15. Scelte e Diritti sulla Privacy", content: "A seconda della tua posizione puoi avere diritti di accesso, correzione, cancellazione, portabilità, limitazione, opposizione, revoca del consenso o informazione su alcune divulgazioni. Può esistere anche un diritto di ricorso. I diritti possono essere soggetti a verifica, eccezioni e obblighi di conservazione. Usa i controlli dell'account o contattaci per altre richieste." },
      { title: "16. Diritti Statali USA e Segnali di Preferenza", content: "Alcuni stati USA riconoscono diritti aggiuntivi su accesso, cancellazione, correzione, portabilità, dati sensibili, pubblicità mirata, vendita o condivisione e determinati profili. Quando legalmente richiesto e tecnicamente applicabile, rispetteremo segnali riconosciuti come Global Privacy Control. I diritti dipendono dalla giurisdizione e dal trattamento effettuato." },
      { title: "17. Utenti Internazionali", content: "Possiamo usare fornitori o infrastrutture in paesi diversi dal tuo. I dati possono quindi essere trasferiti o trattati in giurisdizioni con leggi differenti. Quando richiesto, utilizziamo garanzie legalmente riconosciute per i trasferimenti internazionali." },
      { title: "18. Minori e Utenti Giovani", content: "One2OneLove non è destinato a minori di 13 anni e non raccogliamo consapevolmente dati personali di minori di 13 anni. Chi non ha ancora la maggiore età dovrebbe usare il servizio solo dove consentito e con il coinvolgimento di un genitore o tutore quando richiesto. Alcune funzioni possono essere limitate agli adulti." },
      { title: "19. Obblighi Legali, Sicurezza e Prevenzione degli Abusi", content: "Possiamo conservare, usare o divulgare informazioni quando ragionevolmente necessario per rispettare la legge o processi legali, applicare termini e politiche, indagare frodi, sfruttamento, molestie, minacce o abusi, rispondere a emergenze con rischio grave o proteggere diritti, proprietà e sicurezza, nel rispetto della legge applicabile." },
      { title: "20. Modifiche e Contatti", content: "Possiamo aggiornare questa Informativa quando cambiano One2OneLove, la legge o le nostre pratiche. Mostreremo la data aggiornata e forniremo ulteriori avvisi quando necessario. Privacy o questioni legali: legal@one2onelove.com. Supporto generale: support@one2onelove.com." }
    ]
  },
  de: {
    title: "Datenschutzrichtlinie", subtitle: "Wie One2OneLove personenbezogene Daten erhebt, nutzt, teilt, schützt und verwaltet", back: "Zurück", lastUpdated: "Letzte Aktualisierung: 12. September 2026", translationNotice: "Wenn eine Übersetzung von der englischen Fassung abweicht, gilt die englische Fassung, soweit dies nach geltendem Recht zulässig ist.",
    sections: [
      { title: "1. Geltungsbereich", content: "Diese Richtlinie gilt für One2OneLove-Websites, Anwendungen, Konten, Beziehungstools, Community- und Chatfunktionen, KI-gestützte Funktionen, Quiz, Love Notes, Date-Ideen, Meilensteine, Erinnerungen, Hilfsressourcen, Verzeichnisse von Fachleuten oder Therapeuten, Abonnements und andere Dienste, die auf diese Richtlinie verweisen. Sie gilt nicht für Drittanbieter mit eigenen Datenschutzrichtlinien." },
      { title: "2. Von Ihnen Bereitgestellte Informationen", content: "Wir können Name, E-Mail, Authentifizierungsdaten, Profilangaben, Sprache, Beziehungsstatus oder -kontext, Interessen, Ziele, Meilensteine, Quizantworten, Love Notes, Erinnerungen, Fotos, Nachrichten, Beiträge, Bewertungen, Vorschläge, Supportanfragen und andere freiwillig bereitgestellte Informationen erfassen. Für Fachleute, Therapeuten, Coaches oder ähnliche Anbieter können wir zusätzlich berufliche Profile, Qualifikationen, Praxisdaten, Kontakt, Verfügbarkeit oder Verifizierungsinformationen erfassen." },
      { title: "3. Persönliche oder Potenziell Sensible Informationen", content: "Einige Funktionen können private oder sensible Informationen enthalten, etwa Beziehungsprobleme, sexuelle Orientierung, Geschlechtsidentität, Religion, familiäre Umstände oder emotionale Erfahrungen. Sie entscheiden, was Sie bereitstellen. Vermeiden Sie Informationen, die für die verwendete Funktion nicht erforderlich sind." },
      { title: "4. Community, Chat und Nutzerinhalte", content: "Informationen in Community-Bereichen, Bewertungen, Kommentaren, öffentlichen Profilen oder anderen geteilten Bereichen können für andere sichtbar sein. Direktnachrichten sind für die Gesprächsteilnehmer bestimmt, können aber verarbeitet oder geprüft werden, wenn dies für Betrieb, Missbrauchsuntersuchungen, Regelumsetzung, Rechtsbefolgung oder Nutzerschutz erforderlich ist." },
      { title: "5. KI-Gestützte Funktionen", content: "Bei KI-Funktionen können Eingaben, Fragen, Kontext, Texte, Auswahlen oder andere Informationen verarbeitet werden, um Antworten zu erzeugen. Dienstleister, die KI unterstützen, können Ein- und Ausgaben ebenfalls verarbeiten. Geben Sie besonders sensible Informationen nur an, wenn dies erforderlich und für Sie vertretbar ist. KI kann fehlerhaft sein und ersetzt keine medizinische, psychologische, rechtliche, finanzielle oder Notfallberatung." },
      { title: "6. Automatisch Erfasste Informationen", content: "Wir können IP-Adresse, Browser, Betriebssystem, Gerätekennungen, Sprache, aus Netzwerkdaten abgeleiteten ungefähren Standort, verweisende Seiten, Seitenaufrufe, Klicks, Funktionsnutzung, Zeitangaben, Fehler und Sicherheitsereignisse erfassen. Cookies, lokaler Speicher, Pixel, SDKs und ähnliche Technologien können für Sitzungen, Einstellungen, Sicherheit, Leistung und Analysen eingesetzt werden." },
      { title: "7. Standort, Karten, Wegbeschreibungen und Date-Ideen", content: "Einige Funktionen können Standortdaten anfordern oder verwenden. Präziser Gerätestandort sollte nur verwendet werden, wenn Sie die Berechtigung erteilen. Karten- oder Standortdienste Dritter können ebenfalls Daten verarbeiten. Wir garantieren keine Genauigkeit, Verfügbarkeit, Sicherheit, Öffnungszeiten, Preise oder Eignung vorgeschlagener Orte oder Routen." },
      { title: "8. Zahlungen, Abonnements und Transaktionen", content: "Bei kostenpflichtigen Diensten können Zahlungsdaten von Drittanbietern verarbeitet werden. Vollständige Kartennummern müssen wir normalerweise nicht speichern. Wir können Zahlungsstatus, Abostufe, Datum, Betrag, Währung, begrenzte Angaben zur Zahlungsmethode und Kennungen für Käufe, Erstattungen, Streitfälle, Steuern, Betrugsprävention oder Support erhalten." },
      { title: "9. Verwendung von Informationen", content: "Wir können Daten verwenden, um Konten zu erstellen und zu verwalten, Funktionen bereitzustellen, Sprache, Inhalte und Empfehlungen zu personalisieren, KI-Antworten zu erzeugen, Love Notes oder Einladungen zu liefern, Community und Nachrichten zu betreiben, Erinnerungen, Meilensteine, Ziele und Einstellungen zu speichern, Support zu leisten, Transaktionen zu verarbeiten, Betrug und Missbrauch zu verhindern, Sicherheit zu gewährleisten, Fehler zu beheben, Leistung zu analysieren, Produkte zu verbessern, erlaubte Mitteilungen zu senden und rechtliche Pflichten zu erfüllen." },
      { title: "10. Weitergabe und Offenlegung", content: "Wir können Informationen an Dienstleister weitergeben, die Hosting, Datenbanken, Authentifizierung, E-Mail, Nachrichten, Support, Analyse, Sicherheit, KI, Karten, Speicher, Zahlungen und andere Funktionen unterstützen. Eine Offenlegung kann auch auf Ihre Anweisung, aufgrund einer Funktionsgestaltung, wegen rechtlicher Anforderungen, Sicherheit, Betrug oder Unternehmenstransaktionen erfolgen. Wir verkaufen personenbezogene Daten nicht gegen Geld. Falls künftige Praktiken rechtlich als Verkauf oder Teilen gelten, stellen wir die erforderlichen Hinweise und Wahlmöglichkeiten bereit." },
      { title: "11. Fachleute und Drittanbieter", content: "One2OneLove kann Therapeuten, Berater, Coaches, Unternehmen, Artikel, Videos, Karten, Zahlungsdienste, soziale Netzwerke oder andere Drittressourcen anzeigen oder verlinken. Drittanbieter können Daten nach eigenen Regeln erheben. One2OneLove ist für deren unabhängige Datenschutzpraktiken nicht verantwortlich. Ein Link oder Eintrag bedeutet nicht automatisch Empfehlung, Verifizierung oder Garantie." },
      { title: "12. Cookies und Ähnliche Technologien", content: "Wir können Cookies und ähnliche Technologien für Sicherheit, Sitzungen, Einstellungen, Leistung, Analyse und Betrieb verwenden. Browser-Einstellungen ermöglichen oft Kontrolle, aber das Blockieren wesentlicher Speicherung kann Funktionen beeinträchtigen. Wo Einwilligung für nicht notwendige Technologien gesetzlich erforderlich ist, holen wir sie ein." },
      { title: "13. Speicherung und Löschung", content: "Wir speichern Informationen so lange, wie dies vernünftigerweise für den Dienst, legitime Aufzeichnungen, Streitbeilegung, Vertragsdurchsetzung, Missbrauchsprävention und rechtliche, steuerliche, buchhalterische, sicherheitsbezogene oder regulatorische Pflichten nötig ist. Das Löschen aus aktiven Systemen entfernt nicht immer sofort Sicherungen, Protokolle oder gesetzlich aufzubewahrende Datensätze. Aggregierte oder anonymisierte Daten können erhalten bleiben." },
      { title: "14. Datensicherheit", content: "Wir verwenden angemessene administrative, technische und organisatorische Schutzmaßnahmen. Kein System kann absolute Sicherheit garantieren. Sie sind verantwortlich für ein starkes, einzigartiges Passwort, den Schutz Ihrer Zugangsdaten und Geräte sowie die Meldung verdächtiger Zugriffe." },
      { title: "15. Ihre Wahlmöglichkeiten und Rechte", content: "Je nach Wohnort können Rechte auf Auskunft, Berichtigung, Löschung, Datenübertragbarkeit, Einschränkung, Widerspruch, Widerruf einer Einwilligung oder Informationen über Offenlegungen bestehen. Teilweise gibt es ein Beschwerderecht. Rechte können Verifizierung, Ausnahmen und Aufbewahrungspflichten unterliegen. Nutzen Sie Kontoeinstellungen oder kontaktieren Sie uns für weitere Anfragen." },
      { title: "16. US-Bundesstaatliche Rechte und Präferenzsignale", content: "Einige US-Bundesstaaten gewähren zusätzliche Rechte zu Auskunft, Löschung, Korrektur, Übertragbarkeit, sensiblen Daten, zielgerichteter Werbung, Verkauf oder Teilen und bestimmten Profiling-Aktivitäten. Wo gesetzlich vorgeschrieben und technisch anwendbar, berücksichtigen wir anerkannte Signale wie Global Privacy Control. Rechte hängen von Ihrer Rechtsordnung und unserer Verarbeitung ab." },
      { title: "17. Internationale Nutzer", content: "Wir können Dienstleister oder Infrastruktur in anderen Ländern einsetzen. Daten können daher in Rechtsordnungen mit anderen Datenschutzgesetzen verarbeitet werden. Soweit erforderlich, verwenden wir gesetzlich anerkannte Schutzmechanismen für internationale Übermittlungen." },
      { title: "18. Kinder und Jüngere Nutzer", content: "One2OneLove richtet sich nicht an Kinder unter 13 Jahren und wir sammeln nicht wissentlich deren personenbezogene Daten. Personen unter der Volljährigkeitsgrenze sollten den Dienst nur nutzen, wenn dies rechtlich zulässig ist und gegebenenfalls mit Beteiligung eines Elternteils oder Vormunds. Bestimmte Funktionen können Erwachsenen vorbehalten sein." },
      { title: "19. Gesetzliche Anforderungen, Sicherheit und Missbrauchsprävention", content: "Wir können Informationen speichern, nutzen oder offenlegen, wenn dies vernünftigerweise erforderlich ist, um Gesetze oder Rechtsverfahren zu befolgen, Bedingungen und Richtlinien durchzusetzen, Betrug, Ausbeutung, Belästigung, Drohungen oder Missbrauch zu untersuchen, auf Notfälle mit erheblichem Risiko zu reagieren oder Rechte, Eigentum und Sicherheit zu schützen, vorbehaltlich geltenden Rechts." },
      { title: "20. Änderungen und Kontakt", content: "Wir können diese Richtlinie aktualisieren, wenn sich One2OneLove, Gesetze oder unsere Praktiken ändern. Das Aktualisierungsdatum wird angezeigt; zusätzliche Hinweise erfolgen, wenn nötig. Datenschutz oder Recht: legal@one2onelove.com. Allgemeiner Support: support@one2onelove.com." }
    ]
  }
};

export default function PrivacyPolicy() {
  const { currentLanguage } = useLanguage();
  const t = translations[currentLanguage] || translations.en;

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50">
      <div className="max-w-5xl mx-auto px-4 py-12">
        <div className="mb-6">
          <Link to={createPageUrl("Home")} className="inline-flex items-center px-4 py-2 text-gray-600 hover:text-blue-600 hover:bg-blue-50 rounded-xl transition-all">
            <ArrowLeft size={20} className="mr-2" />
            {t.back}
          </Link>
        </div>

        <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-20 h-20 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full mb-6 shadow-xl">
            <Shield className="w-10 h-10 text-white" />
          </div>
          <h1 className="text-5xl font-bold text-gray-900 mb-4">{t.title}</h1>
          <p className="text-xl text-gray-600 max-w-4xl mx-auto">{t.subtitle}</p>
          <p className="text-sm text-gray-500 mt-4">{t.lastUpdated}</p>
          {currentLanguage !== "en" && <p className="text-sm text-amber-800 bg-amber-50 border border-amber-200 rounded-xl p-3 mt-5 max-w-3xl mx-auto">{t.translationNotice}</p>}
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
          <Card className="shadow-2xl">
            <CardContent className="p-8 md:p-10">
              <div className="prose prose-lg max-w-none">
                {t.sections.map((section, index) => (
                  <div key={index} className="mb-9">
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">{section.title}</h2>
                    <p className="text-gray-700 leading-relaxed">{section.content}</p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
}
