import React from "react";
import { useLanguage } from "@/Layout";
import { Card, CardContent } from "@/components/ui/card";
import { FileText, ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { motion } from "framer-motion";

const translations = {
  en: {
    title: "Terms of Service",
    subtitle: "Rules for using One2OneLove responsibly",
    back: "Back",
    lastUpdated: "Last Updated: September 12, 2026",
    sections: [
      { title: "1. Agreement to These Terms", content: "These Terms of Service govern your access to and use of One2OneLove, including our website, accounts, relationship tools, community features, AI-assisted features, content, subscriptions, and related services. By creating an account or using the platform, you agree to these Terms and our Privacy Policy. If you do not agree, do not use One2OneLove." },
      { title: "2. Eligibility", content: "One2OneLove is intended for adults. You must be at least 18 years old, or the age of majority where you live if higher, and legally able to enter into these Terms. You may not create an account using false identity information or on behalf of another person without authorization." },
      { title: "3. One2OneLove Is Not a Dating Service", content: "One2OneLove does not match users for dates and does not promise romantic compatibility or relationship outcomes. The platform is designed to support people pursuing, building, understanding, and nurturing relationships through tools, content, community, and resources." },
      { title: "4. Accounts and Security", content: "You are responsible for keeping your login credentials secure and for activity that occurs through your account. Provide accurate information, keep your contact information current, and notify us if you believe your account has been compromised. We may require identity or account verification when reasonably necessary for security or support." },
      { title: "5. Acceptable Use and Community Conduct", content: "Use One2OneLove lawfully and respectfully. You may not harass, threaten, stalk, exploit, impersonate, defraud, discriminate against, or intentionally harm another person; post unlawful, hateful, sexually exploitative, fraudulent, or malicious content; distribute malware; interfere with platform security; scrape or access the service in an unauthorized way; or use the platform to facilitate illegal activity." },
      { title: "6. User Content", content: "You keep ownership of content you create or submit. You grant One2OneLove a limited, non-exclusive license to host, store, reproduce, transmit, display, and process that content only as reasonably necessary to operate, improve, secure, and provide the features you choose to use. You are responsible for having the rights and permissions needed for content you submit, including content involving another person." },
      { title: "7. Public and Community Content", content: "Content posted in public or community spaces may be viewed, copied, discussed, or shared by other users. Do not post private relationship information, photographs, messages, or identifying details that you do not want others to see. We may moderate, restrict, or remove content that violates these Terms or creates safety, legal, or platform-integrity concerns." },
      { title: "8. AI-Assisted Features", content: "AI-generated content may be inaccurate, incomplete, repetitive, inappropriate, or unsuitable for your circumstances. AI features are tools for ideas, drafting, education, and reflection; they are not professional judgment. You are responsible for reviewing AI output before using or sharing it. Do not rely on AI for emergencies, medical or mental-health diagnosis, legal advice, financial decisions, or other high-stakes decisions." },
      { title: "9. Relationship, Therapy, and Professional Resources", content: "One2OneLove is not a licensed therapy practice, medical provider, crisis service, or substitute for professional care. Articles, quizzes, relationship-support content, professional listings, referrals, and similar resources are informational. Any therapist, counselor, coach, or other professional you choose to contact is responsible for their own qualifications, services, advice, fees, and professional obligations. If you are in immediate danger or facing a crisis, contact local emergency services or an appropriate crisis resource." },
      { title: "10. Date Ideas, Directions, and Third-Party Services", content: "Date ideas, locations, directions, maps, articles, links, and third-party services may be supplied by external providers. Availability, safety, accessibility, business hours, pricing, directions, and other details can change. Verify important information directly with the relevant third party before relying on it. One2OneLove is not responsible for third-party websites, businesses, products, services, or conduct." },
      { title: "11. Paid Features, Subscriptions, and Billing", content: "Some features may require payment or a subscription. Prices, billing frequency, trial terms, renewal terms, cancellation options, taxes, and any refund policy will be presented at or before purchase. Payments may be handled by a third-party payment processor. You authorize applicable charges when you complete a purchase. Nothing in these Terms limits refund or cancellation rights that cannot legally be waived." },
      { title: "12. Intellectual Property", content: "Except for user content and third-party materials, One2OneLove and its software, branding, designs, graphics, text, interfaces, and other platform materials are owned by or licensed to One2OneLove and are protected by applicable intellectual-property laws. You may use the platform for its intended personal use, but may not copy, sell, reverse engineer, redistribute, or commercially exploit protected platform materials without permission." },
      { title: "13. Suspension and Termination", content: "We may restrict, suspend, or terminate access when reasonably necessary to protect users, comply with law, investigate suspected abuse, address security risks, enforce these Terms, or protect the integrity of One2OneLove. You may stop using the platform at any time and may request account deletion subject to lawful retention requirements." },
      { title: "14. Service Changes and Availability", content: "We may add, modify, pause, or discontinue features as the platform develops. We do not guarantee that every feature will always be available, uninterrupted, compatible with every device, or free of errors. Where practical, we will try to avoid unnecessary disruption to users." },
      { title: "15. Disclaimers", content: "To the maximum extent permitted by law, One2OneLove is provided on an 'as is' and 'as available' basis. We do not guarantee specific relationship results, uninterrupted service, error-free operation, accuracy of user or third-party content, or that any tool, quiz, AI result, recommendation, or resource will be appropriate for every user." },
      { title: "16. Limitation of Liability", content: "To the maximum extent permitted by applicable law, One2OneLove will not be liable for indirect, incidental, special, exemplary, punitive, or consequential damages arising from or related to use of the platform, user interactions, third-party services, loss of content, or reliance on platform information. Some jurisdictions do not allow certain limitations, so those limitations apply only to the extent legally permitted." },
      { title: "17. Changes to These Terms", content: "We may update these Terms to reflect changes in the platform, business practices, technology, or law. The updated date will appear at the top of this page. If a change is material, we may provide additional notice when reasonably appropriate. Continued use after the effective date means you accept the updated Terms." },
      { title: "18. Governing Rights and Contact", content: "These Terms do not waive consumer rights that cannot legally be waived. Questions about these Terms may be submitted through the One2OneLove Contact Us page. We encourage users to contact us first so we can try to address concerns directly." }
    ]
  },
  es: {
    title: "Términos de Servicio", subtitle: "Reglas para usar One2OneLove de forma responsable", back: "Volver", lastUpdated: "Última Actualización: 12 de Septiembre de 2026",
    sections: [
      { title: "1. Acuerdo con Estos Términos", content: "Estos Términos regulan tu acceso y uso de One2OneLove, incluido el sitio web, cuentas, herramientas de relación, comunidad, funciones con IA, contenido, suscripciones y servicios relacionados. Al crear una cuenta o usar la plataforma, aceptas estos Términos y nuestra Política de Privacidad." },
      { title: "2. Elegibilidad", content: "One2OneLove está destinado a adultos. Debes tener al menos 18 años, o la mayoría de edad donde vivas si es superior, y capacidad legal para aceptar estos Términos. No puedes crear una cuenta con una identidad falsa ni en nombre de otra persona sin autorización." },
      { title: "3. One2OneLove No Es un Servicio de Citas", content: "One2OneLove no empareja usuarios para citas ni promete compatibilidad romántica o resultados de relación. La plataforma apoya a personas que buscan, construyen, comprenden y nutren relaciones." },
      { title: "4. Cuentas y Seguridad", content: "Eres responsable de mantener seguras tus credenciales y de la actividad de tu cuenta. Proporciona información precisa y notifícanos si crees que tu cuenta fue comprometida. Podemos solicitar verificación cuando sea razonablemente necesaria." },
      { title: "5. Uso Aceptable y Conducta", content: "Usa One2OneLove legalmente y con respeto. No puedes acosar, amenazar, perseguir, explotar, suplantar, defraudar, discriminar o dañar intencionalmente; publicar contenido ilegal, de odio, explotador o malicioso; distribuir malware; interferir con la seguridad; acceder sin autorización; ni facilitar actividades ilegales." },
      { title: "6. Contenido del Usuario", content: "Conservas la propiedad del contenido que creas o envías. Concedes a One2OneLove una licencia limitada y no exclusiva para alojar, almacenar, reproducir, transmitir, mostrar y procesar dicho contenido solo cuando sea razonablemente necesario para operar, mejorar, proteger y ofrecer las funciones que eliges usar." },
      { title: "7. Contenido Público y Comunitario", content: "El contenido publicado en áreas públicas o comunitarias puede ser visto, copiado, comentado o compartido por otros usuarios. No publiques detalles privados que no quieras que otros vean. Podemos moderar, restringir o eliminar contenido que viole estos Términos o genere riesgos de seguridad, legales o de integridad." },
      { title: "8. Funciones Asistidas por IA", content: "El contenido generado por IA puede ser inexacto, incompleto o inapropiado. Las funciones de IA sirven para ideas, redacción, educación y reflexión; no sustituyen el criterio profesional. Revisa los resultados antes de usarlos y no dependas de ellos para emergencias o decisiones médicas, legales, financieras o de alto riesgo." },
      { title: "9. Recursos de Relación y Profesionales", content: "One2OneLove no es una práctica de terapia licenciada, proveedor médico, servicio de crisis ni sustituto de atención profesional. Artículos, cuestionarios, recursos y listados profesionales son informativos. Cualquier profesional que contactes es responsable de sus propias credenciales, servicios, honorarios y obligaciones." },
      { title: "10. Ideas de Citas, Direcciones y Terceros", content: "Ideas de citas, ubicaciones, direcciones, mapas, artículos, enlaces y servicios de terceros pueden provenir de proveedores externos. Verifica información importante directamente. One2OneLove no es responsable de sitios, negocios, productos, servicios o conductas de terceros." },
      { title: "11. Funciones Pagadas, Suscripciones y Facturación", content: "Algunas funciones pueden requerir pago o suscripción. Precio, frecuencia, prueba, renovación, cancelación, impuestos y cualquier política de reembolso se mostrarán antes o al momento de la compra. Los pagos pueden ser procesados por un tercero." },
      { title: "12. Propiedad Intelectual", content: "Salvo contenido del usuario y materiales de terceros, el software, marca, diseños, gráficos, textos e interfaces de One2OneLove pertenecen o están licenciados a One2OneLove y están protegidos por la ley." },
      { title: "13. Suspensión y Terminación", content: "Podemos restringir, suspender o terminar el acceso cuando sea razonablemente necesario para proteger usuarios, cumplir la ley, investigar abuso, abordar riesgos de seguridad o aplicar estos Términos. Puedes dejar de usar la plataforma y solicitar eliminación de cuenta sujeto a obligaciones legales de conservación." },
      { title: "14. Cambios y Disponibilidad del Servicio", content: "Podemos añadir, modificar, pausar o discontinuar funciones. No garantizamos que todas estén siempre disponibles, sean ininterrumpidas, compatibles con todos los dispositivos o libres de errores." },
      { title: "15. Descargos de Responsabilidad", content: "En la máxima medida permitida por la ley, One2OneLove se ofrece 'tal cual' y 'según disponibilidad'. No garantizamos resultados específicos de relación, operación sin errores ni la exactitud o idoneidad de contenido, cuestionarios, IA, recomendaciones o recursos." },
      { title: "16. Limitación de Responsabilidad", content: "En la máxima medida permitida por la ley, One2OneLove no será responsable de daños indirectos, incidentales, especiales, punitivos o consecuentes derivados del uso de la plataforma, interacciones con usuarios, servicios de terceros, pérdida de contenido o dependencia de información de la plataforma." },
      { title: "17. Cambios a Estos Términos", content: "Podemos actualizar estos Términos para reflejar cambios en la plataforma, prácticas, tecnología o ley. La fecha actualizada aparecerá arriba y podremos proporcionar aviso adicional para cambios importantes." },
      { title: "18. Derechos Aplicables y Contacto", content: "Estos Términos no eliminan derechos del consumidor que legalmente no puedan renunciarse. Las preguntas pueden enviarse mediante la página Contact Us de One2OneLove." }
    ]
  },
  fr: {
    title: "Conditions d'Utilisation", subtitle: "Règles pour utiliser One2OneLove de manière responsable", back: "Retour", lastUpdated: "Dernière Mise à Jour : 12 Septembre 2026",
    sections: [
      { title: "1. Acceptation", content: "Ces Conditions régissent votre accès et votre utilisation de One2OneLove, y compris le site, les comptes, outils relationnels, fonctions communautaires, fonctions assistées par IA, contenus, abonnements et services associés. En créant un compte ou en utilisant la plateforme, vous acceptez ces Conditions et notre Politique de Confidentialité." },
      { title: "2. Éligibilité", content: "One2OneLove est destiné aux adultes. Vous devez avoir au moins 18 ans, ou l’âge de la majorité là où vous vivez s’il est supérieur, et être juridiquement capable d’accepter ces Conditions." },
      { title: "3. One2OneLove N’est Pas un Service de Rencontres", content: "One2OneLove ne met pas les utilisateurs en relation pour des rendez-vous et ne promet ni compatibilité romantique ni résultat relationnel. La plateforme soutient les personnes qui recherchent, construisent, comprennent et nourrissent leurs relations." },
      { title: "4. Comptes et Sécurité", content: "Vous êtes responsable de la sécurité de vos identifiants et de l’activité de votre compte. Fournissez des informations exactes et contactez-nous si vous pensez que votre compte est compromis. Une vérification peut être demandée lorsque cela est raisonnablement nécessaire." },
      { title: "5. Utilisation Acceptable et Conduite", content: "Utilisez One2OneLove légalement et avec respect. Il est interdit de harceler, menacer, traquer, exploiter, usurper une identité, frauder, discriminer ou nuire volontairement; publier du contenu illégal, haineux, exploiteur ou malveillant; diffuser des logiciels malveillants; contourner la sécurité ou faciliter une activité illégale." },
      { title: "6. Contenu Utilisateur", content: "Vous conservez la propriété du contenu créé ou soumis. Vous accordez à One2OneLove une licence limitée et non exclusive pour héberger, stocker, reproduire, transmettre, afficher et traiter ce contenu uniquement dans la mesure raisonnablement nécessaire au fonctionnement, à l’amélioration et à la sécurité des fonctions utilisées." },
      { title: "7. Contenu Public et Communautaire", content: "Le contenu publié dans des espaces publics ou communautaires peut être vu, copié, commenté ou partagé par d’autres utilisateurs. Ne publiez pas d’informations privées que vous ne souhaitez pas rendre visibles. Nous pouvons modérer ou retirer les contenus contraires aux Conditions ou présentant des risques." },
      { title: "8. Fonctions Assistées par IA", content: "Les résultats de l’IA peuvent être inexacts, incomplets ou inadaptés. L’IA sert aux idées, à la rédaction, à l’éducation et à la réflexion, et ne remplace pas le jugement professionnel. Vérifiez les résultats et ne les utilisez pas pour les urgences ou décisions médicales, juridiques, financières ou à haut risque." },
      { title: "9. Ressources Relationnelles et Professionnelles", content: "One2OneLove n’est pas un cabinet de thérapie agréé, un prestataire médical, un service de crise ni un substitut aux soins professionnels. Les articles, quiz, ressources et listes de professionnels sont informatifs. Tout professionnel contacté reste responsable de ses qualifications, services, honoraires et obligations." },
      { title: "10. Idées de Rendez-vous, Itinéraires et Tiers", content: "Les idées, lieux, itinéraires, cartes, articles, liens et services tiers peuvent provenir de prestataires externes. Vérifiez les informations importantes directement. One2OneLove n’est pas responsable des sites, entreprises, produits, services ou comportements de tiers." },
      { title: "11. Fonctions Payantes et Facturation", content: "Certaines fonctions peuvent nécessiter un paiement ou un abonnement. Le prix, la fréquence, les essais, renouvellements, annulations, taxes et éventuelles conditions de remboursement seront présentés avant ou lors de l’achat. Les paiements peuvent être traités par un tiers." },
      { title: "12. Propriété Intellectuelle", content: "À l’exception du contenu utilisateur et de certains éléments tiers, le logiciel, la marque, les designs, textes, graphiques et interfaces One2OneLove sont détenus ou licenciés par One2OneLove et protégés par la loi." },
      { title: "13. Suspension et Résiliation", content: "Nous pouvons restreindre, suspendre ou résilier l’accès lorsqu’il est raisonnablement nécessaire de protéger les utilisateurs, respecter la loi, enquêter sur un abus, gérer un risque de sécurité ou appliquer ces Conditions. Vous pouvez cesser d’utiliser la plateforme et demander la suppression de votre compte sous réserve des obligations légales." },
      { title: "14. Modifications et Disponibilité", content: "Nous pouvons ajouter, modifier, suspendre ou arrêter des fonctionnalités. Nous ne garantissons pas leur disponibilité permanente, l’absence d’interruption, la compatibilité avec tout appareil ou l’absence d’erreurs." },
      { title: "15. Exclusions de Garantie", content: "Dans la mesure maximale permise par la loi, One2OneLove est fourni 'tel quel' et 'selon disponibilité'. Nous ne garantissons aucun résultat relationnel particulier ni l’exactitude ou l’adéquation de tout contenu, quiz, résultat IA, recommandation ou ressource." },
      { title: "16. Limitation de Responsabilité", content: "Dans la mesure maximale permise par la loi, One2OneLove ne sera pas responsable des dommages indirects, accessoires, spéciaux, punitifs ou consécutifs liés à l’utilisation de la plateforme, aux interactions entre utilisateurs, aux services tiers, à la perte de contenu ou à la confiance accordée aux informations." },
      { title: "17. Modifications de Ces Conditions", content: "Nous pouvons mettre ces Conditions à jour pour refléter les évolutions de la plateforme, des pratiques, de la technologie ou de la loi. La date mise à jour figurera en haut de la page et un avis supplémentaire pourra être fourni pour les changements importants." },
      { title: "18. Droits Applicables et Contact", content: "Ces Conditions ne suppriment pas les droits des consommateurs qui ne peuvent légalement être écartés. Les questions peuvent être envoyées via la page Contact Us de One2OneLove." }
    ]
  },
  it: {
    title: "Termini di Servizio", subtitle: "Regole per usare One2OneLove in modo responsabile", back: "Indietro", lastUpdated: "Ultimo Aggiornamento: 12 Settembre 2026",
    sections: [
      { title: "1. Accettazione dei Termini", content: "Questi Termini regolano accesso e uso di One2OneLove, compresi sito, account, strumenti relazionali, community, funzioni IA, contenuti, abbonamenti e servizi correlati. Creando un account o usando la piattaforma accetti questi Termini e la nostra Informativa sulla Privacy." },
      { title: "2. Idoneità", content: "One2OneLove è destinato agli adulti. Devi avere almeno 18 anni, o la maggiore età del luogo in cui vivi se superiore, ed essere legalmente in grado di accettare questi Termini." },
      { title: "3. One2OneLove Non È un Servizio di Incontri", content: "One2OneLove non abbina utenti per appuntamenti e non promette compatibilità romantica o risultati relazionali. La piattaforma sostiene persone che cercano, costruiscono, comprendono e coltivano relazioni." },
      { title: "4. Account e Sicurezza", content: "Sei responsabile della sicurezza delle credenziali e delle attività del tuo account. Fornisci informazioni accurate e contattaci se ritieni che il tuo account sia stato compromesso. Possiamo richiedere verifiche quando ragionevolmente necessarie." },
      { title: "5. Uso Accettabile e Condotta", content: "Usa One2OneLove legalmente e con rispetto. Non puoi molestare, minacciare, perseguitare, sfruttare, impersonare, frodare, discriminare o danneggiare intenzionalmente; pubblicare contenuti illegali, d’odio, sfruttanti o dannosi; distribuire malware; aggirare la sicurezza o facilitare attività illegali." },
      { title: "6. Contenuti Utente", content: "Mantieni la proprietà dei contenuti creati o inviati. Concedi a One2OneLove una licenza limitata e non esclusiva per ospitare, archiviare, riprodurre, trasmettere, mostrare ed elaborare tali contenuti solo quanto ragionevolmente necessario per fornire, migliorare e proteggere le funzioni che usi." },
      { title: "7. Contenuti Pubblici e Community", content: "I contenuti pubblicati in aree pubbliche o della community possono essere visualizzati, copiati, discussi o condivisi da altri utenti. Non pubblicare informazioni private che non vuoi rendere visibili. Possiamo moderare o rimuovere contenuti che violano i Termini o creano rischi." },
      { title: "8. Funzioni Assistite dall’IA", content: "I risultati IA possono essere inesatti, incompleti o inappropriati. L’IA serve per idee, bozze, educazione e riflessione e non sostituisce il giudizio professionale. Verifica i risultati e non usarli per emergenze o decisioni mediche, legali, finanziarie o ad alto rischio." },
      { title: "9. Risorse Relazionali e Professionali", content: "One2OneLove non è uno studio di terapia autorizzato, un fornitore medico, un servizio di crisi o sostituto dell’assistenza professionale. Articoli, quiz, risorse ed elenchi professionali sono informativi. Ogni professionista contattato è responsabile di qualifiche, servizi, tariffe e obblighi." },
      { title: "10. Idee per Appuntamenti, Indicazioni e Terze Parti", content: "Idee, luoghi, indicazioni, mappe, articoli, link e servizi terzi possono provenire da fornitori esterni. Verifica direttamente le informazioni importanti. One2OneLove non è responsabile per siti, attività, prodotti, servizi o condotte di terzi." },
      { title: "11. Funzioni a Pagamento e Fatturazione", content: "Alcune funzioni possono richiedere pagamento o abbonamento. Prezzo, frequenza, prove, rinnovi, cancellazioni, tasse ed eventuali condizioni di rimborso saranno presentati prima o al momento dell’acquisto. I pagamenti possono essere elaborati da terzi." },
      { title: "12. Proprietà Intellettuale", content: "Salvo contenuti utente e materiali di terzi, software, marchi, design, grafica, testi e interfacce di One2OneLove sono di proprietà o concessi in licenza a One2OneLove e protetti dalla legge." },
      { title: "13. Sospensione e Chiusura", content: "Possiamo limitare, sospendere o terminare l’accesso quando ragionevolmente necessario per proteggere utenti, rispettare la legge, indagare abusi, affrontare rischi di sicurezza o applicare i Termini. Puoi smettere di usare la piattaforma e richiedere la cancellazione dell’account nel rispetto degli obblighi legali." },
      { title: "14. Modifiche e Disponibilità", content: "Possiamo aggiungere, modificare, sospendere o interrompere funzioni. Non garantiamo disponibilità continua, assenza di interruzioni, compatibilità con ogni dispositivo o assenza di errori." },
      { title: "15. Esclusioni di Garanzia", content: "Nella misura massima consentita dalla legge, One2OneLove è fornito 'così com’è' e 'come disponibile'. Non garantiamo risultati relazionali specifici né accuratezza o idoneità di contenuti, quiz, risultati IA, raccomandazioni o risorse." },
      { title: "16. Limitazione di Responsabilità", content: "Nella misura massima consentita dalla legge, One2OneLove non sarà responsabile per danni indiretti, incidentali, speciali, punitivi o consequenziali collegati all’uso della piattaforma, interazioni con utenti, servizi terzi, perdita di contenuti o affidamento sulle informazioni." },
      { title: "17. Modifiche ai Termini", content: "Possiamo aggiornare questi Termini per riflettere cambiamenti di piattaforma, pratiche, tecnologia o legge. La data aggiornata apparirà in alto e potremo fornire ulteriore avviso per modifiche importanti." },
      { title: "18. Diritti Applicabili e Contatti", content: "Questi Termini non eliminano diritti dei consumatori che non possono essere legalmente rinunciati. Le domande possono essere inviate tramite la pagina Contact Us di One2OneLove." }
    ]
  },
  de: {
    title: "Nutzungsbedingungen", subtitle: "Regeln für die verantwortungsvolle Nutzung von One2OneLove", back: "Zurück", lastUpdated: "Letzte Aktualisierung: 12. September 2026",
    sections: [
      { title: "1. Zustimmung zu Diesen Bedingungen", content: "Diese Bedingungen regeln Ihren Zugang zu und die Nutzung von One2OneLove einschließlich Website, Konten, Beziehungstools, Community-Funktionen, KI-Funktionen, Inhalten, Abonnements und verbundenen Diensten. Mit Kontoerstellung oder Nutzung stimmen Sie diesen Bedingungen und unserer Datenschutzrichtlinie zu." },
      { title: "2. Berechtigung", content: "One2OneLove richtet sich an Erwachsene. Sie müssen mindestens 18 Jahre alt sein oder das höhere Volljährigkeitsalter Ihres Wohnorts erreicht haben und rechtlich in der Lage sein, diesen Bedingungen zuzustimmen." },
      { title: "3. One2OneLove Ist Kein Dating-Dienst", content: "One2OneLove vermittelt keine Dates und verspricht weder romantische Kompatibilität noch bestimmte Beziehungsergebnisse. Die Plattform unterstützt Menschen beim Suchen, Aufbauen, Verstehen und Pflegen von Beziehungen." },
      { title: "4. Konten und Sicherheit", content: "Sie sind für die Sicherheit Ihrer Zugangsdaten und die Aktivitäten Ihres Kontos verantwortlich. Geben Sie korrekte Informationen an und kontaktieren Sie uns, wenn Sie eine Kompromittierung vermuten. Wir können eine Verifizierung verlangen, wenn dies vernünftigerweise erforderlich ist." },
      { title: "5. Zulässige Nutzung und Verhalten", content: "Nutzen Sie One2OneLove rechtmäßig und respektvoll. Belästigung, Bedrohung, Stalking, Ausbeutung, Identitätsmissbrauch, Betrug, Diskriminierung, vorsätzliche Schädigung, illegale oder hasserfüllte Inhalte, Malware, Sicherheitsumgehung, unbefugter Zugriff und Förderung illegaler Aktivitäten sind untersagt." },
      { title: "6. Nutzerinhalte", content: "Sie behalten das Eigentum an Ihren Inhalten. Sie gewähren One2OneLove eine begrenzte, nicht exklusive Lizenz zum Hosten, Speichern, Reproduzieren, Übertragen, Anzeigen und Verarbeiten dieser Inhalte nur soweit dies für Betrieb, Verbesserung, Sicherheit und die von Ihnen genutzten Funktionen vernünftigerweise erforderlich ist." },
      { title: "7. Öffentliche und Community-Inhalte", content: "In öffentlichen oder Community-Bereichen veröffentlichte Inhalte können von anderen Nutzern gesehen, kopiert, diskutiert oder geteilt werden. Veröffentlichen Sie keine privaten Informationen, die Sie nicht sichtbar machen möchten. Wir können Inhalte moderieren oder entfernen, die gegen diese Bedingungen verstoßen oder Risiken schaffen." },
      { title: "8. KI-gestützte Funktionen", content: "KI-Ergebnisse können ungenau, unvollständig oder ungeeignet sein. KI dient Ideen, Entwürfen, Bildung und Reflexion und ersetzt kein professionelles Urteil. Prüfen Sie Ergebnisse und verlassen Sie sich nicht bei Notfällen oder medizinischen, rechtlichen, finanziellen oder anderen Hochrisikoentscheidungen darauf." },
      { title: "9. Beziehungs- und Fachressourcen", content: "One2OneLove ist keine lizenzierte Therapiepraxis, kein medizinischer Anbieter, kein Krisendienst und kein Ersatz für professionelle Hilfe. Artikel, Quizze, Ressourcen und Fachlisten dienen der Information. Kontaktierte Fachkräfte sind selbst für Qualifikation, Leistungen, Gebühren und Pflichten verantwortlich." },
      { title: "10. Date-Ideen, Wegbeschreibungen und Dritte", content: "Date-Ideen, Orte, Wegbeschreibungen, Karten, Artikel, Links und Drittanbieter können von externen Anbietern stammen. Prüfen Sie wichtige Informationen direkt. One2OneLove ist nicht verantwortlich für Websites, Unternehmen, Produkte, Dienste oder Verhalten Dritter." },
      { title: "11. Bezahlte Funktionen und Abrechnung", content: "Einige Funktionen können Zahlung oder Abonnement erfordern. Preise, Häufigkeit, Testzeiten, Verlängerung, Kündigung, Steuern und mögliche Erstattungsbedingungen werden vor oder beim Kauf angezeigt. Zahlungen können durch einen Drittanbieter verarbeitet werden." },
      { title: "12. Geistiges Eigentum", content: "Mit Ausnahme von Nutzerinhalten und Drittmaterialien sind Software, Marken, Designs, Grafiken, Texte und Oberflächen von One2OneLove Eigentum von oder lizenziert an One2OneLove und gesetzlich geschützt." },
      { title: "13. Sperrung und Beendigung", content: "Wir können den Zugang beschränken, sperren oder beenden, wenn dies vernünftigerweise zum Schutz von Nutzern, zur Einhaltung von Gesetzen, Untersuchung von Missbrauch, Behandlung von Sicherheitsrisiken oder Durchsetzung dieser Bedingungen erforderlich ist. Sie können die Nutzung beenden und eine Kontolöschung vorbehaltlich gesetzlicher Aufbewahrungspflichten verlangen." },
      { title: "14. Änderungen und Verfügbarkeit", content: "Wir können Funktionen hinzufügen, ändern, pausieren oder einstellen. Wir garantieren keine dauerhafte Verfügbarkeit, unterbrechungsfreie Nutzung, Kompatibilität mit jedem Gerät oder Fehlerfreiheit." },
      { title: "15. Haftungsausschlüsse", content: "Soweit gesetzlich zulässig, wird One2OneLove 'wie besehen' und 'wie verfügbar' bereitgestellt. Wir garantieren keine bestimmten Beziehungsergebnisse und keine Richtigkeit oder Eignung von Inhalten, Quizzen, KI-Ergebnissen, Empfehlungen oder Ressourcen." },
      { title: "16. Haftungsbeschränkung", content: "Soweit gesetzlich zulässig, haftet One2OneLove nicht für indirekte, beiläufige, besondere, strafende oder Folgeschäden im Zusammenhang mit Plattformnutzung, Nutzerinteraktionen, Drittanbietern, Inhaltsverlust oder Vertrauen auf Plattforminformationen." },
      { title: "17. Änderungen Dieser Bedingungen", content: "Wir können diese Bedingungen aktualisieren, um Änderungen an Plattform, Praktiken, Technologie oder Recht abzubilden. Das Aktualisierungsdatum erscheint oben; bei wesentlichen Änderungen kann zusätzlicher Hinweis erfolgen." },
      { title: "18. Anwendbare Rechte und Kontakt", content: "Diese Bedingungen schränken Verbraucherrechte, auf die gesetzlich nicht verzichtet werden kann, nicht ein. Fragen können über die Contact Us-Seite von One2OneLove eingereicht werden." }
    ]
  }
};

export default function TermsOfService() {
  const { currentLanguage } = useLanguage();
  const t = translations[currentLanguage] || translations.en;

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50">
      <div className="max-w-4xl mx-auto px-4 py-12">
        <div className="mb-6">
          <Link to={createPageUrl("Home")} className="inline-flex items-center px-4 py-2 text-gray-600 hover:text-blue-600 hover:bg-blue-50 rounded-xl transition-all">
            <ArrowLeft size={20} className="mr-2" />
            {t.back}
          </Link>
        </div>

        <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-20 h-20 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full mb-6 shadow-xl">
            <FileText className="w-10 h-10 text-white" />
          </div>
          <h1 className="text-5xl font-bold text-gray-900 mb-4">{t.title}</h1>
          <p className="text-xl text-gray-600">{t.subtitle}</p>
          <p className="text-sm text-gray-500 mt-4">{t.lastUpdated}</p>
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
          <Card className="shadow-2xl">
            <CardContent className="p-8">
              <div className="prose prose-lg max-w-none">
                {t.sections.map((section, index) => (
                  <div key={index} className="mb-8">
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">{section.title}</h2>
                    <p className="text-gray-700 leading-relaxed">{section.content}</p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
}