import React from "react";
import { useLanguage } from "@/Layout";
import { Card, CardContent } from "@/components/ui/card";
import { FileText, ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { motion } from "framer-motion";

const translations = {
  en: {
    title: "Terms of Service",
    subtitle: "Rules and conditions for using One2OneLove",
    back: "Back",
    lastUpdated: "Last Updated: September 12, 2026",
    translationNotice: "If a translated version differs from the English version, the English version controls to the extent permitted by applicable law.",
    ownershipNotice: "The One2One Love Platform is owned and operated by ERANT Property Services LLC (EPS LLC), its parent company. These Terms are an agreement between you and ERANT Property Services LLC relating to your use of the One2One Love Platform. References to ‘One2OneLove,’ ‘we,’ ‘us,’ or ‘our’ mean ERANT Property Services LLC operating the One2One Love Platform, unless the context requires otherwise.",
    sections: [
      { title: "1. Agreement to These Terms", content: "These Terms of Service govern your access to and use of One2OneLove websites, applications, accounts, relationship tools, community and chat features, AI-assisted features, Love Notes, quizzes, date ideas, milestones, memories, support resources, professional or therapist-related directories, subscriptions, and any other service that links to these Terms. By creating an account, accessing, or using One2OneLove, you agree to these Terms and our Privacy Policy. If you do not agree, do not use the service." },
      { title: "2. Eligibility and Age", content: "You must be at least 13 years old to use One2OneLove. If you are under the age of legal majority where you live, you may use the service only if permitted by law and with the involvement or consent of a parent or legal guardian when required. Certain features may be limited to adults. You may not use One2OneLove if applicable law prohibits you from doing so." },
      { title: "3. Accounts, Registration, and Account Security", content: "You agree to provide accurate information, keep account details reasonably current, protect your password and authentication credentials, and accept responsibility for activity occurring through your account. You may not impersonate another person, create an account using information you are not authorized to use, sell or transfer an account without permission, or attempt to bypass security or account restrictions. Notify us promptly if you suspect unauthorized access." },
      { title: "4. What One2OneLove Is — and Is Not", content: "One2OneLove is a relationship-support platform intended to provide tools, community, education, reflection, communication support, memories, goals, date ideas, and related features. One2OneLove is not a dating or matchmaking service and does not promise to find, match, or introduce romantic partners. We do not guarantee relationship outcomes, compatibility, reconciliation, engagement, marriage, or any other personal result." },
      { title: "5. Acceptable Use and Community Conduct", content: "You must use One2OneLove lawfully and respectfully. You may not harass, threaten, stalk, exploit, shame, discriminate against, defraud, impersonate, or intentionally harm others; send spam or repeated unwanted contact; promote violence or illegal conduct; distribute malware; scrape or harvest data without authorization; interfere with platform security or operation; attempt unauthorized access; use automated systems in a manner we prohibit; or use the service to facilitate trafficking, sexual exploitation, abuse, coercion, extortion, fraud, or other unlawful conduct." },
      { title: "6. User Content and Your Responsibilities", content: "You retain ownership of content you create and submit, subject to rights you grant us to operate the service. You are responsible for your Love Notes, messages, posts, comments, photos, memories, reviews, suggestions, profile information, quiz responses, and other content. You represent that you have the rights and permissions needed to submit that content and that it does not violate law, privacy, publicity, intellectual-property, contractual, or other rights of another person." },
      { title: "7. License to Operate the Service", content: "By submitting content, you grant One2OneLove a non-exclusive, worldwide, royalty-free license to host, store, reproduce, process, transmit, display, format, and otherwise use that content only as reasonably necessary to operate, secure, improve, and provide the service, comply with law, and carry out the sharing or functionality you request. This license ends when the content is deleted from active systems, except to the extent retention is reasonably necessary for backups, legal compliance, safety, fraud prevention, dispute resolution, or other legitimate obligations." },
      { title: "8. Community, Chat, and Private Communications", content: "Community and chat features are provided for respectful communication. Content posted publicly or in shared spaces may be visible to others. Direct messages are intended for participants, but no online messaging system should be treated as guaranteed private or secure. We may preserve, review, restrict, or disclose communications when reasonably necessary to operate the service, investigate violations, respond to reports, protect safety, or comply with law." },
      { title: "9. AI-Assisted Features", content: "Some features may use artificial intelligence to generate messages, prompts, ideas, educational content, summaries, reflections, or relationship-oriented responses. AI output may be inaccurate, incomplete, biased, outdated, unsuitable, or inconsistent with your circumstances. You are responsible for reviewing AI output before using, sending, publishing, or relying on it. Do not treat AI output as a factual guarantee or as professional advice." },
      { title: "10. No Medical, Mental-Health, Legal, Financial, or Other Professional Advice", content: "One2OneLove content, quizzes, AI features, articles, relationship tools, community discussions, and educational materials are for general informational and relationship-support purposes. They are not a diagnosis, treatment plan, legal opinion, financial recommendation, or substitute for a licensed professional who can evaluate your specific circumstances. Never delay seeking qualified professional help because of content you saw on One2OneLove." },
      { title: "11. Therapists, Coaches, Professionals, and Resource Directories", content: "If One2OneLove displays therapists, counselors, coaches, professionals, contributors, or other service providers, listings are provided as a resource unless we expressly state otherwise. You are responsible for evaluating qualifications, licensing, insurance, experience, suitability, cost, availability, and the terms of any relationship you form with a provider. One2OneLove does not guarantee a provider's credentials, conduct, availability, services, outcomes, or compliance with professional obligations unless expressly stated in writing." },
      { title: "12. Date Ideas, Maps, Directions, Businesses, Activities, and Physical Safety", content: "Date ideas, maps, routes, businesses, events, activities, costs, hours, accessibility information, and other local suggestions may come from One2OneLove, users, or third parties and can change without notice. You are responsible for verifying details directly with the relevant provider and for evaluating weather, transportation, physical ability, health considerations, cost, neighborhood conditions, personal safety, and any other risks before participating. Use directions and location information at your own judgment and follow applicable laws and safety instructions." },
      { title: "13. Emergencies, Abuse, Crisis, and Immediate Danger", content: "One2OneLove is not an emergency, crisis, domestic-violence, suicide-prevention, medical, or law-enforcement service. If you or another person is in immediate danger, may be harmed, is experiencing abuse, or has a medical or mental-health emergency, contact local emergency services or an appropriate qualified crisis resource. Do not rely on One2OneLove, community users, AI features, or response times for urgent intervention." },
      { title: "14. Privacy", content: "Our Privacy Policy explains how we collect, use, disclose, retain, and protect personal information. By using One2OneLove, you acknowledge the Privacy Policy. You are also responsible for respecting the privacy of others and for obtaining permission before uploading, posting, or sharing another person's personal information, image, message, or private content when permission is required." },
      { title: "15. Paid Services, Subscriptions, Trials, Renewals, and Taxes", content: "If One2OneLove offers paid services, prices, billing intervals, trial terms, included features, renewal terms, and cancellation options will be shown at or before purchase. Unless stated otherwise, subscriptions may renew automatically until canceled in accordance with the purchase terms and applicable law. You authorize applicable charges and are responsible for taxes, fees, and accurate billing information. Refunds are provided only as stated in the applicable purchase terms or when required by law. Payment processing may be performed by third-party payment providers under their own terms." },
      { title: "16. Third-Party Services, Links, Content, and Integrations", content: "One2OneLove may link to or integrate with third-party websites, maps, social networks, payment providers, businesses, professionals, videos, articles, or other services. We do not control third-party services and are not responsible for their content, availability, security, terms, privacy practices, products, services, or conduct. Your use of a third party is governed by that party's terms and policies." },
      { title: "17. One2OneLove Intellectual Property", content: "The One2OneLove name, logos, branding, platform design, software, code, graphics, text, interfaces, features, compilations, and other materials owned or licensed by One2OneLove are protected by intellectual-property laws. Except for rights expressly granted to you, no license or ownership interest is transferred. You may not copy, modify, distribute, sell, reverse engineer, decompile, create unauthorized derivative works, or use One2OneLove branding in a misleading manner except as permitted by law or written permission." },
      { title: "18. Copyright and Rights Complaints", content: "If you believe content on One2OneLove infringes your copyright, trademark, privacy, publicity, or other legal rights, contact legal@one2onelove.com with enough information for us to identify the content, understand the claimed right, contact you, and evaluate the request. We may request additional information and may remove or restrict content when appropriate or legally required." },
      { title: "19. Moderation, Reporting, Enforcement, Suspension, and Termination", content: "We may investigate reports, moderate content, remove or restrict content, limit features, suspend accounts, or terminate access when we reasonably believe there has been a violation of these Terms, a safety risk, fraud, abuse, legal exposure, repeated harmful conduct, or misuse of the service. We may also preserve relevant information as required for safety, disputes, fraud prevention, or legal compliance. Where appropriate and legally required, we may provide notice or an opportunity to appeal." },
      { title: "20. Service Availability, Changes, Testing, and Discontinuation", content: "One2OneLove may add, modify, test, limit, suspend, or discontinue features, content, pricing, eligibility, integrations, storage limits, or other aspects of the service. Features may be unavailable because of maintenance, technical problems, third-party outages, security measures, or product changes. We do not guarantee uninterrupted access, permanent availability of any feature, preservation of every piece of user content, or that the service will always operate without errors." },
      { title: "21. Disclaimers", content: "To the maximum extent permitted by law, One2OneLove and its services are provided on an 'as is' and 'as available' basis without warranties of any kind, whether express, implied, or statutory, including warranties of merchantability, fitness for a particular purpose, title, non-infringement, accuracy, reliability, availability, security, or relationship outcome. Some jurisdictions do not allow certain warranty exclusions, so some exclusions may not apply to you." },
      { title: "22. Limitation of Liability", content: "To the maximum extent permitted by law, One2OneLove and its owners, affiliates, officers, employees, contractors, licensors, and service providers will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages; loss of profits, data, goodwill, opportunities, relationships, or business; personal decisions made based on platform content; conduct of users or third parties; or events arising from third-party services. Any limitation applies only to the extent allowed by law, and nothing in these Terms limits liability that cannot legally be limited." },
      { title: "23. Indemnification", content: "To the extent permitted by law, you agree to defend, indemnify, and hold harmless One2OneLove and its owners, affiliates, officers, employees, contractors, and service providers from claims, liabilities, damages, losses, and reasonable costs arising from your unlawful use of the service, your content, your violation of these Terms, or your violation of another person's rights. This obligation does not apply where prohibited by law." },
      { title: "24. Governing Law and Disputes", content: "Unless applicable consumer law requires otherwise, these Terms are governed by the laws of the State of Texas, U.S.A., without regard to conflict-of-laws rules. Before filing a formal claim, you are encouraged to contact legal@one2onelove.com so the parties can attempt to resolve the issue informally. Nothing in this section removes rights or remedies that cannot lawfully be waived in your jurisdiction." },
      { title: "25. Electronic Communications", content: "By using One2OneLove, you agree that notices, disclosures, account communications, transaction messages, and other communications may be provided electronically, including through the service or by email, where permitted by law. You are responsible for keeping your contact information current and for maintaining access to the email address associated with your account." },
      { title: "26. Assignment, Severability, Waiver, and Force Majeure", content: "You may not assign your rights or obligations under these Terms without our consent, except where applicable law permits otherwise. We may assign these Terms in connection with a reorganization, financing, merger, acquisition, sale, or transfer of the service. If any provision is found unenforceable, the remaining provisions remain in effect to the extent permitted. Failure to enforce a provision is not a waiver. We are not responsible for delays or failures caused by events beyond reasonable control, subject to applicable law." },
      { title: "27. Changes to These Terms and Contact", content: "We may revise these Terms as the service, law, or business changes. The updated date will appear on this page and additional notice will be provided when required. Continued use after the effective date of revised Terms constitutes acceptance to the extent permitted by law. For legal questions or rights complaints, contact legal@one2onelove.com. For general support, contact support@one2onelove.com." }
    ]
  },
  es: {
    title: "Términos de Servicio", subtitle: "Reglas y condiciones para usar One2OneLove", back: "Volver", lastUpdated: "Última Actualización: 12 de Septiembre de 2026", translationNotice: "Si una versión traducida difiere de la versión en inglés, la versión en inglés prevalece en la medida permitida por la ley aplicable.", ownershipNotice: "La Plataforma One2One Love es propiedad de ERANT Property Services LLC (EPS LLC), su empresa matriz, y es operada por ella. Estos Términos constituyen un acuerdo entre tú y ERANT Property Services LLC en relación con tu uso de la Plataforma One2One Love. Las referencias a ‘One2OneLove’, ‘nosotros’, ‘nos’ o ‘nuestro’ significan ERANT Property Services LLC operando la Plataforma One2One Love, salvo que el contexto indique lo contrario.",
    sections: [
      { title: "1. Aceptación de Estos Términos", content: "Estos Términos regulan el acceso y uso de sitios, aplicaciones, cuentas, herramientas de relación, comunidad y chat, funciones de IA, Notas de Amor, cuestionarios, ideas para citas, hitos, recuerdos, recursos de apoyo, directorios profesionales o de terapeutas, suscripciones y demás servicios One2OneLove que enlacen estos Términos. Al crear una cuenta o usar el servicio, aceptas estos Términos y la Política de Privacidad." },
      { title: "2. Elegibilidad y Edad", content: "Debes tener al menos 13 años. Si no has alcanzado la mayoría de edad donde vives, solo puedes usar el servicio cuando la ley lo permita y con participación o consentimiento de padre, madre o tutor cuando sea necesario. Algunas funciones pueden limitarse a adultos." },
      { title: "3. Cuentas y Seguridad", content: "Debes proporcionar información correcta, mantenerla razonablemente actualizada, proteger contraseña y credenciales y asumir responsabilidad por la actividad de tu cuenta. No puedes suplantar, usar datos sin autorización, vender o transferir cuentas sin permiso ni intentar eludir seguridad o restricciones. Avísanos si sospechas acceso no autorizado." },
      { title: "4. Qué Es One2OneLove — y Qué No Es", content: "One2OneLove es una plataforma de apoyo para relaciones con herramientas, comunidad, educación, reflexión, comunicación, recuerdos, metas e ideas para citas. No es un servicio de citas ni matchmaking y no promete encontrar o emparejar parejas. No garantizamos resultados personales o relacionales." },
      { title: "5. Uso Aceptable y Conducta", content: "Debes usar One2OneLove de forma legal y respetuosa. Se prohíben acoso, amenazas, acecho, explotación, discriminación, fraude, suplantación, daño intencional, spam, contacto repetido no deseado, promoción de violencia o delitos, malware, extracción no autorizada de datos, interferencia con seguridad, acceso no autorizado y uso para trata, explotación sexual, abuso, coacción, extorsión u otras conductas ilegales." },
      { title: "6. Contenido del Usuario", content: "Conservas la propiedad de lo que creas, sujeto a los derechos necesarios para operar el servicio. Eres responsable de Notas de Amor, mensajes, publicaciones, fotos, recuerdos, reseñas, sugerencias, perfil, cuestionarios y demás contenido. Debes tener los derechos y permisos para enviarlo y no violar derechos legales, de privacidad, publicidad, propiedad intelectual o contractuales de otra persona." },
      { title: "7. Licencia para Operar el Servicio", content: "Al enviar contenido otorgas a One2OneLove una licencia no exclusiva, mundial y libre de regalías para alojar, almacenar, reproducir, procesar, transmitir, mostrar y formatear ese contenido únicamente cuando sea razonablemente necesario para operar, proteger, mejorar y prestar el servicio, cumplir la ley y realizar la función o intercambio que solicitas. La licencia termina al eliminarse de sistemas activos, salvo retención legítima por copias de seguridad, ley, seguridad, fraude o disputas." },
      { title: "8. Comunidad, Chat y Comunicaciones", content: "La comunidad y el chat son para comunicación respetuosa. El contenido público o compartido puede ser visible a otros. Los mensajes directos están destinados a sus participantes, pero ningún sistema en línea debe considerarse absolutamente privado o seguro. Podemos conservar, revisar, limitar o divulgar comunicaciones cuando sea necesario para operar, investigar, responder a reportes, proteger seguridad o cumplir la ley." },
      { title: "9. Funciones Asistidas por IA", content: "Algunas funciones usan IA para generar mensajes, ideas, material educativo, resúmenes o reflexiones. El contenido puede ser incorrecto, incompleto, sesgado, desactualizado o inadecuado. Debes revisarlo antes de usarlo, enviarlo, publicarlo o confiar en él. La IA no es una garantía de hechos ni asesoramiento profesional." },
      { title: "10. No Ofrecemos Asesoramiento Profesional", content: "Contenido, cuestionarios, IA, artículos, herramientas y conversaciones son para información general y apoyo relacional. No constituyen diagnóstico, tratamiento, opinión legal, recomendación financiera ni sustituyen a un profesional autorizado. No demores la búsqueda de ayuda cualificada por algo visto en One2OneLove." },
      { title: "11. Terapeutas, Coaches y Profesionales", content: "Los listados de terapeutas, consejeros, coaches, profesionales u otros proveedores son recursos salvo indicación expresa. Debes evaluar licencias, credenciales, experiencia, seguro, idoneidad, costo, disponibilidad y condiciones. One2OneLove no garantiza credenciales, conducta, servicios o resultados salvo declaración escrita expresa." },
      { title: "12. Ideas para Citas, Mapas y Seguridad Física", content: "Lugares, rutas, negocios, eventos, actividades, precios, horarios y accesibilidad pueden provenir de One2OneLove, usuarios o terceros y cambiar sin aviso. Debes verificar detalles con el proveedor y evaluar clima, transporte, capacidad física, salud, costo, vecindario y seguridad antes de participar. Usa direcciones y ubicación bajo tu propio criterio." },
      { title: "13. Emergencias, Abuso y Crisis", content: "One2OneLove no es un servicio de emergencia, crisis, violencia doméstica, prevención del suicidio, médico o policial. Si existe peligro inmediato, posible daño, abuso o emergencia médica o de salud mental, contacta los servicios de emergencia locales o un recurso de crisis cualificado. No dependas de One2OneLove, usuarios, IA o tiempos de respuesta para intervención urgente." },
      { title: "14. Privacidad", content: "La Política de Privacidad explica cómo recopilamos, usamos, divulgamos, conservamos y protegemos información. También eres responsable de respetar la privacidad de otras personas y obtener permiso antes de subir o compartir datos, imágenes, mensajes o contenido privado cuando corresponda." },
      { title: "15. Servicios de Pago, Suscripciones y Pruebas", content: "Si ofrecemos servicios pagados, precios, intervalos, pruebas, funciones incluidas, renovación y cancelación se mostrarán antes de la compra. Salvo indicación contraria, las suscripciones pueden renovarse automáticamente hasta cancelación conforme a los términos y la ley. Autorizas cargos aplicables y eres responsable de impuestos, tasas y datos de facturación. Reembolsos solo según condiciones de compra o la ley." },
      { title: "16. Servicios de Terceros", content: "One2OneLove puede enlazar o integrar sitios, mapas, redes sociales, pagos, negocios, profesionales, videos, artículos u otros servicios externos. No los controlamos ni somos responsables de su contenido, disponibilidad, seguridad, condiciones, privacidad, productos o conducta. Tu uso se rige por sus propias reglas." },
      { title: "17. Propiedad Intelectual de One2OneLove", content: "Nombre, logos, marca, diseño, software, código, gráficos, texto, interfaces, funciones y demás materiales propios o licenciados están protegidos. Salvo derechos expresamente concedidos, no se transfiere propiedad. No puedes copiar, modificar, distribuir, vender, realizar ingeniería inversa ni crear derivados no autorizados salvo permiso o ley aplicable." },
      { title: "18. Reclamos de Derechos", content: "Si crees que contenido infringe copyright, marca, privacidad, publicidad u otro derecho, escribe a legal@one2onelove.com con información suficiente para identificar contenido, derecho reclamado y contacto. Podemos pedir información adicional y retirar o restringir contenido cuando corresponda." },
      { title: "19. Moderación, Suspensión y Terminación", content: "Podemos investigar reportes, moderar, retirar o limitar contenido, restringir funciones, suspender cuentas o terminar acceso cuando razonablemente creamos que hay violación de Términos, riesgo de seguridad, fraude, abuso, exposición legal o uso indebido. Podemos conservar información relevante por seguridad, disputas, fraude o cumplimiento legal." },
      { title: "20. Disponibilidad y Cambios del Servicio", content: "Podemos añadir, modificar, probar, limitar, suspender o retirar funciones, contenido, precios, elegibilidad, integraciones o límites. Puede haber interrupciones por mantenimiento, problemas técnicos, terceros, seguridad o cambios de producto. No garantizamos acceso ininterrumpido, disponibilidad permanente, conservación de todo contenido ni ausencia de errores." },
      { title: "21. Descargos de Responsabilidad", content: "En la máxima medida permitida, One2OneLove se ofrece 'tal cual' y 'según disponibilidad', sin garantías expresas, implícitas o legales, incluidas comerciabilidad, idoneidad, título, no infracción, exactitud, fiabilidad, disponibilidad, seguridad o resultado de una relación. Algunas jurisdicciones no permiten ciertas exclusiones." },
      { title: "22. Limitación de Responsabilidad", content: "En la máxima medida legal, One2OneLove y sus propietarios, afiliados, personal, contratistas, licenciantes y proveedores no serán responsables de daños indirectos, incidentales, especiales, consecuentes, ejemplares o punitivos; pérdidas de beneficios, datos, reputación, oportunidades, relaciones o negocio; decisiones tomadas por contenido de la plataforma; conducta de usuarios o terceros; o eventos de servicios externos. Nada limita responsabilidad que legalmente no pueda limitarse." },
      { title: "23. Indemnización", content: "En la medida permitida por la ley, aceptas defender, indemnizar y mantener indemne a One2OneLove y sus propietarios, afiliados, personal, contratistas y proveedores frente a reclamaciones y costos razonables derivados de tu uso ilegal, tu contenido, violación de estos Términos o derechos de terceros, salvo donde la ley lo prohíba." },
      { title: "24. Ley Aplicable y Disputas", content: "Salvo que la ley de consumo aplicable exija otra cosa, estos Términos se rigen por las leyes del Estado de Texas, EE. UU., sin aplicar reglas de conflicto de leyes. Antes de presentar una reclamación formal, se recomienda contactar legal@one2onelove.com para intentar una solución informal. No se eliminan derechos que no puedan renunciarse legalmente." },
      { title: "25. Comunicaciones Electrónicas", content: "Al usar One2OneLove aceptas recibir avisos, divulgaciones, comunicaciones de cuenta, transacciones y otros mensajes de forma electrónica, incluido dentro del servicio o por email, cuando la ley lo permita. Debes mantener tus datos de contacto actualizados." },
      { title: "26. Cesión, Separabilidad, Renuncia y Fuerza Mayor", content: "No puedes ceder derechos u obligaciones sin nuestro consentimiento salvo donde la ley permita lo contrario. Podemos ceder estos Términos en una reorganización, financiación, fusión, adquisición, venta o transferencia. Si una cláusula es inaplicable, las demás continúan. No aplicar una cláusula no supone renuncia. No respondemos por retrasos o fallos causados por hechos fuera de control razonable, sujeto a la ley." },
      { title: "27. Cambios y Contacto", content: "Podemos modificar estos Términos cuando cambien el servicio, la ley o el negocio. Mostraremos la fecha actualizada y daremos aviso adicional cuando sea obligatorio. El uso continuado tras la entrada en vigor implica aceptación en la medida permitida. Asuntos legales: legal@one2onelove.com. Soporte general: support@one2onelove.com." }
    ]
  },
  fr: {
    title: "Conditions d'Utilisation", subtitle: "Règles et conditions d'utilisation de One2OneLove", back: "Retour", lastUpdated: "Dernière Mise à Jour : 12 Septembre 2026", translationNotice: "Si une traduction diffère de la version anglaise, la version anglaise prévaut dans la mesure permise par le droit applicable.", ownershipNotice: "La Plateforme One2One Love est détenue et exploitée par ERANT Property Services LLC (EPS LLC), sa société mère. Les présentes Conditions constituent un accord entre vous et ERANT Property Services LLC concernant votre utilisation de la Plateforme One2One Love. Les références à « One2OneLove », « nous », « notre » ou « nos » désignent ERANT Property Services LLC exploitant la Plateforme One2One Love, sauf indication contraire du contexte.",
    sections: [
      { title: "1. Acceptation des Conditions", content: "Ces Conditions régissent l'accès et l'utilisation des sites, applications, comptes, outils relationnels, communauté et chat, fonctions IA, Love Notes, quiz, idées de rendez-vous, étapes, souvenirs, ressources de soutien, annuaires professionnels ou de thérapeutes, abonnements et autres services One2OneLove. En créant un compte ou en utilisant le service, vous acceptez ces Conditions et la Politique de confidentialité." },
      { title: "2. Admissibilité et Âge", content: "Vous devez avoir au moins 13 ans. Si vous n'avez pas l'âge de la majorité là où vous vivez, vous ne pouvez utiliser le service que si la loi l'autorise et avec l'implication ou le consentement d'un parent ou tuteur lorsque nécessaire. Certaines fonctions peuvent être réservées aux adultes." },
      { title: "3. Comptes et Sécurité", content: "Vous devez fournir des informations exactes, les tenir raisonnablement à jour, protéger mot de passe et identifiants et assumer la responsabilité des activités du compte. Il est interdit d'usurper une identité, d'utiliser des informations sans autorisation, de vendre ou transférer un compte sans permission ou de contourner la sécurité. Signalez tout accès suspect." },
      { title: "4. Ce Qu'est One2OneLove — et Ce Qu'il N'est Pas", content: "One2OneLove est une plateforme de soutien relationnel offrant outils, communauté, éducation, réflexion, communication, souvenirs, objectifs et idées de rendez-vous. Ce n'est pas un service de rencontres ou de matchmaking et nous ne promettons aucun résultat relationnel ou personnel." },
      { title: "5. Utilisation Acceptable et Conduite", content: "Vous devez utiliser One2OneLove légalement et respectueusement. Sont interdits le harcèlement, les menaces, la traque, l'exploitation, la discrimination, la fraude, l'usurpation, les dommages intentionnels, le spam, les contacts répétés non souhaités, la promotion de violence ou d'activités illégales, les logiciels malveillants, la collecte non autorisée de données, l'atteinte à la sécurité et l'utilisation pour trafic, exploitation sexuelle, abus, coercition, extorsion ou autre activité illégale." },
      { title: "6. Contenu Utilisateur", content: "Vous conservez la propriété de vos contenus, sous réserve des droits nécessaires au fonctionnement du service. Vous êtes responsable des Love Notes, messages, publications, photos, souvenirs, avis, suggestions, profils, réponses aux quiz et autres contenus. Vous devez posséder les droits nécessaires et ne pas violer les droits légaux, de confidentialité, d'image, de propriété intellectuelle ou contractuels d'autrui." },
      { title: "7. Licence Nécessaire au Fonctionnement", content: "En soumettant du contenu, vous accordez à One2OneLove une licence non exclusive, mondiale et gratuite pour héberger, stocker, reproduire, traiter, transmettre, afficher et formater ce contenu uniquement dans la mesure raisonnablement nécessaire pour exploiter, sécuriser, améliorer et fournir le service, respecter la loi et exécuter les fonctions demandées. Elle prend fin après suppression des systèmes actifs, sauf conservation légitime." },
      { title: "8. Communauté, Chat et Communications", content: "La communauté et le chat servent à des échanges respectueux. Le contenu public ou partagé peut être visible à d'autres. Les messages directs sont destinés aux participants, mais aucun système en ligne ne garantit une confidentialité ou sécurité absolue. Nous pouvons conserver, examiner, limiter ou divulguer des communications pour exploiter le service, enquêter, répondre aux signalements, protéger la sécurité ou respecter la loi." },
      { title: "9. Fonctions Assistées par IA", content: "Certaines fonctions utilisent l'IA pour produire messages, idées, contenu éducatif, résumés ou réflexions. Les résultats peuvent être faux, incomplets, biaisés, dépassés ou inadaptés. Vous devez les vérifier avant de les utiliser, envoyer, publier ou suivre. L'IA ne constitue pas une garantie ni un conseil professionnel." },
      { title: "10. Aucun Conseil Professionnel", content: "Le contenu, les quiz, l'IA, les articles, les outils et discussions sont destinés à l'information générale et au soutien relationnel. Ils ne constituent ni diagnostic, ni traitement, ni avis juridique ou financier, ni remplacement d'un professionnel agréé. Ne retardez jamais une aide qualifiée à cause d'un contenu vu sur One2OneLove." },
      { title: "11. Thérapeutes, Coachs et Professionnels", content: "Les fiches de thérapeutes, conseillers, coachs, professionnels ou autres prestataires sont des ressources sauf mention expresse. Vous devez vérifier licences, qualifications, expérience, assurance, pertinence, coût, disponibilité et conditions. One2OneLove ne garantit pas qualifications, conduite, services ou résultats sauf déclaration écrite expresse." },
      { title: "12. Idées de Rendez-vous, Cartes et Sécurité", content: "Lieux, itinéraires, entreprises, événements, activités, prix, horaires et accessibilité peuvent provenir de One2OneLove, d'utilisateurs ou de tiers et changer sans préavis. Vérifiez les informations directement et évaluez météo, transport, santé, capacité physique, coût, environnement et sécurité avant de participer. Utilisez les itinéraires selon votre propre jugement." },
      { title: "13. Urgences, Abus et Crises", content: "One2OneLove n'est pas un service d'urgence, de crise, de violence domestique, de prévention du suicide, médical ou de police. En cas de danger immédiat, d'abus ou d'urgence médicale ou psychologique, contactez les services d'urgence locaux ou une ressource de crise qualifiée. Ne dépendez pas de One2OneLove, des utilisateurs, de l'IA ou des délais de réponse pour une intervention urgente." },
      { title: "14. Confidentialité", content: "La Politique de confidentialité explique la collecte, l'utilisation, la divulgation, la conservation et la protection des données. Vous devez aussi respecter la vie privée d'autrui et obtenir les autorisations nécessaires avant de publier des données, images, messages ou contenus privés appartenant à une autre personne." },
      { title: "15. Services Payants, Abonnements et Essais", content: "Si des services payants sont proposés, prix, périodicité, conditions d'essai, fonctions incluses, renouvellement et annulation seront affichés avant achat. Sauf indication contraire, les abonnements peuvent se renouveler automatiquement jusqu'à annulation. Vous autorisez les frais applicables et êtes responsable des taxes, frais et informations de facturation. Les remboursements suivent les conditions d'achat ou la loi." },
      { title: "16. Services Tiers", content: "One2OneLove peut lier ou intégrer sites, cartes, réseaux sociaux, paiements, entreprises, professionnels, vidéos, articles ou autres services tiers. Nous ne les contrôlons pas et ne sommes pas responsables de leur contenu, disponibilité, sécurité, conditions, confidentialité, produits ou conduite. Leur utilisation est régie par leurs propres règles." },
      { title: "17. Propriété Intellectuelle de One2OneLove", content: "Le nom, les logos, la marque, le design, le logiciel, le code, les graphiques, textes, interfaces, fonctions et autres éléments détenus ou licenciés sont protégés. Aucun droit de propriété n'est transféré sauf autorisation expresse. Copie, modification, distribution, vente, ingénierie inverse et œuvres dérivées non autorisées sont interdites sauf droit applicable ou permission écrite." },
      { title: "18. Plaintes Relatives aux Droits", content: "Si vous pensez qu'un contenu porte atteinte à un droit d'auteur, une marque, la vie privée, le droit à l'image ou un autre droit, contactez legal@one2onelove.com avec les informations permettant d'identifier le contenu, le droit invoqué et vos coordonnées. Nous pouvons demander des informations supplémentaires et retirer ou limiter le contenu si nécessaire." },
      { title: "19. Modération, Suspension et Résiliation", content: "Nous pouvons enquêter, modérer, retirer ou limiter du contenu, restreindre des fonctions, suspendre un compte ou mettre fin à l'accès en cas de violation présumée, risque de sécurité, fraude, abus, exposition juridique ou mauvaise utilisation. Nous pouvons conserver des informations pertinentes pour la sécurité, les litiges, la fraude ou la conformité." },
      { title: "20. Disponibilité et Modifications du Service", content: "Nous pouvons ajouter, modifier, tester, limiter, suspendre ou retirer fonctions, contenu, prix, admissibilité, intégrations ou limites. Des interruptions peuvent survenir pour maintenance, problèmes techniques, pannes tierces, sécurité ou évolution du produit. Nous ne garantissons pas un accès continu, la disponibilité permanente d'une fonction, la conservation de tout contenu ou l'absence d'erreurs." },
      { title: "21. Exclusions de Garantie", content: "Dans la mesure maximale permise par la loi, One2OneLove est fourni 'tel quel' et 'selon disponibilité', sans garantie expresse, implicite ou légale, notamment de qualité marchande, d'adaptation, de titre, de non-contrefaçon, d'exactitude, de fiabilité, de disponibilité, de sécurité ou de résultat relationnel. Certaines juridictions limitent ces exclusions." },
      { title: "22. Limitation de Responsabilité", content: "Dans la mesure maximale permise, One2OneLove et ses propriétaires, affiliés, employés, sous-traitants, concédants et prestataires ne sont pas responsables des dommages indirects, accessoires, spéciaux, consécutifs, exemplaires ou punitifs; pertes de profits, données, réputation, opportunités, relations ou activités; décisions fondées sur le contenu; conduite des utilisateurs ou tiers; ou événements liés à des services tiers. Rien ne limite une responsabilité qui ne peut légalement l'être." },
      { title: "23. Indemnisation", content: "Dans la mesure permise par la loi, vous acceptez de défendre et d'indemniser One2OneLove et ses propriétaires, affiliés, employés, sous-traitants et prestataires contre les réclamations et coûts raisonnables résultant de votre utilisation illégale, de votre contenu, d'une violation de ces Conditions ou des droits d'autrui, sauf interdiction légale." },
      { title: "24. Droit Applicable et Litiges", content: "Sauf si le droit impératif de la consommation exige autrement, ces Conditions sont régies par les lois de l'État du Texas, États-Unis, sans règles de conflit de lois. Avant une réclamation formelle, vous êtes invité à contacter legal@one2onelove.com afin de rechercher une solution amiable. Aucun droit impératif n'est supprimé." },
      { title: "25. Communications Électroniques", content: "En utilisant One2OneLove, vous acceptez de recevoir avis, informations, messages de compte, transactions et autres communications par voie électronique, dans le service ou par e-mail, lorsque la loi le permet. Vous devez maintenir vos coordonnées à jour." },
      { title: "26. Cession, Divisibilité, Renonciation et Force Majeure", content: "Vous ne pouvez pas céder vos droits ou obligations sans notre accord sauf si la loi permet autrement. Nous pouvons céder ces Conditions lors d'une réorganisation, d'un financement, d'une fusion, acquisition, vente ou transfert. Si une clause est inapplicable, les autres restent en vigueur. Le défaut d'application n'est pas une renonciation. Nous ne sommes pas responsables des retards dus à des événements hors de notre contrôle raisonnable, sous réserve de la loi." },
      { title: "27. Modifications et Contact", content: "Nous pouvons modifier ces Conditions avec l'évolution du service, du droit ou de l'activité. La date mise à jour sera affichée et un avis supplémentaire sera donné si nécessaire. L'utilisation continue après prise d'effet vaut acceptation dans la mesure permise. Juridique : legal@one2onelove.com. Assistance : support@one2onelove.com." }
    ]
  },
  it: {
    title: "Termini di Servizio", subtitle: "Regole e condizioni per l'uso di One2OneLove", back: "Indietro", lastUpdated: "Ultimo Aggiornamento: 12 Settembre 2026", translationNotice: "Se una traduzione differisce dalla versione inglese, la versione inglese prevale nella misura consentita dalla legge applicabile.", ownershipNotice: "La Piattaforma One2One Love è di proprietà ed è gestita da ERANT Property Services LLC (EPS LLC), la sua società madre. I presenti Termini costituiscono un accordo tra te ed ERANT Property Services LLC relativo all'uso della Piattaforma One2One Love. I riferimenti a ‘One2OneLove’, ‘noi’, ‘ci’ o ‘nostro’ indicano ERANT Property Services LLC che gestisce la Piattaforma One2One Love, salvo che il contesto richieda diversamente.",
    sections: [
      { title: "1. Accettazione dei Termini", content: "Questi Termini regolano accesso e uso di siti, applicazioni, account, strumenti relazionali, community e chat, funzioni AI, Love Notes, quiz, idee per appuntamenti, traguardi, ricordi, risorse di supporto, directory professionali o di terapeuti, abbonamenti e altri servizi One2OneLove. Creando un account o usando il servizio accetti questi Termini e l'Informativa sulla Privacy." },
      { title: "2. Requisiti ed Età", content: "Devi avere almeno 13 anni. Se non hai raggiunto la maggiore età dove vivi, puoi usare il servizio solo se consentito dalla legge e con il coinvolgimento o consenso di un genitore o tutore quando richiesto. Alcune funzioni possono essere riservate agli adulti." },
      { title: "3. Account e Sicurezza", content: "Devi fornire informazioni accurate, mantenerle ragionevolmente aggiornate, proteggere password e credenziali e assumerti la responsabilità delle attività dell'account. Non puoi impersonare, usare dati senza autorizzazione, vendere o trasferire account senza permesso o aggirare sicurezza e restrizioni. Segnala accessi sospetti." },
      { title: "4. Cos'è One2OneLove — e Cosa Non È", content: "One2OneLove è una piattaforma di supporto relazionale con strumenti, community, educazione, riflessione, comunicazione, ricordi, obiettivi e idee per appuntamenti. Non è un servizio di dating o matchmaking e non promette partner o risultati relazionali specifici." },
      { title: "5. Uso Accettabile e Condotta", content: "Devi usare One2OneLove legalmente e rispettosamente. Sono vietati molestie, minacce, stalking, sfruttamento, discriminazione, frode, impersonificazione, danno intenzionale, spam, contatti ripetuti indesiderati, promozione di violenza o reati, malware, raccolta non autorizzata di dati, interferenze con sicurezza e uso per tratta, sfruttamento sessuale, abuso, coercizione, estorsione o altre attività illegali." },
      { title: "6. Contenuti dell'Utente", content: "Mantieni la proprietà dei contenuti creati, salvo i diritti necessari al funzionamento. Sei responsabile di Love Notes, messaggi, post, foto, ricordi, recensioni, suggerimenti, profilo, quiz e altri contenuti. Devi avere diritti e permessi necessari e non violare diritti legali, privacy, immagine, proprietà intellettuale o contratti altrui." },
      { title: "7. Licenza per Gestire il Servizio", content: "Inviando contenuti concedi a One2OneLove una licenza non esclusiva, mondiale e gratuita per ospitare, archiviare, riprodurre, trattare, trasmettere, mostrare e formattare tali contenuti solo nella misura ragionevolmente necessaria per gestire, proteggere, migliorare e fornire il servizio, rispettare la legge ed eseguire la funzione richiesta. La licenza termina dopo la rimozione dai sistemi attivi salvo conservazione legittima." },
      { title: "8. Community, Chat e Comunicazioni", content: "Community e chat sono per comunicazioni rispettose. I contenuti pubblici o condivisi possono essere visibili ad altri. I messaggi diretti sono destinati ai partecipanti, ma nessun sistema online garantisce privacy o sicurezza assolute. Possiamo conservare, esaminare, limitare o divulgare comunicazioni per gestire il servizio, indagare, rispondere a segnalazioni, proteggere la sicurezza o rispettare la legge." },
      { title: "9. Funzioni Assistite dall'AI", content: "Alcune funzioni usano AI per generare messaggi, idee, contenuti educativi, riassunti o riflessioni. L'output può essere errato, incompleto, distorto, obsoleto o inadatto. Devi verificarlo prima di usarlo, inviarlo, pubblicarlo o seguirlo. L'AI non è una garanzia né una consulenza professionale." },
      { title: "10. Nessuna Consulenza Professionale", content: "Contenuti, quiz, AI, articoli, strumenti e discussioni servono a informazione generale e supporto relazionale. Non sono diagnosi, trattamento, parere legale, consiglio finanziario o sostituto di un professionista autorizzato. Non ritardare l'assistenza qualificata a causa di contenuti visti su One2OneLove." },
      { title: "11. Terapeuti, Coach e Professionisti", content: "Gli elenchi di terapeuti, counselor, coach, professionisti o altri fornitori sono risorse salvo indicazione espressa. Devi verificare licenze, qualifiche, esperienza, assicurazione, idoneità, costi, disponibilità e condizioni. One2OneLove non garantisce credenziali, condotta, servizi o risultati salvo dichiarazione scritta espressa." },
      { title: "12. Idee per Appuntamenti, Mappe e Sicurezza", content: "Luoghi, percorsi, attività, prezzi, orari e accessibilità possono provenire da One2OneLove, utenti o terzi e cambiare senza preavviso. Verifica i dettagli direttamente e valuta meteo, trasporti, salute, capacità fisica, costi, zona e sicurezza prima di partecipare. Usa indicazioni e posizione secondo il tuo giudizio." },
      { title: "13. Emergenze, Abusi e Crisi", content: "One2OneLove non è un servizio di emergenza, crisi, violenza domestica, prevenzione del suicidio, medico o di polizia. In caso di pericolo immediato, abuso o emergenza medica o psicologica, contatta i servizi di emergenza locali o una risorsa di crisi qualificata. Non affidarti a One2OneLove, utenti, AI o tempi di risposta per interventi urgenti." },
      { title: "14. Privacy", content: "L'Informativa sulla Privacy descrive raccolta, uso, divulgazione, conservazione e protezione dei dati. Devi anche rispettare la privacy degli altri e ottenere autorizzazione quando necessaria prima di caricare o condividere dati, immagini, messaggi o contenuti privati di un'altra persona." },
      { title: "15. Servizi a Pagamento, Abbonamenti e Prove", content: "Se offriamo servizi a pagamento, prezzi, intervalli, prove, funzioni incluse, rinnovo e cancellazione saranno mostrati prima dell'acquisto. Salvo diversa indicazione, gli abbonamenti possono rinnovarsi automaticamente fino alla cancellazione. Autorizzi gli addebiti e sei responsabile di imposte, commissioni e dati di fatturazione. Rimborsi solo secondo i termini di acquisto o legge." },
      { title: "16. Servizi Terzi", content: "One2OneLove può collegare o integrare siti, mappe, social, pagamenti, attività, professionisti, video, articoli o altri servizi terzi. Non li controlliamo e non siamo responsabili di contenuti, disponibilità, sicurezza, termini, privacy, prodotti o condotta. L'uso è regolato dalle loro condizioni." },
      { title: "17. Proprietà Intellettuale di One2OneLove", content: "Nome, loghi, marchio, design, software, codice, grafica, testi, interfacce, funzioni e altri materiali di proprietà o in licenza sono protetti. Nessun diritto di proprietà viene trasferito salvo concessione espressa. Sono vietati copia, modifica, distribuzione, vendita, reverse engineering o opere derivate non autorizzate salvo legge o permesso scritto." },
      { title: "18. Reclami sui Diritti", content: "Se ritieni che un contenuto violi copyright, marchio, privacy, diritto all'immagine o altro diritto, contatta legal@one2onelove.com con informazioni sufficienti per identificare contenuto, diritto rivendicato e contatto. Possiamo chiedere ulteriori dati e rimuovere o limitare contenuti quando appropriato." },
      { title: "19. Moderazione, Sospensione e Chiusura", content: "Possiamo indagare segnalazioni, moderare, rimuovere o limitare contenuti, restringere funzioni, sospendere account o terminare accesso in caso di presunta violazione, rischio di sicurezza, frode, abuso, esposizione legale o uso improprio. Possiamo conservare informazioni rilevanti per sicurezza, controversie, frode o conformità." },
      { title: "20. Disponibilità e Modifiche", content: "Possiamo aggiungere, modificare, testare, limitare, sospendere o ritirare funzioni, contenuti, prezzi, requisiti, integrazioni o limiti. Possono verificarsi interruzioni per manutenzione, problemi tecnici, terzi, sicurezza o modifiche del prodotto. Non garantiamo accesso continuo, disponibilità permanente, conservazione di tutti i contenuti o assenza di errori." },
      { title: "21. Esclusioni di Garanzia", content: "Nella misura massima consentita, One2OneLove è fornito 'così com'è' e 'come disponibile', senza garanzie espresse, implicite o legali, incluse commerciabilità, idoneità, titolo, non violazione, accuratezza, affidabilità, disponibilità, sicurezza o risultato relazionale. Alcune giurisdizioni limitano tali esclusioni." },
      { title: "22. Limitazione di Responsabilità", content: "Nella misura massima consentita, One2OneLove e proprietari, affiliati, personale, appaltatori, licenzianti e fornitori non rispondono di danni indiretti, incidentali, speciali, consequenziali, esemplari o punitivi; perdita di profitti, dati, reputazione, opportunità, relazioni o attività; decisioni basate sui contenuti; condotta di utenti o terzi; o eventi di servizi esterni. Nulla limita responsabilità non legalmente limitabile." },
      { title: "23. Indennizzo", content: "Nella misura consentita, accetti di difendere e tenere indenne One2OneLove e proprietari, affiliati, personale, appaltatori e fornitori da reclami e costi ragionevoli derivanti da uso illecito, contenuti, violazione di questi Termini o diritti altrui, salvo dove vietato dalla legge." },
      { title: "24. Legge Applicabile e Controversie", content: "Salvo norme imperative dei consumatori, questi Termini sono regolati dalle leggi dello Stato del Texas, USA, senza norme sui conflitti di legge. Prima di un reclamo formale sei invitato a contattare legal@one2onelove.com per tentare una soluzione informale. Nessun diritto inderogabile viene eliminato." },
      { title: "25. Comunicazioni Elettroniche", content: "Usando One2OneLove accetti che avvisi, informazioni, messaggi di account, transazioni e altre comunicazioni possano essere fornite elettronicamente, nel servizio o via email, quando consentito. Devi mantenere aggiornati i contatti." },
      { title: "26. Cessione, Separabilità, Rinuncia e Forza Maggiore", content: "Non puoi cedere diritti o obblighi senza consenso salvo dove la legge consenta diversamente. Possiamo cedere questi Termini in riorganizzazione, finanziamento, fusione, acquisizione, vendita o trasferimento. Se una clausola è inapplicabile, le altre restano valide. La mancata applicazione non è rinuncia. Non rispondiamo di ritardi dovuti a eventi fuori dal ragionevole controllo, nel rispetto della legge." },
      { title: "27. Modifiche e Contatti", content: "Possiamo modificare questi Termini con l'evoluzione del servizio, della legge o dell'attività. Mostreremo la data aggiornata e forniremo avvisi aggiuntivi quando richiesto. L'uso continuato dopo l'efficacia vale come accettazione nei limiti di legge. Legale: legal@one2onelove.com. Supporto: support@one2onelove.com." }
    ]
  },
  de: {
    title: "Nutzungsbedingungen", subtitle: "Regeln und Bedingungen für die Nutzung von One2OneLove", back: "Zurück", lastUpdated: "Letzte Aktualisierung: 12. September 2026", translationNotice: "Wenn eine Übersetzung von der englischen Fassung abweicht, gilt die englische Fassung, soweit dies nach geltendem Recht zulässig ist.", ownershipNotice: "Die One2One Love Plattform befindet sich im Eigentum von ERANT Property Services LLC (EPS LLC), ihrer Muttergesellschaft, und wird von ihr betrieben. Diese Bedingungen sind eine Vereinbarung zwischen Ihnen und ERANT Property Services LLC in Bezug auf Ihre Nutzung der One2One Love Plattform. ‘One2OneLove’, ‘wir’, ‘uns’ und ‘unser’ beziehen sich auf ERANT Property Services LLC als Betreiberin der One2One Love Plattform, sofern der Kontext nichts anderes verlangt.",
    sections: [
      { title: "1. Zustimmung zu Diesen Bedingungen", content: "Diese Bedingungen regeln Zugang und Nutzung von Websites, Anwendungen, Konten, Beziehungstools, Community und Chat, KI-Funktionen, Love Notes, Quiz, Date-Ideen, Meilensteinen, Erinnerungen, Hilfsressourcen, Verzeichnissen von Fachleuten oder Therapeuten, Abonnements und anderen One2OneLove-Diensten. Durch Kontoerstellung oder Nutzung stimmen Sie diesen Bedingungen und der Datenschutzrichtlinie zu." },
      { title: "2. Teilnahmeberechtigung und Alter", content: "Sie müssen mindestens 13 Jahre alt sein. Wenn Sie an Ihrem Wohnort noch nicht volljährig sind, dürfen Sie den Dienst nur nutzen, wenn dies rechtlich zulässig ist und gegebenenfalls mit Beteiligung oder Zustimmung eines Elternteils oder Vormunds. Bestimmte Funktionen können Erwachsenen vorbehalten sein." },
      { title: "3. Konten und Sicherheit", content: "Sie müssen korrekte Informationen angeben, diese angemessen aktuell halten, Passwort und Zugangsdaten schützen und Verantwortung für Kontoaktivitäten übernehmen. Identitätsmissbrauch, unbefugte Datennutzung, Verkauf oder Übertragung von Konten ohne Erlaubnis sowie Umgehung von Sicherheitsmaßnahmen sind untersagt. Melden Sie verdächtige Zugriffe unverzüglich." },
      { title: "4. Was One2OneLove Ist — und Was Nicht", content: "One2OneLove ist eine Beziehungsplattform mit Tools, Community, Bildung, Reflexion, Kommunikation, Erinnerungen, Zielen und Date-Ideen. Es ist kein Dating- oder Matchmaking-Dienst und verspricht keine Partnervermittlung oder bestimmten Beziehungsergebnisse." },
      { title: "5. Zulässige Nutzung und Verhalten", content: "One2OneLove muss rechtmäßig und respektvoll genutzt werden. Untersagt sind Belästigung, Drohungen, Stalking, Ausbeutung, Diskriminierung, Betrug, Identitätsmissbrauch, absichtliche Schädigung, Spam, wiederholter unerwünschter Kontakt, Förderung von Gewalt oder Straftaten, Malware, unbefugte Datenerhebung, Sicherheitsstörungen sowie Nutzung für Menschenhandel, sexuelle Ausbeutung, Missbrauch, Zwang, Erpressung oder andere illegale Handlungen." },
      { title: "6. Nutzerinhalte", content: "Sie behalten das Eigentum an Ihren Inhalten, vorbehaltlich der für den Betrieb erforderlichen Rechte. Sie sind verantwortlich für Love Notes, Nachrichten, Beiträge, Fotos, Erinnerungen, Bewertungen, Vorschläge, Profilangaben, Quizantworten und andere Inhalte. Sie müssen über die notwendigen Rechte verfügen und dürfen keine gesetzlichen, Datenschutz-, Persönlichkeits-, Urheber-, Marken- oder Vertragsrechte anderer verletzen." },
      { title: "7. Lizenz für den Betrieb", content: "Mit dem Einreichen von Inhalten gewähren Sie One2OneLove eine nicht ausschließliche, weltweite, gebührenfreie Lizenz zum Hosten, Speichern, Reproduzieren, Verarbeiten, Übertragen, Anzeigen und Formatieren, soweit dies vernünftigerweise nötig ist, um den Dienst zu betreiben, zu sichern, zu verbessern und bereitzustellen, Gesetze einzuhalten und gewünschte Funktionen auszuführen. Die Lizenz endet nach Löschung aus aktiven Systemen, außer bei legitimer Aufbewahrung." },
      { title: "8. Community, Chat und Kommunikation", content: "Community und Chat dienen respektvoller Kommunikation. Öffentliche oder geteilte Inhalte können für andere sichtbar sein. Direktnachrichten sind für Teilnehmer bestimmt, aber kein Onlinesystem garantiert absolute Privatheit oder Sicherheit. Wir können Kommunikation speichern, prüfen, beschränken oder offenlegen, wenn dies für Betrieb, Untersuchungen, Meldungen, Sicherheit oder Rechtspflichten erforderlich ist." },
      { title: "9. KI-Gestützte Funktionen", content: "Einige Funktionen verwenden KI für Nachrichten, Ideen, Bildungsinhalte, Zusammenfassungen oder Reflexionen. Ergebnisse können falsch, unvollständig, voreingenommen, veraltet oder ungeeignet sein. Sie müssen sie prüfen, bevor Sie sie verwenden, senden, veröffentlichen oder befolgen. KI ist keine Tatsachengarantie oder professionelle Beratung." },
      { title: "10. Keine Professionelle Beratung", content: "Inhalte, Quiz, KI, Artikel, Tools und Diskussionen dienen allgemeiner Information und Beziehungsunterstützung. Sie sind keine Diagnose, Behandlung, Rechtsmeinung, Finanzempfehlung oder Ersatz für zugelassene Fachleute. Verzögern Sie keine qualifizierte Hilfe aufgrund von Inhalten auf One2OneLove." },
      { title: "11. Therapeuten, Coaches und Fachleute", content: "Einträge von Therapeuten, Beratern, Coaches, Fachleuten oder anderen Anbietern sind Ressourcen, sofern nicht ausdrücklich anders angegeben. Sie müssen Lizenzen, Qualifikationen, Erfahrung, Versicherung, Eignung, Kosten, Verfügbarkeit und Bedingungen selbst prüfen. One2OneLove garantiert keine Qualifikation, Leistung oder Ergebnisse, außer ausdrücklich schriftlich erklärt." },
      { title: "12. Date-Ideen, Karten und Sicherheit", content: "Orte, Routen, Unternehmen, Veranstaltungen, Aktivitäten, Preise, Öffnungszeiten und Barrierefreiheit können von One2OneLove, Nutzern oder Dritten stammen und sich ändern. Prüfen Sie Angaben direkt und berücksichtigen Sie Wetter, Transport, Gesundheit, körperliche Fähigkeiten, Kosten, Umgebung und Sicherheit. Nutzen Sie Wegbeschreibungen nach eigenem Urteil." },
      { title: "13. Notfälle, Missbrauch und Krisen", content: "One2OneLove ist kein Notfall-, Krisen-, häusliche-Gewalt-, Suizidpräventions-, medizinischer oder Polizeidienst. Bei unmittelbarer Gefahr, Missbrauch oder medizinischem bzw. psychischem Notfall wenden Sie sich an örtliche Notdienste oder qualifizierte Krisenstellen. Verlassen Sie sich für dringende Interventionen nicht auf One2OneLove, Nutzer, KI oder Reaktionszeiten." },
      { title: "14. Datenschutz", content: "Die Datenschutzrichtlinie beschreibt Erhebung, Nutzung, Offenlegung, Speicherung und Schutz von Informationen. Sie müssen außerdem die Privatsphäre anderer respektieren und erforderliche Erlaubnisse einholen, bevor Sie deren Daten, Bilder, Nachrichten oder private Inhalte hochladen oder teilen." },
      { title: "15. Kostenpflichtige Dienste, Abonnements und Testphasen", content: "Bei kostenpflichtigen Diensten werden Preise, Abrechnungsintervalle, Testbedingungen, enthaltene Funktionen, Verlängerung und Kündigung vor dem Kauf angezeigt. Soweit nicht anders angegeben, können Abonnements sich bis zur Kündigung automatisch verlängern. Sie autorisieren anfallende Gebühren und sind für Steuern, Entgelte und korrekte Abrechnungsdaten verantwortlich. Erstattungen erfolgen nur nach Kaufbedingungen oder Gesetz." },
      { title: "16. Dienste Dritter", content: "One2OneLove kann Websites, Karten, soziale Netzwerke, Zahlungsanbieter, Unternehmen, Fachleute, Videos, Artikel oder andere Drittservices verlinken oder integrieren. Wir kontrollieren diese nicht und sind nicht verantwortlich für Inhalte, Verfügbarkeit, Sicherheit, Bedingungen, Datenschutz, Produkte oder Verhalten. Ihre Nutzung richtet sich nach den Regeln des Dritten." },
      { title: "17. Geistiges Eigentum von One2OneLove", content: "Name, Logos, Marke, Design, Software, Code, Grafiken, Texte, Schnittstellen, Funktionen und andere eigene oder lizenzierte Materialien sind geschützt. Eigentumsrechte werden nur ausdrücklich übertragen. Unbefugtes Kopieren, Ändern, Verteilen, Verkaufen, Reverse Engineering oder Erstellen abgeleiteter Werke ist untersagt, soweit nicht gesetzlich erlaubt oder schriftlich genehmigt." },
      { title: "18. Rechtebeschwerden", content: "Wenn Sie glauben, dass Inhalte Urheberrecht, Marke, Datenschutz, Persönlichkeitsrecht oder andere Rechte verletzen, kontaktieren Sie legal@one2onelove.com mit ausreichenden Angaben zu Inhalt, geltend gemachtem Recht und Kontaktmöglichkeit. Wir können weitere Informationen anfordern und Inhalte gegebenenfalls entfernen oder beschränken." },
      { title: "19. Moderation, Sperrung und Beendigung", content: "Wir können Meldungen untersuchen, Inhalte moderieren, entfernen oder beschränken, Funktionen einschränken, Konten sperren oder Zugang beenden, wenn wir vernünftigerweise einen Verstoß, ein Sicherheitsrisiko, Betrug, Missbrauch, rechtliches Risiko oder Fehlgebrauch annehmen. Relevante Informationen können für Sicherheit, Streitfälle, Betrug oder Compliance aufbewahrt werden." },
      { title: "20. Verfügbarkeit und Änderungen", content: "Wir können Funktionen, Inhalte, Preise, Voraussetzungen, Integrationen oder Grenzen hinzufügen, ändern, testen, beschränken, aussetzen oder einstellen. Unterbrechungen können durch Wartung, Technik, Drittanbieter, Sicherheit oder Produktänderungen entstehen. Wir garantieren keinen ununterbrochenen Zugang, dauerhafte Funktionsverfügbarkeit, Erhalt aller Inhalte oder Fehlerfreiheit." },
      { title: "21. Gewährleistungsausschlüsse", content: "Soweit gesetzlich zulässig, wird One2OneLove 'wie besehen' und 'wie verfügbar' ohne ausdrückliche, stillschweigende oder gesetzliche Gewährleistungen bereitgestellt, einschließlich Marktgängigkeit, Eignung, Rechtsmängelfreiheit, Nichtverletzung, Genauigkeit, Zuverlässigkeit, Verfügbarkeit, Sicherheit oder Beziehungsergebnis. Manche Rechtsordnungen beschränken solche Ausschlüsse." },
      { title: "22. Haftungsbeschränkung", content: "Soweit gesetzlich zulässig, haften One2OneLove und Eigentümer, verbundene Unternehmen, Mitarbeiter, Auftragnehmer, Lizenzgeber und Anbieter nicht für indirekte, zufällige, besondere, Folge-, exemplarische oder Strafschäden; Verlust von Gewinn, Daten, Ruf, Chancen, Beziehungen oder Geschäft; Entscheidungen aufgrund von Plattforminhalten; Verhalten von Nutzern oder Dritten; oder Ereignisse durch Drittservices. Unbeschränkbare Haftung bleibt unberührt." },
      { title: "23. Freistellung", content: "Soweit gesetzlich zulässig, erklären Sie sich bereit, One2OneLove und Eigentümer, verbundene Unternehmen, Mitarbeiter, Auftragnehmer und Anbieter von Ansprüchen und angemessenen Kosten freizustellen, die aus rechtswidriger Nutzung, Ihren Inhalten, einem Verstoß gegen diese Bedingungen oder Rechten anderer entstehen, soweit dies nicht gesetzlich ausgeschlossen ist." },
      { title: "24. Anwendbares Recht und Streitigkeiten", content: "Soweit zwingendes Verbraucherschutzrecht nichts anderes verlangt, gelten die Gesetze des Staates Texas, USA, ohne Kollisionsrecht. Vor einer formellen Klage werden Sie gebeten, legal@one2onelove.com zu kontaktieren, um eine informelle Lösung zu versuchen. Unverzichtbare gesetzliche Rechte bleiben bestehen." },
      { title: "25. Elektronische Kommunikation", content: "Durch die Nutzung stimmen Sie zu, dass Hinweise, Offenlegungen, Kontonachrichten, Transaktionsmitteilungen und andere Kommunikation elektronisch, im Dienst oder per E-Mail, bereitgestellt werden können, soweit gesetzlich zulässig. Halten Sie Ihre Kontaktdaten aktuell." },
      { title: "26. Abtretung, Teilunwirksamkeit, Verzicht und Höhere Gewalt", content: "Sie dürfen Rechte oder Pflichten ohne unsere Zustimmung nicht abtreten, sofern das Gesetz nichts anderes erlaubt. Wir können diese Bedingungen bei Reorganisation, Finanzierung, Fusion, Übernahme, Verkauf oder Übertragung abtreten. Ist eine Klausel unwirksam, bleiben die übrigen bestehen. Nichtdurchsetzung ist kein Verzicht. Für Verzögerungen durch Ereignisse außerhalb angemessener Kontrolle haften wir vorbehaltlich geltenden Rechts nicht." },
      { title: "27. Änderungen und Kontakt", content: "Wir können diese Bedingungen bei Änderungen von Dienst, Recht oder Geschäft anpassen. Das Aktualisierungsdatum wird angezeigt und zusätzliche Hinweise erfolgen, wenn erforderlich. Fortgesetzte Nutzung nach Inkrafttreten gilt soweit zulässig als Zustimmung. Recht: legal@one2onelove.com. Support: support@one2onelove.com." }
    ]
  }
};

export default function TermsOfService() {
  const { currentLanguage } = useLanguage();
  const t = translations[currentLanguage] || translations.en;

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50">
      <div className="max-w-5xl mx-auto px-4 py-12">
        <div className="mb-6">
          <Link to={createPageUrl("Home")} className="inline-flex items-center px-4 py-2 text-gray-600 hover:text-blue-600 hover:bg-blue-50 rounded-xl transition-all">
            <ArrowLeft size={20} className="mr-2" />
            {t.back}
          </Link>
        </div>

        <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-20 h-20 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full mb-6 shadow-xl">
            <FileText className="w-10 h-10 text-white" />
          </div>
          <h1 className="text-5xl font-bold text-gray-900 mb-4">{t.title}</h1>
          <p className="text-xl text-gray-600 max-w-4xl mx-auto">{t.subtitle}</p>
          <p className="text-sm text-gray-500 mt-4">{t.lastUpdated}</p>
          {currentLanguage !== "en" && <p className="text-sm text-amber-800 bg-amber-50 border border-amber-200 rounded-xl p-3 mt-5 max-w-3xl mx-auto">{t.translationNotice}</p>}
          <p className="text-sm text-slate-700 bg-white/80 border border-blue-200 rounded-xl p-4 mt-5 max-w-4xl mx-auto shadow-sm">{t.ownershipNotice}</p>
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
          <Card className="shadow-2xl">
            <CardContent className="p-8 md:p-10">
              <div className="prose prose-lg max-w-none">
                {t.sections.map((section, index) => (
                  <div key={index} className="mb-9">
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">{section.title}</h2>
                    <p className="text-gray-700 leading-relaxed">{section.content}</p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
}
