// @ts-nocheck
import { Client } from 'pg';
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H}),fail=(m,s=400,c='bad_request')=>json({ok:false,error:{code:c,message:m}},s);
async function withDb(env,fn){const c=new Client({connectionString:env.HYPERDRIVE.connectionString});await c.connect();try{return await fn(c)}finally{await c.end()}}
async function session(req,env){const cookie=req.headers.get('cookie');if(!cookie)return null;const r=await fetch(env.NEON_AUTH_BASE_URL.replace(/\/$/,'')+'/get-session',{headers:{cookie,accept:'application/json'}});if(!r.ok)return null;const p=await r.json().catch(()=>null),u=p?.user??p?.data?.user,s=p?.session??p?.data?.session;return u?.id&&u?.emailVerified===true&&s?u:null}
async function stripe(env,method,path,params=null){if(!env.STRIPE_SECRET_KEY)throw Object.assign(new Error('Billing is not configured.'),{status:503});const h={authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,accept:'application/json'};let body;if(params){h['content-type']='application/x-www-form-urlencoded';body=params}const r=await fetch('https://api.stripe.com/v1'+path,{method,headers:h,body});const p=await r.json().catch(()=>null);if(!r.ok)throw Object.assign(new Error(p?.error?.message||'Stripe request failed.'),{status:502});return p}
export async function foundingStatus(c,userId){const mine=await c.query('SELECT * FROM public.founding_members WHERE user_id=$1::uuid',[userId]),count=await c.query('SELECT count(*)::int AS n FROM public.founding_members'),n=count.rows[0]?.n||0;return {member:mine.rows[0]||null,claimed:n,remaining:Math.max(0,200-n)}}
export async function claimFoundingMember(c,userId,subscriptionId){await c.query('BEGIN');try{const old=await c.query('SELECT * FROM public.founding_members WHERE user_id=$1::uuid FOR UPDATE',[userId]);if(old.rows[0]){await c.query('COMMIT');return old.rows[0]}let n;try{n=Number((await c.query("SELECT nextval('public.o2ol_founding_member_number_seq') AS n")).rows[0].n)}catch(e){if(String(e?.message||'').includes('maximum value'))throw Object.assign(new Error('Founding Member enrollment is full.'),{status:409,code:'founding_full'});throw e}if(n>200)throw Object.assign(new Error('Founding Member enrollment is full.'),{status:409,code:'founding_full'});const first=n<=100,plan=first?'Exclusive':'Premiere',rate=first?1599:null;const ins=await c.query(`INSERT INTO public.founding_members(user_id,member_number,club,founding_plan,founding_rate_cents,trial_ends_at) VALUES($1::uuid,$2,$3,$4,$5,now()+interval '30 days') RETURNING *`,[userId,n,first?'FIRST_100':'FOUNDING_MEMBER',plan,rate]);await c.query(`UPDATE public.users SET subscription_plan=$1,subscription_status='trial',subscription_price=$2,trial_end_date=now()+interval '30 days',stripe_subscription_id=$3,updated_at=now() WHERE id=$4::uuid`,[plan,first?15.99:9.99,subscriptionId,userId]);await c.query('COMMIT');return ins.rows[0]}catch(e){await c.query('ROLLBACK');throw e}}
async function customer(c,env,u){const q=await c.query('SELECT stripe_customer_id,email FROM public.users WHERE id=$1::uuid',[u.id]);if(q.rows[0]?.stripe_customer_id)return q.rows[0].stripe_customer_id;const p=new URLSearchParams();p.set('email',u.email||q.rows[0]?.email||'');p.set('metadata[user_id]',u.id);p.set('metadata[platform]','One2OneLove');const x=await stripe(env,'POST','/customers',p);await c.query('UPDATE public.users SET stripe_customer_id=$1,updated_at=now() WHERE id=$2::uuid',[x.id,u.id]);return x.id}
async function checkout(req,env,u){return withDb(env,async c=>{const s=await foundingStatus(c,u.id);if(s.member)return fail('This account already has its Founding Member membership.',409,'founding_already_claimed');if(s.claimed>=200)return fail('The Founding Member enrollment is full.',409,'founding_full');const cid=await customer(c,env,u),origin=new URL(req.url).origin,p=new URLSearchParams();p.set('customer',cid);p.set('mode','subscription');p.set('payment_method_types[0]','card');p.set('payment_method_collection','always');p.set('line_items[0][price_data][currency]','usd');p.set('line_items[0][price_data][product_data][name]','One2OneLove Exclusive — Founding Member');p.set('line_items[0][price_data][unit_amount]','1599');p.set('line_items[0][price_data][recurring][interval]','month');p.set('line_items[0][quantity]','1');p.set('subscription_data[trial_period_days]','30');p.set('client_reference_id',u.id);p.set('metadata[user_id]',u.id);p.set('metadata[o2ol_founding_offer]','true');p.set('subscription_data[metadata][user_id]',u.id);p.set('subscription_data[metadata][o2ol_founding_offer]','true');p.set('subscription_data[metadata][plan_name]','Exclusive');p.set('success_url',origin+'/payment-success?founding=1&session_id={CHECKOUT_SESSION_ID}');p.set('cancel_url',origin+'/subscription?canceled=true');const x=await stripe(env,'POST','/checkout/sessions',p);return json({ok:true,url:x.url,sessionId:x.id})})}
export async function finalizeFoundingCheckout(c,env,s){if(s?.metadata?.o2ol_founding_offer!=='true')return null;const uid=s.metadata?.user_id||s.client_reference_id,sid=typeof s.subscription==='string'?s.subscription:s.subscription?.id;if(!uid||!sid)return null;const m=await claimFoundingMember(c,uid,sid);await sendWelcomeEmail(c,env,uid,m).catch(e=>console.error('Founding welcome email:',e?.message||e));if(m.member_number>100){const sub=await stripe(env,'GET','/subscriptions/'+encodeURIComponent(sid)),item=sub?.items?.data?.[0]?.id;if(!item||!env.STRIPE_PRICE_PREMIERE)throw new Error('Premiere price is not configured.');const p=new URLSearchParams();p.set('items[0][id]',item);p.set('items[0][price]',env.STRIPE_PRICE_PREMIERE);p.set('proration_behavior','none');p.set('metadata[user_id]',uid);p.set('metadata[plan_name]','Premiere');p.set('metadata[o2ol_founding_member_number]',String(m.member_number));await stripe(env,'POST','/subscriptions/'+encodeURIComponent(sid),p)}return m}
async function sendWelcomeEmail(c,env,userId,member){
  if(!env.RESEND_API_KEY)return false;
  const q=await c.query('SELECT email,name FROM public.users WHERE id=$1::uuid',[userId]),u=q.rows[0];
  if(!u?.email)return false;
  const first=Number(member.member_number)<=100;
  const title=first?'WELCOME To One2OneLove as a 1st 100 FOUNDING MEMBERS CLUB.':'WELCOME To One2OneLove as FOUNDING MEMBER CLUB.';
  const terms=first
    ? 'You have 30 days of Exclusive access free. Unless you choose Premiere before the trial ends, your Exclusive membership continues at US$15.99/month while continuously subscribed. If you cancel, your permanent 1st 100 Founding Member recognition remains, but the special US$15.99 rate is forfeited if you return.'
    : 'You have 30 days of Premiere access free. After the trial, your membership continues automatically at the then-current regular Premiere monthly price unless you cancel.';
  const html=`<div style="font-family:Arial,sans-serif;max-width:640px;margin:auto;padding:28px"><div style="border:2px solid #db2777;border-radius:24px;padding:28px;text-align:center;background:#fff7fb"><div style="font-size:14px;font-weight:800;letter-spacing:2px;color:#7e22ce">ONE2ONELOVE</div><h1 style="font-size:28px;margin:14px 0;color:#111827">${title}</h1><div style="font-size:18px;font-weight:800;color:#be185d">Founding Member #${member.member_number}</div><p style="font-size:16px;line-height:1.6;color:#374151">${terms}</p><p style="font-size:14px;color:#6b7280">Your Founding Member designation and member number are permanent.</p></div></div>`;
  const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from:'One2OneLove <support@one2onelove.com>',to:[u.email],subject:title,html})});
  if(!r.ok)throw new Error('Founding Member welcome email could not be sent.');
  await c.query('UPDATE public.founding_members SET welcome_email_sent_at=COALESCE(welcome_email_sent_at,now()),updated_at=now() WHERE user_id=$1::uuid',[userId]);
  return true;
}
async function choosePremiere(c,env,userId){
  const q=await c.query('SELECT * FROM public.founding_members WHERE user_id=$1::uuid',[userId]),m=q.rows[0];
  if(!m||Number(m.member_number)>100)return fail('This option is available to 1st 100 Founding Members.',409,'not_first_100');
  if(new Date(m.trial_ends_at).getTime()<=Date.now())return fail('The 30-day Founding Member trial has ended.',409,'trial_ended');
  const u=(await c.query('SELECT stripe_subscription_id FROM public.users WHERE id=$1::uuid',[userId])).rows[0];
  if(!u?.stripe_subscription_id||!env.STRIPE_PRICE_PREMIERE)return fail('Premiere billing is not configured.',503,'billing_not_configured');
  const sub=await stripe(env,'GET','/subscriptions/'+encodeURIComponent(u.stripe_subscription_id)),item=sub?.items?.data?.[0]?.id;
  if(!item)return fail('Stripe subscription item could not be found.',502,'stripe_subscription_item_missing');
  const p=new URLSearchParams();p.set('items[0][id]',item);p.set('items[0][price]',env.STRIPE_PRICE_PREMIERE);p.set('proration_behavior','none');p.set('metadata[user_id]',userId);p.set('metadata[plan_name]','Premiere');p.set('metadata[o2ol_founding_offer]','true');p.set('metadata[o2ol_founding_member_number]',String(m.member_number));
  await stripe(env,'POST','/subscriptions/'+encodeURIComponent(u.stripe_subscription_id),p);
  await c.query("UPDATE public.founding_members SET founding_plan='Premiere',founding_rate_cents=NULL,updated_at=now() WHERE user_id=$1::uuid",[userId]);
  await c.query("UPDATE public.users SET subscription_plan='Premiere',subscription_price=9.99,updated_at=now() WHERE id=$1::uuid",[userId]);
  return json({ok:true,plan:'Premiere',member_number:m.member_number});
}
export async function forfeitFoundingRate(c,userId){await c.query(`UPDATE public.founding_members SET continuous_subscription=false,founding_rate_forfeited_at=COALESCE(founding_rate_forfeited_at,now()),updated_at=now() WHERE user_id=$1::uuid AND founding_rate_forfeited_at IS NULL`,[userId])}
export async function handleFoundingMemberRequest(req,env,url){if(!url.pathname.startsWith('/api/founding-members'))return null;try{const u=await session(req,env);if(!u)return fail('Authentication required.',401,'unauthorized');if(url.pathname==='/api/founding-members/status'&&req.method==='GET')return withDb(env,async c=>json({ok:true,...await foundingStatus(c,u.id)}));if(url.pathname==='/api/founding-members/checkout'&&req.method==='POST')return checkout(req,env,u);if(url.pathname==='/api/founding-members/choose-premiere'&&req.method==='POST')return withDb(env,c=>choosePremiere(c,env,u.id));return fail('Not found.',404,'not_found')}catch(e){return fail(e?.message||'Founding Member request failed.',e?.status||500,'founding_member_error')}}