// @ts-nocheck
import { Client } from 'pg';

const HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'};
const PACKAGES={
  single:{code:'single',credits:1,amountCents:199,name:'MyMatchIQ Single Credit'},
  six:{code:'six',credits:6,amountCents:999,name:'MyMatchIQ Six-Credit Bundle'},
  twelve:{code:'twelve',credits:12,amountCents:1999,name:'MyMatchIQ Twelve-Credit Bundle'},
};

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:HEADERS});}
function fail(message,status=400,code='bad_request'){return json({ok:false,error:{code,message}},status);}
async function readJson(request){if(!(request.headers.get('content-type')||'').includes('application/json'))throw new Error('Expected application/json body.');return request.json();}
async function session(request,env){const cookie=request.headers.get('cookie');if(!cookie)return null;const response=await fetch(env.NEON_AUTH_BASE_URL.replace(/\/$/,'')+'/get-session',{headers:{cookie,accept:'application/json'}});if(!response.ok)return null;const payload=await response.json().catch(()=>null);const user=payload?.user??payload?.data?.user??null;const active=payload?.session??payload?.data?.session??null;return user?.id&&user?.emailVerified===true&&active?{user,session:active}:null;}
async function withDb(env,fn){const db=new Client({connectionString:env.HYPERDRIVE.connectionString});await db.connect();try{return await fn(db);}finally{await db.end();}}
function billingEnabled(env){return env.MMIQ_CREDIT_BILLING_ENABLED==='true'&&Boolean(env.STRIPE_SECRET_KEY);}
async function stripeRequest(env,method,path,params=null){if(!env.STRIPE_SECRET_KEY)throw Object.assign(new Error('Stripe is not configured.'),{status:503,code:'billing_not_configured'});const headers={authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,accept:'application/json'};let body;if(params){headers['content-type']='application/x-www-form-urlencoded';body=params instanceof URLSearchParams?params:new URLSearchParams(params);}const response=await fetch(`https://api.stripe.com/v1${path}`,{method,headers,body});const payload=await response.json().catch(()=>null);if(!response.ok)throw Object.assign(new Error(payload?.error?.message||'Stripe request failed.'),{status:502,code:payload?.error?.code||'stripe_error'});return payload;}
async function member(db,userId){const r=await db.query('SELECT id,email,name,phone_number_verified,is_active,stripe_customer_id FROM public.users WHERE id=$1::uuid',[userId]);return r.rows[0]||null;}
async function ensureWallet(db,userId){await db.query(`INSERT INTO mymatchiq.credit_wallets(user_id) VALUES($1::uuid) ON CONFLICT(user_id) DO NOTHING`,[userId]);const r=await db.query(`SELECT balance,lifetime_purchased,lifetime_used,created_at,updated_at FROM mymatchiq.credit_wallets WHERE user_id=$1::uuid`,[userId]);return r.rows[0];}
async function ensureSettings(db,userId){await db.query(`INSERT INTO mymatchiq.auto_replenish_settings(user_id) VALUES($1::uuid) ON CONFLICT(user_id) DO NOTHING`,[userId]);const r=await db.query(`SELECT enabled,refill_package_cents,threshold_credits,payment_method_reference,created_at,updated_at FROM mymatchiq.auto_replenish_settings WHERE user_id=$1::uuid`,[userId]);return r.rows[0];}
async function getOrCreateCustomer(db,env,auth,row){if(row.stripe_customer_id)return row.stripe_customer_id;const params=new URLSearchParams();params.set('email',auth.user.email||row.email||'');params.set('name',row.name||'');params.set('metadata[user_id]',auth.user.id);params.set('metadata[platform]','MyMatchIQ');const customer=await stripeRequest(env,'POST','/customers',params);await db.query('UPDATE public.users SET stripe_customer_id=$1,updated_at=now() WHERE id=$2::uuid',[customer.id,auth.user.id]);return customer.id;}
async function checkout(db,env,request,auth,input){if(!billingEnabled(env))return fail('MyMatchIQ credit checkout is disabled in this Prelaunch environment.',503,'credit_checkout_disabled');const pkg=PACKAGES[String(input?.packageCode||input?.package||'')];if(!pkg)return fail('Choose a valid credit package.');const row=await member(db,auth.user.id);if(!row||row.is_active===false)return fail('Account access is unavailable.',403,'forbidden');if(row.phone_number_verified!==true)return fail('Phone verification is required before purchasing credits.',428,'phone_verification_required');const customerId=await getOrCreateCustomer(db,env,auth,row);const origin=new URL(request.url).origin;const params=new URLSearchParams();params.set('customer',customerId);params.set('mode','payment');params.set('payment_method_types[0]','card');params.set('payment_intent_data[setup_future_usage]','off_session');params.set('line_items[0][price_data][currency]','usd');params.set('line_items[0][price_data][unit_amount]',String(pkg.amountCents));params.set('line_items[0][price_data][product_data][name]',pkg.name);params.set('line_items[0][quantity]','1');params.set('success_url',`${origin}/MyMatchIQ/Credits?purchase=success&session_id={CHECKOUT_SESSION_ID}`);params.set('cancel_url',`${origin}/MyMatchIQ/Credits?purchase=canceled`);params.set('client_reference_id',auth.user.id);for(const [key,value] of Object.entries({mmiq_type:'credit_checkout',user_id:auth.user.id,package_code:pkg.code,credits:String(pkg.credits),amount_cents:String(pkg.amountCents)})){params.set(`metadata[${key}]`,String(value));params.set(`payment_intent_data[metadata][${key}]`,String(value));}const checkoutSession=await stripeRequest(env,'POST','/checkout/sessions',params);await db.query(`INSERT INTO mymatchiq.credit_purchases(user_id,package_code,amount_cents,credits,status,idempotency_key) VALUES($1::uuid,$2,$3,$4,'created',$5) ON CONFLICT(idempotency_key) DO NOTHING`,[auth.user.id,pkg.code,pkg.amountCents,pkg.credits,`checkout:${checkoutSession.id}`]);return json({ok:true,url:checkoutSession.url,sessionId:checkoutSession.id,package:pkg});}
async function updateAuto(db,env,userId,input){const current=await ensureSettings(db,userId);const enabled=Boolean(input?.enabled);const cents=Number(input?.refillPackageCents??input?.refill_package_cents??current.refill_package_cents);const threshold=Number(input?.thresholdCredits??input?.threshold_credits??current.threshold_credits);if(![199,999,1999].includes(cents))return fail('Choose a valid Auto Replenish package.');if(!Number.isInteger(threshold)||threshold<0||threshold>50)return fail('Choose a valid minimum credit balance.');if(enabled){if(!billingEnabled(env))return fail('Auto Replenish is disabled in this Prelaunch environment.',503,'auto_replenish_disabled');if(!current.payment_method_reference)return fail('Purchase credits once and save a verified payment method before enabling Auto Replenish.',409,'payment_method_required');}const r=await db.query(`UPDATE mymatchiq.auto_replenish_settings SET enabled=$1,refill_package_cents=$2,threshold_credits=$3,updated_at=now() WHERE user_id=$4::uuid RETURNING enabled,refill_package_cents,threshold_credits,(payment_method_reference IS NOT NULL) AS payment_method_ready,updated_at`,[enabled,cents,threshold,userId]);return json({ok:true,settings:r.rows[0]});}
async function creditWallet(db,userId){const [wallet,settings]=await Promise.all([ensureWallet(db,userId),ensureSettings(db,userId)]);return {wallet,settings:{enabled:settings.enabled,refill_package_cents:settings.refill_package_cents,threshold_credits:settings.threshold_credits,payment_method_ready:Boolean(settings.payment_method_reference)}};}
async function fulfill(db,userId,pkg,idempotencyKey,paymentIntentId,paymentMethodReference,reason='purchase'){await db.query('BEGIN');try{const existing=await db.query('SELECT status FROM mymatchiq.credit_purchases WHERE idempotency_key=$1 FOR UPDATE',[idempotencyKey]);if(existing.rows[0]?.status==='paid'){await db.query('ROLLBACK');return false;}await db.query(`INSERT INTO mymatchiq.credit_purchases(user_id,package_code,amount_cents,credits,status,stripe_payment_intent_id,idempotency_key) VALUES($1::uuid,$2,$3,$4,'paid',$5,$6) ON CONFLICT(idempotency_key) DO UPDATE SET status='paid',stripe_payment_intent_id=EXCLUDED.stripe_payment_intent_id,updated_at=now()`,[userId,pkg.code,pkg.amountCents,pkg.credits,paymentIntentId||null,idempotencyKey]);await db.query(`INSERT INTO mymatchiq.credit_wallets(user_id,balance,lifetime_purchased) VALUES($1::uuid,$2,$2) ON CONFLICT(user_id) DO UPDATE SET balance=mymatchiq.credit_wallets.balance+$2,lifetime_purchased=mymatchiq.credit_wallets.lifetime_purchased+$2,updated_at=now()`,[userId,pkg.credits]);await db.query(`INSERT INTO mymatchiq.credit_ledger(user_id,delta,reason,reference,metadata) VALUES($1::uuid,$2,$3,$4,$5::jsonb)`,[userId,pkg.credits,reason,paymentIntentId||idempotencyKey,JSON.stringify({packageCode:pkg.code,amountCents:pkg.amountCents})]);if(paymentMethodReference)await db.query(`INSERT INTO mymatchiq.auto_replenish_settings(user_id,payment_method_reference) VALUES($1::uuid,$2) ON CONFLICT(user_id) DO UPDATE SET payment_method_reference=EXCLUDED.payment_method_reference,updated_at=now()`,[userId,paymentMethodReference]);await db.query('COMMIT');return true;}catch(error){await db.query('ROLLBACK');throw error;}}
async function packageFromMetadata(metadata){const pkg=PACKAGES[String(metadata?.package_code||'')];if(!pkg)return null;const credits=Number(metadata?.credits),amount=Number(metadata?.amount_cents);return credits===pkg.credits&&amount===pkg.amountCents?pkg:null;}
export async function handleMyMatchIQCreditStripeEvent(db,env,event){const object=event?.data?.object||{};if(event?.type==='checkout.session.completed'&&object?.metadata?.mmiq_type==='credit_checkout'){if(object.payment_status!=='paid')return true;const userId=object.metadata?.user_id||object.client_reference_id;const pkg=await packageFromMetadata(object.metadata);if(!userId||!pkg)return true;let paymentIntentId=typeof object.payment_intent==='string'?object.payment_intent:object.payment_intent?.id||null;let paymentMethod=null;if(paymentIntentId&&env.STRIPE_SECRET_KEY){const pi=await stripeRequest(env,'GET',`/payment_intents/${encodeURIComponent(paymentIntentId)}`);paymentMethod=typeof pi?.payment_method==='string'?pi.payment_method:pi?.payment_method?.id||null;}await fulfill(db,userId,pkg,`checkout:${object.id}`,paymentIntentId,paymentMethod,'purchase');return true;}if(event?.type==='payment_intent.succeeded'&&object?.metadata?.mmiq_type==='auto_replenish'){const userId=object.metadata?.user_id;const pkg=await packageFromMetadata(object.metadata);if(userId&&pkg)await fulfill(db,userId,pkg,`payment_intent:${object.id}`,object.id,typeof object.payment_method==='string'?object.payment_method:object.payment_method?.id||null,'auto_replenish');return true;}if(event?.type==='payment_intent.payment_failed'&&object?.metadata?.mmiq_type==='auto_replenish'){await db.query(`UPDATE mymatchiq.credit_purchases SET status='failed',updated_at=now() WHERE idempotency_key=$1`,[`payment_intent:${object.id}`]);return true;}return false;}
export async function debitMyMatchIQCredits(db,env,userId,amount,reason,reference=null,metadata={}){if(!Number.isInteger(amount)||amount<=0)throw new Error('Invalid credit amount.');await db.query('BEGIN');let newBalance;try{const wallet=await db.query(`SELECT balance FROM mymatchiq.credit_wallets WHERE user_id=$1::uuid FOR UPDATE`,[userId]);const balance=Number(wallet.rows[0]?.balance||0);if(balance<amount)throw Object.assign(new Error('Not enough MyMatchIQ credits.'),{status:402,code:'insufficient_credits'});newBalance=balance-amount;await db.query(`UPDATE mymatchiq.credit_wallets SET balance=$1,lifetime_used=lifetime_used+$2,updated_at=now() WHERE user_id=$3::uuid`,[newBalance,amount,userId]);await db.query(`INSERT INTO mymatchiq.credit_ledger(user_id,delta,reason,reference,metadata) VALUES($1::uuid,$2,$3,$4,$5::jsonb)`,[userId,-amount,reason,reference,JSON.stringify(metadata)]);await db.query('COMMIT');}catch(error){await db.query('ROLLBACK');throw error;}if(billingEnabled(env)){const s=(await db.query(`SELECT enabled,refill_package_cents,threshold_credits,payment_method_reference FROM mymatchiq.auto_replenish_settings WHERE user_id=$1::uuid`,[userId])).rows[0];if(s?.enabled&&s.payment_method_reference&&newBalance<=Number(s.threshold_credits)){const pkg=Object.values(PACKAGES).find(p=>p.amountCents===Number(s.refill_package_cents));const user=await member(db,userId);if(pkg&&user?.stripe_customer_id){const params=new URLSearchParams();params.set('amount',String(pkg.amountCents));params.set('currency','usd');params.set('customer',user.stripe_customer_id);params.set('payment_method',s.payment_method_reference);params.set('confirm','true');params.set('off_session','true');for(const [key,value] of Object.entries({mmiq_type:'auto_replenish',user_id:userId,package_code:pkg.code,credits:String(pkg.credits),amount_cents:String(pkg.amountCents)}))params.set(`metadata[${key}]`,String(value));const pi=await stripeRequest(env,'POST','/payment_intents',params);await db.query(`INSERT INTO mymatchiq.credit_purchases(user_id,package_code,amount_cents,credits,status,stripe_payment_intent_id,idempotency_key) VALUES($1::uuid,$2,$3,$4,$5,$6,$7) ON CONFLICT(idempotency_key) DO NOTHING`,[userId,pkg.code,pkg.amountCents,pkg.credits,pi.status==='succeeded'?'created':'failed',pi.id,`payment_intent:${pi.id}`]);}}}return newBalance;}

export async function handleMyMatchIQCreditsRequest(request,env,url){
 if(!url.pathname.startsWith('/api/mymatchiq/credits'))return null;
 const auth=await session(request,env);if(!auth)return fail('Verified MyMatchIQ sign-in is required.',401,'unauthorized');
 try{return await withDb(env,async db=>{
   const row=await member(db,auth.user.id);if(!row||row.is_active===false)return fail('Account access is unavailable.',403,'forbidden');if(row.phone_number_verified!==true)return fail('Phone verification is required for MyMatchIQ credits.',428,'phone_verification_required');
   if(url.pathname==='/api/mymatchiq/credits/config'&&request.method==='GET')return json({ok:true,billingEnabled:billingEnabled(env),packages:Object.values(PACKAGES)});
   if(url.pathname==='/api/mymatchiq/credits/wallet'&&request.method==='GET')return json({ok:true,...await creditWallet(db,auth.user.id)});
   if(url.pathname==='/api/mymatchiq/credits/auto-replenish'){
      if(request.method==='GET'){const s=await ensureSettings(db,auth.user.id);return json({ok:true,settings:{enabled:s.enabled,refill_package_cents:s.refill_package_cents,threshold_credits:s.threshold_credits,payment_method_ready:Boolean(s.payment_method_reference)}});}
      if(request.method==='PUT')return updateAuto(db,env,auth.user.id,await readJson(request));
      return fail('Method not allowed.',405,'method_not_allowed');
   }
   if(url.pathname==='/api/mymatchiq/credits/checkout'&&request.method==='POST')return checkout(db,env,request,auth,await readJson(request));
   if(url.pathname==='/api/mymatchiq/credits/history'&&request.method==='GET'){const r=await db.query(`SELECT id,delta,reason,reference,metadata,created_at FROM mymatchiq.credit_ledger WHERE user_id=$1::uuid ORDER BY created_at DESC LIMIT 100`,[auth.user.id]);return json({ok:true,history:r.rows});}
   return fail('Not found.',404,'not_found');
 });}catch(error){console.error('MyMatchIQ credits error',error);return fail(error?.message||'Credit request failed.',error?.status||500,error?.code||'credit_error');}
}
