// @ts-nocheck
import { Client } from 'pg';

const HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const VERSION='2026.1';
const LANGS=new Set(['en','es','fr','it','de']);

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:HEADERS});}
function fail(message,status=400,code='bad_request',extra={}){return json({ok:false,error:{code,message,...extra}},status);}
async function readJson(request){if(!(request.headers.get('content-type')||'').includes('application/json'))throw new Error('Expected application/json body.');return request.json();}
async function session(request,env){const cookie=request.headers.get('cookie');if(!cookie)return null;const response=await fetch(env.NEON_AUTH_BASE_URL.replace(/\/$/,'')+'/get-session',{headers:{cookie,accept:'application/json'}});if(!response.ok)return null;const payload=await response.json().catch(()=>null);const user=payload?.user??payload?.data?.user??null;const active=payload?.session??payload?.data?.session??null;return user?.id&&user?.emailVerified===true&&active?{user,session:active}:null;}
async function withDb(env,fn){const db=new Client({connectionString:env.HYPERDRIVE.connectionString});await db.connect();try{return await fn(db);}finally{await db.end();}}
async function memberGate(db,userId){const r=await db.query(`SELECT id,phone_number_verified,is_active FROM public.users WHERE id=$1::uuid`,[userId]);const row=r.rows[0];if(!row)return {response:fail('MyMatchIQ profile is not available.',404,'profile_not_found')};if(row.is_active===false)return {response:fail('Account access is unavailable.',403,'forbidden')};if(row.phone_number_verified!==true)return {response:fail('Phone verification is required for MyMatchIQ.',428,'phone_verification_required')};return {row};}
async function ownedPassport(db,id,userId){if(!UUID.test(String(id||'')))throw Object.assign(new Error('Invalid passport ID.'),{status:400,code:'bad_request'});const r=await db.query(`SELECT * FROM mymatchiq.compatibility_passports WHERE id=$1::uuid AND user_id=$2::uuid`,[id,userId]);if(!r.rows[0])throw Object.assign(new Error('Compatibility Passport not found.'),{status:404,code:'not_found'});return r.rows[0];}
async function currentPassport(db,userId){const r=await db.query(`SELECT p.*,(SELECT count(*)::int FROM mymatchiq.assessment_answers a WHERE a.passport_id=p.id) AS answered_count FROM mymatchiq.compatibility_passports p WHERE p.user_id=$1::uuid AND p.assessment_version=$2 ORDER BY p.created_at DESC LIMIT 1`,[userId,VERSION]);return r.rows[0]||null;}
async function questions(db,language){const lang=LANGS.has(language)?language:'en';const r=await db.query(`SELECT id,question_key,dimension_key,position,COALESCE(prompt_i18n->>$2,prompt_i18n->>'en') AS prompt,COALESCE(answer_options->$2,answer_options->'en') AS options FROM mymatchiq.assessment_questions WHERE assessment_version=$1 AND active=true ORDER BY position`,[VERSION,lang]);return r.rows;}
async function answers(db,passportId,userId){await ownedPassport(db,passportId,userId);const r=await db.query(`SELECT a.question_id,q.question_key,q.dimension_key,q.position,a.answer_value,a.answered_at,a.updated_at FROM mymatchiq.assessment_answers a JOIN mymatchiq.assessment_questions q ON q.id=a.question_id WHERE a.passport_id=$1::uuid ORDER BY q.position`,[passportId]);return r.rows.map(row=>({...row,value:Number(row.answer_value?.value??row.answer_value)}));}
async function saveAnswer(db,passportId,userId,input){const passport=await ownedPassport(db,passportId,userId);if(passport.status!=='draft')return fail('Completed Compatibility Passports cannot be edited.',409,'passport_locked');const questionId=String(input?.questionId||'');const value=Number(input?.value);if(!UUID.test(questionId)||!Number.isInteger(value)||value<1||value>5)return fail('A valid question and answer value from 1 to 5 are required.',400,'invalid_answer');const q=await db.query(`SELECT id FROM mymatchiq.assessment_questions WHERE id=$1::uuid AND assessment_version=$2 AND active=true`,[questionId,VERSION]);if(!q.rowCount)return fail('Assessment question is unavailable.',404,'question_not_found');await db.query(`INSERT INTO mymatchiq.assessment_answers(passport_id,question_id,answer_value) VALUES($1::uuid,$2::uuid,$3::jsonb) ON CONFLICT(passport_id,question_id) DO UPDATE SET answer_value=EXCLUDED.answer_value,answered_at=now(),updated_at=now()`,[passportId,questionId,JSON.stringify({value})]);await db.query('UPDATE mymatchiq.compatibility_passports SET updated_at=now() WHERE id=$1::uuid',[passportId]);const count=(await db.query('SELECT count(*)::int AS count FROM mymatchiq.assessment_answers WHERE passport_id=$1::uuid',[passportId])).rows[0]?.count||0;return json({ok:true,answeredCount:count,totalQuestions:225});}
async function completePassport(db,passportId,userId){const passport=await ownedPassport(db,passportId,userId);if(passport.status==='complete'){const scores=await dimensionScores(db,passportId);return json({ok:true,passport,dimensionScores:scores,alreadyComplete:true});}const totals=await db.query(`SELECT (SELECT count(*)::int FROM mymatchiq.assessment_questions WHERE assessment_version=$2 AND active=true) AS total,(SELECT count(*)::int FROM mymatchiq.assessment_answers WHERE passport_id=$1::uuid) AS answered`,[passportId,VERSION]);const total=totals.rows[0]?.total||0,answered=totals.rows[0]?.answered||0;if(answered<total)return fail('Complete every assessment question before finishing the Compatibility Passport.',409,'assessment_incomplete',{answered,total,remaining:total-answered});const scores=await dimensionScores(db,passportId);const evidence=(await db.query(`SELECT jsonb_agg(jsonb_build_object('questionKey',q.question_key,'dimension',q.dimension_key,'value',(a.answer_value->>'value')::int) ORDER BY q.position) AS answers FROM mymatchiq.assessment_answers a JOIN mymatchiq.assessment_questions q ON q.id=a.question_id WHERE a.passport_id=$1::uuid`,[passportId])).rows[0]?.answers||[];await db.query('BEGIN');try{const updated=(await db.query(`UPDATE mymatchiq.compatibility_passports SET status='complete',completed_at=now(),updated_at=now() WHERE id=$1::uuid RETURNING *`,[passportId])).rows[0];await db.query(`INSERT INTO public.mmiq_assessment_sessions(user_id,assessment_version,language,status,question_count,answers,dimension_scores,completed_at,updated_at) VALUES($1::uuid,$2,'en','completed',$3,$4::jsonb,$5::jsonb,now(),now())`,[userId,VERSION,total,JSON.stringify(evidence),JSON.stringify(scores)]);await db.query(`INSERT INTO mymatchiq.audit_events(user_id,event_type,entity_type,entity_id,metadata) VALUES($1::uuid,'passport_completed','compatibility_passport',$2::uuid,$3::jsonb)`,[userId,passportId,JSON.stringify({assessmentVersion:VERSION,questionCount:total})]);await db.query('COMMIT');return json({ok:true,passport:updated,dimensionScores:scores});}catch(error){await db.query('ROLLBACK');throw error;}}
async function dimensionScores(db,passportId){const r=await db.query(`SELECT q.dimension_key,round((((avg((a.answer_value->>'value')::numeric)-1)/4)*100)::numeric,1) AS score,count(*)::int AS answered FROM mymatchiq.assessment_answers a JOIN mymatchiq.assessment_questions q ON q.id=a.question_id WHERE a.passport_id=$1::uuid GROUP BY q.dimension_key ORDER BY q.dimension_key`,[passportId]);return Object.fromEntries(r.rows.map(row=>[row.dimension_key,{score:Number(row.score),answered:row.answered}]));}

export async function handleMyMatchIQCoreRequest(request,env,url){
 if(!url.pathname.startsWith('/api/mymatchiq/'))return null;
 if(url.pathname.startsWith('/api/mymatchiq/bianca'))return null;
 const auth=await session(request,env);if(!auth)return fail('Verified MyMatchIQ sign-in is required.',401,'unauthorized');
 try{return await withDb(env,async db=>{
   const gate=await memberGate(db,auth.user.id);if(gate.response)return gate.response;
   if(url.pathname==='/api/mymatchiq/assessment/questions'&&request.method==='GET')return json({ok:true,assessmentVersion:VERSION,questions:await questions(db,url.searchParams.get('lang')||'en')});
   if(url.pathname==='/api/mymatchiq/passport'){
     if(request.method==='GET')return json({ok:true,passport:await currentPassport(db,auth.user.id)});
     if(request.method==='POST'){await db.query(`INSERT INTO mymatchiq.profiles(user_id,locale) VALUES($1::uuid,$2) ON CONFLICT(user_id) DO NOTHING`,[auth.user.id,LANGS.has(url.searchParams.get('lang'))?url.searchParams.get('lang'):'en']);const r=await db.query(`INSERT INTO mymatchiq.compatibility_passports(user_id,assessment_version) VALUES($1::uuid,$2) ON CONFLICT(user_id,assessment_version) DO UPDATE SET updated_at=now() RETURNING *`,[auth.user.id,VERSION]);return json({ok:true,passport:r.rows[0]},201);}
     return fail('Method not allowed.',405,'method_not_allowed');
   }
   const answerList=url.pathname.match(/^\/api\/mymatchiq\/passport\/([0-9a-f-]{36})\/answers$/i);
   if(answerList){if(request.method==='GET')return json({ok:true,answers:await answers(db,answerList[1],auth.user.id)});if(request.method==='PUT'||request.method==='POST')return saveAnswer(db,answerList[1],auth.user.id,await readJson(request));return fail('Method not allowed.',405,'method_not_allowed');}
   const complete=url.pathname.match(/^\/api\/mymatchiq\/passport\/([0-9a-f-]{36})\/complete$/i);
   if(complete&&request.method==='POST')return completePassport(db,complete[1],auth.user.id);
   return null;
 });}catch(error){console.error('MyMatchIQ core API error',error);return fail(error?.message||'Unable to process MyMatchIQ request.',error?.status||500,error?.code||'mymatchiq_error');}
}
