// @ts-nocheck
import { Client } from 'pg';

const HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'};
const PACKAGES={
  single:{code:'single',credits:1,amountCents:199,name:'MyMatchIQ Single Credit'},
  six:{code:'six',credits:6,amountCents:999,name:'MyMatchIQ Six-Credit Bundle'},
  twelve:{code:'twelve',credits:12,amountCents:1999,name:'MyMatchIQ Twelve-Credit Bundle'},
};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:HEADERS});}
function fail(message,status=400,code='bad_request'){return json({ok:false,error:{code,message}},status);}
async function readJson(request){if(!(request.headers.get('content-type')||'').includes('application/json'))throw new Error('Expected application/json body.');return request.json();}
async function session(request,env){const cookie=request.headers.get('cookie');if(!cookie)return null;const response=await fetch(env.NEON_AUTH_BASE_URL.replace(/\/$/,'')+'/get-session',{headers:{cookie,accept:'application/json'}});if(!response.ok)return null;const payload=await response.json().catch(()=>null);const user=payload?.user??payload?.data?.user??null;const active=payload?.session??payload?.data?.session??null;return user?.id&&user?.emailVerified===true&&active?{user,session:active}:null;}
async function withDb(env,fn){const db=new Client({connectionString:env.HYPERDRIVE.connectionString});await db.connect();try{return await fn(db);}finally{await db.end();}}
function billingEnabled(env){return env.MMIQ_CREDIT_BILLING_ENABLED==='true'&&Boolean(env.STRIPE_SECRET_KEY);}
async function stripeRequest(env,method,path,params=null){if(!env.STRIPE_SECRET_KEY)throw Object.assign(new Error('Stripe is not configured.'),{status:503,code:'billing_not_configured'});const headers={authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,accept:'application/json'};let body;if(params){headers['content-type']='application/x-www-form-urlencoded';body=params instanceof URLSearchParams?params:new URLSearchParams(params);}const response=await fetch(`https://api.stripe.com/v1${path}`,{method,headers,body});const payload=await response.json().catch(()=>null);if(!response.ok)throw Object.assign(new Error(payload?.error?.message||'Stripe request failed.'),{status:502,code:payload?.error?.code||'stripe_error'});return payload;}
async function member(db,userId){const r=await db.query('SELECT id,email,name,phone_number_verified,is_active,stripe_customer_id FROM public.users WHERE id=$1::uuid',[userId]);return r.rows[0]||null;}
async function ensureWallet(db,userId){await db.query('INSERT INTO public.mmiq_credit_wallets(user_id) VALUES($1::uuid) ON CONFLICT(user_id) DO NOTHING',[userId]);const r=await db.query('SELECT balance,lifetime_purchased,lifetime_used,created_at,updated_at FROM public.mmiq_credit_wallets WHERE user_id=$1::uuid',[userId]);return r.rows[0];}
async function ensureSettings(db,userId){await db.query('INSERT INTO public.mmiq_auto_replenish_settings(user_id) VALUES($1::uuid) ON CONFLICT(user_id) DO NOTHING',[userId]);const r=await db.query('SELECT enabled,package_code,trigger_balance,payment_method_reference,last_triggered_at,created_at,updated_at FROM public.mmiq_auto_replenish_settings WHERE user_id=$1::uuid',[userId]);return r.rows[0];}
function normalizedSettings(row){const pkg=PACKAGES[row?.package_code]||PACKAGES.six;return {enabled:Boolean(row?.enabled),package_code:pkg.code,refill_package_cents:pkg.amountCents,threshold_credits:Number(row?.trigger_balance??0),payment_method_ready:Boolean(row?.payment_method_reference),last_triggered_at:row?.last_triggered_at||null,updated_at:row?.updated_at||null};}
async function getOrCreateCustomer(db,env,auth,row){if(row.stripe_customer_id)return row.stripe_customer_id;const params=new URLSearchParams();params.set('email',auth.user.email||row.email||'');params.set('name',row.name||'');params.set('metadata[user_id]',auth.user.id);params.set('metadata[platform]','MyMatchIQ');const customer=await stripeRequest(env,'POST','/customers',params);await db.query('UPDATE public.users SET stripe_customer_id=$1,updated_at=now() WHERE id=$2::uuid',[customer.id,auth.user.id]);return customer.id;}
async function checkout(db,env,request,auth,input){if(!billingEnabled(env))return fail('MyMatchIQ credit checkout is disabled in this Prelaunch environment.',503,'credit_checkout_disabled');const pkg=PACKAGES[String(input?.packageCode||input?.package||'')];if(!pkg)return fail('Choose a valid credit package.');const row=await member(db,auth.user.id);if(!row||row.is_active===false)return fail('Account access is unavailable.',403,'forbidden');if(row.phone_number_verified!==true)return fail('Phone verification is required before purchasing credits.',428,'phone_verification_required');const customerId=await getOrCreateCustomer(db,env,auth,row);const origin=new URL(request.url).origin;const params=new URLSearchParams();params.set('customer',customerId);params.set('mode','payment');params.set('payment_method_types[0]','card');params.set('payment_intent_data[setup_future_usage]','off_session');params.set('line_items[0][price_data][currency]','usd');params.set('line_items[0][price_data][unit_amount]',String(pkg.amountCents));params.set('line_items[0][price_data][product_data][name]',pkg.name);params.set('line_items[0][quantity]','1');params.set('success_url',`${origin}/MyMatchIQ/Credits?purchase=success&session_id={CHECKOUT_SESSION_ID}`);params.set('cancel_url',`${origin}/MyMatchIQ/Credits?purchase=canceled`);params.set('client_reference_id',auth.user.id);for(const [key,value] of Object.entries({mmiq_type:'credit_checkout',user_id:auth.user.id,package_code:pkg.code,credits:String(pkg.credits),amount_cents:String(pkg.amountCents)})){params.set(`metadata[${key}]`,String(value));params.set(`payment_intent_data[metadata][${key}]`,String(value));}const s=await stripeRequest(env,'POST','/checkout/sessions',params);return json({ok:true,url:s.url,sessionId:s.id,package:pkg});}
async function updateAuto(db,env,userId,input){const current=await ensureSettings(db,userId);const enabled=Boolean(input?.enabled);const cents=Number(input?.refillPackageCents??input?.refill_package_cents??normalizedSettings(current).refill_package_cents);const pkg=Object.values(PACKAGES).find(x=>x.amountCents===cents);const threshold=Number(input?.thresholdCredits??input?.threshold_credits??current.trigger_balance);if(!pkg)return fail('Choose a valid Auto Replenish package.');if(!Number.isInteger(threshold)||threshold<0||threshold>12)return fail('Choose a minimum balance from 0 to 12 credits.');if(enabled){if(!billingEnabled(env))return fail('Auto Replenish is disabled in this Prelaunch environment.',503,'auto_replenish_disabled');if(!current.payment_method_reference)return fail('Purchase credits once and save a verified payment method before enabling Auto Replenish.',409,'payment_method_required');}const r=await db.query('UPDATE public.mmiq_auto_replenish_settings SET enabled=$1,package_code=$2,trigger_balance=$3,updated_at=now() WHERE user_id=$4::uuid RETURNING *',[enabled,pkg.code,threshold,userId]);return json({ok:true,settings:normalizedSettings(r.rows[0])});}
async function walletPayload(db,userId){const [wallet,settings]=await Promise.all([ensureWallet(db,userId),ensureSettings(db,userId)]);return {wallet,settings:normalizedSettings(settings)};}
function validPackage(metadata){const pkg=PACKAGES[String(metadata?.package_code||'')];return pkg&&Number(metadata?.credits)===pkg.credits&&Number(metadata?.amount_cents)===pkg.amountCents?pkg:null;}
async function addCreditsTx(db,userId,pkg,type,providerReference,paymentMethod=null,metadata={}){await db.query('INSERT INTO public.mmiq_credit_wallets(user_id) VALUES($1::uuid) ON CONFLICT(user_id) DO NOTHING',[userId]);const dup=await db.query('SELECT 1 FROM public.mmiq_credit_transactions WHERE provider=$1 AND provider_reference=$2 LIMIT 1',['stripe',providerReference]);if(dup.rowCount)return false;const locked=await db.query('SELECT balance FROM public.mmiq_credit_wallets WHERE user_id=$1::uuid FOR UPDATE',[userId]);const next=Number(locked.rows[0]?.balance||0)+pkg.credits;await db.query('UPDATE public.mmiq_credit_wallets SET balance=$1,lifetime_purchased=lifetime_purchased+$2,updated_at=now() WHERE user_id=$3::uuid',[next,pkg.credits,userId]);await db.query(`INSERT INTO public.mmiq_credit_transactions(user_id,wallet_delta,balance_after,transaction_type,package_code,amount_cents,provider,provider_reference,metadata) VALUES($1::uuid,$2,$3,$4,$5,$6,'stripe',$7,$8::jsonb)`,[userId,pkg.credits,next,type,pkg.code,pkg.amountCents,providerReference,JSON.stringify(metadata)]);if(paymentMethod)await db.query(`INSERT INTO public.mmiq_auto_replenish_settings(user_id,payment_method_reference) VALUES($1::uuid,$2) ON CONFLICT(user_id) DO UPDATE SET payment_method_reference=EXCLUDED.payment_method_reference,updated_at=now()`,[userId,paymentMethod]);return true;}
async function beginEvent(db,event,userId){const r=await db.query(`INSERT INTO public.mmiq_payment_events(provider,event_id,event_type,user_id,payload) VALUES('stripe',$1,$2,$3::uuid,$4::jsonb) ON CONFLICT(provider,event_id) DO NOTHING RETURNING id`,[event.id,event.type,userId||null,JSON.stringify({objectId:event?.data?.object?.id||null})]);return r.rows[0]?.id||null;}
async function finishEvent(db,eventId){await db.query(`UPDATE public.mmiq_payment_events SET processed_at=now() WHERE provider='stripe' AND event_id=$1`,[eventId]);}
export async function handleMyMatchIQCreditStripeEvent(db,env,event){const object=event?.data?.object||{};const isCheckout=event?.type==='checkout.session.completed'&&object?.metadata?.mmiq_type==='credit_checkout';const isAutoSuccess=event?.type==='payment_intent.succeeded'&&object?.metadata?.mmiq_type==='auto_replenish';const isAutoFail=event?.type==='payment_intent.payment_failed'&&object?.metadata?.mmiq_type==='auto_replenish';if(!isCheckout&&!isAutoSuccess&&!isAutoFail)return false;const userId=object?.metadata?.user_id||object?.client_reference_id||null;let paymentIntentId=typeof object?.payment_intent==='string'?object.payment_intent:object?.payment_intent?.id||null;let paymentMethod=typeof object?.payment_method==='string'?object.payment_method:object?.payment_method?.id||null;if(isCheckout&&paymentIntentId&&env.STRIPE_SECRET_KEY){const pi=await stripeRequest(env,'GET',`/payment_intents/${encodeURIComponent(paymentIntentId)}`);paymentMethod=typeof pi?.payment_method==='string'?pi.payment_method:pi?.payment_method?.id||null;}await db.query('BEGIN');try{const eventRow=await beginEvent(db,event,userId);if(!eventRow){await db.query('ROLLBACK');return true;}if(isAutoFail){if(userId)await db.query('UPDATE public.mmiq_auto_replenish_settings SET enabled=false,updated_at=now() WHERE user_id=$1::uuid',[userId]);await finishEvent(db,event.id);await db.query('COMMIT');return true;}if(isCheckout&&object.payment_status!=='paid'){await finishEvent(db,event.id);await db.query('COMMIT');return true;}const pkg=validPackage(object.metadata);if(userId&&pkg){const ref=isCheckout?`checkout:${object.id}`:`payment_intent:${object.id}`;await addCreditsTx(db,userId,pkg,isCheckout?'purchase':'auto_replenish',ref,paymentMethod,{stripeEventId:event.id});if(isAutoSuccess)await db.query('UPDATE public.mmiq_auto_replenish_settings SET last_triggered_at=now() WHERE user_id=$1::uuid',[userId]);}await finishEvent(db,event.id);await db.query('COMMIT');return true;}catch(error){await db.query('ROLLBACK');throw error;}}
async function triggerAuto(db,env,userId,newBalance){if(!billingEnabled(env))return;const s=(await db.query('SELECT enabled,package_code,trigger_balance,payment_method_reference,last_triggered_at FROM public.mmiq_auto_replenish_settings WHERE user_id=$1::uuid',[userId])).rows[0];if(!s?.enabled||!s.payment_method_reference||newBalance>Number(s.trigger_balance))return;if(s.last_triggered_at&&Date.now()-new Date(s.last_triggered_at).getTime()<5*60*1000)return;const user=await member(db,userId);const pkg=PACKAGES[s.package_code];if(!user?.stripe_customer_id||!pkg)return;const claimed=await db.query(`UPDATE public.mmiq_auto_replenish_settings SET last_triggered_at=now(),updated_at=now() WHERE user_id=$1::uuid AND (last_triggered_at IS NULL OR last_triggered_at<now()-interval '5 minutes') RETURNING user_id`,[userId]);if(!claimed.rowCount)return;const params=new URLSearchParams();params.set('amount',String(pkg.amountCents));params.set('currency','usd');params.set('customer',user.stripe_customer_id);params.set('payment_method',s.payment_method_reference);params.set('confirm','true');params.set('off_session','true');for(const [key,value] of Object.entries({mmiq_type:'auto_replenish',user_id:userId,package_code:pkg.code,credits:String(pkg.credits),amount_cents:String(pkg.amountCents)}))params.set(`metadata[${key}]`,String(value));try{await stripeRequest(env,'POST','/payment_intents',params);}catch(error){await db.query('UPDATE public.mmiq_auto_replenish_settings SET enabled=false,updated_at=now() WHERE user_id=$1::uuid',[userId]);throw error;}}
export async function debitMyMatchIQCredits(db,env,userId,amount,reason='play',reference=null,metadata={}){if(!Number.isInteger(amount)||amount<=0)throw new Error('Invalid credit amount.');await db.query('BEGIN');let next;try{await db.query('INSERT INTO public.mmiq_credit_wallets(user_id) VALUES($1::uuid) ON CONFLICT(user_id) DO NOTHING',[userId]);const r=await db.query('SELECT balance FROM public.mmiq_credit_wallets WHERE user_id=$1::uuid FOR UPDATE',[userId]);const balance=Number(r.rows[0]?.balance||0);if(balance<amount)throw Object.assign(new Error('Not enough MyMatchIQ credits.'),{status:402,code:'insufficient_credits'});next=balance-amount;await db.query('UPDATE public.mmiq_credit_wallets SET balance=$1,lifetime_used=lifetime_used+$2,updated_at=now() WHERE user_id=$3::uuid',[next,amount,userId]);await db.query(`INSERT INTO public.mmiq_credit_transactions(user_id,wallet_delta,balance_after,transaction_type,provider_reference,metadata) VALUES($1::uuid,$2,$3,'use',$4,$5::jsonb)`,[userId,-amount,next,reference,JSON.stringify({reason,...metadata})]);await db.query('COMMIT');}catch(error){await db.query('ROLLBACK');throw error;}await triggerAuto(db,env,userId,next).catch(error=>console.error('MyMatchIQ Auto Replenish trigger failed',error?.message||error));return next;}
export async function handleMyMatchIQCreditsRequest(request,env,url){if(!url.pathname.startsWith('/api/mymatchiq/credits'))return null;const auth=await session(request,env);if(!auth)return fail('Verified MyMatchIQ sign-in is required.',401,'unauthorized');try{return await withDb(env,async db=>{const row=await member(db,auth.user.id);if(!row||row.is_active===false)return fail('Account access is unavailable.',403,'forbidden');if(row.phone_number_verified!==true)return fail('Phone verification is required for MyMatchIQ credits.',428,'phone_verification_required');if(url.pathname==='/api/mymatchiq/credits/config'&&request.method==='GET')return json({ok:true,billingEnabled:billingEnabled(env),packages:Object.values(PACKAGES)});if(url.pathname==='/api/mymatchiq/credits/wallet'&&request.method==='GET')return json({ok:true,...await walletPayload(db,auth.user.id)});if(url.pathname==='/api/mymatchiq/credits/auto-replenish'){if(request.method==='GET')return json({ok:true,settings:normalizedSettings(await ensureSettings(db,auth.user.id))});if(request.method==='PUT')return updateAuto(db,env,auth.user.id,await readJson(request));return fail('Method not allowed.',405,'method_not_allowed');}if(url.pathname==='/api/mymatchiq/credits/checkout'&&request.method==='POST')return checkout(db,env,request,auth,await readJson(request));if(url.pathname==='/api/mymatchiq/credits/history'&&request.method==='GET'){const h=await db.query('SELECT id,wallet_delta AS delta,balance_after,transaction_type AS reason,package_code,amount_cents,provider,provider_reference AS reference,metadata,created_at FROM public.mmiq_credit_transactions WHERE user_id=$1::uuid ORDER BY created_at DESC LIMIT 100',[auth.user.id]);return json({ok:true,history:h.rows});}return fail('Not found.',404,'not_found');});}catch(error){console.error('MyMatchIQ credits error',error);return fail(error?.message||'Credit request failed.',error?.status||500,error?.code||'credit_error');}}
